### ISSUE TITLE
[QST] Output Type of DecimalType Binary Operation

### ISSUE THREAD

**Issue by codereport** [rapidsai/cudf#10230]
@GregoryKimball was recently trying out the cuDF `Decimal128Dtype` and ran into an issue:
```py
In [1]: import cudf
In [2]: from cudf.core.dtypes import Decimal128Dtype
In [3]: t1 = Decimal128Dtype(precision=10, scale=2)
In [4]: df = cudf.DataFrame()
In [5]: df["fixed"] = cudf.Series([1]).astype(t1)
In [6]: df["ep_d"] = cudf.Series([0.1]).astype(t1)
In [7]: df["fixed"] + df["ep_d"]
Out[22]: 
0    1.10
dtype: decimal64
```
The resulting type of a binary operation adding two `Decimal128Dtype` columns was a `Decimal64Dtype` column. I looked into it, and it seems we always set the output type to be the "minimum" width that works. See this [line](https://github.com/rapidsai/cudf/blob/2e458b93b639d5068452c9559ff045b60cc9b933/python/cudf/cudf/core/column/decimal.py#L373).
```py
def _get_decimal_type(lhs_dtype, rhs_dtype, op):
    # ...
    for decimal_type in (
        cudf.Decimal32Dtype,
        cudf.Decimal64Dtype,
        cudf.Decimal128Dtype,
    ):
        try:
            min_decimal_type = decimal_type(precision=precision, scale=scale)
        except ValueError:
            # Call to _validate fails, which means we need
            # to try the next dtype 
            pass
        else:
            return min_decimal_type

    raise OverflowError("Maximum supported decimal type is Decimal128")
```

Is this intentional? I would expect it to be the same as the input columns. I can set up a PR to fix but I just wanted to check if there was motivation behind this.

@galipremsagar (you worked on the recent PR that introduced this https://github.com/rapidsai/cudf/pull/9533)
@shwina (you worked on the initial support for DecimalTypes with me)

**Comment by galipremsagar** [comment]
This was intentional, because wherever we had control over changing dtype i.e., we get new `precision` & `scale` (which can result in new dtype):

```python
>>> (df["fixed"] + df["ep_d"]).dtype
Decimal64Dtype(precision=11, scale=2)
>>> df["fixed"].dtype
Decimal128Dtype(precision=10, scale=2)
>>> df["ep_d"].dtype
Decimal128Dtype(precision=10, scale=2)
```
The motivation to return a `dtype` that can accommodate resulting precision & scale was to not use extra memory here, since we could fit in the precision and scale comfortably in `Decimal64Column` instead of `Decimal128Column`.. But open to inputs here if we want to return `Decimal128Column`. 

cc: @beckernick

**Comment by beckernick** [comment]
In general, reducing memory is a worthwhile goal as out of memory errors are one of the most common failure modes. Beyond potentially surprising some users familiar with Decimal operations in engines like Spark, Hive, etc., do you think this poses any correctness concern @codereport @galipremsagar @GregoryKimball ?

**Comment by codereport** [comment]
From my POV, it doesn't pose any correctness concerns. I think it is just a bit surprising. If you have two columns A and B that are both Decimal128Dtype, you add them and get column C. You now might have to cast column C to 128 if it is 32 or 64, and I would just expect it to still be 128. I guess an even odder example is that if you column A and you multiply it by a scalar 1, you might end up getting back a column with a "different type".

There is nothing wrong about the above, just could be a bit confusing is all. As long as we know this is what we want I am fine with it.

**Comment by bdice** [comment]
Is the opposite true as well? Do 64 bit types overflow into 128 bit types? Regardless of the answer, I’d err on the side of preserving dtype, but if overflow does not cast to a wider type then we should definitely avoid casting to a narrower type for correctness.

Secondly, how is this done? This behavior seems like it must induce an extra cast (unnecessary copying?) if it chooses to change types - I would guess that we do not know the type that will fit the results until the results have been computed. Is a temporary array allocated for the wider type and then checked to see if a narrower type is sufficient, and performing a cast-and-copy if so? That approach wouldn’t help much with OOM concerns and seems needlessly costly, but perhaps we have a better implementation.

**Comment by galipremsagar** [comment]
> Is the opposite true as well? Do sums of 64 bit types overflow into 128 bit types? Regardless of the answer, I’d favor preserving dtype, but if overflow does not cast to a wider type then we should definitely avoid casting to a narrower type for correctness.
Sum of two 64bit types could result in 128bit types but not always, it is purely based on `precision` & `scale`: https://docs.microsoft.com/en-us/sql/t-sql/data-types/precision-scale-and-length-transact-sql?view=sql-server-ver15 

> 
> Secondly, how is this done? This behavior seems like it must induce an extra cast (unnecessary copying?) if it chooses to change types - I would guess that we do not know the type that will fit the results until the results have been computed. Is a temporary array allocated for the wider type and then checked to see if a narrower type is sufficient, and performing a cast-and-copy if so? That approach with the larger temporary array wouldn’t help as much with OOM concerns and seems needlessly costly, but perhaps we have a better implementation.

I can't speak for what is happening inside libcudf layer, but from the cython side we are required to pass the expected output type before hand here: https://github.com/rapidsai/cudf/blob/branch-22.04/python/cudf/cudf/_lib/binaryop.pyx#L159

**Comment by revans2** [comment]
Spark plans the input and output types of all operations ahead of time when preparing the query plan. They have rules about how each operator will impact the output type. Generally these rules are looking at the worst case situation and do not take into account the data itself. For example for the add operator the output precision is

```
max(p1 - s1, p2 - s2) + max(s1, s2) + 1
```

Where p1 and p2 are the lhs and rhs precisions and s1 and s2 are the lhs and rhs scales of the input operators. (note that scale in spark is the negative cudf scale)

But if I was adding 1.0 + 1.0 where the precision was 10 and the scale was 1 the output data type would have a precision of 11. Does not matter what the actual data in those columns holds. So yes in Spark we end up with a lot of casting to wider types and processing data in types that can cover the worst possible situation.

Overflow checking tends to happen after the operation is done, and really only is an issue when the normal rule would produce a precision that is too large for a DECIMAL_128 to hold (precision of 38).  Spark has somewhat arbitrary and configurable rules about what the output precision/scale should be if the rules would cause the precision to go above 38.

I can get into all of the ugly details of all of this if you want to, but it is not pretty.  If CUDF could provide APIs, for at least some operations, that would let us pick the smallest data type needed for the output of a decimal operation without overflowing, based off of the data, it would be interesting, and something that we would look into using. However it would be a significant amount of work for us to use it because of things like joins where we need both sides to match the same type.

**Comment by vyasr** [comment]
There's some discussion of how similar rules could be defined in the Python layer [here](https://github.com/rapidsai/cudf/issues/7680#issuecomment-821577340).

**Comment by revans2** [comment]
I am happy to help with that if anyone has questions about what Spark is doing. I have been up to my eyeballs in it for quite a while.  Some of the odd parts of Spark are with divide, where for what ever reason that assume you want a scale of at least 6. And then with the SUM aggregation where they arbitrarily decide that the output precision should be 10 more than the input precision.

**Comment by vyasr** [comment]
I think that would be a discussion to have with @brandon-b-miller who spearheaded a lot of that work, and perhaps @randerzander regarding what our Python users would expect.

**Comment by shwina** [comment]
FWIW, my 2c here is that the Decimal128 type should be preserved.  Similarly, summing two Decimal32s should give you back a Decimal32. There's no way to tell what might happen downstream of the binop that might need the 128 bits of precision.

**Comment by vyasr** [comment]
My 2c: you should never implicitly narrow the data type since there's no way to know if that's safe without some level of data introspection. Anything else is surprising, and it could even lead to users making unsafe assumptions later. Conversely, I think widening should follow rules similar to what @revans2 mentions above since that may be necessary for safety. Both of these conventions seem important enough to eat the memory costs.

**Comment by shwina** [comment]
Thanks @galipremsagar, I think that's fair. I opened https://github.com/rapidsai/cudf/issues/10282 as a bug to track this on the Python side.

**Comment by codereport** [comment]
Thanks @shwina @galipremsagar and everyone that weighed in. I will close this now that there is another issue open.
