### ISSUE TITLE
[BUG] Use a typedef for representing a number-of-columns

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1030]
We currently have some API functions which take a variable number of columns using `gdf_column **`, and an extra parameter indicating the number of columns. Right now, such parameters are "hard-typed" as `int`. Instead, such values should have a more meaningful type: `gdf_column_index_type` (or another name if you like; it could be `gdf_record_size_type` as opposed to `gdf_column_size_type`, for consistency).

There are, and will be additional, other places in the code which count columns, and their authors too should be able to use this type rather than guessing and looking around. That is, why should it not be `unsigned int`? Or `gdf_size_type`? etc.

**Comment by jrhemstad** [comment]
It definitely should be `gdf_size_type`, and all new features and updates to existing APIs I have reviewed I've requested the change be from hardcoded types to `gdf_size_type`.

However, a cleanup pass is required to update existing APIs to make the same change.

**Comment by eyalroz** [comment]
1. Are you sure we intend to support 2^32-1 columns rather than, say, 2^16-1?
2. Why not gdf_index_type then?
3. Even if it's the same type, I would prefer a gdf_column_index_type, but would not feel very strongly about it.

**Comment by williamBlazing** [comment]
I think that there should be a different gdf_size_type for number of columns, like gdf_column_index_type. The scales of those numbers and what we should support are very different. I agree that it would take a large effort to refactor the whole code base so that it would all consistently use the new type, but we dont have to do it all at once. Which is the mantra we have been having for almost all improvements to our code quality. We can easily introduce a new typedef and have people become aware of it and use it in new code.

**Comment by jrhemstad** [comment]
I don't see the advantage of having a distinct `typedef` for the number of columns vs. the size of the column.

`gdf_size_type` is currently an `int`, and it is used for both the number of elements in a column _and_ the number of columns.

Sure, we don't _need_ to use an `int32_t` for the number of columns, because `MAX_INT` columns would be ludicrous. What are we going to use instead `int16_t`? What would be the point of that? It's not going to save you any performance.

In my mind, bifurcating `gdf_size_type` into `gdf_size_type` and `gdf_column_index_type` would only increase the burden developers to remember which one to use when, and for no benefit that I can see.

**Comment by eyalroz** [comment]
> I don't see the advantage of having a distinct `typedef` for the number of columns vs. the size of the column.

Mostly - clarity of the source code; better adherence to the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment); intuitivity of the API.

> `gdf_size_type` is currently an `int`, and it is used for both the number of elements in a column _and_ the number of columns.

But this is not necessarily the case; it's a choice that we could have made differently. Let's not "bake it in" more than we have to. Also, we've separated an index_type from a size_type; why did we do that? We could have  used `gdf_size_type` everywhere, after all.

> What are we going to use instead `int16_t`? What would be the point of that? It's not going to save you any performance.

It could, but for now let's agree this is esoteric. (Example: Suppose you wanted to compare two sequences of records lexicographically, and get the indices of the first column on which each of them differs.)

> In my mind, bifurcating `gdf_size_type` into `gdf_size_type` and `gdf_column_index_type` would only increase the burden on developers to remember which one to use when, and for no benefit that I can see.

I'd say the opposite is true. I find myself confusing column lengths with numbers of columns if they have the same type. If you want to reduce bifrucation, merging the size and index types is a much more reasonable way to go. The C++ standard library only uses only size types and no index types.


>  It would also increase the burden in doing code reviews to ensure `gdf_column_index_type` is only used for "number of columns" and `gdf_size_type` is only used for "number of elements in a column".

It would _decrease_ this burden. In review, we need to make sure column indices/sizes don't get mixed up with record indices/sizes - even now; if they have different types, noticing this mix-up becomes easier.

**Comment by jrhemstad** [comment]
> Also, we've separated an index_type from a size_type; why did we do that? We could have used gdf_size_type everywhere, after all.

The independence of `index` type vs `size` type is to one day allow supporting chunked-arrays. The maximum length of any one "chunk" may be `MAX_INT`, but we may updated `gdf_index_type` to `int64_t` because it's convenient to have an `int64_t` type for indexing into the entire chunked array. (Instead of having to use `int32_t` and potentially add offsets to the indices in order to index into a chunk array whose size is larger than `MAX_INT`).

I don't see anywhere near the same benefit of adding `gdf_column_index_type` independent of `gdf_size_type`. 

> I find myself confusing column lengths with numbers of columns if they have the same type

This sounds like an issue that could be better addressed through better variable naming.

> we need to make sure column indices/sizes don't get mixed up with record indices/sizes - even now

I've never seen this be an issue. 

Another reason against `gdf_column_index_type` is let's say we chose `int8_t` or `int16_t`. If someone were to accidentally use `gdf_column_index_type` to store the number of elements in a column, there's a high likelihood of a difficult to track down overflow bug. 

If I had to choose between merging `gdf_index_type` into `gdf_size_type` vs. adding an additional `gdf_column_index_type`, I would choose the former.

**Comment by eyalroz** [comment]
> The independence of `index` type vs `size` type is to one day allow supporting chunked-arrays.
>  The maximum length of any one "chunk" may be `MAX_INT`, but we may update `gdf_index_type` to `int64_t` because it's convenient to have an `int64_t` type for indexing into the entire chunked array. (Instead of having to use `int32_t` and potentially add offsets to the indices in order to index into a chunked array whose total size is larger than `MAX_INT`).

Oh, but then you'll really not want this pair of type names. Because when `X_index_type` and `X_size_type` are used in proximity to each other, you always assume the former is indices into sequences whose size is of the latter. It would then need to be `gdf_chunk_size_type` and `gdf_column_size_type` or something of that sort.

Also, I doubt whether everybody using `gdf_index_type` today are really considering the possibility that it can exceed the size type. This is doubly true if we use the same types for columns and for records : The types would then read to means "type for all indices of stuff in gdf" and "type for all sizes of stuff in gdf".

> I don't see anywhere near the same benefit of adding `gdf_column_index_type` independent of `gdf_size_type`.

If it's not confusing for you, and it's clearer for others, then there's your benefit right there. Being more specific with types is rarely a bad thing.

> Another reason against `gdf_column_index_type` is let's say we chose `int8_t` or `int16_t`. If someone were to accidentally use `gdf_column_index_type` to store the number of elements in a column, there's a high likelihood of a difficult to track down overflow bug.

You're undermining your previous argument about this never being an issue :-)

Besides, we could just turn on [`-Wconversion`](https://gcc.gnu.org/wiki/NewWconversion).

**Comment by jrhemstad** [comment]
This is no longer relevant in libcudf++.
