### ISSUE TITLE
[FEA] Expose groupby C++ class in Java

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#10352]
Currently, cudf Java supports calling groupby aggregations on an input table with a list of aggregation requests. As such, all the requests have to be sent all at once in order to leverage the internal caching mechanism of the groupby object. Any subsequent call to groupby aggregations will create a new, fresh groupby object which does not hold any cache result from the previous call.

Sometimes, we need to call groupby on the same key tables but with a different set of aggregation requests. Some other times, the input to different aggregation calls may be the same but we can't know beforehand. Since we can't cache the results between different calls, we have to spend time to re-compute everything (even all these were previously computed).

In order to retain cache between different calls to groupby aggregations, we should expose the C++ groupby class in Java in the form of a Java wrapper class holding an internal member pointer that points to a cudf groupby instance. JNI for groupby aggregations will accept an optional pointer that executes aggregation on the given groupby instance (if it exists) or create a new one if necessary.

**Comment by ttnghia** [comment]
Tag @abellina for reference and monitoring the issue.

**Comment by revans2** [comment]
@ttnghia do you have a specific need right now? Because all of the use cases we have had up until now allowed us to pass all of the aggregations at once. We also would need to make sure that we tracked this class and closed it/collected it so we didn't leak memory.

**Comment by ttnghia** [comment]
Yes, I believe that we need it. @abellina did some optimization before but stalled at some points because of this issue. He can give more specific use case for it.

**Comment by abellina** [comment]
> Yes, I believe that we need it. @abellina did some optimization before but stalled at some points because of this issue. He can give more specific use case for it.

I don't think this is something we need to pursue. The reason I was looking into this was to check if there was a performance benefit from re-using the sort helper in the sort aggregates, given some slowness we were seeing because the decimal type needed to use sort-based aggregates.

The reason why I stalled was because my theory was wrong and I couldn't reuse the sort helper for multiple invocations of the aggregate (for N batches that formed a partition). I wasn't considering the case where we could invoke the aggregate with different aggregate requests, as @ttnghia suggested here. I agree I don't think there is a need to do something like this because we are told what all the aggregation requests should be up front by the Spark plan.

So +1 on closing or prioritizing lower. I am not sure if there are other use cases outside of Spark.

**Comment by ttnghia** [comment]
Okay, if it doesn't bring much benefit to us then close it.
