### ISSUE TITLE
[FEA] Hashing of LIST columns

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#10378]
**Is your feature request related to a problem? Please describe.**
Spark supports partitioning on `ArrayType` columns and expressions. To support this in the RAPIDS Accelerator, we need libcudf support for hashing of cudf `LIST` columns.

**Describe the solution you'd like**
The existing libcudf `hash` function works on `LIST` columns, hashing each array element in order and combining to the result hash, similar to how `STRUCT` column hashing combines the hashes of each field column as it iterates the child columns.

**Comment by jlowe** [comment]
Still desired.

**Comment by sameerz** [comment]
still needed.

**Comment by bdice** [comment]
This is partially resolved by #10641. While libcudf now supports hashing nested types, the hash values won't match what is generated by Spark when using `cudf::hash(input, cudf::hash_id::HASH_SPARK_MURMUR3)` because Spark has different conventions for hashing lists and null values.

Spark’s Murmur3 hash function appears to [ignore null values](https://github.com/apache/spark/blob/16b5124d75dc974c37f2fd87c78d231f8a3bf772/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/hash.scala#L339) (so that `hash([1, null]) == hash([null, 1])` and `hash([]) == hash([null]) == hash([null, null])`. The libcudf experimental row hasher, by contrast, [considers the element validity and invoke a `hash_combine` function](https://github.com/rapidsai/cudf/blob/0fdb6dc6d23d46d55819de718d882b7866fad78a/cpp/include/cudf/table/experimental/row_operators.cuh#L822) to ensure that the examples above all have different hash values. Supporting Spark hashing behavior on nested types will require a nontrivial adaptation of the row hasher.

<details>
<summary>Example code using PySpark to demonstrate Spark hashing conventions with null values:</summary>

```python
from pyspark.sql import Row, SparkSession
from pyspark.sql.functions import hash as murmur3
from pyspark.sql.functions import struct

spark = SparkSession.builder.getOrCreate()

print("Hashing a DataFrame with lists:")

df = spark.createDataFrame(
    [
        Row(l=[0]),
        Row(l=[]),
        Row(l=[None]),
        Row(l=[None, None]),
        Row(l=[1, None]),
        Row(l=[None, 1]),
    ]
)

results = [
    df.select(murmur3("l").alias("murmur3")).collect(),
]

df.show()
df.printSchema()

for result in results:
    for row in result:
        print(row)

print("Hashing a DataFrame with structs of lists:")

df = spark.createDataFrame(
    [
        Row(a=[0], b=[0]),
        Row(a=[1, None], b=None),
        Row(a=[1, None], b=[]),
        Row(a=[], b=[None, 1]),
        Row(a=None, b=[1]),
    ]
)

df = df.select(struct("a", "b").alias("struct"))

results = [
    df.select(murmur3("struct").alias("murmur3")).collect(),
]

df.show()
df.printSchema()

for result in results:
    for row in result:
        print(row)
```

Output:

```
Hashing a DataFrame with lists:
+------------+
|           l|
+------------+
|         [0]|
|          []|
|      [null]|
|[null, null]|
|   [1, null]|
|   [null, 1]|
+------------+

root
 |-- l: array (nullable = true)
 |    |-- element: long (containsNull = true)

Row(murmur3=-1670924195)
Row(murmur3=42)
Row(murmur3=42)
Row(murmur3=42)
Row(murmur3=-1712319331)
Row(murmur3=-1712319331)
Hashing a DataFrame with structs of lists:
+-----------------+
|           struct|
+-----------------+
|       {[0], [0]}|
|{[1, null], null}|
|  {[1, null], []}|
|  {[], [null, 1]}|
|      {null, [1]}|
+-----------------+

root
 |-- struct: struct (nullable = false)
 |    |-- a: array (nullable = true)
 |    |    |-- element: long (containsNull = true)
 |    |-- b: array (nullable = true)
 |    |    |-- element: long (containsNull = true)

Row(murmur3=1972096366)
Row(murmur3=-1712319331)
Row(murmur3=-1712319331)
Row(murmur3=-1712319331)
Row(murmur3=-1712319331)
```

</details>

This will require a different approach for handling nested types. The [nested type hashing implementation here](https://github.com/rapidsai/cudf/blob/0fdb6dc6d23d46d55819de718d882b7866fad78a/cpp/include/cudf/table/experimental/row_operators.cuh#L811-L845) would need to be adapted to ignore element validity, and just use each non-null value's hash as the seed for the next hash function. Additionally, [reducing the hash values from each column into an output hash value should not call `hash_combine`](https://github.com/rapidsai/cudf/blob/0fdb6dc6d23d46d55819de718d882b7866fad78a/cpp/include/cudf/table/experimental/row_operators.cuh#L779-L782), and should use the hash of each column as a seed for the hash function on the next column.

These are nontrivial differences that probably warrant separating the Spark-compatible implementation from the core libcudf nested hashing algorithms, rather than forcing a Spark-compatible approach into the existing experimental hashing code.

**Comment by rwlee** [comment]
For clarity, how deeply do we want to support nesting of nested types in hashing for this Spark application and in general?
e.g. Struct[List[List[Struct[]]]]

**Comment by revans2** [comment]
> For clarity, how deeply do we want to support nesting of nested types in hashing for this Spark application and in general? e.g. Struct[List[List[Struct[]]]]

I would like to not have to limit it if possible. Most people are asking for relatively small levels of nesting. List[String] or List[Int], but we have seen people with very deep schemas. Some big tech companies supposedly have thousands of levels deep, but I don't think we have to work on those cases.

**Comment by bdice** [comment]
The sublist structure does not factor in at all. Example:

```
+---------------------+----------+
|lists                |hash      |
+---------------------+----------+
|[[1]]                |-559580957|
|[[1, 2]]             |-222940379|
|[[1, 2, 3]]          |-912918097|
|[[1, 2], [3]]        |-912918097|
|[[1], [2, 3]]        |-912918097|
|[[1], [2, 3, null]]  |-912918097|
|[[1, 2], [3], [null]]|-912918097|
|[[1, 2], null, [3]]  |-912918097|
+---------------------+----------+
```

<details><summary>Source code</summary>

Save as `test.scala` and run with `spark-shell -i test.scala`.

```scala
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types.{ArrayType, IntegerType, StructType}
import org.apache.spark.sql.Row

val schema = new StructType()
  .add("lists",ArrayType(ArrayType(IntegerType)))

val data = Seq(
  Row(List(List(1))),
  Row(List(List(1, 2))),
  Row(List(List(1, 2, 3))),
  Row(List(List(1, 2), List(3))),
  Row(List(List(1), List(2, 3))),
  Row(List(List(1), List(2, 3, null))),
  Row(List(List(1, 2), List(3), List(null))),
  Row(List(List(1, 2), null, List(3))),
)


val df = spark.createDataFrame(
  spark.sparkContext.parallelize(data), schema)

val df2 = df.selectExpr("lists", "hash(lists) as hash")
df2.printSchema()
df2.show(false)
```

</details>
