### ISSUE TITLE
Should libcudf use Arrow data structures natively? 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1045]
This issue is to focus the conversation that started in https://github.com/rapidsai/cudf/issues/1027

The question is, should libcudf natively use Arrow structures such as `arrow::Array` and `arrow::Table`? 

This can take at least two forms:

1. libcudf accepts `arrow::*` structures in its external C++ API, but immediately converts it to our own internal structure

   - This would mainly be for convenience of users of the C++ API who are familiar with the Arrow classes. It would require a lot of reduplication of effort to implement our own functionality that the `Arrow` classes likely already provide.

2. Accept `arrow::*` structures in libcudf API, _and_ use the Arrow structures natively throughout libcudf internals.

   - This is appealing because it would reduce the amount of work we have to do in creating column and table abstractions as well as just improve our Arrow compatibility overall. However, there are several issues:
       - NVStrings doesn't target Arrow's string representation, meaning we wouldn't be able to use NVStrings in it's current form with `arrow::Array`
      - If we want to use `arrow::` structures in device code, we'd need a PR against Arrow to add the `__device__` keyword to the functions we need.
      - `If` we get the necessary `__device__` functions, the larger problem is [relocatable device code](https://devblogs.nvidia.com/separate-compilation-linking-cuda-device-code/). Since Arrow would be a shared external library (i.e., the source code of Arrow isn't available at compile time of libcudf), in order to use Arrow's `__device__` functions, both Arrow and libcudf would need to be compiled with relocatable device code enabled (`-rdc=true`). `rdc` can have performance implications because it treats _all_ `__device__` functions as indirect function calls which can limit the optimizations that compiler can perform, like inlining, and requires the function call to incur the full ABI overhead for each call. There may be performance regressions just from compiling libcudf with `-rdc=true`. Extensive further testing would be needed to determine if this is really a blocker or not. 
    - Other, smaller issues: we may just not like the design. Having spent a little time looking through the Arrow CPP docs, it seems like they dramatically overuse `std::shared_ptr`, but it's not a showstopper.

**Comment by eyalroz** [comment]
We should not use the Arrow data structures (i.e. the software _code_; I don't mean the physical memory layout which we are adhering to).

1. They are written in outdated and inopportune C++. I suppose I should elaborate on this point - will do so later.
2. Adopting the Arrow code is not necessary for maintaining our physical compatibility with the Arrow layout.
3. Once we're physical-layout-compatible (and IIANM we are in that state raight now), using the Arrow data structures is not helpful in maintaining that compatibility, and will not / should not reduce the amount of work to create these columns.
4. If we provide better-designed, more aesthetic and easier to use data structures for the same physical layout as Arrow - we could pitch them to other projects adhering to the Arrow layout, and perhaps even to Arrow itself.

About the NVStrings issue - that's actually orthogonal to the question here, since whether we use Arrow's structures or not, we will need to convert Arrow-strings to NVstrings and back - or support Arrow strings directly (with or without the Arrow code).

**Comment by jrhemstad** [comment]
@eyalroz to be clear, you're suggesting we pursue neither 1. nor 2. from what I wrote, and instead if someone wants to use `arrow::Array` or similar in `libcudf`, then we need to provide a converter from arrow -> cudf? 

This is largely a minor implementation detail vs. option 1 I provided. It's just a matter of if we take care of the conversion automatically, or require the conversion be done before calling libcudf APIs. 

> About the NVStrings issue - that's actually orthogonal to the question here, since whether we use Arrow's structures or not, we will need to convert Arrow-strings to NVstrings and back - or support Arrow strings directly (with or without the Arrow code).

Not quite orthogonal, as we could always push to update NVStrings to use Arrow's memory layout.

**Comment by eyalroz** [comment]
@jrhemstad : I am suggesting we pursue neither 1 nor 2. If we adhere to the Arrow memory layout with gdf_column or whatever may replace it, and someone wants to use `arrow::Array`, well - fine, they can just do: `reinterprect_cast<arrow::Array*>(my_gdf_column_ptr)`. And that's that.

To put it more bluntly, I'm suggesting we don't "get into bed" with the `arrow::Array` code at all.

About NVStrings - I would rather not get into a discussion of NVStrings' design, since I haven't been following that work well enough (barely at all TBH). But if we are committed/required to hold columns in Arrow's physical layout, then either we can't use NVStrings directly or NVStrings supports such conforming physical layout. Am I wrong?

**Comment by eyalroz** [comment]
This discussion is also relevant to that in issue #1304 .

**Comment by kkraus14** [comment]
Given the `cudf::column` design discussions I believe we've landed on not using Arrow directly so I'm going to close this.
