### ISSUE TITLE
[FEA] Refactor `apply_bitmask_to_mask` and provide cleaner API for `AND`ing two bitmasks together

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1057]
The current function `apply_bitmask_to_bitmask` has a couple of problems and just generally needs to be simplified. 

https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/bitmask/bitmask_ops.cu#L62

1. Should use `gdf_get_num_chars_bitmask` directly instead of recomputing it itself

2. Lots of unnecessary Thrust iterator stuff going on 

3. Uses inscrutable magic vector of numbers https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/bitmask/bitmask_ops.cu#L35 that I'm not quite sure what it's being used for

4. Should use `gdf_count_nonzero_mask` for computing null counts https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/bitmask/valid_ops.cu#L173

**Comment by devavret** [comment]
There's a small design issue: `apply_bitmask_to_bitmask` is called from `gdf_hash_columns` which receives a pointer to a stream in the API. This same stream is passed on to `update_null_count`. If we want to replace it with `gdf_count_nonzero_mask` then we probably should have a way to pass the stream to it. This won't be possible until the API is converted to C++ because I cannot add a default parameter 0 stream to `gdf_count_nonzero_mask` as long as it is C.

This is not a blocker. Just non-ideal.
