### ISSUE TITLE
[BUG] 10 Minutes to cuDF and CuPy throws AttributeError

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cudf#10612]
**Describe the bug**
The 10 Minutes to cuDF and CuPy throws the following error: 
```AttributeError: module 'cupy' has no attribute 'from_dlpack'```

**Steps/Code to reproduce bug**
Run the notebook.

**Expected behavior**
This error should not appear in the notebook.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
`docker pull rapidsai/rapidsai-core:22.02-cuda11.2-runtime-centos7-py3.8`
` docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786     -v ~/extra:/rapids/notebooks/extra rapidsai/rapidsai-core-nightly:22.04-cuda11.2-runtime-centos7-py3.8`

**Comment by charlesbluca** [comment]
Looks like I introduced this issue through https://github.com/rapidsai/cudf/pull/10594, as my containers were picking up the newest version of CuPy (10.3.0) that gave a FutureWarning at the use of `fromDlpack` - out of interest, what version did you end up picking up in your containers?

Perhaps we should continue using `fromDlpack` here until our constraint is bumped enough that the majority of users would be calling `from_dlpack`? cc @galipremsagar since you originally reviewed #10594 not sure if you have some thoughts on this

**Comment by galipremsagar** [comment]
Yeah, we currently support cupy `9.5.0` aswell which doesn't have `from_dlpack`. We can change back to using `from_dlpack` in `22.06` based on version. But not a pressing issue to do a patch release for `22.04`.

```python
>>> import cupy as cp
>>> cp.fromDlpack
<built-in function fromDlpack>
>>> cp.from_dlpack
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.8/site-packages/cupy/__init__.py", line 874, in __getattr__
    raise AttributeError(
AttributeError: module 'cupy' has no attribute 'from_dlpack'
>>> cp.__version__
'9.5.0'
```

cc: @shwina @rapidsai/ops just FYI.

**Comment by shwina** [comment]
To address @robocopnixon's original issue, it looks like one would need to use `fromDlpack()` instead of `from_dlpack` (depending on what version of `cupy` got pulled into the container).

This is unfortunate, but I would agree it's too small a change for a patch release right now.
