### ISSUE TITLE
[QST] cudf styling

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1078]
I am currently working on a PR which adds some functionality and I want to have nice docstrings/documentation along with the features.  What should the *ideal* import and variable name be for cudf.  Essentially, I would like a style guide and try to adhere to that guide as best as possible. Variations I have seen thus for imports/names

## Imports:
- import cudf
- import cudf as gd
- from cudf import DataFrame
- from cudf import Series

## Variable names
- df = cudf.DataFrame(...)
- gdf = cudf.DataFrame(...)
- cdf = cudf.DataFrame(...)
- my_gdf = cudf.DataFrame(...)
- pdf = cudf.DataFrame(...)
- sr = cudf.Series(...)

It would be nice to build consensus around one import style and one variable assignment style when creating DataFrames and/or Series.  This would be a benefit not only to developers but also to users when they read consistent docs/docstring/notebooks/etc. 

However, the above demonstrates that there are currently many held styles.  How should this be decided?  And to be clear, once a decision has been made I would like to reformat (at least) the python facing cudf docstrings and eventually tests

cc @thomcom @kkraus14 @mrocklin

**Comment by mrocklin** [comment]
### Imports

I like 
    
    import cudf

Because it's fully explicit, there is only one name, and it's short.

Secondarily I understand the motivation for 

    import cudf as gd

Because it looks like `import pandas as pd` and `import dask.dataframe as dd` (I think that this is @kkraus14 's preference and am happy to defer to him) .  

Personally I don't think that it's necessary to establish a `*d` convention like this.  I also think that if we can avoid injecting an alias then we should do so.  This helps users who see `cudf` code only rarely because they won't necessarily know that `gd` means `cudf`.  We made this choice also for `dask`, where we encourage people to use functions like `dask.compute` and `dask.delayed` rather than something like `dk.compute`.  There is a cost to aliases, especially when people unfamiliar with libraries review code.  *Very* popular libraries like `numpy` and `pandas` can get away with it, but I think that most libraries should avoid it.

    from cudf import DataFrame
    from cudf import Series

I'm fully against these.  They make it unclear *which* DataFrame/Series class we're using within code.

### Variable Names

I like using `df` when there is only one kind of dataframe around.  I think I've seen `pdf`/`gdf` most commonly when there are both Pandas and cuDF dataframes around.  I could imagine replacing `gdf` with `cdf` for "CUDA DataFrame", but don't have a strong preference.

**Comment by thomcom** [comment]
I approve of
```
import cudf
gdf = cudf.DataFrame(...)
```
for now. :)

**Comment by randerzander** [comment]
It sounds like we've settled on:

1. `import cudf`
2. It's fine to use `df` as DataFrame variable names.
3. When using both pandas and cudf DataFrames in related examples, distinguishing type with `pdf` and `gdf` is a good idea.

I'd like to eventually add these suggestions to dev docs/wiki pages.

Any other comments or suggestions?

**Comment by kkraus14** [comment]
@randerzander I 110% agree with @mrocklin that we should avoid:
```
from cudf import DataFrame
from cudf import Series
from cudf import ${YOUR_CLASS_HERE}
```
Because it becomes completely ambiguous.

**Comment by thomcom** [comment]
Is it really that ambiguous? How often do you think we should expect to be using pandas objects and cudf objects intermixed in our own library code?

How do you feel about using `from cudf import DataFrame` as a local import to avoid circular dependencies?

**Comment by randerzander** [comment]
I think @kkraus14 meant in example and notebook code, where it is certainly common to mix cudf and Pandas code.

**Comment by kkraus14** [comment]
Settled on `import cudf`
