### ISSUE TITLE
[DOC] `cudf.read_csv` and internal `ioutils` should indicate how `**kwargs` are used.

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#10823]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.read_csv.html#cudf.read_csv

**Describe the problems or issues found in the documentation**
The `cudf.read_csv` function accepts `**kwargs` but it does not indicate how they are used. We should avoid accepting arbitrary keyword arguments because it makes it difficult for users to recognize when unsupported keywords are passed. For example, this silently ignores the user's intention (which might be to use `usecols` and `dtype` instead of `cols` and `dtypes`):

```python
data = cudf.read_csv(data_file, cols=cols, dtypes=dtypes)[col]
```

These `**kwargs` are passed on in a couple places but I'm not familiar with their intended use:
- https://github.com/rapidsai/cudf/blob/4539e5e60d2bc2c81338a5d646f5a9c3ac5ef7cf/python/cudf/cudf/utils/ioutils.py#L1145
- https://github.com/rapidsai/cudf/blob/4539e5e60d2bc2c81338a5d646f5a9c3ac5ef7cf/python/cudf/cudf/utils/ioutils.py#L1331

**Suggested fix for documentation**
Investigate `read_csv` and related utility functions to determine how `**kwargs` are used, and document them accordingly.

If possible, I would prefer to _remove_ `**kwargs` from the I/O functions in favor of named keyword(s) that can serve the same purpose.

Tagging @rjzamora @ayushdg who may have insight from editing this code in the past.

**Comment by ayushdg** [comment]
Thanks for the ping @bdice. iirc the origin for `kwargs` was to allow users to pass in the `storage_options` kwarg for filesystem specific options (for eg the s3 key or gcs token) while reading data from remote filesystems. At the time this could not be an explicit argument in cudf apis since the goal was to match Pandas API which did not support this at the time. 

However since then Pandas has also adopted `fsspec`, the same library used by cudf and dask for handling different filesystems and as a result does expose `storage_options` (more details in #6916). 
IMO we should be good to remove kwargs and expose `storage_options` for the relevant io api's that expose the same param as well.

**Comment by rjzamora** [comment]
>IMO we should be good to remove kwargs and expose storage_options for the relevant io api's that expose the same param as well.

Right - We can remove `kwargs` if we expose `storage_options` and `open_file_options` (used for remote-storage optimizations) in `read_csv`. In an ideal world, the information in `open_file_options` could be included in `storage_options`, but this isn't quite possible yet.

**Comment by galipremsagar** [comment]
Resolved by https://github.com/rapidsai/cudf/pull/11762
