### ISSUE TITLE
[BUG]dask-cudf groupby call failing

### ISSUE THREAD

**Issue by jnke2016** [rapidsai/cudf#10863]
A recent change in dask-cudf is causing an issue with the `groupby` call. Below is a minimal reproducer
```
import cudf
import cugraph
from dask_cuda import LocalCUDACluster
import dask_cudf
from dask.distributed import Client
​
def setup():
    cluster = LocalCUDACluster()
    client = Client(cluster)
​
    return (client, cluster)
​
def teardown(client, cluster=None):
    client.close()
    if cluster:
        cluster.close()
​
def symmetrize(ddf, src_name, dst_name):
    if not isinstance(src_name, list):
        src_name = [src_name]
    if not isinstance(dst_name, list):
        dst_name = [dst_name]
​
    num_partitions = ddf.npartitions
    
    ddf2 = ddf[[*dst_name, *src_name]]
    ddf2.columns = [*src_name, *dst_name]
    result = dask_cudf.concat([ddf, ddf2]).reset_index(drop=True)
    
    vertex_col_name = src_name + dst_name
    result = result.groupby(by=[*vertex_col_name]).min(
        split_out=num_partitions).reset_index()
​
    return result
​
​
if __name__ == "__main__":
    setup_objs = setup()
    client = setup_objs[0]
    workers = client.scheduler_info()['workers']
    num_gpus = len(workers)
    
​
    df = cudf.DataFrame()
​
    df["src"] = [v for v in range(20)]
    df["dst"] = [v for v in range(1, 21)]
    ddf = dask_cudf.from_cudf(df, npartitions=num_gpus)
    ddf_sym = symmetrize(ddf, "src", "dst")
​
    print(ddf_sym.compute())
​
    teardown(*setup_objs)
```

The above script works on `dask-cudf 22.4.0a0+gb50ae82 pypi_0  pypi` and worked on a prior 22.6 version from a 22.06 `Rapids container` (but since it recently got updated with a later `dask-cudf` version, it is no longer working).

The script above is currently failing on `dask-cudf 22.06.00a220514` which I believe is the latest version.

**Comment by charlesbluca** [comment]
Thanks for opening this issue! It looks like this failure was introduced by https://github.com/rapidsai/cudf/pull/10449 by adding `min()` to the list of supported dask-cudf aggregation methods - however, this problem actually existed before then, and I was able to get the same failure without this PR by replacing `min()` with `mean()`.

At its core, it looks like this is because dask-cudf doesn't have the correct handling when grouping by all columns of a table; currently working on a fix
