### ISSUE TITLE
[FEA] How should error reporting be handled in libcudf? 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1101]
This is a sub-issue of https://github.com/rapidsai/cudf/issues/1027

**The question is, how would we like error reporting to be done in an ideally designed libcudf library?**

Currently, we use `gdf_error` error codes. This has several downsides:
- It requires all `libcudf` functions to return a `gdf_error` code, i.e., cannot have output return parameters from functions
- It requires developers to be sure to check the return-code from all libcudf functions
- An error code provides very limited information and context about why an error occured

Instead, I propose that we should throw `std::logic_error` exceptions when a runtime error occurs such as violating some precondition of a function. 

The benefits of this are:
- Allows `libcudf` functions to return whatever they want
- Does not require manually checking the error code from every libcudf functions
- Via the Exception's `what()` message, we can provide more detail and context about when and why an error occurs.

This is also in-line with the ISO CPP core guidelines: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Ri-expects

In this vein, I've created a `CUDF_EXPECTS` macro inspired by the `gsl` library's `Expects()` macro: https://github.com/rapidsai/cudf/pull/1100

**Comment by kkraus14** [comment]
@harrism @jrhemstad is this for 0.6?

**Comment by jrhemstad** [comment]
> @harrism @jrhemstad is this for 0.6?

No. Just part of a larger design discussion.

**Comment by eyalroz** [comment]
Jacob, since you've asked about an "ideally-designed" libcudf, I'll suggest everyone have a look at this talk at CppCon 2018:

[Simon Brand & Phil Nash
**"What Could Possibly Go Wrong?": A Tale of Expectations and Exceptions**](https://www.youtube.com/watch?v=GC4cp4U2f2E)

which surveys and evaluates several approaches to error handling in C++. They finally argue in favor of a monad-like approach, which is currently not supported in C++, but is proposed:

[**Zero-overhead deterministic exceptions: Throwing values** (P0709R2)](http://open-std.org/JTC1/SC22/WG21/docs/papers/2018/p0709r2.pdf)

Now, since we're talking about an ideal scenario, we can assume that:

* This proposal has been accepted
* We're using a C++ standard version with this proposal accepted, and NVCC supports it
* We no longer have a C API, or at least - we have C bindings which we ignore when designing libcudf proper.

under these assumptions - I would seriously consider using static errors ("exceptions") in the return channel.

If we're not so idealistic - I think it's reasonable to throw exceptions. They're quite expensive, but then - we're far from being done:

* No catch-all "logic_error". We should provide more specific and detailed information about our error situations.
* Stack dumps. Stacks are an expensive thing to provide, but seeing how exceptions are already super-expensive - why not? Have a look at [Boost StackTrace](https://www.boost.org/doc/libs/1_69_0/doc/html/stacktrace.html).
* Have a look at our current list of possible errors:
    ```
    GDF_SUCCESS=0,                
    GDF_CUDA_ERROR,                    
    GDF_UNSUPPORTED_DTYPE,             
    GDF_COLUMN_SIZE_MISMATCH,          
    GDF_COLUMN_SIZE_TOO_BIG,           
    GDF_DATASET_EMPTY,                 
    GDF_VALIDITY_MISSING,              
    GDF_VALIDITY_UNSUPPORTED,          
    GDF_INVALID_API_CALL,              
    GDF_JOIN_DTYPE_MISMATCH,           
    GDF_JOIN_TOO_MANY_COLUMNS,         
    GDF_DTYPE_MISMATCH,                
    GDF_UNSUPPORTED_METHOD,            
    GDF_INVALID_AGGREGATOR,            
    GDF_INVALID_HASH_FUNCTION,         
    GDF_PARTITION_DTYPE_MISMATCH,      
    GDF_HASH_TABLE_INSERT_FAILURE,     
    GDF_UNSUPPORTED_JOIN_TYPE,         
    GDF_C_ERROR,                       
    GDF_FILE_ERROR,                    
    GDF_MEMORYMANAGER_ERROR,           
    GDF_UNDEFINED_NVTX_COLOR,          
    GDF_NULL_NVTX_NAME,                
    GDF_TIMESTAMP_RESOLUTION_MISMATCH, 
    GDF_NOTIMPLEMENTED_ERROR,          
```
  There's a bunch of structure and patterns here. A lot of the errors are "something" is one of: missing, mismatched, invalid or unsupported. And the rest are "one of many possible errors from a library other than ours" (e.g. libc, CUDA runtime API, RMM), which when thinking in exceptions means a _nested_ or rethrown exception. This should be reflected in either the inheritance structure or the fields of our exceptions. Or in both.
* Contracts. See [this presentation](https://cppeurope.com/wp-content/uploads/2018/03/contracts.pdf) for example. I think they're in C++20. I haven't worked with them myself, and I haven't even watched the [C++2018 talk](https://www.youtube.com/watch?v=aAFRxRznVjQ) by Alisdair Meredith, but once they're available they would probably be an alternative to `EXCEPT()` and `ENSURES()` macros

**Comment by jrhemstad** [comment]
With the introduction of https://github.com/rapidsai/cudf/pull/1100, the consensus is that we are going to move to using exceptions via macros like `CUDF_EXPECTS` and `CUDA_TRY`. 

We can refine our approach and usage of exceptions over time, but I'm going to close this issue as we're already down the path of using exceptions due to the convenience of Cython automatically converting C++ exceptions into Python exceptions.

**Comment by eyalroz** [comment]
@jrhemstad : But having these macros doesn't mean much, except that we _can_ throw exceptions. It doesn't mean that we _do_ throw them instead of returning error codes. So, before you close the issue - is it a consensus that we replace all/most functions of the form:
```
gdf_error some_function(type1_t in1, type2_t* out_param)
```
with
```
type2_t some_function(type1_t in1) noexcept(false)
```
?

**Comment by jrhemstad** [comment]
>>> So, before you close the issue - is it a consensus that we replace all/most functions of the form:

gdf_error some_function(type1_t in1, type2_t* out_param)
with

type2_t some_function(type1_t in1) noexcept(false)
?

> @jrhemstad : But having these macros doesn't mean much, except that we _can_ throw exceptions. It doesn't mean that we _do_ throw them instead of returning error codes. So, before you close the issue - is it a consensus that we replace all/most functions of the form:
> 
> ```
> gdf_error some_function(type1_t in1, type2_t* out_param)
> ```
> with
> 
> ```
> type2_t some_function(type1_t in1) noexcept(false)
> ```
> ?

This is style question orthogonal to the discussion of error/exception reporting and is better suited for this issue: https://github.com/rapidsai/cudf/issues/479

Personally, I do prefer the style you suggested of returning outputs rather than using output parameters and would advocate for such a style. 

> * What about the C API functions?

We are moving away from developing a pure C API. Our focus is on a pure C++ library and C API wrappers can be added if and when they are necessary.

**Comment by eyalroz** [comment]
It's not orthogonal - it's exactly what this issue asks: "How shall we report errors?" - with one option being through exceptions, and another being through the return value. This is not a question of style, it's a question of substance. Also, as long a a gdf_error is returned, it must also _always_ be checked. If we keep returning `gdf_error`'s _and_ throw exceptions, we'll have to check errors in two ways, always: We'll need to catch exceptions as well as checking the return value. (Or perhaps I'm misunderstanding.)

**Comment by jrhemstad** [comment]
> I don't think that's an orthogonal question - it's exactly what this issue's title asks: "How shall we report errors?" - with one option being through exceptions, and another being through the return value. It's not just a matter of style..

It is a style question because your example could also have been changed to:

```
void some_function(type1_t in1, type2_t* out_param)
```

The `gdf_error` is removed, but still uses an output parameter.

**Comment by eyalroz** [comment]
@jrhemstad : Even this is not just a matter of stype. In that example, you always need to define variables to serve as output; and you can't chain invocations of functions: `another_function(some_function(my_in))`. But, ok, suppose that's just style. The non-style question is: Do we need to continue returning `gdf_error`'s or not...

**Comment by jrhemstad** [comment]
> Do we need to continue returning `gdf_error`'s or not...

No. As I've said elsewhere. `gdf_error` is deprecated and will be removed from functions in a ever continuing process.
