### ISSUE TITLE
[FEA] Support `duplicate_keep_option` in places that use unordered map

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#11050]
In several places, we need to support `duplicate_keep_option` to drop duplicates except for the first or last element in a duplicate sequence. Such an option requires to stable-sort the input column so we can identify the first or last duplicate element.

Hash table/unordered_map for drop duplicates can avoid sorting and enhance performance from `O(nlogn)` to `O(n)` but the output elements are unordered thus it cannot support `duplicate_keep_option`. I believe that such limitation can be overcome somehow. I'll think about it and will prototype a solution if found any idea.

**Comment by ttnghia** [comment]
@PointKernel I have an idea for this, with the help of `cuco::static_map::pair_contains`. Please implement it too (FEA https://github.com/NVIDIA/cuCollections/issues/173). This is at a lower priority than `pair_contains` for `static_multimap`.

**Comment by ttnghia** [comment]
@PointKernel Is it possible to modify `static_map`'s values? I look into `static_map::device_mutable_view` but can't see any `__device__` function for doing so.

**Comment by PointKernel** [comment]
> Is that using the __device__ static_map::device_view::find() function?

Yes

>  I'm not sure if calling it in a provided kernel will be fast or not

Whether it's a cuco kernel or a custom kernel doesn't matter. Those APIs are designed to be invoked on the device side.

> should I use the overload of find that has CG g parameter or not?

There is no short answer for this. Using CG or not and the optimal size of CG vary on a use-case base. But in general, if we stick with 50% occupancy (the default occupancy for all use cases of `static_map` in cudf), The non-CG version is slightly more efficient since hash collisions are rare with such low occupancy.

**Comment by GregoryKimball** [comment]
Closed by #11052
