### ISSUE TITLE
[FEA] Revert changes to nvcomp decompression status check in parquet

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#11065]
First discussed here: https://github.com/rapidsai/cudf/pull/11064#pullrequestreview-997748437

#10699 made a change to the decompression status check that reverted the changes made in #9995. 
The latter added a custom kernel to check statuses to avoid using `thrust::all_of` which supposedly caused a device synchronize and deteriorated perf when running multiple parquet read calls on the same device.

This issue is to request the reverting of this particular change https://github.com/rapidsai/cudf/pull/10699/files#diff-69acbfcb0f4330a9fc3feec2aca0ceab2da0715fc1d7831304c2b154fb1a91e5L1053-L1083

**Comment by jbrennan333** [comment]
I talked to @cheinger about this at our sync up today.  He mentioned TPC-DS query 9 as one of the ones that was most affected by his optimization.  Looking back at our spark-rapids weekly benchmarks, we don't see any degradation in q9 since #10699 went in.   Based on what he said, it is not clear that we need to revert this change.

**Comment by jbrennan333** [comment]
@devavret, @vuule, do you agree this can be closed?
