### ISSUE TITLE
[BUG] to_pandas() produces slightly different results for some edge cases

### ISSUE THREAD

**Issue by VamsiTallam95** [rapidsai/cudf#11080]
**Describe the bug**
When using the to_pandas() from cudf.core.dataframe, for some edge cases the expected output is slightly different due to a subtle bug. This leads to a bug in #10979. This bug is raised following upon the discussion: [https://github.com/rapidsai/cudf/pull/10979#discussion_r890424348](url)

**Steps/Code to reproduce bug**
``` python
>>> import cudf
>>> import pandas as pd


>>> p1 = pd.DataFrame()
>>> c1 = cudf.DataFrame()
>>> p1.index
Index([], dtype='object')
>>> c1.to_pandas().index
RangeIndex(start=0, stop=0, step=1)


>>> p2 = pd.DataFrame([1,2,3])
>>> c2 = cudf.DataFrame([1,2,3])
>>> p2.columns
RangeIndex(start=0, stop=1, step=1)
>>> c2.to_pandas().columns
Int64Index([0], dtype='int64')

>>> c3 = cudf.DataFrame(columns = [1,2,3])
>>> p3 = pd.DataFrame(columns = [1,2,3])
>>> p3.index
Index([], dtype='object')
>>> c3.to_pandas().index
RangeIndex(start=0, stop=0, step=1)
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: from source (branch-22.06)

**Comment by shwina** [comment]
Thanks for reporting @VamsiTallam95! Unfortunately, I don't know that we can truly match Pandas in any of these scenarios, but I'm open to suggestions/alternatives:

> ```python
> >>> p1 = pd.DataFrame()
> >>> c1 = cudf.DataFrame()
> >>> p1.index
> Index([], dtype='object')
> >>> c1.to_pandas().index
> RangeIndex(start=0, stop=0, step=1)
> ```

The problem for us here is that `Index()` in cuDF is purely a factory for making concrete indexes, and cannot be instantiated.  It's for a similar reason we can't match behaviour in your third example.

> ```python
> >>> p2 = pd.DataFrame([1,2,3])
> >>> c2 = cudf.DataFrame([1,2,3])
> >>> p2.columns
> RangeIndex(start=0, stop=1, step=1)
> >>> c2.to_pandas().columns
> Int64Index([0], dtype='int64')
> ```

The "column names" in cuDF are stored not in an `Index`, but rather as the keys of an internal dictionary that maps column names to columns. When converting to Pandas, we construct an index out of those keys. We _could_ choose to convert to a range index if the keys constitute a range, but that will be equally wrong if the cuDF dataframe was constructed like this:

```python

In [11]: df = pd.DataFrame({0: [1, 2, 3], 1: [2, 3, 4]})

In [12]: df.columns
Out[12]: Int64Index([0, 1], dtype='int64')

In[13] gdf = cudf.from_pandas(df)  # should gdf.to_pandas() return Int64Index or RangeIndex?
```

**Comment by vyasr** [comment]
Is there any scenario in which pandas can construct a nonempty `Index` object? If we really care about edge cases like these we could special case the behavior of `Index.__new__`. There are other cases where we deviate from pandas too, for instance if a user constructs an Index composed of booleans:
```
>>> import cudf
>>> cudf.Index([True, False])
GenericIndex([True, False], dtype='bool')
>>> import pandas as pd
>>> pd.Index([True, False])
Index([True, False], dtype='object')
``` 

I'm not necessarily convinced that we should care about these cases though; is there a functional difference between returning Index vs returning one of its subclasses? There are two possible ways that this could matter that I see offhand: 1) if a user does something explicitly like `if type(obj) == Index`, or 2) if a user is depending on the dtype of empty indexes to be `object` rather than `int`. I really don't care about the former case. I could be convinced that the latter isn't entirely unimportant.

CC @brandon-b-miller

**Comment by mroeschke** [comment]
A few context points from the pandas side:

1. We are moving away from Index subclasses based on dtypes and toward just using Index parameterized with a dtypes. (`GenericIndex` in cuDF looks to be the direction where we want to go). `RangeIndex` will stay though. https://pandas.pydata.org/pandas-docs/stable/whatsnew/v1.4.0.html#deprecated-int64index-uint64index-float64index
2. I would say the `RangeIndex` "philosophy" generally is:
* It's the default index if the user doesn't provide one (and the DataFrame/Series is not empty)
* Operations on a `RangeIndex` should return a `RangeIndex` if feasible otherwise return the appropriate Index subclass. We've fixed bugs along this premise but don't have a good catalog of all the cases where "feasible" is defined. (Anecdotally, I haven't seen too many bug reports from users getting a `Int64Index` when starting from a `RangeIndex`)
* `RangeIndex` is more-or-less an optimization of an integer index. From the user perspective it should quack like an integer index.

**Comment by vyasr** [comment]
> We are moving away from Index subclasses based on dtypes

Right, I've seen that this is the general direction. I guess that means that in the long run we will need to make some changes.  Do you anticipate that it will always be the case that `pandas.Index(SOME_MULTIDIMENSIONAL_OBJECT)` will return a `MultiIndex`? Will `pandas.Index(range(...))` always automatically return a `RangeIndex`? That causes some (not insurmountable) problems for cuDF because of the ugliness with overriding `__new__` rather than `__init__` that we've made a significant effort to work around. In fact, that is the main reason why we introduced [the `BaseIndex` class](https://github.com/rapidsai/cudf/blob/branch-22.08/python/cudf/cudf/core/_base_index.py#L68), so as to isolate the `__new__` behavior to a [special subclass `cudf.Index`](https://github.com/rapidsai/cudf/blob/branch-22.08/python/cudf/cudf/core/index.py#L2797) that is basically just a factory. If `Index` needs to become concrete again we'd probably want to do some careful thinking about how we implement this so that all the other Index subclasses. Things like `StringIndex` and `CategoricalIndex` will remain separate subclasses, right?

**Comment by mroeschke** [comment]
> Do you anticipate that it will always be the case that pandas.Index(SOME_MULTIDIMENSIONAL_OBJECT) will return a MultiIndex?

I think we've made a lot of changes to move away from this case. Ideally (for backward compat reasons), the only case where `pandas.Index` returns a `pandas.MultiIndex` should be if `tupleize_cols=True`.

> Will pandas.Index(range(...)) always automatically return a RangeIndex? 

I think so as this might be a hard to change justify since `pandas.Index(range(...))` would return `pandas.Index(..., dtype=np.int64)` after a deprecation cycle which would get rid of the automatic memory benefit. But in theory since `RangeIndex` accepts `range` objects now, a deprecation could be possible for the explicit `RangeIndex(range(...))` call.

> Things like StringIndex and CategoricalIndex will remain separate subclasses, right?

Personally I would be supportive of those subclasses being replaced by `pandas.Index(..., dtype="categorical[...]"/"string")` and dedicated methods being availlable on the `str` and `cat ` accessors. I don't recall immediately why it wasn't included with the other Index subclasses deprecated in 1.4 but I think it would be worth revisiting

**Comment by vyasr** [comment]
I'm happy to discuss some of these possibilities with you going forward. I'm not sure if @shwina (or anyone else) has already had similar discussions about these directions with the pandas maintainers, but it would certainly be nice to try to coordinate our efforts here.

**Comment by vyasr** [comment]
All of these issues have been fixed in the latest version of cudf:
```
In [56]: import cudf
    ...: import pandas as pd
    ...: 
    ...: p1 = pd.DataFrame()
    ...: c1 = cudf.DataFrame()
    ...: print(p1.index)
    ...: print(c1.to_pandas().index)
    ...: 
    ...: p2 = pd.DataFrame([1,2,3])
    ...: c2 = cudf.DataFrame([1,2,3])
    ...: print(p2.index)
    ...: print(c2.to_pandas().index)
    ...: 
    ...: c3 = cudf.DataFrame(columns = [1,2,3])
    ...: p3 = pd.DataFrame(columns = [1,2,3])
    ...: print(p3.index)
    ...: print(c3.to_pandas().index)
RangeIndex(start=0, stop=0, step=1)
RangeIndex(start=0, stop=0, step=1)
RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=3, step=1)
RangeIndex(start=0, stop=0, step=1)
RangeIndex(start=0, stop=0, step=1)
```

Many of these are pandas changes in pandas 2.0.
