### ISSUE TITLE
[FEA] Sort-merge join should support partitioned tables

### ISSUE THREAD

**Issue by nsakharnykh** [rapidsai/cudf#1124]
**Is your feature request related to a problem? Please describe.**
For very large joins when it's impossible to keep the complete hash table in GPU memory, other join algorithms such as the sort-merge join (SMJ) may be interesting. In this scenario, usually both left and right tables are sorted and then streamed in large partitions, so cuDF needs to perform a join of two sorted partitions. 

**Describe the solution you'd like**
Once the sort-merge join API and implementation are stabilized, we should update the API to support incomplete/partitioned tables, in which case in addition to the output join indices, the join operator should report the range of valid row ids for both left and right sorted partitions. The remaining rows would be appended to the next partition by the higher level framework (e.g. Dask). This way we can keep going through the table partitions and join tables that do not fit in GPU memory.

**Comment by jrhemstad** [comment]
I think it would be sensible for this to be a separate API from the existing sort-join, because I do not think it makes sense for the algorithm you're proposing to materialize the result tables and instead just return the pairs of matching row indices between the left and right tables.

Furthermore, if the output is just the matching pairs of indices, I think we can represent an "invalid" result as a `-1` value.

**Comment by jrhemstad** [comment]
Closing as we no longer have a sort-merge join. If that changes in the future, we can open a new issue.
