### ISSUE TITLE
[DOC] ColumnView not clickable link in doxygen

### ISSUE THREAD

**Issue by dagardner-nv** [rapidsai/cudf#11295]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/libcudf/stable/classcudf_1_1detail_1_1table__view__base.html#details

**Describe the problems or issues found in the documentation**
The return type of the `column` method `ColumnView` should be a link to the definition of the `column_view` class.

I believe the issue is that in `table_view_base` `ColumnView` is in the template type. 
While in `table_view` its a type alias and most of the methods are inherited from the base.

**Steps taken to verify documentation is incorrect**
Not sure if there is a way in Doxygen to fix this.

**Comment by davidwendt** [comment]
> The return type of the column method ColumnView should be a link to the definition of the column_view class.

The `ColumnView` here is a template type name that can represent either `column_view` or `mutable_column_view` and so making it link to just `column_view` would be incorrect and it is not possible to link to both.

**Comment by dagardner-nv** [comment]
Ahh OK that makes sense, any chance it could be a link to `column_view_base` then?
If not, OK to close.

**Comment by davidwendt** [comment]
> Ahh OK that makes sense, any chance it could be a link to `column_view_base` then?

I don't see how doxygen would do that with the given source code. Also, I don't agree that this should link to `column_view_base` since `ColumnView` would not be strictly that type.

The doxygen [here](https://docs.rapids.ai/api/libcudf/stable/classcudf_1_1detail_1_1table__view__base.html#details) does look poorly formed so I'm inclined to clean it up and add a comment that `ColumnView` is expected to be either a `column_view` or a `mutable_column_view`.

**Comment by davidwendt** [comment]
Closed by #11340
