### ISSUE TITLE
[BUG] to_json ignores index=True

### ISSUE THREAD

**Issue by dagardner-nv** [rapidsai/cudf#11317]
**Describe the bug**
Documentation for the `index` argument for `cudf.DataFrame.to_json` https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.to_json.html
states:

> indexbool, default True
Whether to include the index values in the JSON string. Not including the index (index=False) is only supported when orient is ‘split’ or ‘table’.

However this is ignored, and appears to be caused by Pandas as cudf's to_json uses Panda's to_json.
https://github.com/pandas-dev/pandas/issues/37600

**Steps/Code to reproduce bug**
Issue can be reproduced in both cudf and pandas.

cudf repro:
```python
import cudf

df = cudf.DataFrame([3,4,5,6])

# Including CSV output for comparison
print(df.to_csv(header=True, index=True))

print(df.to_json(index=True, orient="records"))
```
Yields this output:
```
,0
0,3
1,4
2,5
3,6

[{"0":3},{"0":4},{"0":5},{"0":6}]
```

Pandas repro:
```python
import pandas

df = pandas.DataFrame([3,4,5,6])

# Including CSV output for comparison
print(df.to_csv(header=True, index=True))

print(df.to_json(index=True, orient="records"))
```

**Expected behavior**
Include index column when `index=True`

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Comment by GregoryKimball** [comment]
Thank you for raising this issue. `cudf.DataFrame.to_json` currently uses a host-fallback to pandas, and it seem that the `index` argument is not correctly passed. 

Seems like this could be related to other changes in #11780

**Comment by galipremsagar** [comment]
@dagardner-nv 

This is expected behavior in pandas `to_json`, which is documented here: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html

![Screen Shot 2022-11-01 at 5 03 28 PM](https://user-images.githubusercontent.com/11664259/199350534-f35e4bb7-3036-4825-a50a-e67cdc2082db.png)

However if you really need index data in json, you will need to pass `orient='index'` instead, which is shown in the example right below:
![Screen Shot 2022-11-01 at 5 04 21 PM](https://user-images.githubusercontent.com/11664259/199350680-c9fc2f68-5d95-4e25-b436-433ecd06b01d.png)

Both these example have been snapshotted from the [to_json docs page](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_json.html)

Hence closing this issue on cudf side as there is no action item.
