### ISSUE TITLE
[FEA] Series.floor method is removed in version 22.06

### ISSUE THREAD

**Issue by alwaysprep** [rapidsai/cudf#11331]
I looked at the changelog but I could not see any remark on floor method for version 22.06. Was removing it intentional or it was mistake? If it was intentional what was the reason? Also is there any alternative right now?

**Comment by shwina** [comment]
Hi @alwaysprep - you could use the `.apply()` method to compute the `floor` or `ceil`:

```python
>>> import math
>>> import cudf
>>> s = cudf.Series([1.5, 2.2, None, 1.7])
>>> s.apply(lambda x: math.floor(x))
Out[17]:
0     1.0
1     2.0
2    <NA>
3     1.0
dtype: float64
```

**Comment by beckernick** [comment]
Thanks for filing an issue. We make a concerted effort to mark any public API changes with a `DeprecationWarning` for a release before removing them. Removal of this functionality have slipped through the cracks due it not being explicitly supported in our API (i.e., we didn't have a `floor` function exposed on `Series`).

Following pandas, we provide `Series.dt.floor` and (in theory) I believe we do not support `Series.floor`. In the past, it's possible we were providing this API implicitly, perhaps due to the way in which we were handling NumPy (CuPy) ufuncs (the behavior that allows you to do `np.floor(pandas_series)` but not `pandas_series.floor()`, and the equivalent with cuDF).

Hopefully the workaround noted above resolves your problem. This `apply` approach is preferred to `cupy.floor(ser)` as it handles null values. We'll take a look at our ufunc handling to see if this may have happened with any other APIs.

I'm going to close this issue as answered, but please feel free to reopen.

**Comment by vyasr** [comment]
Just to add some information here to @beckernick and @shwina explanations: we did explicitly support `Series.floor`, but we removed it because pandas does not have a comparable API in favor of asking users to use numpy. The simplest solution here is the same, using numpy. Unfortunately, due to some subtleties in the ways that `cupy` handles the ufunc protocol you won't get some nice things like null handling (as noted by Nick above), but you should with numpy:
```
>>> import cupy as cp
>>> import numpy as np
>>> import cudf
>>> s = cudf.Series([1, None, 3.5])
>>> np.floor(s)
0     1.0
1    <NA>
2     3.0
dtype: float64
>>> import math
>>> s.apply(lambda x: math.floor(x))
0     1.0
1    <NA>
2     3.0
dtype: float64
>>> cp.floor(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "cupy/_core/_kernel.pyx", line 1218, in cupy._core._kernel.ufunc.__call__
  File "cupy/_core/_kernel.pyx", line 138, in cupy._core._kernel._preprocess_args
  File "cupy/_core/_kernel.pyx", line 113, in cupy._core._kernel._preprocess_arg
  File "cupy/_core/core.pyx", line 2640, in cupy._core.core._convert_object_with_cuda_array_interface
ValueError: CuPy currently does not support masked arrays.
```
