### ISSUE TITLE
[FEA] Computing optimal partition bounds

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1134]
It is a common pattern to partition a dataset into a set of `N` buckets/partitions. 

For example, [`gdf_hash_partition`](https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/include/cudf/functions.h#L720 ) re-partitions the rows of a set of columns based on the hash value of each row. However, it assumes that each partition size is the same. This can lead to load imbalance where the number of keys in each partition are non-uniformly distributed. 

There is a large body of work on computing the optimal partition boundaries based on computing a histogram of the size of each partition, and then splitting partitions to provide a more optimal, uniform distribution of partition sizes.

If we implemented this as a generic primitive operation, it could be reused for several features such as `gdf_hash_partition`, sorting, etc.

**Comment by jrhemstad** [comment]
Here's a good paper on doing the bucket-histogram operation: http://www.vldb.org/pvldb/vol8/p1518-cho.pdf

**Comment by jeaton32** [comment]
This also comes up in graph analytics, but with a twist that makes it a lot harder. We have two sets to partition, edges and vertices, and each vertex is directly associated with a subset of edges. Usually we want to balance load AND minimize communications at the same time, since it's assumed some edges will have to be 'cut' to achieve a balanced partition.  This leads to the 'min-cut' partitioner family, METIS is one example.  In other cases we want to partition not for the sake of compute, but to find some inherent propery of the graph itself, this is usually called 'clustering'.  Clustering and partitioning are inherently different things, so we can't just throw out one of them.  Clustering allows for overlaps between the parts for example, partitioning requires the intersection is empty and the union of parts forms the whole graph. 
For compute, to achieve load balance, we have very similar needs to the hash-partition approach above.  We might be able to use the same methods in these cases.   For clustering, dynamic clustering, dynamic load balancing, we have much different needs.

**Comment by jrhemstad** [comment]
Relevant paper, "GPU Multisplit": https://dl.acm.org/citation.cfm?id=2851169

**Comment by vyasr** [comment]
Closing as stale for now. The definition of an optimal partition is somewhat context-dependent, so we can reopen if we find a use case where this becomes important.
