### ISSUE TITLE
Old issue( std::bad_alloc: CUDA error at: /workspace/.conda-bld/work/include/rmm/mr/device/cuda_memory_resource.hpp:70: cudaErrorNotSupported operation not supported)

### ISSUE THREAD

**Issue by Shafi2016** [rapidsai/cudf#11382]
Hi,

I'm getting the error given below and using the WSL2 Ubuntu 20.04 instance on Windows 11 Preview.

RuntimeError: CUDA error encountered at: /workspace/.conda-bld/work/cpp/src/bitmask/null_mask.cu:93: 801 cudaErrorNotSupported operation not supported.

I saw old posts but could not find the solution. The following chunk of codes works fine 
```

import cudf; print('cuDF Version:', cudf.__version__)
import numpy as np; print('NumPy Version:', np.__version__)
```
output

cuDF Version: 22.06.01
NumPy Version: 1.22.4

![image](https://user-images.githubusercontent.com/56795978/181431625-1e4c00c5-56c6-4ecf-9aa3-8ce97f33b9f3.png)

```
s = cudf.Series([1,2,3,None,4])
s
```
![image](https://user-images.githubusercontent.com/56795978/181431791-cc89db08-e16e-412b-b2af-160819f02d9a.png)

**Comment by bdice** [comment]
@Shafi2016 What kind of GPU do you have? I see `GeForce ...` in the output of `nvidia-smi`. It sounds like a previous issue concluded that Pascal GPUs (which would include the GeForce 10xx series) are not supported on WSL2. You may need newer hardware to run cuDF on WSL2. See: https://github.com/rapidsai/cudf/issues/9427#issuecomment-975902493

**Comment by Shafi2016** [comment]
> Pascal GPUs

Thank you @bdice. I have GeForce GTX 1050 Ti. So used  [driver](https://www.nvidia.com/Download/driverResults.aspx/190552/en-us/ ). By the way how to know which hardware supports the CuDF.  I followed this  [tutorial](https://developer.nvidia.com/blog/run-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux/)

**Comment by Shafi2016** [comment]
> The WSL2 requirements are listed here: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#known-limitations-for-linux-cuda-apps The RAPIDS requirements are documented here: https://rapids.ai/start.html#requirements From [#9427 (comment)](https://github.com/rapidsai/cudf/issues/9427#issuecomment-975902493) it looks like we may need to update the requirements page specifically for WSL2 and RAPIDS. @JohnZed @beckernick @taureandyernv

Thank you for the updated info.

**Comment by taureandyernv** [comment]
@shafi2016, the GTX1050TI is a Pascal card.  I regret to inform you that the last RAPIDS version to work with WSL2 and Pascal cards was 21.08 IIRC.  We still have conda and docker packages for hat release.  After that release, things stopped working and we haven't yet figured out a workaround or solution for newer versions of RAPIDS.  We hope that it could resolve itself through driver, CUDA, and WSL2 updates, like how running dask-cudf on WSL2 did.  Please remember that WSL2 has Experimental support and we have to prioritize with our limited bandwidth.  I say that as someone who was also affected by this issue and also terribly disappointed at first, but knowing what I know, I'm really understanding about the situation.

While this is not a supported method, you can refer to https://docs.rapids.ai/notices/rgn0024/ for documentation on installing WSL2 on your system and then trying the older versions with the newer driver (I had been using an older driver).  If it works out, please let us know so that we can continue to best advise others in the community who are trying WSL2 and RAPIDS on a Pascal card

**Comment by Shafi2016** [comment]
Thank you, @taureandyernv, for the detailed note. It is indeed encouraging. Let me do the experiments.

**Comment by mattharrison** [comment]
I'm running into the same error with 22.08 and 22.10 on my WSL2 machine. I have a Quadro P1000 card. 

Is there a known older version that works? (FWIW Cupy seems to work just fine with my card).

**Comment by taureandyernv** [comment]
@mattharrison , 21.08 had success on the P1000 (I have one too), but ymmv, as I did the old install method as well.  Let us know if you are successful

**Comment by mattharrison** [comment]
I used the conda command generated from the "Install Rapids" gui/thing https://rapids.ai/start.html#get-rapids

**Comment by taureandyernv** [comment]
wsl2 had a few changes to the installation method.  I don't know if there are breaking changes that occurred for 21.08's compatibility with the P series cards.  Try both conda and docker and it would be awesome to get an update on if it still works.

**Comment by mattharrison** [comment]
For those following along at home, I was able to get version 21.08 installed with this command and create dataframes succesfully!

` conda create -n rapidsai -c rapidsai -c nvidia -c conda-forge      cudf=21.08 python=3.8 cudatoolkit=11.4`

**Comment by davidwendt** [comment]
Closing this as resolved. Feel free to reopen if there is new information.
