### ISSUE TITLE
Investigate changing `get_extremum` to a type dispatch function in parquet statistics

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#11468]
As brought up in the review of some statistics code and also Jake has mentioned it as well. The function `get_extremum` is basically a pile of if/else if and calling the correct function, it seems like this should be a type dispatch.

_Originally posted by @hyperbolic2346 in https://github.com/rapidsai/cudf/pull/11403#discussion_r937319177_

**Comment by karthikeyann** [comment]
Discussed with @hyperbolic2346 offline.
Right now, this code is changes to a switch case statement.
Not all enums of `statistics_dtype` has equivalent type. So, IdTypeMap does not have equivalent types. Also, it's not used more than twice, and hence does not warrant to create own dispatcher. Even if we created a dispatcher, the generated code will almost identical to existing switch statement, with additional SFINAE conditions.
So, I suggest to close the issue since the current code is at better state, and readable.

**Comment by hyperbolic2346** [comment]
I agree here. The big killer is the type mapping. We don't have types for byte_array. This is mapping parquet statistics dtypes, not cudf types. If we built our own type dispatcher, it wouldn't be used much and add to the cognitive overload.
