### ISSUE TITLE
Rapids take >42 minutes to install on google colab pro.

### ISSUE THREAD

**Issue by priyanshu7401** [rapidsai/cudf#11529]
Hi all,
   I have been trying to use the rapids library in my project but rapids take close to 42 minutes to installation. If my notebooks get disconnected or I change the runtime type, I have to install it again, is there any better solution to this problem?
Regards

**Comment by shwina** [comment]
Hi @priyanshu7401 - thanks for reporting, and sorry for the trouble you've been having with Colab. 

Please note that because Colab [does not support Python 3.8+](https://github.com/googlecolab/colabtools/issues/2165), we can not support RAPIDS on Colab at this time. The last version of RAPIDS that _should_ work with Colab is 21.12, and that is too old for us to test and maintain. If you are using the demo notebook provided at https://rapids.ai/start.html to install RAPIDS on Colab, we cannot guarantee that it will work. I apologize.

If/when Colab supports newer versions of Python, you should be able to run RAPIDS on it.

Generally speaking though, when installing RAPIDS via `conda`, the dependency resolver can take a while to run. In our experience, [`mamba`](https://mamba.readthedocs.io/en/latest/) is much faster. (I understand that this information may not be very useful to you right now).

**Comment by vyasr** [comment]
This should no longer be an issue, see https://colab.google/articles/cudf
