### ISSUE TITLE
[QST] What happens in map_partitions under the hood? 

### ISSUE THREAD

**Issue by maxbalrog** [rapidsai/cudf#11591]
Hello! I'm interested in some details what actually happens when one calls `df.map_partitions(func)` where `func` has some common parameters for multiple GPUs. I would appreciate comments.

Here is an example. Transformer `MinTransformer` after `fit` method has an attribute `self.min` which is located on gpu-0. When one calls `df.map_partitions(self._transform)` (df is a dask_cudf dataframe with two partitions located at gpu-0 and gpu-1), how the 2nd partition uses `self.min` attribute? Is there some `scatter` call happening at the beginning of dask graph execution?
```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client

cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="0,1")
client = Client(cluster)

import cudf
import dask_cudf
import cupy as cp

class MinTransformer:
    def __init__(self):
        pass

    def fit(self, df):
        self.min = df.min(axis=0).compute()
        print(type(self.min))

    def _transform(self, df):
        return df - self.min

    def transform(self, df):
        new_df = df.map_partitions(self._transform)
        return new_df


df = cudf.DataFrame({'age': [10, 20, 30, 40, 50, 60],
                     'result': [5, 4, 6, 5, 3, 7]})
df_daskcudf = dask_cudf.from_cudf(df, npartitions=2)

cls = MinTransformer()
cls.fit(df_daskcudf)
output = cls.transform(df_daskcudf)
print(output.compute())
```
```
<class 'cudf.core.series.Series'>
   age  result
0    0       2
1   10       1
2   20       3
3   30       2
4   40       0
5   50       4

```

**Comment by wence-** [comment]
> Here is an example. Transformer MinTransformer after fit method has an attribute self.min which is located on gpu-0. When one calls df.map_partitions(self._transform) (df is a dask_cudf dataframe with two partitions located at gpu-0 and gpu-1), how the 2nd partition uses self.min attribute? Is there some scatter call happening at the beginning of dask graph execution?

There are a few things going on here. dask is offering a data-parallel API where the dataframe is divided up (in some way) between the available GPUs. Although it doesn't look like it, there are actually three(*) python processes in the loop in this example. The code you write is all executed on the process that owns the `client`, which is connected to the two python processes that were launched by `LocalCUDACluster`.

[(*) this is a minor simplification but I'll brush that under the carpet]

So in this example, you make the initial `df` on the client process, and then `from_cudf` scatters that dataframe to the two worker processes (which each get half of the dataframe). When you call `cls.fit`, `df_daskcudf.min` asks the workers to call `min` on each piece and the does a reduction to combine those results. Calling `compute()` on that object then says "please pull the result of this computation back to the client":
```
n [74]: df_daskcudf
Out[74]: <dask_cudf.DataFrame | 2 tasks | 2 npartitions>

In [75]: df_daskcudf.min(axis=0)
Out[75]: <dask_cudf.Series | 5 tasks | 1 npartitions>
In [76]: df_daskcudf.min(axis=0).compute()
Out[76]: 
age       10
result     3
dtype: int64
```

So now you call `cls.transform` on the distributed dataframe which does `df - self.min`, since every worker needs the min, then dask broadcasts the `self.min` data from the client out to the workers which can then subtract things locally. Finally, the last `compute()` call again pulls the results back to the client from the workers
```
In [77]: df_daskcudf - df_daskcudf.min(axis=0).compute()
Out[77]: <dask_cudf.DataFrame | 5 tasks | 2 npartitions>

In [78]: (df_daskcudf - df_daskcudf.min(axis=0).compute()).compute()
Out[78]: 
   age  result
0    0       2
1   10       1
2   20       3
3   30       2
4   40       0
5   50       4
```

Note that if you're running with `LocalCUDACluster` (and hence dask + distributed) it is often the case that it makes more sense to call `some_operation.persist()` over `some_operation.compute()`. As noted above, the latter pulls the data back to the client (so if you have a large dataframe distributed across many GPUs you pay the cost of concatenating the pieces and storing them all on the client), the former just says "please make sure that the result of this computation is stored, distributed in some sense, amongst the workers". A reasonable rule of thumb is to say that you use `compute` when what you want to do is look at some "small" aggregated final result, whereas `persist` is when you think that this is the result of a computation that the workers should hold on to.

This model of computation takes a little bit of getting used to, it's worthwhile reading through some of the introductory material on the [distributed documentation site](https://distributed.dask.org/en/stable/index.html) as well as the computational model in dask ([10 minutes to dask](https://docs.dask.org/en/stable/10-minutes-to-dask.html) is a good overview).

**Comment by maxbalrog** [comment]
@wence- thanks for a really comprehensive answer! I guess I'm going on an adventure into the documentation world...
