### ISSUE TITLE
Move functions in jit/type.hpp into the main cudf namespace

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#11673]
The functions in [jit/type.hpp](https://github.com/rapidsai/cudf/blob/branch-22.10/cpp/src/jit/type.hpp) are used in a number of places outside of the JIT namespace. Although they may have initially been introduced to support JIT use cases, at this point that choice of namespace seems inappropriate. `jit::get_type_name` should probably be defined in `types.hpp`, while the two `get_data_ptr` overloads should probably live in `column_view.hpp` and `scalar.hpp`.

**Comment by vyasr** [comment]
The original description on this issue is not accurate. The JIT functions are almost exclusively used within JIT context, whether they be binaryops, rolling, or transforms. The one exception is what was originally raised [here](https://github.com/rapidsai/cudf/pull/11129#discussion_r964284620).

@bdice what would you like to do here? We're pretty much exclusively making use of the JIT function to provide a nice error message in that code, which I think is helpful but we can remove it if you have a better alternative to using this function (or feel strongly that including the name of the type in the error message isn't strictly necessary).

**Comment by bdice** [comment]
Let's break it down by function. Overall this feels like it should be named `jit/util.cpp` instead of `jit/type.cpp` if we keep it. It's not defining any types (only a type-stringify function in `get_type_name`) and _barely_ deals with types in the context of `get_data_ptr`.

### `jit::get_data_ptr`

I don't see any similar functionality to this elsewhere in libcudf. I think this is necessary but could fit better in a `util.cpp`.

### `jit::get_type_name`

For error messages, I think this can be replaced by the [`type_to_name` dispatch that it uses as a fallback](https://github.com/rapidsai/cudf/blob/08ffeccca565aff25f7ca0e718bde8de99dffd35/cpp/src/jit/type.cpp#L84). I don't think we need to have special names for lists/structs/decimal types in error messages -- only in special JIT contexts where that name mapping is meaningful. It would be good enough (or even better) for errors to say `cudf::list_view` or `cudf::numeric::decimal32` as far as I am concerned. Cases where this type name is used for code generation, however, may not be replaceable. I propose:
- Eliminate uses of `jit::get_type_name` for error messages across the code base - just use `type_to_name`.
- Clarify the docs or name of `jit::get_type_name` to reflect its uses in JIT code generation. It's a special name that is returned, not literally the type's name (as suggested by its use in error messages). Based on how this is used for decimal types, maybe it could query for the name of the underlying "representation type" (if applicable) instead of having a custom path for the string generation. That is, maybe we can separate the "type mapping" from the "stringify name mapping."

**Comment by vyasr** [comment]
Assigning to @bdice after offline discussion. I agree on the steps to take. The only places where we need to remove the usage of `get_type_name` for error messages that I am aware of are in `cpp/src/table/row_operators.cu` as introduced by the list lexicographic comparator.

**Comment by bdice** [comment]
I think #12158 will solve this. I deleted `get_type_name`, refactored the type-to-name dispatch, and renamed `src/jit/type.{cpp,hpp}` to `src/jit/type.{cpp,hpp}`.
