### ISSUE TITLE
All null string column representation

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#11756]
**What is your question?**

For a string column containing all null values, is it a valid cudf column representation to have no children while having a non-zero size and an allocated nullmask?
```
column = {
  data = nullptr
  nullmask = 000
  size = 3
  children = {}
}
```

This seems to suggest it is valid https://github.com/rapidsai/cudf/blob/ca952f8355810c46bb132f0b50a67e4109108ccb/cpp/src/column/column_factories.cu#L63

But the string column factories prevent this https://github.com/rapidsai/cudf/blob/f4f34287dadd9ee9a946b253aa045ba3256028b6/cpp/src/strings/strings_column_factories.cu#L155

There might be a concern that to allow this, there would have to be a check of num_values == num_nulls, which might require a kernel launch to get num_nulls from the passed nullmask. Considering we can pass an explicit null_count, there won't be a requirement to launch this kernel.

**Comment by davidwendt** [comment]
I don't think we have a strings-column factory that would create such a column since all of the factory functions take something to tell it how big the column is to be. I don't think the libcudf code will generally handle an all null-column with no data/children regardless if it is strings column or not.

**Comment by devavret** [comment]
> I don't think we have a strings-column factory that would create such a column since all of the factory functions take something to tell it how big the column is to be.

Some factories accept the column size.
https://github.com/rapidsai/cudf/blob/f4f34287dadd9ee9a946b253aa045ba3256028b6/cpp/src/strings/strings_column_factories.cu#L142
https://github.com/rapidsai/cudf/blob/f4f34287dadd9ee9a946b253aa045ba3256028b6/cpp/src/strings/strings_column_factories.cu#L117
 
> I don't think the libcudf code will generally handle an all null-column with no data/children regardless if it is strings column or not.

@felipeblazing found some APIs (`cudf::make_column_from_scalar`) that create such a column. And that seems to consider this valid. https://github.com/rapidsai/cudf/blob/ca952f8355810c46bb132f0b50a67e4109108ccb/cpp/src/column/column_factories.cu#L63 and some other APIs that work fine when passed this kind of column.

**Comment by davidwendt** [comment]
I did a quick scan through the code and found many places that would fail for strings and lists column if there were no offsets child.

**Comment by devavret** [comment]
Alright, then this just means that there's a bug in `make_column_from_scalar`

**Comment by davidwendt** [comment]
I will look into this more today in the context of strings only. Most of the code should handle this fine since we should not try to access any data elements for null rows. I think that we should fix the code that accesses the offsets directly or fix `make_column_from_scalar`.

**Comment by davidwendt** [comment]
After looking through several functions that would fail with a non-empty, all-null column with no children, I think it would be best to fix the `make_column_from_scalar`. The deciding factor is the case where a column is sliced and the resulting elements are all null. Rather than adding special logic for all these considerations, I think it best to fix the `make_column_from_scalar`. We can re-label this issue as a bug.
