### ISSUE TITLE
[FEA] The final step of the parquet preprocess step can get very slow for highly complicated schemas.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#11922]
For parquet files that contain columns with lists in them, we do a preprocess step to compute column sizes (and other information).  As a very last step, we iterate over the input columns and march through them by depth here:

https://github.com/rapidsai/cudf/blob/e91d7d9ef1eb3128de99f78d0127050bb12110d4/cpp/src/io/parquet/page_data.cu#L1827

For very complicated schemas, this can result in a large number of calls to `thrust::reduce()` and `thrust::exclusive_scan_by_key()`. In some cases, cases, so much so that it can dominate the rest of the decompress/decode work.

We should spend some time figuring out how to coalesce this into fewer (perhaps 1 each of `reduce_by_key` and `exclusive_scan_by_key`) calls.

**Comment by nvdbaranec** [comment]
@abellina

**Comment by vyasr** [comment]
@SrikarVanavasam FYI [Github supports certain keywords to automate linking issues to PRs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword). If you had commented `Closes #11922` instead of `Addresses #11922` in it would have automatically linked and closed this issue when the PR merged. For future reference :smile:
