### ISSUE TITLE
[FEA] Pipeline IO, decompression and decoding in Parquet reader for performance improvements

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#11951]
**Is your feature request related to a problem? Please describe.**
Parquet reading has three distinct steps: reading data from disk, decompressing, and processing the data. These are accomplished in series, the entire file is read from disk before decompression or processing begins. This feature request is to overlap these parts of the work for a performance increase. 

**Describe the solution you'd like**
Chunk the reads into a natural boundary such as a page or row group and asynchronously read the next chunk while the current chunk is decompressing and processing.

**Comment by GregoryKimball** [comment]
@hyperbolic2346 thank you for your work exploring performance improvements in the parquet reader based on pipelining the work across multiple streams. Although this work did not result in a pipelining pattern ready to be applied for the libcudf parquet reader, we did learn important lessons along the way.

1. Given the details of the parquet format, it is difficult to compute the size of a column without seeing all of the data. This is primarily a problem for `list` types.
2. We need to pre-allocate our working buffers to prevent extra stream syncs, but this is harder to do efficiently because of (1)
3. The relative time of IO, decompression and decoding vary based on the details of each file. If the pipelined steps are unbalanced and bottlenecked by one of the operations, then the benefit of overlapping work may not outweigh the overhead introduced by pipelining.

We are still interested in pipelining the parquet reader as well as other IO operations in cuIO. The next deep dive we do in this area should focus on design challenges for `list` and deeply nested `list` types.

**Comment by GregoryKimball** [comment]
Closing in favor of https://github.com/rapidsai/cudf/issues/13828
