### ISSUE TITLE
[BUG] Passing a dict of dtypes to cudf.read_csv causes core dump

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#1198]
[Pandas's read_csv method](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) accepts a dict of column names and dtypes:
```
dtype : Type name or dict of column -> type, optional
Data type for data or columns. E.g. {‘a’: np.float64, ‘b’: np.int32, ‘c’: ‘Int64’} Use str or object together with suitable na_values settings to preserve and not interpret dtype. If converters are specified, they will be applied INSTEAD of dtype conversion.
```
cudf.read_csv accepts a list of strings that must be in the same order as column names.

Description of Request:
cudf.read_csv should detect and support dtypes as either a list or a dict.

If dtype was supplied as a list, throw a warning noting that lists of dtypes are deprecated and users should supply a dict instead.

**Comment by beckernick** [comment]
From a quick debugging on the Python side, this appears to be coming from the line
`libgdf.read_csv(csv_reader)` inside the `read_csv` in the Python bindings, which makes this a bug instead of a feature request. The `read_csv` call causes a core dump when a dictionary is passed to the dtype keyword argument:

```
import cudf
dtypes = {'A':'str', 'B':'str', 'C':'int'}
gdf = cudf.read_csv('foo.csv', dtype=dtypes)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted (core dumped)
```
I'm going to update the label from cuDF (Python) to libcuDF (C++/CUDA), and switch the category to be a bug.

**Comment by AK-ayush** [comment]
This error is coming because the case, when `names` is None and `dtypes` is a dict is not handled in `csv.py`. If you provides the columns names in `names` and provide `dtypes` as dict, it works.

I am working on it and will submit a PR asap.
