### ISSUE TITLE
[FEA] Support a strings_column_view as the target parameter in cudf::string::find

### ISSUE THREAD

**Issue by amahussein** [rapidsai/cudf#12013]
**Is your feature request related to a problem? Please describe.**
Currently there is a limitation in RAPIDS plugin to support some string functions such as instr and locate `instr(column, column)`.
The plugin can do partial support (column, scalar)
To fully support the string operations, ColumnView.stringLocate needs to support two columns as arguments.

**Additional context**

- https://github.com/NVIDIA/spark-rapids/issues/6884
- https://github.com/NVIDIA/spark-rapids/issues/6930

**Comment by ttnghia** [comment]
Related cudf API: `cudf::strings::find`, which currently only supports `(column, scalar)` parameter pair. We need `(column, column)` parameter pair to close this issue..

**Comment by revans2** [comment]
Supporting a start and stop as columns would also be awesome.

**Comment by davidwendt** [comment]
Can you provide an example of input and expected output for this function as well as limitations perhaps?
Also, there is an existing `cudf::strings::find_multiple` function that accepts a `strings_column_view` as the target parameter that maybe could be considered?
https://docs.rapids.ai/api/libcudf/stable/group__strings__find.html#ga908b46bbd1eacdf6a008c0450e820297

**Comment by revans2** [comment]
This is for the Spark/SQL `locate`, `instr` functions or `POSITION IN` expression.

https://spark.apache.org/docs/latest/api/sql/index.html#locate
https://spark.apache.org/docs/latest/api/sql/index.html#instr

The common use case of `locate('ABC', someStringColumn)` we support using `cudf::strings:find` which can take `ABC` as a `string_scalar`.  `find_multiple` does not work because we need an API with a one to one relationship between the rows.

| strings | target | locate(target, strings, 1) |
|-|-|-|
|ABCDEFGHIJKLMNOP|     A|                         1|
|ABCDEFGHIJKLMNOP|     B|                         2|
|ABCDEFGHIJKLMNOP|     C|                         3|
|ABCDEFGHIJKLMNOP|     D|                         4|
|ABCDEFGHIJKLMNOP|     E|                         5|
|ABCDEFGHIJKLMNOP|     f|                         0|
|abcdefghijklmnop|     g|                         7|
|ABCDEFGHIJKLMNOP|  null|                      null|
|            null|     H|                      null|

Ideally any null input would result in a null output, and if the value is not found we would get a 0 back.

We adjust the start and end indexes to match what is being requested by the `pos` in locate and we could continue to support that for only scalar values.

**Comment by davidwendt** [comment]
For consistency with the other `find` functions (and `cudf::strings` function in general), position values are always 0-based indexed which means locating the target in the first position of the source string would return `0`. Likewise, specifying a location `0` means include the first character in the search. And if the target is not found, return `-1`.

Some documentation that mentions 0-based indexing.
https://docs.rapids.ai/api/libcudf/stable/group__strings__find#gad8c350177450eeb7f0bab04f51e39dd2
https://docs.rapids.ai/api/libcudf/stable/group__strings__find#gabb2a72f7974b2738efe2657cedb79d5e
https://docs.rapids.ai/api/libcudf/stable/group__strings__find#ga908b46bbd1eacdf6a008c0450e820297
https://docs.rapids.ai/api/libcudf/nightly/group__strings__replace#gaf32673f092aff04905bbc815129e702b
