### ISSUE TITLE
[FEA] Allow creation of nullable Index objects via `to_pandas`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#12216]
**Is your feature request related to a problem? Please describe.**
We currently support converting a `cudf.Series` to a pandas nullable Series by doing `series.to_pandas(nullable=True)`. But pandas recently added support for nullable types in `pd.Index`, so we should add support for `index.to_pandas(nullable=True)` to be possible.

**Comment by bdice** [comment]
The test function `test_index_hasnans` should be updated from #12214 when this feature is added.

**Comment by galipremsagar** [comment]
> The test function `test_index_hasnans` should be updated from #12214 when this feature is added.

Sounds good

**Comment by mroeschke** [comment]
If possible, allowing the user to chose the nullable type e.g. `pd.ArrowDtype(pa.int64)` vs `pd.Int64Dtype` would be great to include

**Comment by galipremsagar** [comment]
> If possible, allowing the user to chose the nullable type e.g. `pd.ArrowDtype(pa.int64)` vs `pd.Int64Dtype` would be great to include

@mroeschke is there a good documentation where we can learn how pandas uses arrow types? or is it configurable by pandas options or a variable?

**Comment by mroeschke** [comment]
As of 1.5.2, user typically need to specify `dtype="<type>[pyarrow]"` or `dtype=pd.ArrowDtype(pa.<type>())` to opt into the pyarrow types, but otherwise a lot of common operations work similarly with these types. Actually, since this issue is specifically referencing converting `Index` objects, my suggestion may be a bit premature. `pandas.Index` can _store_ arrow types but the _indexing operations_ (engine) work on numpy arrays currently

The documentation isn't too great right now. https://pandas.pydata.org/pandas-docs/stable/reference/arrays.html#pyarrow is the only documentation.
