### ISSUE TITLE
Cudf vs Spark discrepancies when comparing nested list column with null entries

### ISSUE THREAD

**Issue by cindyyuanjiang** [rapidsai/cudf#12298]
**Is your feature request related to a problem? Please describe.**
When we test `order by` on array of array (of short) with null entries, we find the following discrepancy.
For Spark,
`[[None], [-21827]] < [[None, None], [40, -21636], [None, None, -7359, 0], [13408], [-25000, 21133, -14473]]`
For Cudf, the above is false.

Due to this issue, we cannot support `order by` on nested list column (e.g. array of array type).

**Additional context**
Cudf supports nested list column comparison https://github.com/rapidsai/cudf/pull/11129.

**Comment by revans2** [comment]
@cindyyuanjiang can you clarify this a bit more, and possibly make the repro case simpler? What are the data types involved here?  Is it `LIST<LIST<INT32>>`?

Also can we simplify the data and possibly help to track down exactly what is different about this.  Does CUDF sort `[None] vs [None, None]` correctly? Is CUDF missing that arrays of null values are equal if they have the same length, but need to also be sorted by length shortest first? Or does it take more data to reproduce the issue?

**Comment by ttnghia** [comment]
Here is a reproducible test in cudf:
```
using lcw = cudf::test::lists_column_wrapper<T, int32_t>;
  using cudf::test::iterators::nulls_at;
  lcw col{
    lcw{lcw{{0}, nulls_at({0})}, lcw{-21827}},  // 0
    lcw{lcw{{0, 0}, nulls_at({0, 1})},
        lcw{40, -21636},
        lcw{{0, 0, -7359, 0}, nulls_at({0, 1})},
        lcw{13408},
        lcw{-25000, 21133, -14473}}  // 1
  };

  auto result = cudf::sorted_order(cudf::table_view({col}));
  cudf::test::print(*result);
```
Output:
```
1,0
```

**Comment by ttnghia** [comment]
Here is the output in Spark with the same example:
```
scala> val df = Seq(Seq(Seq[Integer](null), Seq[Integer](-21827)), Seq(Seq[Integer](null, null))).toDF
df: org.apache.spark.sql.DataFrame = [value: array<array<int>>]

scala> df.show
+------------------+
|             value|
+------------------+
|[[null], [-21827]]|
|    [[null, null]]|
+------------------+


scala> df.orderBy("value").show
+------------------+
|             value|
+------------------+
|[[null], [-21827]]|
|    [[null, null]]|
+------------------+
```

**Comment by revans2** [comment]
Thanks @ttnghia

**Comment by cindyyuanjiang** [comment]
Thank you @revans2 @ttnghia! My observation aligns with the above repro case.

**Comment by ttnghia** [comment]
Another example:
Spark:
```
scala> val df = Seq(Seq(Seq[Integer](1), Seq[Integer](2)), Seq(Seq[Integer](1, null), Seq[Integer](2,3))).toDF
df: org.apache.spark.sql.DataFrame = [value: array<array<int>>]

scala> df.show
+-------------------+
|              value|
+-------------------+
|         [[1], [2]]|
|[[1, null], [2, 3]]|
+-------------------+


scala> df.orderBy("value").show
+-------------------+
|              value|
+-------------------+
|         [[1], [2]]|
|[[1, null], [2, 3]]|
+-------------------+
```

libcudf gives an opposite order:
```
auto const col = lcw{lcw{lcw{1}, lcw{2}}, lcw{lcw{{1, 0}, nulls_at({1})}, lcw{2, 3}}};
auto result    = cudf::sorted_order(cudf::table_view({col}), {});
cudf::test::print(*result);

Output: 1, 0
```

**Comment by GregoryKimball** [comment]
Thank you @cindyyuanjiang and @ttnghia for studying these comparisons!

I've reviewed the design notes from @devavret and #11129 - and I believe our lexicographic comparison for lists is failing in the case where a `null` leaf element in one item aligns with a starting list element in another item.

I'll need to get into the implementation details to explain this. When we compare list items lexicographically, for each leaf element we generate a "definition level" based on the depth of nesting combined with the empty/null state and a "repetition level" based on the relationship with the previous leaf element. The "definition level" integer is compared first, followed by the "repetition level" integer, followed by the leaf value to compute the comparison. Here is the detailed comparison for the last example from @ttnghia:

```
[[1],[2]]
def  5 5
rep  0 1
val  1 2

[[1, None], [2,3]]
def  5 4 5 5
rep  0 2 1 2
val  1 - 2 3
```

You can see why  `[[1],[2]]` compares as greater than `[[1, None], [2,3]]` - it's because the "definition level" for the second leaf element is greater. In this case we should have considered the "repetition level" to make the comparison, reflection that the second leaf element of `[[1],[2]]` starts a new list.

It's fair to characterize this issue as a bug in the list lexicographic comparator. We will take a closer look and evaluate our options for addressing this.

**Comment by divyegala** [comment]
For this example, @GregoryKimball please correct me if it looks wrong:
```  
using lcw = cudf::test::lists_column_wrapper<T, int32_t>;
using cudf::test::iterators::nulls_at;
lcw col{
  lcw{lcw{{0}, nulls_at({0})}, lcw{-21827}},  // 0
  lcw{lcw{{0, 0}, nulls_at({0, 1})}}          // 1
};

auto result = cudf::sorted_order(cudf::table_view({col}));
cudf::test::print(*result);
```
  
I believe the Dremel encoding is:
```
[[[NULL], [-21827]], [[NULL, NULL]]
Def: 4, 5, 4, 4
Rep: 0, 1, 0, 2
```
Going by the early exit criterion for `definition level` at [this](https://github.com/rapidsai/cudf/blob/d24bf11838863739da014d828156e8bf638430ff/cpp/include/cudf/table/experimental/row_operators.cuh#L449) line, we can see why the answer is `1, 0`
