### ISSUE TITLE
Aggregation Unique supports the list format.

### ISSUE THREAD

**Issue by mjshare** [rapidsai/cudf#12437]
Aggregation Unique supports the list format. Does the community have a plan?

**Comment by beckernick** [comment]
Could you provide a little bit more information?

Are you working in C++ or Python? Are you looking for a way to get the unique elements per list, the unique lists across a column, or something else?

**Comment by GregoryKimball** [comment]
Hello @mjshare thank you for your message. I believe the issue here is that we don't support `groupby` aggregations on List columns yet in cuDF-python.

We support `unique` on List columns:
```
>>> df = cudf.DataFrame({'a':[[1],[2],[1]], 'b':[1,2,3]})
>>> df['a'].unique()
0    [1]
1    [2]
Name: a, dtype: list
```
however, `groupby` throws a `NotImplementedError`
```
>>> df.groupby('a').min()
Traceback (most recent call last):
...
NotImplementedError: Unsupported column type passed to create an Index: <class 'cudf.core.column.lists.ListColumn'>
```

This issue appears to already be covered by #8039. For now I'll close this issue in favor of #8039 and the related #12037.
