### ISSUE TITLE
[QST] How does cudf perform groupby and aggregation on uint128 types?

### ISSUE THREAD

**Issue by infzo** [rapidsai/cudf#12716]
How does cudf perform groupby and aggregation on uint128 types?

**Comment by bdice** [comment]
cuDF only supports 128 bit types for decimal (fixed point) data. Generic 128 bit signed/unsigned data types are not supported. See this blog post for information about 128 bit decimals, which are internally represented by the CUDA extension type `__int128`: https://developer.nvidia.com/blog/implementing-high-precision-decimal-arithmetic-with-cuda-int128/

**Comment by infzo** [comment]
@bdice Is there a plan to support it in the future? "128 bit types for decimal" cannot be used for the group by column. Is there any other solution?

**Comment by bdice** [comment]
Currently I don’t think there is a plan for supporting 128 bit integer types. The cost to extend the type matrix is very high due to compile time, and there are a lot of places where 64 bit integers are the maximum width we could support for computation without significant changes to the library’s internals.

How is your input data being stored / computed? (Where do the 128 bit types come from?) Do you need this for cuDF Python or some other interface?

**Comment by bdice** [comment]
Side note: I did a little more research and I think the CUDA extended types may only include signed `__int128`. I didn’t see any references to unsigned `__uint128`, so it is unlikely that cuDF could support the unsigned type without new CUDA language features.

**Comment by infzo** [comment]
@bdice Data in uint128 format is obtained after hash calculation. To ensure a very low collision probability, 128 bits are used.

**Comment by bdice** [comment]
Since you don't have to do math on these hash values, you just need to store them, you have some decent options:
- You could use a string column with a UTF-8 encoding of the raw binary data
- You could use two uint64s in a struct column
- You could use two uint64s in a list column
- You could use two separate uint64 columns and always group by both keys

**Comment by infzo** [comment]
@bdice Thank you! The struct and list do not support the GroupBy operation in the cudf. Therefore, the two-column uint64 is used.

**Comment by GregoryKimball** [comment]
Hello @infzo, thank you for this discussion. Please feel free to reopen if you'd like to revisit this.
