### ISSUE TITLE
[DOC] C++ build problem missing custrings submodule/outdated includes

### ISSUE THREAD

**Issue by IceTDrinker** [rapidsai/cudf#1309]
**Describe the bug**
Following current C++ compile instructions
C++ build fails because of missing custrings dependency/submodule.
C++ build with custrings dependency will fail because of outdated includes.

**Describe the problems or issues found in the documentation**
Custrings is missing from requirements of cudf.

Cudf is missing the custrings submodule to compile.

Cudf includes <nvstrings/NVStrings.h> while custrings would install to /usr/local/include/custrings for example.

Creating a symlink nvstrings -> custrings in /usr/local/include fixes that last problem.

Cheers

**Comment by harrism** [comment]
Please follow the bug report instructions and provide full details on your environment. What version of cudf are you using? Are you building from source? Please run the cudf/print_env.sh script and include the results. 

If you have used a version of cudf before 0.6, then your environment is likely not up to date with the latest nvstrings package from anaconda. Please update your conda environment following these instructions: https://github.com/rapidsai/cudf/blob/branch-0.7/CONTRIBUTING.md#build-from-source then try again.

**Comment by IceTDrinker** [comment]
Hello @harrism,

Thanks for your answer.
I am not alllowed to use Anaconda in my dev environment, I was able to build cudf by building custrings from source and then creating the symlink as indicated in my original issue. This allows cudf to find the proper headers, from what I understand nvstrings is now legacy and custrings is the way to go.

- Environment location: [Bare-metal]
- Linux Distro/Architecture: [Ubuntu 18.04 amd64]
- GPU Model/Driver: [GTX1060 and driver 418]
- CUDA: [10.0]
  - cuDF v0.6.1
  - cmake 3.14.0
  - g++ 7.3.0
  - custrings v0.3.0

The point of this is, I guess, that Anaconda is not required to build cudf. For C++ devs there is a solution using the custrings project. I would argue that having it as a submodule of the git repository would be a nice QoL change and having the symlink auto-generated would be nice too.

Cheers.

**Comment by harrism** [comment]
I see what you are saying.

We are trying to reduce submodules because we have multiple repos in the RAPIDS platform and they often depend on the same submodules. When those submodules get out of sync (due to libraries pointing at different versions, or more often due to users not knowing how to update submodules) we get even more issues filed. Anaconda may not be required, but even for C++ devs it is a big help, because it makes it easy for the whole suite to depend on a single installation.

nvstrings is the python bindings for custrings, and the name of the anaconda package for both. So it's not legacy.

The environment variable `NVSTRINGS_ROOT` allows you to override where CMake looks for nvstrings when you configure the libcudf build. https://github.com/rapidsai/cudf/blob/9c49d49fef6341aeebbc1e9333fa8fef88ff8de9/cpp/CMakeLists.txt#L162

So you can do `NVSTRINGS=ROOT=<path> cmake .. <args>` where <path> is the path to where you installed nvstrings/custrings, and <args> is the normal arguments you are passing to cmake.

I'm going to close this out since there's not a specific issue. If I'm wrong about that, feel free to reopen it. Thanks!
