### ISSUE TITLE
[BUG] cuDF expression evaluation of some comparison operators creates AssertionError

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#13185]
**Describe the bug**
cuDF expression evaluation created `AssertionError` for less equal, greater equal and not equal operators.

**Steps/Code to reproduce bug**
```python
import cudf
df = cudf.DataFrame({'a': 1, 'b': 's'})
df.to_pandas().eval("a>=2")
df.to_pandas().eval("a<=2")
df.to_pandas().eval("a!=2")

#these statements error ou
df.eval("a>=2")
df.eval("a<=2")
df.eval("a!=2")
```

**Comment by vyasr** [comment]
The problem is [this line of code](https://github.com/rapidsai/cudf/blob/branch-23.06/python/cudf/cudf/core/dataframe.py#L7136) that is using a regex to search for an assignment operator. It correctly filters out `==`, but is not currently aware of `>=` or `<=`. Adding those to characters to the excluded character classes should fix the issue.
