### ISSUE TITLE
[FEA] Support the `case=` argument to `str.contains(...)`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#13253]
In Pandas `.str.contains()` function accepts a `case=` argument that ignores case when searching for substrings:

```python
>>> s = pd.Series(['a', 'A', 'b'])
>>> s.str.contains('a')
0     True
1    False
2    False
dtype: bool
>>> s.str.contains('a', case=False)
0     True
1     True
2    False
dtype: bool
```

We don't currently support the `case=` argument, but I believe it can easily be supported by calling `lower()` (or alternatively `upper()`) on both the input string Series as well as the substring before the call to `contains()`.

**Comment by davidwendt** [comment]
This approach likely work if `regex=False`. The description does not indicate the intention specifically.
Be careful here with the target input string since some regex character classes are different depending on the case of the flag. Specifically `\d, \s, \w` vs `\D, \S, \W` so changing the case on the regex pattern without accounting for those would give incorrect results. https://docs.rapids.ai/api/libcudf/stable/md_regex.html
