### ISSUE TITLE
[FEA] Python3.11 support

### ISSUE THREAD

**Issue by Pedrexus** [rapidsai/cudf#13314]
Python3.11 has been released a few months ago. Is there plans to support it by rapids anytime soon? Is there anything holding it back?

The rapids install page says support goes up to 3.10 right now.

**Comment by bdice** [comment]
Hi @Pedrexus, thanks for the question. We usually have some platform support changes in each RAPIDS release (every 2 months). Most of the time, we can’t adopt new Python versions immediately because it takes a few months for all RAPIDS dependencies to be available for a new Python version. I expect Python 3.11 support might be added in the 23.08 or 23.10 releases but I don’t think there is a specific plan yet. Another constraint is the CI matrix. We build and test aggressively for a wide range of platforms (AMD64/ARM64, CUDA versions, Python versions, Linux distributions) so adding new entries to that matrix is done slowly, usually when we can drop another entry.

To help us scope — would you be most interested in conda or pip packages for Python 3.11? What OS / CUDA version / CPU architecture do you have?

**Comment by bdice** [comment]
Also: you can probably get Python 3.11 compatibility if you build from source. We try to make it possible to build RAPIDS from source for newer Python versions but I haven’t tested that personally with 3.11. I’m happy to give that a shot and report back here next time I’m doing a fresh build.

**Comment by Pedrexus** [comment]
> Hi @Pedrexus, thanks for the question. We usually have some platform support changes in each RAPIDS release (every 2 months). Most of the time, we can’t adopt new Python versions immediately because it takes a few months for all RAPIDS dependencies to be available for a new Python version. I expect Python 3.11 support might be added in the 23.08 or 23.10 releases but I don’t think there is a specific plan yet. Another constraint is the CI matrix. We build and test aggressively for a wide range of platforms (AMD64/ARM64, CUDA versions, Python versions, Linux distributions) so adding new entries to that matrix is done slowly, usually when we can drop another entry.
> 
> To help us scope — would you be most interested in conda or pip packages for Python 3.11? What OS / CUDA version / CPU architecture do you have?

Thank you for the reply. 

I recently changed my setup to use the pip packages of rapids, which was simpler for me to control with the other dependencies. 

I use it on a Docker container based on the CUDA 11.8 Ubuntu 22.04 image on a machine with 8 V100 GPUs. I also use on my local computer for testing, which has CUDA 12.1, and a RTX 4090. 

As a side note, I use Rapids together with pytorch, which seems like it will be adding support for python 3.11 soon. That is the reason of my question. Thus, It's not really a urgent matter, so I could wait for official support.

**Comment by GregoryKimball** [comment]
Thank you @Pedrexus for asking about Python 3.11 support. Please keep an eye on our [homepage ](https://rapids.ai/) and [platform notices](https://docs.rapids.ai/notices?_gl=1*n9b39r*_ga*MjA2NjU0MDE2LjE2Mzk1MTY0ODM.*_ga_RKXFW6CM42*MTY4NTk5MTQ1My4xMC4wLjE2ODU5OTE0NTMuNjAuMC4w) for when we add support for Python 3.11. Thank you for using our pip wheels! 😊

**Comment by jtest09** [comment]
Hi, it has been 8 months since this conversation above. asking the same question again. Is there plans to support Python3.11 by rapids anytime soon? Is there anything holding it back?

**Comment by bdice** [comment]
@jtest09, thanks for checking in. We have a tracking issue here: https://github.com/rapidsai/build-planning/issues/3

This is targeting the 24.04 release, but it is queued behind a couple other efforts that are in progress.
