### ISSUE TITLE
[FEA] Remove all batch processing code in parquet writer

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#13440]
As batch processing is no longer supported (https://github.com/rapidsai/cudf/pull/13438), we should remove all the relevant code from parquet writer.

Note that we can also optimize memory usage to some extent, such as keeping only the memory blocks that is needed for writing to sink (either compressed or uncompressed), instead of keeping all.

**Comment by GregoryKimball** [comment]
Thank you @ttnghia for raising this issue, and also your focused work on #13438.

Let's please revisit this during 23.08 - for now I'll summarize the Slack discussion:

We may want to maintain the batching code as useful step towards pipelining the parquet writer. In this context, "pipelining" refers to processing batches of data across multiple CUDA streams and overlapping compute with IO. The goal of pipelining is increased utilization and reduced end-to-end runtime.

Removing batching for the chunked writer makes sense, because in this case we expect the user application to catch OOM errors and retry with smaller table segments. For the non-chunked/standard writer the batching code could be useful for providing lower peak memory usage.

**Comment by GregoryKimball** [comment]
After further discussion, we have committed to removing the batching code because it complicates applications that rely on catch-and-retry behavior in the writer APIs. We will maintain the chunked writer API and removing the internal batching.
