### ISSUE TITLE
[QST] How to stop `cudf` from using the GPU during `import`?

### ISSUE THREAD

**Issue by asnaylor** [rapidsai/cudf#13563]
This code snippet leads to python starting up a process on both GPU0&3:
```python
import cudf
import cupy
cupy.cuda.Device(3).use()
s = cudf.Series([1, 2, 3, None, 4])
```
```
+------------------------------------------------------------------------------+
|  GPU    PID     USER    GPU MEM  %CPU  %MEM      TIME  COMMAND               |
|    0 658352    elvis     414MiB   3.1   0.5     07:54  python                |
|    3 658352    elvis     876MiB   3.1   0.5     07:54  python                |
+------------------------------------------------------------------------------+
```
*Information from nvidia-smi

I know if i put `cupy.cuda.Device(3).use()` before `import cudf` that it will just use GPU3 but **i was wondering if I could stop `cudf` from creating a gpu process during the import?**

Environment:
```
cuda-python               11.8.2           py38h241159d_0    conda-forge
cuda-version              11.8                 h70ddcb2_2    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
cudf                      23.04.01        cuda_11_py38_230421_g7e070fce16_0    rapidsai
cugraph                   23.04.01        cuda11_py38_230421_g73f4327a_0    rapidsai
cupy                      11.6.0           py38h405e1b6_0    conda-forge
python                    3.8.16          he550d4f_1_cpython    conda-forge
```

Similar to https://github.com/rapidsai/cudf/issues/3428

**Comment by shwina** [comment]
Hi @asnaylor


1. Instead of selecting device `3` in your code, you could set the environment variable `CUDA_VISIBLE_DEVICES=3`. This will make it so that both CuPy and cuDF default to using device `3` by default. If you do this, you should _not_ include the line `cupy.cuda.Device(3).use()` in your code.

2. If for some reason that's not an option, could you try the same snippet of code you posted, but run it after setting the environment variable `RAPIDS_NO_INITIALIZE=1`?

**Comment by asnaylor** [comment]
Thanks for the quick reply @shwina. 2 is exactly what i need. I can't use `CUDA_VISIBLE_DEVICES` as i'm using nvidia triton and each code doesn't know which gpu it will use until execution time so `RAPIDS_NO_INITIALIZE` is perfect. thanks.
