### ISSUE TITLE
Retest Numba CUDA 12 dependencies

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#13683]
Currently the CUDA 12 CI images used contain the full CTK. As a result even though additional dependencies are needed for Numba to work correctly on CUDA 12, CI doesn't currently fail when they are missing ( https://github.com/rapidsai/cudf/pull/13673#discussion_r1258887610 )

Fixing this so that CI does fail as expected will require some other work. However once this is done, it would be good to confirm that removing Numba's CTK dependencies does cause CI to fail.

cc @bdice

**Comment by vyasr** [comment]
We'll probably want to use `nvidia/cuda-runtime` base images rather than `nvidia/cuda-devel` images. We may want to wait on addressing this until we merge the `cibuildwheel-imgs` into the `ci-imgs` repo so that we can have coordinate and have a consistent strategy between the two (as much as possible, there will likely be cases where pip wheels require more in the base image in the long run).

**Comment by vyasr** [comment]
This was resolved in https://github.com/rapidsai/ci-imgs/pull/77.
