### ISSUE TITLE
[BUG] Pin wheel builds to `numpy <1.25`

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#14155]
**Describe the bug**

Numpy 1.26 is out, and produces deprecation warnings in pandas (1.5.x). We notice this in wheel builds which don't have an upper bound pin (e.g. https://github.com/rapidsai/cudf/actions/runs/6262541728/job/17005833818?pr=14142)

**Expected behavior**

Pin to appropriate version

**Comment by bdice** [comment]
The reason we're seeing this warning now is not due to numpy 1.26 (which came out last week). It's because numba 0.58 came out 6 hours ago. The previous release of 0.57.1 was transitively bounding our numpy to `<1.25`. That restriction is lifted in numba 0.58 (https://github.com/numba/numba/pull/9011) so now cudf was able to fetch numpy 1.25 which raises these deprecations. The proper solution is still to bound to numpy <1.25.
