### ISSUE TITLE
[BUG] `cp.sum` fails with cuDF series

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#14191]
**Describe the bug**
Passing a cudf series to `cp.sum` results in a `NotImplementedError`.

**Steps/Code to reproduce bug**
```python
cp.sum(cudf.Series([1, 2, 3]))
```

```
NotImplementedError: level parameter is not implemented yet
```

**Comment by wence-** [comment]
This is, I think, a bug (or at least an API-mismatch) in the signature of sum compared to pandas:
```
import pandas as pd
import cudf
import inspect

inspect.signature(pd.Series.sum)
# <Signature (self, axis: 'Axis | None' = None, skipna: 'bool' = True, numeric_only: 'bool' = False, min_count: 'int' = 0, **kwargs)>

inspect.signature(cudf.Series.sum)
# <Signature (self, axis=<no_default>, skipna=True, dtype=None, level=None, numeric_only=None, min_count=0, **kwargs)>
``

Note how the cudf version has two extra positional arguments: `dtype` and `level`. `cupy` is passing `False` to mean `numeric_only` (or something different probably). pandas does a bunch of validation in this cross-calling scenario, but cudf doesn't.

**Comment by isVoid** [comment]
I see - so that if cupy puts it's effort in making `cupy.sum(pd.Series)` work, cudf will benefit it for free. Onboard with it's a bug.

**Comment by wence-** [comment]
No, cudf needs to change the signature of `sum` to handle being called from numpy/cupy

**Comment by wence-** [comment]
Ah wait, maybe both.

**Comment by vyasr** [comment]
I don't think this should be expected to work. At minimum, this is probably a feature request that needs to be made to cupy, There's probably some confusion here about what cupy promises relative to numpy. numpy defines two protocols `__array_ufunc__` and `__array_function__` that are used to determine how an arbitrary object should behave in certain contexts within numpy. ufuncs are for elementwise ops (e.g. `np.add(x, y)`) while `__array_function__` covers everything else. Objects that implement either of these protocols will be dispatched to by certain numpy function calls. 

cupy arrays (`cp.ndarray` objects) support both of these protocols. However, cupy the library does not really support other objects implementing those interfaces. You can see that through this example:

```
In [1]: import numpy as np

In [2]: import cupy as cp

In [3]: class A:
   ...:     def __array_ufunc__(self, *args, **kwargs):
   ...:         print(f"ufunc: {args}; {kwargs}")
   ...:     def __array_function__(self, *args, **kwargs):
   ...:         print(f"array_function: {args}; {kwargs}")
   ...: 

In [4]: np.sum(A())
array_function: (<function sum at 0x7f747dffe7a0>, (<class '__main__.A'>,), (<__main__.A object at 0x7f747f5e6f80>,), {}); {}

In [5]: np.add(A(), A())
ufunc: (<ufunc 'add'>, '__call__', <__main__.A object at 0x7f747f895300>, <__main__.A object at 0x7f747e0e7d90>); {}

In [6]: cp.sum(A())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[7], line 1
----> 1 cp.sum(A())

File ~/compose/etc/conda/cuda_11.8/envs/rapids/lib/python3.10/site-packages/cupy/_math/sumprod.py:38, in sum(a, axis, dtype, out, keepdims)
     34     return _fusion_thread_local.call_reduction(
     35         func, a, axis=axis, dtype=dtype, out=out)
     37 # TODO(okuta): check type
---> 38 return a.sum(axis, dtype, out, keepdims)

AttributeError: 'A' object has no attribute 'sum'

In [7]: cp.add(A(), A())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 1
----> 1 cp.add(A(), A())

File cupy/_core/_kernel.pyx:1283, in cupy._core._kernel.ufunc.__call__()

File cupy/_core/_kernel.pyx:159, in cupy._core._kernel._preprocess_args()

File cupy/_core/_kernel.pyx:145, in cupy._core._kernel._preprocess_arg()

TypeError: Unsupported type <class '__main__.A'>
```

Therefore, I wouldn't expect an arbitrary object to work with `cp.foo` just because it works with `np.foo` because the override paths are different. In this case, I wouldn't expect `cp.sum` (or `cp.add`) to work with a cudf Series (or a pandas Series, for that matter).
