### ISSUE TITLE
Comparing pandas test suite pass rates on PRs against the target branch

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#14389]
Each PR to this repo tests cudf.pandas against the pandas test suite ([workflow](https://github.com/rapidsai/cudf/blob/7da0336ff9a0f1f06e06973c0ce21497e3549611/.github/workflows/pr.yaml#L141-L149)).

We would like for PRs to be able to measure the diff (change in passing/failing tests) relative to the current development branch.

Some ways to do this are listed below. For all the options below, we would propose to do test suite comparison for only one configuration, like CUDA 12 and Python 3.10 on x86-64.

### Option 1: Build and test dev branch on every PR

This option would add a step to build the dev branch and get pandas test suite results as a part of every PR workflow. This increases the build/test cost of every PR, but provides always-correct results. I don't think this option is especially viable due to the increased cost.

### Option 2: Compare to a recent build of the dev branch

On merging a PR, the dev branch triggers package builds and uploads them to the nightly channels. We could add a step that runs the pandas test suite after building the new packages, and save that artifact in CI for comparison. However, merges to the dev branch are often canceled pre-emptively by other merges -- so not every commit to the dev branch has a nightly package. The PR comparison step would require looking back in the commit history on the dev branch to find the most recent commit that built, tested, and uploaded an artifact. This won't always provide accurate data, but it would be close enough for most cases.

### Option 3: Compare to a recent PR build

@vyasr proposed an option that wouldn't involve PRs on the dev branch, but some kind of comparison to test results from recently merged PRs. More details needed here.

More ideas are welcome!

**Comment by mroeschke** [comment]
I would be OK with Option 3.

Related, it would be related to have the pandas tests suite pass rate conveniently accessible somewhere without having to open a PR as well.

**Comment by vyasr** [comment]
On further thought I'm pretty skeptical of my previous proposal, but I'll document it here anyway for posterity.

Essentially what I'm proposing for option 3 is that every PR runs the full pandas test suite, just like it does now, and then uploads the result to the PR's S3 bucket as an output artifact. Then, when a PR is merged one of two things can happen: 1) that PR's artifact is copied to some centralized branch S3 bucket location, or 2) the most recently merged PR is simply recorded somewhere. Then, when subsequent PRs are running CI, after they finish running the pandas test suite they can diff their output against the last uploaded one from a merged PR.

Even when I proposed it I knew this would only be approximate, but my concern on further thought is that unless devs are diligent about keeping their branches up-to-date with the latest upstream main branch, there's a good chance that there will be enough false positives showing that test coverage dropped that using this code will be difficult.

**Comment by david8dixon** [comment]
Does cuDF have a [cdash](https://www.cdash.org/) dashboard? Here is an example:

https://open.cdash.org/index.php?project=ADIOS

If you were just interested in looking at the difference in the total number of test failures on head of develop and some feature branch the main dashboard page would capture that. If you wanted to know e.g. test-x and test-y are now failing on feature/branch and they aren't failing on develop you would have to dive down into the dashboard to get the actual list of test failures. There may be a way to customize the a dashboard to present this type of info in a new column. 

As an aside, the fail column has the following notation:

$$X^Y$$

where X is the total number of failures for a given (build, revision) and Y is the number of new failures for the given (build, revision). As an example, if we had four failures total and one was new the fail summary would appear as follows:

$$4^{+1}$$

This doesn't get you what you want but suggests that cdash provides a similar metric out of the box.

**Comment by galipremsagar** [comment]
> Essentially what I'm proposing for option 3 is that every PR runs the full pandas test suite, just like it does now, and then uploads the result to the PR's S3 bucket as an output artifact. Then, when a PR is merged one of two things can happen: 1) that PR's artifact is copied to some centralized branch S3 bucket location, or 2) the most recently merged PR is simply recorded somewhere. Then, when subsequent PRs are running CI, after they finish running the pandas test suite they can diff their output against the last uploaded one from a merged PR.

I'm +1 to this option(**3**). Agree we will not always have a perfect comparison without having upto-date branches but I feel this is the best of all the options we have.

**Comment by shwina** [comment]
> Agree we will not always have a perfect comparison without having upto-date branches

I don't understand -- why is option 3 not perfect?

**Comment by shwina** [comment]
Also, the kind of report @david8dixon is referring to sounds like exactly what we want - so definitely worth exploring!

**Comment by vyasr** [comment]
> > Agree we will not always have a perfect comparison without having upto-date branches
> 
> I don't understand -- why is option 3 not perfect?

Consider the following sequence
1. PR 1 is opened and fixes bug X, improving pandas test coverage by 2%
2. PR 2 is opened and fixes bug Y, improving pandas test coverage by 1%
3. PR 1 is merged
4. PR 2 has changes requested in review, so changes are made

After step 4, the diff will compare test pass rate in PR 2 against a run where PR 1 is merged and bug X is fixed, but in PR 2 bug X is not yet fixed. Therefore, we will see a diff suggesting that PR 2 actually lowers the test pass rate by 1% unless and until we merge the latest main branch down into PR 2. Since always merging isn't really viable from a practical/resource usage perspective, you'll always have this kind of issue (unless we implement merge queues, which is a separate discussion and not going to happen on a relevant timeline for this).

> Does cuDF have a [cdash](https://www.cdash.org/) dashboard?

We do not currently. It's come up once or twice. I don't think CDash really solves the problem though. Unless I'm misunderstanding some magic in how this works, what it provides is a way to display the results, and while I agree that the display is helpful, if you click through that dashboard you linked the data is coming from CI runs. The issue here is not that we don't have a way to display the data. The issues are that 1) we don't run the full test suite on every commit to the main branch and 2) there's no guarantee that any given PR is fully up-to-date with the main branch. It looks like the repo for the linked dashboard does, and therefore they have a source of truth for what tests are currently passing on the main branch. The solutions discussed in this thread are about what the best comparison is that we can make on a PR given the two limitations above.

**Comment by galipremsagar** [comment]
> Therefore, we will see a diff suggesting that PR 2 actually lowers the test pass rate by 1% unless and until we merge the latest main branch down into PR 2.

Exactly. This is expected for us but for someone new who is seeing the reports this is sort of an implementation detail. Which is what I meant by "perfect comparison". But I'm a huge +1 to this option after looking at other options, this is the best we can do.

**Comment by shwina** [comment]
Thanks for the explanation. Agree, it's a more than acceptable limitation.

**Comment by vyasr** [comment]
The discussion on this issue is very helpful, but for tracking the action items let's use #14404.
