### ISSUE TITLE
`read_json` does not compile if using `std::string_view` instead of `std::string`

### ISSUE THREAD

**Issue by divyegala** [rapidsai/cudf#14413]
Reference thread: https://github.com/rapidsai/cudf/pull/13795#discussion_r1373437533

Error:
```/home/nfs/dgala/cudf/cpp/examples/nested_types/deduplication.cpp: In function 'cudf::io::table_with_metadata read_json(std::string_view)':
/home/nfs/dgala/cudf/cpp/examples/nested_types/deduplication.cpp:66:52: error: no matching function for call to 'cudf::io::source_info::source_info(std::string_view&)'
   66 |   auto source_info = cudf::io::source_info(filepath);```

**Comment by bdice** [comment]
Looks like there are a bunch of `explicit` constructors for `source_info`, and it happens to be missing one for `string_view`.

https://github.com/rapidsai/cudf/blob/8e1ef05b2b96775ce7e1a2f22894ec7a8ebb65a4/cpp/include/cudf/io/types.hpp#L306

**Comment by bdice** [comment]
@vuule Do you have feedback on this? If I understand correctly, we might be able to replace several of the existing constructors with one for `std::string_view`.

**Comment by vuule** [comment]
the source_info constructors are a scary place, because two completely different input types can be represented with the same object. Namely, a buffer of characters could be a file path or the actual file content. Currently the supported types are slightly limited to reduce the chance of surprising overload resolutions for the user.
That said, I'm surprised passing string_view does not work. I'll take a look.

**Comment by vuule** [comment]
Now I remember, string implicitly converts to string_view, not the other way around. Makes sense.
The constructors need more clean up, but I do agree that we could add string_view and deprecate string and char* ones :+1:

**Comment by vyasr** [comment]
Closing in favor of https://github.com/rapidsai/cudf/issues/15907.
