### ISSUE TITLE
[BUG] `df.index.name = "indexer"` does not work as expected under `cudf.pandas`

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#14524]
**Describe the bug**
When setting the `name` attribute for `df.index`, the name of the index is supposed to update. When following the reproducer below, it doesn't work as expected.

**Steps/Code to reproduce bug**
```python
import pandas as pd

df1 = pd.DataFrame(columns=["x"], dtype="int64")
df2 = df1.dtypes
df3 = df2.reset_index()

df3.index.name = "indexer"
assert df3.index.name == "indexer"
```

**Expected behavior**
No exception should be thrown from above.

**Environment overview (please complete the following information)**
Bare-metal, conda

**Comment by wence-** [comment]
This is, approximately, because `df2` has a column that is not representable as a fast object. Simpler example:

```
s = pd.Series([object()])
s.index.name = "what"
print(s.index.name) # => None
```

I think what happens is that `s.index` provokes a fast->slow conversion (so that `s._fsproxy_state` is slow). But then we have a "final" object at this point, so we then do `index.name = "what"` and that pushes the index to cudf, sets the name there. But now this destroyed the link between `s.index` and the name we set.

**Comment by shwina** [comment]
Yeah we might need a custom `name` setter and getter for our proxy index type, given how common this operation is and we need to support it correctly.

**Comment by vyasr** [comment]
> I think what happens is that s.index provokes a fast->slow conversion (so that s._fsproxy_state is slow).

I'm confused, shouldn't the original object in this case already be a slow object? In which case `s.index` should also be a slow object. And then what triggers the final slow->fast conversion when doing `s.index.name = "what"`?
