### ISSUE TITLE
[DOC] deleted docs in cudf python for building should be removed

### ISSUE THREAD

**Issue by DanialJavady96** [rapidsai/cudf#14649]
https://github.com/rapidsai/cudf/blob/branch-24.02/python/cudf/CONTRIBUTING.md#setting-up-your-build-environment

^ these docs referenced here https://github.com/rapidsai/cudf/tree/branch-24.02/python/cudf in the section Build/Install from Source no longer exist

**Comment by DanialJavady96** [comment]
https://github.com/rapidsai/cudf/blob/branch-24.02/CONTRIBUTING.md

Docs here should also be updated for cudf python. 

```
python setup.py build_ext --inplace
python setup.py develop
``` 
Are no longer valid, `setup.py` was removed. I presume you need to run `python -m pip install --no-build-isolation --no-deps -e .`.

**Comment by shwina** [comment]
> I presume you need to run python -m pip install --no-build-isolation --no-deps -e ..

That sounds right. Any chance you could throw in a PR? :)

**Comment by DanialJavady96** [comment]
> > I presume you need to run python -m pip install --no-build-isolation --no-deps -e ..
> 
> That sounds right. Any chance you could throw in a PR? :)

Sure I don't mind, with that being said #14653 did update the docs alongside the build script to make it more convenient

**Comment by bdice** [comment]
It looks like there are two topics here:

1. The links in the README.md work from the README.md in the root, but not in the symlinked `python/cudf/README.md`. We might be able to use absolute https paths instead of relative links, but I don't think that would be a net benefit for the main README. I'm not sure what the best course of action would be here. I'm leaning towards taking no action here. We still want to symlink the README rather than copy it, and changing to absolute URLs would be a worse outcome for developers and readers alike because the branch names in an absolute URL would go out of date (and would need to be kept in sync with `ci/release/update-version.sh`.

2. There were some references to `setup.py` but these are now removed.

I think we can close this issue for now. If others have strong feelings about how we should handle (1), please feel free to reopen.
