### ISSUE TITLE
[BUG] ORC writer does not correctly output statistics for empty data file

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#14675]
From our ORC tests, we found that for an empty table the output file does not contains column statistics and some file statistics are also incorrect:
```
File Version: 0.12 with FUTURE by Unknown(5) 
Rows: 0
Compression: SNAPPY
Compression size: 262144
Calendar: Julian/Gregorian
Type: struct<id:bigint,p:bigint>

Stripe Statistics:

File Statistics:

Stripes:

File length: 68 bytes
Padding length: 0 bytes
Padding ratio: 0%
```

So there are at least two (observable) problems:
 * `Compression size: 262144`: This is incorrect, since there is no data.
 * There are no stripes/column statistics.

**Comment by ttnghia** [comment]
CC @vuule.

**Comment by vuule** [comment]
I have a repro of "no stripes/column statistics". I think it's expected to have no stripe statistics, since there are no stripes. But we should probably include file statistics.

Where are you reading the compression size from? We do have a (passing) test that might be related, `CompStatsEmptyTable`.

**Comment by ttnghia** [comment]
I'm reading metadata using orc tool. This is my script:
```
java -jar /home/nghiat/Softwares/orc-tools-1.8.4-uber.jar meta $1
```

**Comment by ttnghia** [comment]
It seems that orc tool is wrong about compression size. I dug into its code and saw that it prints the value of `compressionBlockSize` for that.
