### ISSUE TITLE
[QST] When will we be able to use cudf on Windows Home/Pro (not WSL)

### ISSUE THREAD

**Issue by IMA18** [rapidsai/cudf#14859]
I used to use cudf on Windows WSL, WSL is full of bugs and issues. Are you planning to make cudf compatible with the regular Windows Home or Pro? If so, when? My alternative is using VirtualBox and install Linux because Windows WSL is extremely buggy and interferes with my other windows applications. Please advise on your timeline in order for me to make a decision. Thank you for your good work.

**Comment by bdice** [comment]
@IMA18 Thanks for your question. WSL2 is currently the only supported way to use cuDF on Windows. Can you give a little more detail about the issues you are facing with WSL2?

The RAPIDS installation guide offers some information about system requirements and installation steps. https://docs.rapids.ai/install

Also, there is a recent video with a guide for using WSL2 with CUDA. It might help: https://www.youtube.com/watch?v=JaHVsZa2jTc&ab_channel=NVIDIADeveloper

Virtual machines may be a viable alternative, as long as they support GPU passthrough.

xref: #28

**Comment by GregoryKimball** [comment]
Thank you @IMA18 for asking about native Windows support. There has been consistent demand for this support since the founding of RAPIDS (see #28), and progress is currently blocked by compiler incompatibilities between MSVC and GCC (see [comment](https://github.com/rapidsai/cudf/issues/28#issuecomment-1122544127)). We are not planning to add native Windows support in the foreseeable future.

**Comment by IMA18** [comment]
Thank you for your answer. Do you know if [Parallels](https://www.parallels.com/) support GPU passthrough? I will check Hyper-V. 

Windows WSL is definitely not an option to me because other important applications to my research are not stable on Windows WSL, though RAPIDS would work fine on Windows WSL.

**Comment by bdice** [comment]
I don't think Parallels has a Windows product that would be suitable for running a Linux VM. I think it's meant to run a Windows VM on a Mac. Macs do not support NVIDIA GPUs (and thus do not support RAPIDS).

**Comment by IMA18** [comment]
Hyper-V supports GPU passthrough but requires windows Server edition (not home or pro). So I have two follow up questions.
1. If I install Linux as my host (primary) OS and then install Windows Pro as guest virtually using VirtualBox, I assume I don’t need the GPU pass through anymore as I would be using it on Linux (the host/primary OS). 

2. Do you recommend the approach I described in step 1 or install Windows server as host and Linux as guest using Hyper-V? I am just worried that Windows Server would cause my other applications to crash (i.e., similar to what I experienced with WSL). Thank you.

**Comment by bdice** [comment]
1. Correct, if you use Linux as the host/primary OS and install the NVIDIA drivers, you will have native GPU support.
2. I haven't used Hyper-V so I can't offer much advice here. WSL2 is the best option that I am aware of, and the latest versions of WSL2 have been pretty much rock solid for me and most of the colleagues who I know use it. If you're experiencing application crashes, you might need more system resources? WSL2 does split the system memory, and the amount is configurable, but so does every virtualization solution.

I'm going to close this issue for now, since the original question is answered -- but feel free to continue the conversation if we can help further.

**Comment by Matin-Mahzad** [comment]
As a scientific Windows application developer, it really saddens me that there is no native support for cuDF on Windows. WSL is useless to me; I need native support to develop on Windows.

**Comment by YisroelLen** [comment]
I'm in a little bit of a quandary. I'm trying to query an Azure Analytics Database, which, in python, requires the pyadomd library. Unfortunately, the pyadomd library can only be run on Windows. But, I can't utilize my gpu or cudf because it's Linux only... Any chance Windows will eventually get support?

**Comment by vyasr** [comment]
I'm afraid we have no updates here. If we do, we'll post in #28.
