### ISSUE TITLE
CuDF and tensorflow GPU issues in python

### ISSUE THREAD

**Issue by rajnraj100** [rapidsai/cudf#14963]
Hello all, 
I have written few codes where I need tensorflow (using gpu) and cudf, cupy all together. Before, it was not a problem but now, if I install:
conda create --solver=libmamba -n rapids-23.12 -c rapidsai -c conda-forge -c nvidia  \
    cudf=23.12 python=3.9 cuda-version=11.2 \
    tensorflow
    tensorflow can only use CPU and can not utilize GPU. Even, I tried pip install tensorflow-gpu and pip install tensorflow[and-cuda] and the problem exists as cudf requires protobuf <5, >=4.21 and tensorflow for gpu requires protobuf<3.20,>=3.9.2.
    Is there any way so that I can install all the rapids packages including cudf and tensorflow which can utilize GPU?
    PLEASE HELP.
```[tasklist]
### Tasks
```

**Comment by shwina** [comment]
Thanks for reporting @rajnraj100. We'll investigate and get back to you with next steps.

**Comment by bdice** [comment]
@rajnraj100 Hello! I looked into this problem. The short answer is that using `cuda-version=12.0` instead of `cuda-version=11.2` should help. You will need CUDA driver 525 or higher to use CUDA 12.

CUDA 11 builds of TensorFlow aren't working right now. The conda-forge maintainers are seeking a motivated contributor to help fix them: https://github.com/conda-forge/tensorflow-feedstock/pull/367#issuecomment-1890784430

Only TensorFlow 2.15 is new enough to be compatible with other dependencies (protobuf, libabseil) that cudf relies on, so older builds of TensorFlow 2.14 (which had working CUDA 11 support) aren't compatible with cudf 23.12.

We will update our installation selector to disable CUDA 11 + TensorFlow for now.

**Comment by bdice** [comment]
Closing as resolved -- feel free to add any other comments you may have.

**Comment by bdice** [comment]
I updated the RAPIDS install selector to reflect this change in CUDA version support from the conda-forge TensorFlow packages: https://github.com/rapidsai/docs/pull/470

When that finishes deploying to the RAPIDS website (in another 1-2 hours), the install selector at https://docs.rapids.ai/install will force users to have CUDA 12.
