### ISSUE TITLE
[FEA] GPU support for DataFrame.min and DataFrameGroupBy.filter

### ISSUE THREAD

**Issue by stckwok** [rapidsai/cudf#15083]
This issue template is intended to be used primarily for requests related to pandas accelerator mode. If you'd like to file a general cuDF feature request, please [click here](https://github.com/rapidsai/cudf/issues/new?assignees=&labels=%3F+-+Needs+Triage%2C+feature+request&projects=&template=feature_request.md&title=%5BFEA%5D).

**Missing Pandas Feature Request**
A clear and concise summary of the pandas function(s) you'd like to be able run with cuDF.

**Profiler Output**
**DataFrameGroupBy.filter**
![cuDF-DataFrameGroupBy filter](https://github.com/rapidsai/cudf/assets/3154357/ce5bcae4-1c04-4d73-97fa-723933dfa58b)

**DataFrame.min**
![cuDF-DataFrame min](https://github.com/rapidsai/cudf/assets/3154357/d3d08d9c-67d1-49e8-b582-4e8ded67e23c)

**Additional context**
Please see attached screen captures for code details.

**Comment by shwina** [comment]
Thank you for reporting, @stckwok.

1. While we don't currently support `GroupBy.filter`, I describe a workaround for it here: https://github.com/rapidsai/cudf/issues/7354. Note that in the general case you might not see very good performance, but for this particular case (`len(group) > 1`) you might see decent performance.

2. We likely cannot support the `.min(axis=1)` operation in your example because we don't support comparisons between `int` and `str` types. Unfortunately, this particular operation will always fall back to using the CPU.

**Comment by shwina** [comment]
cc: @galipremsagar - perhaps we can implement a simple `GroupBy.filter` using the workaround described above.

**Comment by vyasr** [comment]
Thanks for this issue! I am going to close it for tracking though because 1) as mentioned above, we cannot support min(axis=1), and 2) the groupby.filter request is tracked in #7354.
