### ISSUE TITLE
[FEA] Allow `cudf.concat` to process a dictionary of frames / add `keys=`

### ISSUE THREAD

**Issue by amanlai** [rapidsai/cudf#15115]
In pandas, you can pass a dictionary of dataframes to construct a MultiIndex dataframe. This is especially useful if the values contain frames that have the same columns, in which case the keys can help differentiate them.

Right now, the following code:
```python
d = {
    'first': cudf.DataFrame({'A': [1, 2], 'B': [3, 4]}),
    'second': cudf.DataFrame({'A': [5, 6], 'B': [7, 8]}),
}

cudf.concat(d, axis=1)
```
raises the error
```none
TypeError: cannot concatenate object of type <class 'str'>
```
If we try to construct a dataframe from the values of `d`:
```python
cudf.concat(d.values(), axis=1)
```
we get:
```none
NotImplementedError: A Column with duplicate name found: A, cuDF doesn't support having multiple columns with same names yet.
```

If we try to pass keys:
```none
cudf.concat(d.values(), keys=d.keys(), axis=1)
```
we get
```none
TypeError: concat() got an unexpected keyword argument 'keys'
```

Right now, I can do one of two things to get around this issue:
- Mangle the column names of each dataframe beforehand (in a loop) to make them unique and concatenate them. Afterwards, work the columns to make it MultiIndex. 
- Concatenate at the cupy level, create MultiIndex from scratch and create a new dataframe object from these.

In pandas, we could do `pd.concat(d, axis=1)` and call it a day. I wish the same was possible in cudf.

**Comment by shwina** [comment]
Thanks for reporting @amanlai!

If anyone would like to contribute a fix, here's one approach:

```python
d = {
    'first': cudf.DataFrame({'A': [1, 2], 'B': [3, 4]}),
    'second': cudf.DataFrame({'A': [5, 6], 'B': [7, 8]}),
}
names = [(key, name) for key in d for name in d[key]]
cols = list(itertools.chain.from_iterable([df._data.columns for df in d.values()]))
df = cudf.DataFrame(dict(zip(names, cols)))
print(df)
  first    second
      A  B      A  B
0     1  3      5  7
1     2  4      6  8
```

**Comment by shwina** [comment]
I think this would be a great first contribution for someone looking to get their feet wet contributing to cuDF! I'll leave it open as a `good-first-issue` for a while to see if anyone takes it up.

**Comment by amanlai** [comment]
@shwina Can I do it?

**Comment by shwina** [comment]
Absolutely! I've assigned you this issue. Please feel free to ask questions here if you have any, or you can reach me on the RAPIDS slack.

**Comment by amanlai** [comment]
@shwina I didn't realize concatenation along the first axis was very different.

**Comment by shwina** [comment]
Ah, yeah doing the same thing along `axis=0` complicates things somewhat. Here's why:

- The column names in cuDF are stored and operated on in CPU memory. This is fine, because typically you're working with just a handful of columns (~10s).
- The row names ("index") in cuDF are stored and operated on in GPU memory. This is because the index is of the same size as the data (~millions).

So often the two need to be handled in very different ways.

Taking a peek at your PR, I think there could be some potential performance issues when concatenating along `axis=0`. For instance, calling `MultiIndex.from_product(...)` on very large inputs will be extremely slow, because [cudf actually uses pandas for that operation](https://github.com/rapidsai/cudf/blob/c84e1e8b3dde5be9c3c095f5cf89a5c181848b5d/python/cudf/cudf/core/multiindex.py#L1348).

Here's what I recommend:

- In your current PR, let's only handle the `axis=1` case - raising `NotImplementedError` for the `axis=0` case
- Once that's merged (or concurrently), open a separate PR for the `axis=0` case that builds off of the first PR

This way we can iterate for a bit on the approach for (2).

Does that sound alright to you?

**Comment by shwina** [comment]
You don't have to worry about the checks running; I would push a new commit that removes the `axis=0` code to that PR

**Comment by er-eis** [comment]
based on the comment here: https://github.com/rapidsai/cudf/pull/15160#issuecomment-2030637894

i'll take this

**Comment by er-eis** [comment]
> Taking a peek at your PR, I think there could be some potential performance issues when concatenating along `axis=0`. For instance, calling `MultiIndex.from_product(...)` on very large inputs will be extremely slow, because [cudf actually uses pandas for that operation](https://github.com/rapidsai/cudf/blob/c84e1e8b3dde5be9c3c095f5cf89a5c181848b5d/python/cudf/cudf/core/multiindex.py#L1348).
> ...
> * Once that's merged (or concurrently), open a separate PR for the `axis=0` case that builds off of the first PR


@shwina here's a simple and naive PR building off the axis=1 pr: https://github.com/er-eis/cudf/pull/1

what are your thoughts?
