### ISSUE TITLE
[FEA] Logical `and` (&&) and `or` (||) support.

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1517]
**Is your feature request related to a problem? Please describe.**
Add C++ `&&` and `||` binary operators to libcudf, and Python `and` and `or` binary operators to cudf

**Describe the solution you'd like**
Support performing logical operators between Series / columns

**Additional context**
#1142 adds a first-class Boolean type, so this functionality makes more sense now.

#1071 requested binary `&` and `|` but refers to them as "logical" operators, when they are actually bitwise operators. The bitwise operators have been implemented.

#49 appears to have requested this feature, but it was also interpreted as requesting bitwise operators.

**Comment by ButkiewiczP** [comment]
Hey @harrism , you're definitely _technically_ correct when you say those are bitwise operators and that we should use logical operators instead, but just to provide context here, the reason those other issues request bitwise operators instead of the logical operators `&&` and `||` is (I believe) because of how the [pandas library handles boolean indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#boolean-indexing). I personally think it would be confusing if cudf and pandas implemented boolean indexing differently, but I understand why it can be confusing.

**Comment by jrhemstad** [comment]
> Hey @harrism , you're definitely _technically_ correct when you say those are bitwise operators and that we should use logical operators instead, but just to provide context here, the reason those other issues request bitwise operators instead of the logical operators `&&` and `||` is (I believe) because of how the [pandas library handles boolean indexing](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#boolean-indexing). I personally think it would be confusing if cudf and pandas implemented boolean indexing differently, but I understand why it can be confusing.

It looks like in Pandas `|` is equal to `||` in C++, likewise with `&` and `&&`. So really, the ask is just for the logical operators. The confusion is just an inconsistency between how Pandas and C++ names these operators.

**Comment by harrism** [comment]
Regardless of how the Python side chooses to expose them, we don't have the logical operators in *libcudf* today.

**Comment by devavret** [comment]
This can be added pretty quickly in JIT code.
