### ISSUE TITLE
[BUG] table does not copy/clear array of cudf pointers passed in.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#1567]
**Describe the bug**
cudf::table takes as input an array of columns, but it does not make a copy of this array, nor does it have a destructor to free the array.  This means that if I want to create a table that has a life time longer than a single method call I either need to do some ugliness and reach into hidden parts of table to free the array

```
delete[] table->begin();
```

or I have to keep a pointer to that array around and wrap table in something else.  
Or just live with a small memory leak.
neither feels like an ideal option.

**Steps/Code to reproduce bug**
Create a table, not on the stack.

**Expected behavior**
It would be nice not to have to worry about table reusing a data structure I passed into it and knowing the internals of how table works.

**Comment by jrhemstad** [comment]
I'm not 100% sure what the ask is for here.

I originally made `cudf::table` to trivially replace:

`void some_function(gdf_column* cols[], int num_cols)`

with:

`void some_function(cudf::table const& cols)`

As such, `cudf::table` simply holds a single `gdf_column**` double-pointer and doesn't presume to own the `gdf_column*` pointers nor the `gdf_column` objects. 

Would you instead prefer that it makes a copy of the `gdf_column*` pointers? I could definitely support that.

However, if you're suggesting making copies of the actual `gdf_column` objects, I don't think it's safe at this time. This is because a `cudf::table` may be wrapping columns that are outputs/inputs to other functions to do not yet use `cudf::table`. Therefore, if a `cudf::table` were to make copies of the `gdf_column` objects themselves (not just the pointers), then changes to those `gdf_column` objects may be lost (e.g., setting the `null_count`).

I can't solve the user's burden of being responsible for deleting the `gdf_column` objects at this time.  It's just an ugly state of affairs until we can work on a `cudf::column` design that handles that for you.

**Comment by revans2** [comment]
All I am suggesting is making a copy of the array of pointers.  The issue is that if I allocate the table on the heap.

```
gdf_column* cols[] = ...
new cudf::table(cols, num_cols);
```
and pass that back to the JVM, so we can reuse it for other operations that need a table, I now have to keep track of the array `cols` separately form the pointer to the table.

**Comment by jrhemstad** [comment]
Okay, cool. I can definitely do that.

**Comment by jrhemstad** [comment]
@revans2 see https://github.com/rapidsai/cudf/pull/1585
