### ISSUE TITLE
[QST] Based on the cuDF, How can I know which function is enable the cuDF

### ISSUE THREAD

**Issue by shou123** [rapidsai/cudf#16074]
**For cuDF, some functions can be accelerated on the GPU, while others cannot. How can I determine which functions are GPU-enabled? Do you have a list of methods that can run on the GPU?**

**Comment by bdice** [comment]
Hi @shou123, thanks for the question.

The list of GPU-accelerated methods would be those listed in the cuDF API: https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/

There are exceptions. For example, some methods are GPU-accelerated by cudf but without support for every combination of keyword arguments. In cases like unsupported keyword arguments, cudf.pandas will fall back to the CPU.

The most useful way to assess GPU performance and fallback is to use the cudf.pandas profiler: https://docs.rapids.ai/api/cudf/stable/cudf_pandas/usage/#understanding-performance-the-cudf-pandas-profiler

The profiler will tell you which functions ran on CPU and which on GPU, and you can use that to optimize performance: try to use only functions that are in cuDF, so that cudf.pandas can run entirely on GPU without fallback to CPU.
