### ISSUE TITLE
[FEA] Dictionary type support for `row_bit_count`

### ISSUE THREAD

**Issue by jihoonson** [rapidsai/cudf#16121]
**Is your feature request related to a problem? Please describe.**
`row_bit_count` currently does not support the dictionary type.

**Describe the solution you'd like**
It seems that we could add a new `flatten_functor` specialized for the dictionary type in [here](https://github.com/rapidsai/cudf/blob/branch-24.08/cpp/src/transform/row_bit_count.cu#L169-L275).

**Describe alternatives you've considered**
I have not considered alternatives.

**Additional context**
When `row_bit_count` fails because of unsupported data types, it does not say what is the type unsupported. It would be nice to include the name of the unsupported type in the error message.

**Comment by davidwendt** [comment]
Changes in #16564 resolved the need for this feature in the benchmark no longer necessary.
Computing the row bit count for dictionary is tricky since the rows are technically integers.
Since the number of keys is normally less than the rows, it would be difficult to account for them in a row bit count.
The purpose of `row_bit_count` was likely never intended to support dictionary types and I'd rather minimize dictionary support in general.
Given the above, I'm inclined to close this issue as either fixed (by #16564) or wont-fix.

**Comment by jihoonson** [comment]
Thanks @davidwendt for your comment and #16564. I'm fine with moving to nvbench as you suggested, but would like to understand your concern better.

> it would be difficult to account for them in a row bit count.

What is the difficulty here? I thought it would be more or less than `index column size + key column size + null mask size`.

**Comment by davidwendt** [comment]
> What is the difficulty here? I thought it would be more or less than `index column size + key column size + null mask size`.

This formula can be use to estimate the number of bytes total in the dictionary column perhaps but the `cudf::row_bit_count` returns the number of bits in each row. There is no easy calculation to account for the keys properly IMO. This issue is requesting for _dictionary type support for `row_bit_count`_ and not an estimate on the number of bytes total.
