### ISSUE TITLE
[FEA] Updates to groupby_max multithreaded benchmark

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#16237]
Thank you @srinivasyadav18 for the great work in #16154. I took another pass to study this benchmark and came up with some questions. @PointKernel I would love your feedback as well. 

* As I understand the code, the current implementation of `num_aggregations` increases the number of aggregation requests against the same data. So when we increase the value of `num_aggregations`, the input size is not changing.  With the current `add_element_count` formula, we see dramatically increasing throughput values with increasing `num_aggregations`. Do you think we should change the formula back to `num_rows / elapsed_time` from `(num_rows * num_aggregations) / elapsed_time`?

Example: note how `Mrow/s` is 2x for `num_aggregations=2` and 3.5x for `num_aggregations=4`
`cpp/build/benchmarks/GROUPBY_NVBENCH -d 0 -b 0 -a T=[I64] -a num_rows[pow2]=[24] -a cardinality=1000000 -a num_aggregations=[1,2,4] -a null_probability=0.1`

```
|  T  | cardinality |    num_rows     | null_probability | num_aggregations | Samples | CPU Time | Noise  | GPU Time | Noise  | Mrows/s | peak_memory_usage |
|-----|-------------|-----------------|------------------|------------------|---------|----------|--------|----------|--------|---------|-------------------|
| I64 |     1000000 | 2^24 = 16777216 |              0.1 |                1 |    592x | 2.030 ms | 31.79% | 2.001 ms | 30.01% |    8385 |       337.855 MiB |
| I64 |     1000000 | 2^24 = 16777216 |              0.1 |                2 |   2784x | 1.916 ms | 14.42% | 1.904 ms | 13.26% |   17620 |       388.014 MiB |
| I64 |     1000000 | 2^24 = 16777216 |              0.1 |                4 |    193x | 2.608 ms |  0.29% | 2.602 ms |  0.17% |   25788 |       648.014 MiB |
```

* I noticed that sometimes we see huge throughput increases with large `num_aggregations`. I believe this is due to uncaught OOM errors that reduce the runtime without actually completing the work. Is there a way to adjust the benchmark to make a test fail if any of the threads fail?

Example: note how runtime for 1 agg is longer than for 16 aggs.
`cpp/build/benchmarks/GROUPBY_NVBENCH -d 0 -b 2 -a T=[I64] -a num_rows[pow2]=[30] -a cardinality=1000000 -a num_aggregations=[1,16] -a null_probability=0.1 -a num_threads=8`

```
|  T  | cardinality |     num_rows      | null_probability | num_aggregations | num_threads | Samples |  CPU Time  |  Noise  |  GPU Time  |  Noise  | Mrows/s | peak_memory_usage |
|-----|-------------|-------------------|------------------|------------------|-------------|---------|------------|---------|------------|---------|---------|-------------------|
| I64 |     1000000 | 2^30 = 1073741824 |              0.1 |                1 |           8 |     44x | 341.514 ms |  64.77% | 341.507 ms |  64.77% |   25153 |        44.375 GiB |
| I64 |     1000000 | 2^30 = 1073741824 |              0.1 |               16 |           8 |    104x | 150.298 ms | 128.60% | 150.289 ms | 128.60% |  914494 |        40.625 GiB |
```

* In it's current form, the benchmark is still dominated by threading overhead when row count is <1M or so. I'm hopeful that #16210 will reduce the threaded overhead enough to show throughput increases for small batch sizes. Do we have an early indication if this will be the case?

**Comment by srinivasyadav18** [comment]
Thank you @GregoryKimball for going studying the benchmark again!

> Do you think we should change the formula back to num_rows / elapsed_time from (num_rows * num_aggregations) / elapsed_time?

I belive we should stick to `(num_rows * num_aggregations)/elapsed_time` for **groupby_max** and `(num_rows * num_aggregations * num_threads)/elapsed_time` for **groupby_max_multithreaded**. Even though input data is fixed (num_rows), the aggregations that are happening are independent. The aggregation algorithm will process the entire input `num_rows` independently for each of the aggregation request. 

> I noticed that sometimes we see huge throughput increases with large num_aggregations. I believe this is due to uncaught OOM errors that reduce the runtime without actually completing the work. Is there a way to adjust the benchmark to make a test fail if any of the threads fail?

The current benchmark will definitely hit the OOM error. I re-checked again on **T4** which has only `16GB` memory and it did fail successfully. 
```
Run:  [1/2] groupby_max_multithreaded [Device=0 T=I64 cardinality=1000000 num_rows=2^30 null_probability=0.1 num_aggregations=1 num_threads=8]
Fail: Unexpected error: std::bad_alloc: out_of_memory: RMM failure at:/home/coder/cudf_groupby_max_bench/cpp/build/_deps/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:255: Maximum pool size exceeded
Run:  [2/2] groupby_max_multithreaded [Device=0 T=I64 cardinality=1000000 num_rows=2^30 null_probability=0.1 num_aggregations=16 num_threads=8]
Fail: Unexpected error: std::bad_alloc: out_of_memory: RMM failure at:/home/coder/cudf_groupby_max_bench/cpp/build/_deps/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:255: Maximum pool size exceeded
```
For the huge throughput increase in the benchmark you posted above also shows decrease in total time taken for the benchmark. I would need to further investigate if it is actually an OOM error and a true performance gain.

> In it's current form, the benchmark is still dominated by threading overhead when row count is <1M or so. I'm hopeful that https://github.com/rapidsai/cudf/pull/16210 will reduce the threaded overhead enough to show throughput increases for small batch sizes. Do we have an early indication if this will be the case?

Yes right, the threading overhead would still be dominant because the overheads did only became negligable when I made **threadpool** `sleep_time = 0`. Since the changes to **threadpool** are not **upstream** (not included inhttps://github.com/rapidsai/cudf/pull/16154), yet the performace would still be the same (slow). To get the performance without threading overheads, we can either update the **threadpool** `sleep_time = 0` in the current implementation, and/or test with https://github.com/rapidsai/cudf/pull/16210 and see which ever works the best.

**Comment by GregoryKimball** [comment]
These topics have been adequately addressed.
