### ISSUE TITLE
[BUG] read_csv with nrows loads all rows in memory and then samples it 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#1643]
**Describe the bug**
Read_csv with nrows seems to reading all the rows to memory and then sampling n out of it . It should only read n rows and not sample later. 

This behavior beats the point of having nrows as as a user I like to use nrows to sample when my data frame does not fit in memory.

**Steps/Code to reproduce bug**
Code:
```python
import cudf
import pandas as pd

def generate_file(output_file,rows=1000):
    with open(output_file, 'wb') as f:
        f.write(b'A,B,C,D,E,F,G,H,I,J,K\n')
        f.write(b'22,697,56,0.0,0.0,0.0,0.0,0.0,0.0,0,0\n'*rows)
        f.close()
        
fn = 'bigfile.csv'
generate_file(fn,rows=500_000_000)


pandas_df = pd.read_csv(fn,nrows=1)
print("pandas len = {}".format(len(pandas_df)))
gdf = cudf.read_csv(fn,nrows=1)
print("gdf len ={}".format(len(gdf)))


```

**Expected behavior**

It is expected that only n rows will be read first. 

**Additional context**
The gpu usage shoots up  looks like below:

```sh
Mon May  6 12:11:34 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   37C    P0    80W / 300W |   8501MiB / 16280MiB |    100%      Default |
```

May be we need a rewrite of below (Dont know for sure) :
https://github.com/rapidsai/cudf/blob/7cb7142d0e89f2c39fbba88725c1e408ca9dcb25/cpp/src/io/csv/csv_reader.cu#L1018-L1022

**Comment by mjsamoht** [comment]
CSV files don't contain a header so we need to parse the entire file in order to find all the record/row starts.  Once we determined the file offsets for processing the requested `n` rows we only upload the necessary data to the GPU.

For large files it's probably better to use the `byte_range` feature.  Are you familiar with that, @VibhuJawa ?

**Comment by VibhuJawa** [comment]
Yeah. I am familiar with `byte_range` . 

I have a couple of clarifying questions . New to rapids so have limited understanding.  

1. When you say we parse, are we parsing the entire file in gpu memory or system memory?

2. If we are doing it at system memory level, i think just reading n rows should  be possible (as pandas does it at https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/io/parsers.py#L435) 

Please correct me if this is wrong .

**Comment by mjsamoht** [comment]
@vuule would be the best person to explain.

But, yes, we are parsing the entire file in gpu memory to find line terminators (and quote characters).  This is done on the GPU because it can be parallelized.  We don't load the entire file into gpu memory at once.  Instead we break it up into chunks and copy and process one chunk at a time.

**Comment by harrism** [comment]
@vuule @VibhuJawa is this really an issue, or can we close?

**Comment by VibhuJawa** [comment]
Closing the issue because this is by design.  

Thanks for the reminder.
