### ISSUE TITLE
[QST] Regarding erased_key_sentinel in static map

### ISSUE THREAD

**Issue by avithemad** [rapidsai/cudf#16734]
**How does the erased_key_sentinel work with linear probing in static_map when using the find function?**

I wanted to know when we initialize the static map like following:
```
  auto part_map = cuco::static_map{part_capacity, cuco::empty_key{-1}, cuco::empty_value{-1}, thrust::equal_to<int>{},
                              cuco::double_hashing<TILE_SIZE, cuco::default_hash_function<int>>{}};
```

We do not specify the delete sentinel so does it assume it is the same key as empty sentinel?
If so how do I distinguish between empty and deleted sentinel so that I get a better unsuccessful search performance? Could you please provide a sample constructor for doing so? 

Why I ask this is because, in my use case there are a lot of unsuccessful searches, and I observe that L1 and L2 cache hit rate is very low as the hash table does not fit in L2, so I am assuming that for every unsuccessful search it traverses the entire hash table since its not able to distinguish between deleted and empty key.
Apologies for my ignorance if any or anything wrong with the above reasoning, I am fairly new to this library and cuda.

**Comment by davidwendt** [comment]
Did you mean to open this in https://github.com/NVIDIA/cucollections ?

**Comment by sleeepyjack** [comment]
Hi @avithemad!

cuco dev here. Let me explain how the `erased_key_sentinel` logic works in this case:

Each slot in a new map is initialized with `empty_key_sentinel`. When probing for a key that is not contained in the map, we can apply an early exited once we encounter the first empty slot. Assuming keys in the map are distributed uniformly random across slots, it is very likely to hit such an early exit with only a few probing steps. So you don't actually probe through the entire map for a negative lookup.

The `erased_key_sentinel` is only relevant if you actually delete keys from the map. If this is intended, then you have to pass in an `erased_key_sentinel` that must be different from the `empty_key_sentinel`. In other words: it is only legal to erase keys if the two sentinels are not equal. I think the map's host-sided APIs [will throw an error](https://github.com/NVIDIA/cuCollections/blob/4454de4b878f31d41c5b7578fe6ca24bba5ea3f4/include/cuco/static_map.cuh#L597) in this case.

If you're not doing any deletion, then there will be no `erased_key_sentinel`s in the map so performance is not impacted at all. If your application relies on frequent deleetions from the map then at some extreme point you'll see some performance degradation due to longer probing sequences (we can't apply the aforementioned early exit on erased slots`.
In this (very specialized) case I would advise to call `map.rehash` every now and then which will regenerate the map and remove any erased slots.

>  I observe that L1 and L2 cache hit rate is very low

Hash table operations are inherently tight to random memory access patterns. Thus, if the map's extent exceeds the available L2$ size, then it is expected to have poor cache hit rate. Hash map performance is usually bound by the raw random access performance of the underlying memory system.

**Comment by vyasr** [comment]
FYI GH does not allow transferring issues between organizations so I don't think we can migrate this over to cuco that easily now.
