### ISSUE TITLE
[BUG] libcudf install does not install nvcomp dependency

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#16986]
**Describe the bug**
After #16946 performing a cmake install of libcudf no longer installs the files for the nvcomp dependency (i.e.: cmake config, shared libraries, etc.).  This results in downstream projects depending on the libcudf build result to fail to configure due to the missing nvcomp dependency of libcudf, e.g.:
```
09:25:30  [INFO]      [exec] -- Configuring incomplete, errors occurred!
09:25:30  [INFO]      [exec] CMake Error at /usr/local/cmake-3.26.4-linux-x86_64/share/cmake-3.26/Modules/CMakeFindDependencyMacro.cmake:76 (find_package):
09:25:30  [INFO]      [exec]   By not providing "Findnvcomp.cmake" in CMAKE_MODULE_PATH this project has
09:25:30  [INFO]      [exec]   asked CMake to find a package configuration file provided by "nvcomp", but
09:25:30  [INFO]      [exec]   CMake did not find one.
09:25:30  [INFO]      [exec] 
09:25:30  [INFO]      [exec]   Could not find a package configuration file provided by "nvcomp" with any
09:25:30  [INFO]      [exec]   of the following names:
09:25:30  [INFO]      [exec] 
09:25:30  [INFO]      [exec]     nvcompConfig.cmake
09:25:30  [INFO]      [exec]     nvcomp-config.cmake
09:25:30  [INFO]      [exec] 
09:25:30  [INFO]      [exec]   Add the installation prefix of "nvcomp" to CMAKE_PREFIX_PATH or set
09:25:30  [INFO]      [exec]   "nvcomp_DIR" to a directory containing one of the above files.  If "nvcomp"
09:25:30  [INFO]      [exec]   provides a separate development package or SDK, be sure it has been
09:25:30  [INFO]      [exec]   installed.
09:25:30  [INFO]      [exec] Call Stack (most recent call first):
09:25:30  [INFO]      [exec]   /target/libcudf-install/lib64/cmake/cudf/cudf-dependencies.cmake:53 (find_dependency)
09:25:30  [INFO]      [exec]   /target/libcudf-install/lib64/cmake/cudf/cudf-config.cmake:90 (include)
09:25:30  [INFO]      [exec]   /target/jni/cmake-build/_deps/rapids-cmake-src/rapids-cmake/find/package.cmake:125 (find_package)
09:25:30  [INFO]      [exec]   CMakeLists.txt:146 (rapids_find_package)
```

**Steps/Code to reproduce bug**
Perform a cmake install of libcudf and note the lack of nvcomp artifacts in the install area.

To reproduce the downstream project error noted above:
```
git clone --depth 1 --branch branch-24.12 https://github.com/NVIDIA/spark-rapids-jni.git
cd spark-rapids-jni/thirdparty/cudf
git checkout branch-24.12
git pull
cd ../..
build/build-in-docker clean package -Dsubmodule.check.skip=true -Dlibcudf.dependency.mode=latest -DskipTests
```

Reverting #16946 in thirdparty/cudf before the build/build-in-docker command allows the build to succeed.

**Expected behavior**
nvcomp build artifacts are installed alongside libcudf artifacts for a libcudf install since nvcomp is a required dependency.

**Comment by bdice** [comment]
@KyleFromNVIDIA Could you take a look?

**Comment by KyleFromNVIDIA** [comment]
Well, that is unfortunate. Luckily, this is only an issue for static builds, since nvcomp is a `PRIVATE` dependency of cudf, and even in static builds the only thing we need is the nvcomp shared library.

We may be able to add special logic to the cudf export file that, instead of calling `find_dependency(nvcomp)`, simply adds the `nvcomp::nvcomp` imported target based on the location of the shared library in the nvcomp wheel.

**Comment by bdice** [comment]
I was with you up to the last part “based on the location of the shared library in the nvcomp wheel.” This should not affect wheel builds? This should only affect static libcudf builds, like those used by Spark — which have nothing to do with wheels. I think the issue is with the CPM-fetch code path, because we find nvcomp via conda packages or wheels for the other paths.

**Comment by KyleFromNVIDIA** [comment]
Ah, you're right. In that case the solution is much simpler: provide an option in `cpp/CMakeLists.txt` to export or not export nvcomp.
