### ISSUE TITLE
[QST] Our recent benchmarking of cuDF and OmniSci Core DB

### ISSUE THREAD

**Issue by MasoodK** [rapidsai/cudf#1699]
Hello cuDF devs,

Mainly informing you about our recent benchmarking of cuDF and OmniSci Core DB, but also seeking comments and feedback regarding the methodology and results.

- [Deck](https://speakerdeck.com/patternedscience/supercharging-analytics-with-gpus-masood-krohy)
- [Presentation/Demo video](https://www.youtube.com/watch?v=UteAyQStPyQ)
- [GitHub repo containing jupyter notebooks/results](https://github.com/patternedscience/GPU-Analytics-Perf-Tests)

Feel free to reach out for any questions, if there are any, and I'll be happy to receive your feedback. Thanks for your work on cuDF!

**Comment by kkraus14** [comment]
@MasoodK Thanks for running these and reporting back the results. Regarding the OmniSci numbers: you noted that you only captured the first run as it was caching results afterwards. Are you sure it was actually caching the results as opposed to it just loading the data into GPU memory? Want to make sure you're fairly and accurately showing OmniSci's capabilities here 😄 

cc @andrewseidl @randyzwitch from OmniSci who may have some comments about this

**Comment by kkraus14** [comment]
Would also love to see results from a more recent release of cuDF!

**Comment by randyzwitch** [comment]
Keith is correct here, “caching” is the wrong way to look at this from an OmniSci perspective. The first run is comprised of two events: loading the data into GPU memory and LLVM compiling the query. The first doesn’t necessarily have to happen (it’s possible the required data is already in memory), but the LLVM compilation will happen for each new query. However, one thing that we aren’t doing is actually caching the results. Upon running a second time, the calculations still happen, you just don’t load data into GPU RAM nor do you compile.

So this benchmark is representative of cold-start performance of OnniSci, but ultimately not representative of the use cases we target, which is repetitive drilling-in to data, whether that’s zooming into a map or cross-filtering across time. In each of those examples, you pay the LLVM compilation cost once, the data load time once, and then potentially hundreds or thousands of queries as you look at different slices of the data.

It’s also not clear to me that the benchmarks measure the same thing. For pandas and cudf, if you’re measuring data loading separate from running the calculations, you are essentially starting from a “cached” state: the data are loaded into GPU/CPU RAM. That’s what the first load of OmniSci is doing, putting the data into the equivalent location for the GPU to operate on it. In that sense, load_table_columnar or our load from CSV is only comparable to loading data in another database, not comparable to cudf or pandas.

**Comment by MasoodK** [comment]
Thanks guys for the feedback!

@kkraus14:
- The first-run results as well as results of subsequent runs are both captured; the latter are in the jupyter notebooks, linked above
- Yes, you guessed it right. I am not sure whether it was time-to-load-into-GPU-memory or caching of intermediary results; this is not visible to the user. In hindsight, I see that I should have used a more general term which covers both cases.
- Recent release of cuDF would be good to have, I agree. This is currently not scheduled, however.

@randyzwitch: thanks Randy for the explanations! I hinted at a bad choice of term above. However, technically, the time-to-load is there. That's the delay that the user would face, no matter what one calls it. The results, as structured in the graph, should be compared in 2 categories: databases and dataframes. I explained verbally during the presentation (cf. the video) that both databases are being hit by IO time and dataframes are benchmarked after data load.
Regarding "this benchmark is representative of cold-start performance of OnniSci, but ultimately not representative of the use cases we target", as mentioned above, the results of subsequent runs are already produced; see the notebooks. I'd just add that the use cases you target might not be the use cases I target. For me, both delays are generally important, but I understand that OmniSci would shine much better in 2nd and subsequent runs. It is already shinning well enough, however, and we're using it :)

I think I covered everything here; feel free to comment if I missed sth.

**Comment by kkraus14** [comment]
> * The first-run results as well as results of subsequent runs are both captured; the latter are in the jupyter notebooks, linked above

With all due respect, I didn't dig into the Jupyter notebooks because it's time consuming and non-straightforward to do so. If developers of the libraries you're benchmarking aren't digging in, then I would strongly guess that the vast majority of end users aren't doing so either.

> * Yes, you guessed it right. I am not sure whether it was time-to-load-into-GPU-memory or caching of intermediary results; this is not visible to the user. In hindsight, I see that I should have used a more general term which covers both cases.

Without explaining this in the presentation deck I would argue that you're not fairly portraying OmniSci in this context and giving users consuming your presentation the wrong conclusions. If cold start queries are your target benchmark then you should clearly indicate that as well as indicate that OmniSci is not optimized for these types of workloads.

> That's the delay that the user would face, no matter what one calls it. The results, as structured in the graph, should be compared in 2 categories: databases and dataframes. I explained verbally during the presentation (cf. the video) that both databases are being hit by IO time and dataframes are benchmarked after data load.

That's the delay someone would face once in a cold start query. You could strongly argue that if a user was concerned about one time or cold start query performance they would create a temporary table in OmniSci as opposed to a normal table since that would remove the cold start penalty. Again, the lack of a clear indication in the deck is what makes the conclusions confusing as an end user.

> I understand that OmniSci would shine much better in 2nd and subsequent runs. It is already shinning well enough, however, and we're using it :)

"It is already shining well enough" is not something that should be said when it comes to presenting benchmarks. The results should be presented so that the conclusions end users arrive at are based on factual data as opposed to just technology a is better than technology b.

**Comment by MasoodK** [comment]
> With all due respect, I didn't dig into the Jupyter notebooks because it's time consuming and non-straightforward to do so. If developers of the libraries you're benchmarking aren't digging in, then I would strongly guess that the vast majority of end users aren't doing so either.

@kkraus14 
With all due respect, you should have checked the notebooks that are well-documented as well as watched the video of the presentation before writing this last comment. Overall and when all material is consulted, I still believe OmniSci and other components have been represented fairly. The graphs in the deck clearly say that the 2nd and subsequent runs are faster for OmniSci.

Thanks for your comments and feedback so far; however, I am no longer interested in this discussion. This does not seem a fair, technical feedback and debate to me.

**Comment by randyzwitch** [comment]
> @randyzwitch: thanks Randy for the explanations! I hinted at a bad choice of term above. However, technically, the time-to-load is there. That's the delay that the user would face, no matter what one calls it. 

Right, but I think there's a strong distinction between keeping data in 'hot memory' (which most if not all databases do) vs. memoization by caching the results of function calls/queries. 

As @kkraus14 mentions, how you select the benchmark can determine the results. If you're going solely on cold start, then OmniSci likely isn't going to win just like C++ isn't going to beat Python in "Hello, World!" (because you have to compile the C++ code).

>  I'd just add that the use cases you target might not be the use cases I target. 

Sure, but ultimately how the results are presented currently make it look like OmniSci isn't even competitive with pandas, which isn't true for anything but the smallest or most trivial problems. You might not have been making that comparison, but having them both on the same slide absolutely does.
