### ISSUE TITLE
[PERF] Remove stream sync in concatenate for better pipelining

### ISSUE THREAD

**Issue by tgujar** [rapidsai/cudf#17172]
Concatenate function uses `thrust::copy` in its implementation but throws away the return value from `thrust::copy`. Since `thrust::copy` needs to return an iterator it leads to an unnecessary stream sync.
https://github.com/rapidsai/cudf/blob/2de545b41ce936dabfaa47e7d482e707dcf7df62/cpp/src/copying/concatenate.cu#L310

**Comment by wence-** [comment]
Note that it does not suffice to use the `nosync` exec policy for such thrust calls, since whenever thrust returns a host-side value, even with the nosync exec policy it must sync.

There are numerous places (I have not audited them) where we make such calls but don't actually need the sync. So we should, with benchmarking evidence, consider either implementing non-syncing implementations in libcudf, or upstreaming a CCCL request for such features so that everyone can get them.
