### ISSUE TITLE
[FEA] Error message that explains why installing failed

### ISSUE THREAD

**Issue by betatim** [rapidsai/cudf#17296]
**Is your feature request related to a problem? Please describe.**
I tried to install cudf (to try out `cudf.pandas` in a freshly created conda environment. This failed with a large error message but no clear indication of what went wrong.

I used `pip install --extra-index-url=https://pypi.nvidia.com "cudf-cu12==24.10.*"` (had to add the `"` to make my shell happy but otherwise verbatim from the RAPIDS install selector).

The output:
```
pip install --extra-index-url=https://pypi.nvidia.com "cudf-cu12==24.10.*"
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu12==24.10.*
  Downloading cudf_cu12-24.10.1.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp310-cp310-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp310-cp310-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp310-cp310-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp310-cp310-manylinux_2_24_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp310-cp310-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp310-cp310-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp310-cp310-manylinux_2_24_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp311-cp311-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp311-cp311-manylinux_2_24_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp311-cp311-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp311-cp311-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp311-cp311-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp311-cp311-manylinux_2_24_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp312-cp312-manylinux_2_24_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp312-cp312-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp312-cp312-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp312-cp312-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp312-cp312-manylinux_2_24_x86_64
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for cudf-cu12 24.10.1

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/thead/miniconda/envs/cudf-pandas-explore/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/Users/thead/miniconda/envs/cudf-pandas-explore/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/thead/miniconda/envs/cudf-pandas-explore/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/wheel.py", line 179, in download_wheel
          report_install_failure(distribution, version, exception_context)
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/k4/18n83cqx1pn8fvwjbr2ly1n40000gp/T/pip-build-env-_w1y5qep/overlay/lib/python3.13/site-packages/nvidia_stub/error.py", line 63, in report_install_failure
          raise InstallFailedError(
          ...<8 lines>...
          )
      nvidia_stub.error.InstallFailedError:
      *******************************************************************************

      The installation of cudf-cu12 for version 24.10.1 failed.

      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com. If https://pypi.nvidia.com is not reachable, we
      cannot download the real wheel file to install.

      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com cudf-cu12
      ```

      Here is some debug information about your platform to include in any bug
      report:

      Python Version: CPython 3.13.0
      Operating System: Darwin 24.1.0
      CPU Architecture: arm64
      nvidia-smi command not found. Ensure NVIDIA drivers are installed.

      *******************************************************************************

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Describe the solution you'd like**
A clear error message about what went wrong and why it could not install cudf. In this case it is because Python 3.13 isn't supported, but I think figuring this out is impossible, unless you already know that this is the problem.

There is a bit of a helpful message but its main recommendation is to try and do what I already did (the command it suggests to try).

I am actually not sure if this is something that can be fixed in cudf or if it needs fixing in the `nvidia-stub` package/code?

**Comment by betatim** [comment]
After downgrading Python to 3.12 I still got an error, which looks basically like the above. The solution in this case was "There are no wheels for MacOS" but it took me much longer to figure out and I had to ask a friend for a second pair of eyes.

**Comment by brandon-b-miller** [comment]
Thank you @betatim for reporting. I'd agree that at the very least, it's not helpful for the error to suggest the same instructions that are already being followed. I know this has come up before but I'm not sure what the blockers/issues were, so I'll circle back here when I know more.

**Comment by bdice** [comment]
```
      Here is some debug information about your platform to include in any bug
      report:

      Python Version: CPython 3.13.0
      Operating System: Darwin 24.1.0
      CPU Architecture: arm64
      nvidia-smi command not found. Ensure NVIDIA drivers are installed.
```
This is the debug info we added a few release ago. You can also see there is no compatible tag in the info logs above:
```
INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp310-cp310-manylinux_2_24_aarch64.manylinux_2_28_aarch64.whl against tag cp310-cp310-manylinux_2_28_aarch64
```

Can you provide an example of a package that provides clearer information so we can learn from it?

**Comment by betatim** [comment]
Unfortunately I have no example to point to. The ideal case would be a message saying "There is no wheel available for your Python version (Python 3.13)."

Looking at `INFO:nvidia-stub:Testing wheel cudf_cu12-24.10.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl against tag cp311-cp311-manylinux_2_28_x86_64` (and its friends) I am not even sure which side of the comparison shows what is available and which side shows "what we are looking for". But even so it looks like the two sides should match? The right hand side looks like it is a substring of the left. And for the other lines this is true as well?

So the first "weirdness" is that I am seeing lines that say "Testing X against Y" where X and Y seem to match, but the overall result is still "nothing matches". The second hurdle is that you need to know that `cp313` should appear somewhere in that list because I'm using Python 3.13 and that the fact that it is absent is probably the reason it doesn't work.

So overall there is a lot of information there but somehow, unless you already know what to look for (aka are helping someone debug their problem) it is too much information and at the same time not enough. Which is why I think having a short thing like "We couldn't find a match for your Python version (Python 3.13)" would be more useful.

But it is tricky figuring out why the matching didn't work, or you'd have to make a hierarchy of where to start from. Because in my case there are actually two problems (Python version and architecture), and I have no idea how you'd detect both in one go.

**Comment by vyasr** [comment]
This isn't a cudf issue. The same issue will exist for any package using nvidia-stub, and in different form for any pip package at all that only provides wheels and not sdists. There are two levels of problems here, one in pip and one in nvidia-stub. 

**nvidia-stub**

The nvidia-stub loops over all available packages in our repository, checks for compatibility, and then errors if at the end no compatible wheels were found. It is configured with [Python's logging module](https://docs.python.org/3/howto/logging.html). One way to get more information is to set the environment variable `WHEEL_STUB_LOGLEVEL` and see why each wheel individually did not match. Possible AIs here:
- Increase the default logging level in nvidia-stub. I think this is fairly harmless since pip will hide all of that output by default anyway unless the build fails. Then you would at least see a list of why each available wheel failed to match.
- Collect all log messages and save them so that if an exception is raised when nothing is found the full set of logs can be printed.
- If a wheel fails to match for one reason, instead of breaking out immediately continue to check all the other components in order to provide full debugging information (e.g. this wheel doesn't match the abi tag or the Python version or the glibc version). That may have measurably negative performance implications for installation, though, so I'd want to use that approach with caution.

As you noted, though, there is no universal way to indicate "why no wheel was found" though because you will have different reasons for each candidate being rejected. You could put together some heuristics that check if the same reason applied to all wheels, for example, but at that point things start getting complicated enough that I'd be worried about slowing down installs in the default case since you'd have to collect al the information as you go along for each wheel that did not match in anticipation of the fact that at the end no wheels will have matched and you need to fail. IMO the end-user will have to at least recognize that "all wheels failed because the OS didn't match". This is especially true because (as I mention below) that is how pip itself works.

All of this discussion is also relevant for every other RAPIDS package, so if we think that any of these changes to improve reporting are worth pursuing I can report up the proper channels.

**pip**

Unfortunately, all of the above discussion will become moot for cudf in 24.12 because cudf is going to be released onto PyPI, so we won't be using nvidia-stub anymore. At that point, we'll be stuck with pip's own default logging, which is no more informative than nvidia-stub. If pip fails to install a package when nothing is available, you get equally uninformative information (see e.g. [this SO post](https://stackoverflow.com/questions/55406059/how-to-get-pip-to-tell-me-why-it-doesnt-match-pypi-binary-wheels)). There's not much that we can do about that.

**Comment by betatim** [comment]
I guess I just became a fan of the nvidia-stub indirection :D

More seriously, if cudf is switching to directly being on PyPI then there is indeed not much to be done here.

**Comment by bdice** [comment]
This issue tracks adding Python 3.13 support: https://github.com/rapidsai/build-planning/issues/120
