### ISSUE TITLE
[DISCUSSION] Leveraging CuPy for transposing large numeric dataframes

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1822]
The transpose operation is time consuming / expensive for large dataframes. As @thomcom mentioned in the [column redesign discussion](https://github.com/rapidsai/cudf/issues/1443#issuecomment-489109734), transpose operations are used pretty frequently. 

I'd like to raise a discussion about allowing users to leverage CuPy for transpose under select circumstances. While CuPy is not currently a dependency of cuDF, users can currently operate within the broader GPU analytics ecosystem by leveraging interoperability interfaces like dlpack and the cuda array interface. CuPy only supports numeric arrays, but its transpose appears to be quite efficient.

Below is a timing comparison I just ran of transposing a dense 10,000 x 10,000 dataframe of float64 values on a V100 (the cuDF transpose clock time here is slower than I ran it last night, but there was still a significant difference).

```python
import cudf
import cupy

arr = cupy.random.normal(5,5,100000000).reshape(10000, -1) # 10,000 x 10,000 array
df = cudf.from_dlpack(arr.toDlpack())

%time df.T
%time cudf.from_dlpack(cupy.fromDlpack(df.to_dlpack()).T.toDlpack())
CPU times: user 1min, sys: 16.2 s, total: 1min 16s
Wall time: 1min 35s
CPU times: user 1.24 s, sys: 176 ms, total: 1.42 s
Wall time: 1.55 s
```

Another example, transposing a dense 10,000 x 10 array of float64 values.

```python
import pandas as pd
import numpy as np
import cudf
import cupy

arr = np.random.normal(5,5,100000).reshape(10000, -1) # 10,000 x 10 array
df = pd.DataFrame(arr)
df = cudf.from_pandas(df)

%time df.T
%time cudf.from_dlpack(cupy.fromDlpack(df.to_dlpack()).T.toDlpack())
CPU times: user 56.7 s, sys: 660 ms, total: 57.3 s
Wall time: 57.3 s
CPU times: user 840 ms, sys: 20 ms, total: 860 ms
Wall time: 860 ms
<cudf.DataFrame ncols=10000 nrows=10 >

```

We could allow users to leverage CuPy when they have it installed in their environment already. Something similar to what we have in our test suite for dlpack perhaps could work:

```python
try:
    import cupy
    _have_cupy = True
except ImportError:
    _have_cupy = False
```

followed by branching logic based on `_have_cupy`.

If this kind of support is potentially desirable, it might be worth someone profiling the distribution of array shapes in the 2-d space that result in a large speedup in transpose. Adding a third dimension of data type could be valuable as well.

**Comment by jrhemstad** [comment]
I'd be very curious to find out how cuPy is doing their transpose. Is the output of a cuPy transpose a DataFrame or an nd-array?  

Likewise, would be curious to find out what's going on in `from/toDlpack`. 

The bottleneck in cuDF transpose has always been the allocation of Python column objects. So for example, in 

```
cudf.from_dlpack(cupy.fromDlpack(df.to_dlpack()).T.toDlpack())
```
I would think this line would suffer from the same bottleneck of having to allocate 10,000 Python column objects for the output DataFrame. 

If the `from_dlpack` operation is somehow doing this efficiently, then we should just emulate this functionality in cuDFs transpose rather than more circuitous path of going through cuPy.

**Comment by beckernick** [comment]
@jrhemstad , the output of the CuPy transpose is a cupy.ndarray. All of what you've suggested makes sense to me and seems worth more investigation.

**Comment by dantegd** [comment]
@jrhemstad the output of cuPy is an nd-array, and your explanation is indeed the reason for the relatively slow transpose of cuDF as far as I understand. For that matter numba also has a pretty fast transpose implementation, would be interesting to see a comparison between those two libraries.

But regardless of that, @beckernick's idea is something I had thought about as well since in cuML we end up having a pretty efficient transpose as well, but the main reason is that we don't have bitmasks so our memory arrangements are easier to work with than cuDF. The main issue then becomes that this path can only be done if there are no bitmasks, or at the very least there are no missing values. 

So I could see the execution path being: 

1. Check the dataframe is only cupy compatible types (i.e. np.float* for example)
2. Check there are no missing values, if there are then stop
3. Given there are no missing values (but still probably bitmasks), then create a gpu matrix with to_gpu_matrix.
4. Use cupy for the traspose
5. Create the new dataframe from the trasposed data

Let me know if my analysis misses something :)

**Comment by jrhemstad** [comment]
> But regardless of that, @beckernick's idea is something I had thought about as well since in cuML we end up having a pretty efficient transpose as well, but the main reason is that we don't have bitmasks so our memory arrangements are easier to work with than cuDF. The main issue then becomes that this path can only be done if there are no bitmasks, or at the very least there are no missing values.
> 
> So I could see the execution path being:
> 
> 1. Check the dataframe is only cupy compatible types (i.e. np.float* for example)
> 2. Check there are no missing values, if there are then stop
> 3. Given there are no missing values (but still probably bitmasks), then create a gpu matrix with to_gpu_matrix.
> 4. Use cupy for the traspose
> 5. Create the new dataframe from the trasposed data
> 
> Let me know if my analysis misses something :)

Transposing the bitmasks isn't the bottleneck for the cuDF transpose. We've got an efficient way to do that.

Step 5. was the bottleneck when @devavret did the initial investigation, i.e., how do you create a DataFrame from an nd-array?

**Comment by devavret** [comment]
Our bottleneck is entirely in allocating and constructing new columns, both in python and in C++. The gtests are also slow but all because of the allocations. Actual data movement takes no time at all. This problem can only go away if we have some sort of ndarray support in dataframe. Or if we figure out fast allocations on C++ side, then some sort of lazy loading of columns on the python side. 

I am more interested in how people use the result of the transpose. I cannot imagine people needing all the millions of columns that get created. So is it possible to somehow indicate earlier what rows might they in interested in transposing. Then it's a matter of applying a simple gather and then a transpose of a much smaller dataframe. My solution about lazy loading also makes the same presumption, that most of the columns in the transposed df won't be needed so we could construct the python side column objects only when accessed.

**Comment by jrhemstad** [comment]
> Our bottleneck is entirely in allocating and constructing new columns, both in python and in **C++.** 

So we can make that part fast by just allocating `n` `gdf_column`s all at once instead of one by one. E.g.,

`gdf_column * cols = malloc(n * sizeof(gdf_column));` 

Clearly though, somehow the cuPy path is able to do the allocation of the output columns much faster than we can. So something funny is going on there.

**Comment by devavret** [comment]
No I meant include the time for allocating data memory as well.

**Comment by beckernick** [comment]
Comparing the following:

```python
%time cudf_got = df.T
%time cupy_got =  cudf.DataFrame.from_gpu_matrix(cuda.as_cuda_array(cupy.fromDlpack(df.to_dlpack()).T))
```
It appears that using our native transpose spends a lot of time in `DataFrame.set_index` and `DataFrame.rename` compared to using CuPy transpose and then grabbing the result (whether through `from_dlpack` or the array interface via Numba). In fact, we don't spend any time in `dataframe.rename` when don't use our transpose function according to the cProfile results.

Some snakeviz screenshots:

`df.T`
![Screen Shot 2019-05-23 at 9 56 12 PM](https://user-images.githubusercontent.com/8457388/58328475-2bb6a280-7e00-11e9-926e-8e0ade233c6a.png)

`cudf.DataFrame.from_gpu_matrix(cuda.as_cuda_array(cupy.fromDlpack(df.to_dlpack()).T))`
![Screen Shot 2019-05-23 at 9 51 44 PM](https://user-images.githubusercontent.com/8457388/58328479-2fe2c000-7e00-11e9-8a03-05998f2f9680.png)

**Comment by kkraus14** [comment]
Okay, so most of the time in the transpose is in nonsense operations that we can eliminate. The rename is to just rename the columns of the output dataframe and is doing a deep copy instead of a shallow copy, which for a very wide dataframe is obviously super expensive. For the `set_index` we're doing an elementwise equals and then an `.all()` to check that the indexes are the same instead of just checking if they reference the same index object. We should be able to eliminate most of both of those blocks.

**Comment by kkraus14** [comment]
No longer need to do this with the merge of #4802
