### ISSUE TITLE
[FEA] libcudf boolean mask scatter and boolean mask scatter scalar

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1895]
Instead of providing an integer scatter map, there are times where a user wants to provide a boolean mask and set the values of the corresponding True values by either a dense buffer (of the same length as the number of True values) or by a scalar.

**Comment by harrism** [comment]
This would be implemented using a modification of `cudf::copy_if` that would take a second functor for generating the input rather than a column as input. e.g. a cross between `cudf::copy_if()`
https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/stream_compaction/copy_if.cuh#L276

and PR #1908's `cudf::copy_range()`.

**Comment by rgsl888prabhu** [comment]
> Instead of providing an integer scatter map, there are times where a user wants to provide a boolean mask and set the values of the corresponding True values by either a dense buffer (of the same length as the number of True values) or by a scalar.

Can you please provide an example ?

**Comment by harrism** [comment]
Could use a `copy_if` from a counting iterator to generate a gather mask and then call cudf::gather. 

For the scalar case, just a `copy_if` from a constant iterator.

**Comment by harrism** [comment]
Actually, rereading @kkraus14's description, this should be implementable using `cudf::copy_if_else` (CC @nvdbaranec ). 

For the dense buffer case, just set the dense buffer as the LHS and the original column as the RHS.  The output will have values from the target buffer in the true locations and values from the original buffer in the false locations.

For the scalar case, @nvdbaranec is adding support for taking a scalar as one of the inputs, so you could just set the LHS to the scalar and the RHS to the original column. 

So this issue should be fixed by #3446

**Comment by rgsl888prabhu** [comment]
@harrism as per Keith's comment `a dense buffer (of the same length as the number of True values)`, which can be of different size compared to RHS, but copy_if_else expects `LHS` and `RHS` to be of same size. So, we might have to resize `LHS` the dense buffer to match the size of RHS to use cop_if_else.

**Comment by rgsl888prabhu** [comment]
We have to get `scatter_map` from `copy_if` and use `column_scatterer` to scatter, for `dense buffer` variant.

**Comment by harrism** [comment]
Closed by #3681
