### ISSUE TITLE
[BUG] Compiling tests is slow because of `cudf_test_utils.cu`

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#2035]
**Describe the bug**
Tests take a long time to compile because of one common source file `cudf_test_utils.cu` that is compiled for each test. 

**Steps/Code to reproduce bug**
Compile libcudf from source

**Comment by jrhemstad** [comment]
Yeah, as we grow the number of testing utilities, we should probably create a separate library of test utilities to build once and link against for all tests.

@williamBlazing has actually expressed a desire for something like this in the past so that they could re-use our testing utilities in Blazing code.

**Comment by jrhemstad** [comment]
> Yeah, as we grow the number of testing utilities, we should probably create a separate library of test utilities to build once and link against for all tests.
> 
> @williamBlazing has actually expressed a desire for something like this in the past so that they could re-use our testing utilities in Blazing code.

Well you beat me to it! Great minds think alike! :smile:

**Comment by devavret** [comment]
I only created this issue only for bureaucratic reasons.
