### ISSUE TITLE
[BUG] to_csv fails with 200 million records

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2100]
**Describe the bug**
There is an OOM that happens when I have a data frame that fits into my single GPU. 

**Steps/Code to reproduce bug**

```python
import cudf
x = cudf.DataFrame({'first':[234] * 219586129 })
```

after this, the GPU memory occupancy is 1.8GB out of 16GB. nvidia-smi is:
![image](https://user-images.githubusercontent.com/11664259/60110746-37182900-9732-11e9-9102-eabaee91a66b.png)

Next, when I do `to_csv` on the above created dataframe my GPU usage spikes to 12GB and I get below exception:
```python
x.to_csv('sample.csv')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-359466d1c761> in <module>
----> 1 sample.to_csv('op.csv')

/conda/envs/cudf/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in to_csv(self, path, sep, na_rep, columns, header, index, line_terminator)
   3057         import cudf.io.csv as csv
   3058         return csv.to_csv(self, path, sep, na_rep, columns,
-> 3059                           header, index, line_terminator)
   3060 
   3061 

/conda/envs/cudf/lib/python3.7/site-packages/cudf/io/csv.py in to_csv(df, path, sep, na_rep, columns, header, index, line_terminator)
     74         columns=columns,
     75         header=header,
---> 76         line_terminator=line_terminator)

cudf/bindings/csv.pyx in cudf.bindings.csv.cpp_write_csv()

cudf/bindings/csv.pyx in cudf.bindings.csv.cpp_write_csv()

RuntimeError: rmm_allocator::allocate(): RMM_ALLOC: unspecified launch failure
```

![image](https://user-images.githubusercontent.com/11664259/60110885-80687880-9732-11e9-8491-49830c3958ef.png)

**Expected behavior**
This kind of memory explosion looked strange to me. Should this happen for a dataframe which is taking 2GB of memory?

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source

**Environment details**
[env.txt](https://github.com/rapidsai/cudf/files/3325998/env.txt)

**Additional context**
The actual dataframe has much more columns which almost fills to half of the single GPU memory.

**Comment by davidwendt** [comment]
The `to_csv()` requires converting columns to strings to place the character in CSV format in memory before writing the file. Column count and CPU memory capacity will be a factor along with GPU memory.
The integers are converted into 219586129 strings (['234','234',...]) which take a significant amount of memory ~24 bytes per string in this example so about 5.2GB. It may need to make copies to add delimiters,etc meaning there could be 2 in memory at the same time briefly -- spiking to 10GB. So this would explain the 12GB since you started with 1.8GB in integers in the dataframe.

I was able to execute your example on my 32GB card without error. I would recommend using smaller number of rows especially as the number of columns increase. Each column must be converted and resident in memory to write out even the first line of the CSV file.

**Comment by ayushdg** [comment]
I also noticed that on the python end setting `index=True` incurs a 2x memory overhead because it creates a copy of the df with the index as a column. In either case setting `index=False` still results in a 12 GB spike followed by an OOM error.
