### ISSUE TITLE
[BUG] string column functions returning lists - inconsistent with pandas

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2119]
**Describe the bug**
We currently have an inconsistency with pandas & cudf series string operations. Found this to be the case with few functions like `islower`, `isupper`, etc..
In pandas, for above functions, the return type is series but for a cudf series, it is list. 

**Steps/Code to reproduce bug**
Our behavior:
```python
import cudf
df = cudf.Series(['None'] * 5, dtype='str', name='sdf')
print(df.str.isalpha())
[True, True, True, True, True]
```
Pandas behavior:
```python
import pandas as pd
df = pd.Series(['None'] * 5, dtype='str', name='sdf')
print(df.str.isalpha())
0    True
1    True
2    True
3    True
4    True
Name: sdf, dtype: bool
```
**Expected behavior**
We should aswell be returning Series instead of list in all such functions. We can fix it either at either of places:
1. Fix this in nvstrings by bringing support for Boolean values in nvstrings. But I don't see a logical reasoning behind why we will ever have Boolean values as input to nvstrings.(Part of the reason why logging this issue in cudf is due to second option below.)
2. Currently we are only checking for nvstrings instance and creating a series out of it. We can handle it in cudf if the returned type is a list and create a series out of list.
https://github.com/rapidsai/cudf/blob/dff2b20fc4a680ce148477f4159041a655e05aaa/python/cudf/dataframe/string.py#L55

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install:from source(branch-0.9)

**Comment by beckernick** [comment]
This brings up a good point @galipremsagar : what should we do about non-explicitly implemented nvstrings methods in cuDF (and when should we do it)?

As you noted, with the current implementation, if the code doesn't follow that path of the branching logic this behavior occurs. However, this doesn't occur for `contains` (for example), as we have an explicit implementation that builds a column for the output device array used in the strings function.

We could check if the return type is a list, but we should avoid passing large Python lists around as it will be less efficient than passing device arrays. Two potential ways to address this could be:

- Explicitly allocating a device array and passing the pointer to the `__getattr__`. This has some drawbacks, as we wouldn't know in advance whether we should allocate the device array before the call to the nvstrings function, which means we'd have to do it every time (inefficient) or based on whether the attribute is in a pre-specified list (requires manual maintenance as we change/add functionality)
- Implementing more functions as explicit methods like contains, cat, extract, etc. This would take more effort and requires maintenance as well, but allows users and developers to look at the actual source code more easily.

If this is an immediate blocker, I'd vote for option one as it is simpler and would likely resolve the issue. Otherwise, I think option two is a better approach for future developers/users.

Would be interested to get @shwina and @thomcom thoughts on what makes the most sense.

**Comment by galipremsagar** [comment]
Makes sense, not a blocker to me. But it was something that I've observed while fixing another bug so brought this up.

**Comment by ayushdg** [comment]
I think methods like `islower`  `isalpha` etc. is supported by nvstrings so these methods could explicitly be added to strings.py. But I agree that it would take more effort as well as maintenance. 
- I'm not sure if this is feasible but the ideal case would be if we are able to have some sort of generic method that can identify if the method already exists in nvstrings in which case we can call that method directly or else go down the other route instead of writing a new cudf equivalent for every nvstrings method we want to expose.

**Comment by kkraus14** [comment]
> 2\. Currently we are only checking for nvstrings instance and creating a series out of it. We can handle it in cudf if the returned type is a list and create a series out of list.

We should absolutely not do this. If something is returning a list it's likely because the function wasn't called in a way consistent with the NVStrings API to return a device array. This leaves us with a few different options:

1. Continue to build on the StringColumn implementation in cuDF and implement the functions where needed in properly passing device arrays as inputs to NVStrings function calls and construct output columns from them.
2. Update the NVStrings Python API to default to allocating and returning device arrays instead of Python lists in situations like these.
3. Wait until NVStrings is merged into cuDF and tackle the problem along with the other rework we'll be doing.

I would support 1 or 3 above as both of those options end up being reusable when we start to merge the codebases.

**Comment by kkraus14** [comment]
I'm going to close this as the path forward is to continue building functions where appropriate to actually return device arrays properly.
