### ISSUE TITLE
[FEA] Behavior of apply_rows on dataframes with missing values

### ISSUE THREAD

**Issue by asmeurer** [rapidsai/cudf#2155]
I'm not sure if this is intended behavior or not. Right now it's a little annoying to use `apply_rows` on dataframes with missing values. This is the current behavior:

```py
>>> cudf.__version__
'0.8.0+0.g8fa7bd3.dirty'
>>> df = cudf.DataFrame({'a': [1., 2., None, 3.]})
>>> print(df)
     a
0  1.0
1  2.0
2
3  3.0
>>> def kernel(a, out):
...     for i, val in enumerate(a):
...         out[i] = val
>>> df = df.apply_rows(kernel, ['a'], {'out': float}, {})
>>> print(df)
     a       out
0  1.0       1.0
1  2.0       2.0
2            3.0
3  3.0  1.5e-323
```

You can see that the loop index in the kernel skipped the rows of `a` with missing values, but the 
same index applied to `out` did not skip those rows. So the `out` rows are out of order. To get what I really want, I have to first mask out the missing values from `a`, apply the kernel, then apply it back to the original dataframe with some sort of merge. That is, I would want

```py
     a  out
0  1.0  1.0
1  2.0  2.0
2            
3  3.0  3.0
```

It would be nice if 

1. The automatic masking out of missing values in the kernel also applied to the output columns.
2. The output column was initialized with missing values, rather than whatever happened to be in memory, or at least missing values were applied to `out` for the indices where `a` has missing values. 

I don't know how missing values are implemented in cudf so it's possible 2 might be considered too inefficient to do by default.

**Comment by cwharris** [comment]
Python has nulls, PANDAS has nulls, Arrow has nulls. Unfortunately, NumPy, and therefore Numba (which we use under the hood for `apply_rows` (as well as other `apply_`s), has no concept of nulls outside of `NaN` for floating point types and Numba's `optional` type (which might be useful for us).

Currently we're [removing nulls](https://github.com/rapidsai/cudf/blob/branch-0.9/python/cudf/cudf/utils/applyutils.py#L95) as a side effect of `.to_gpu_array()`, which leads to the mis-aligned outputs. Output is allocated based on the size of the input, but the input is then filtered before being passed to the kernel. Since the output' memory isn't initialized, we end up with trash values at the end.

There's a few ways to solve this problem, but the most promising looks like Numba's `optional` type: letting `numba.cuda.jit` take advantage of it and make sure it gets mapped back to arrow properly.

**Comment by cwharris** [comment]
If we set the `fillna` parameter to `"pandas"` in the `to_gpu_array` method, we can get around this issue, but only for floating point types. For other values, they will be filled with the defaults (as according to how we think pandas would fill it). We could utilize this to re-create a null mask from the `fillna` sentinel value.

@kkraus14 how do we feel about exposing `fillna` in `apply_rows`?

Another way to handle this is injecting the null map explicitly and manually manipulating the func source to account for assignments operations. I don't know if we already do this sort of on-the-fly refactoring somewhere. It's possible a library already exists for this, but we probably don't want to add a dependency on a new library?

**Comment by kkraus14** [comment]
@cwharris I'm not following the issue. From my perspective this should be simple in that we currently call `.to_gpu_array()` to get to the underlying memory, instead of using `.data.mem`. And then we should deep copy the bitmask from the input column(s) to the output column(s).

**Comment by cwharris** [comment]
@kkraus14 I don't understand how the output bitmask would necessarily be identical to the input bitmask. `apply_rows` can do operations against the inputs, and therefore the output bitmask is a function of the input bitmasks. `None + 1 = None`?, `1 + None = None`? Which bitmask would be use in this case, or should the output be `NaN`? We need to declare expected output before we can decide on an implementation.

**Comment by kkraus14** [comment]
Sorry, should have read more closely, didn't realize this was for dataframes with multiple columns as opposed to just a single column. That is absolutely trickier because we don't know which columns have ops ran against them or if they're doing something crazier with conditionally using one column or another. For the time being I guess we could just do a bitwise logical or of all of the input columns masks and set that for all of the output columns, but that doesn't sound ideal.

**Comment by cwharris** [comment]
One possible solution is to enforce an "any rows with a null in any column will result in nulls being written to all output columns in that row " rule. That would be the simplest solution, but not 100% correct.

**Comment by cwharris** [comment]
@kkraus14 I think that's the simplest solution. I'd rather filter outputs we aren't 100% sure are correct. To know 100%, we would need to refactor the input func before sending though Numba. Let's enforce an "any row with a null in any column will result in null in all output columns" rule, and make sure the documentation is clear on that behavior.

**Comment by kkraus14** [comment]
+1

**Comment by hmgaudecker** [comment]
Would it be possible to have a switch and let the user function in apply_rows optionally deal with nan/missings? If I have a column that I do not necessarily care about that has missings, I would be very surprised by this behavior and a workaround would seem tough. I might be missing something, though. Plus, if there was a switch, the documentation would have a higher chance of being read as part of the interface...

**Comment by cwharris** [comment]
@hmgaudecker The problem is that your function won't get `null`s /`None`s, it will get `NaN`'s, at best, and only if the input is a floating point value. Therefore your output is also not `null`/`None`, but could be `NaN`. So the problem is not that we couldn't figure out which outputs were null, it's that your function won't know which inputs are null.

**Comment by hmgaudecker** [comment]
Sorry if I am missing something - I cannot fully concentrate right now. Looking at the example of Aaron above, I would imagine two possibilities:

1. What you describe, i.e., the user function only sees the three automatically filtered rows.
2. Pass all four rows to the user and let him/her deal with missings in input columns (IIUC, skip the bitmask entirely)

**Comment by hmgaudecker** [comment]
Put differently, some of the values in the input columns might be genuine nan's and not missings; pandas (unfortunately) happens to interpret them to be the same thing. Working with survey data, I would often like to have finer control.

**Comment by kkraus14** [comment]
@hmgaudecker That's exactly what we're trying to solve here. You can have both `NaN`s and `null`s and they're treated differently. `NaN` logic here should work as expected, the problem is handling `null` bits because numba doesn't have a concept of them and it's very non-trivial to inject it into the UDF.

**Comment by hmgaudecker** [comment]
Ah, I think I see. Ignoring the bitmask might mean that I would be using potential rubbish without me being able to tell. 

In that sense, pandas would not have a real concept of missings in that it does not treat nan and missing differently,? That is where I was getting things wrong. One would have to be careful doing conversion from pandas then, right?

**Comment by kkraus14** [comment]
@hmgaudecker Correct, by default we convert `NaN` values to null, but we also expose a parameter `nan_as_null` that allows you to control the behavior.

From my perspective, it's safer to mark potentially valid data as null vs leaving garbage data as non-null.

**Comment by hmgaudecker** [comment]
Sounds great, sorry for not being aware of the entire picture!

**Comment by kkraus14** [comment]
Thank you for your feedback as a user!
