### ISSUE TITLE
Support methods on dataframes

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#257]
Many methods like `__add__` and `.sum()` seem to exist for Series objects, but not DataFrames.  As an example, the following test might be nice.

```python
@pytest.mark.parametrize('func', [
    lambda df: df.sum(),
    lambda df: df.max(),
    lambda df: df.count(),
    lambda df: df.std(ddof=1),
])
def test_dataframe_reductions(func):
    pdf = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6]})
    gdf = cudf.from_pandas(pdf)
    assert_eq(func(pdf), func(gdf))
```

**Comment by AK-ayush** [comment]
I have opened a PR #621 for this issue. I have implemented the `__add__` for dataframe. 
I need your suggestion for `DataFrame.sum()` method since I was looking at the pandas's  [`DataFrame.sum()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sum.html#pandas-dataframe-sum) and I am not able to find any correct example.

**Comment by thomcom** [comment]
Unfortunately we need to have `nvstrings` support to implement this properly @mrocklin. In particular, right now we don't support strings in indexes. Pandas returns a `Series` object with the index set to the column names of the DF, which of course will usually be strings.
