### ISSUE TITLE
[FEA] Replace dask-cudf merge/join/set_index implementations with upstream

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2598]
Now that some changes have been merged into Dask.dataframe, we should be able to remove some of the shuffle-based methods in the dask-cudf library and rely on the implementations upstream.  This is in service of https://github.com/rapidsai/cudf/issues/2272 .  

To be clear, these implementations aren't fully on the device yet, but anecdotally they do seem to be faster than the current implementation, and are likely less buggy (they're under heavy use by the Pandas community).  Plus, once we do have some of the GPU primitives that we need, this step to transition things over will already be done.

I anticipate that we'll run into a couple of small issues along the way, but hopefully nothing as complex as we had to deal with when generalizing the shuffle code.

**Comment by rjzamora** [comment]
After [dask#5205](https://github.com/dask/dask/pull/5205), Dask's `set_index` works with cudf dataframes when `shuffle="tasks"`, but not for `shuffle="disk"` (the default).  The disk-backed version constructs a graph using groupby (e.g. `d = {i: g.get_group(i) for i in g.groups}`), and cudf does not supprot `groups` and/or `get_group`.

In order to allow dask_cudf to completely fall back on dask here, we need to do one of two things:
1. Change the disk-based dask code, or
2. Add `groups` and `get_group` to cudf

In the meantime, leaving a simple `set_index` wrapper in dask-cudf (using `shuffle="tasks"`) also works, but (1) or (2) is probably a better long-term solution.

@kkraus14 - In [#1720](https://github.com/rapidsai/cudf/issues/1720), you seemed hesitant to add the groupby functionality needed for (2).  Do you believe (2) is a "no go"?

**Comment by mrocklin** [comment]
I think that we should just omit the use of the "disk" based shuffle technique for now and hard-code the "tasks" technique.

**Comment by kkraus14** [comment]
Resolved in 0.11.
