### ISSUE TITLE
[QST] Is reading `bytes` natively as compared to reading from `disk` expected to be slower ?

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2665]
Is reading `bytes` natively as compared to reading from `disk` expected to be slower ?

In `cudf` , i have seen that when i read from disk as compared to a byte-stream the performance is approx. 1.7x worse 

I would expect behavior to be better (as it takes away reading from disk) or similar (with file cached in memory) .  
 
### In `cudf` the behavior is below:

```python
import cudf
import io
import pandas as pd
data_dir = '/datasets/nyc_taxi/2015/'
fname = data_dir + 'yellow_tripdata_2015-01.csv'
```

#### reading from disk
```python
%time df = cudf.read_csv(fname)
CPU times: user 2.58 s, sys: 1.67 s, total: 4.24 s
Wall time: 4.4 s
```

#### reading from bytes
```python
with open(fname, 'rb') as f:
    df_bytes = f.read()
    
%timeidf = cudf.read_csv(io.BytesIO(df_bytes))
CPU times: user 3.6 s, sys: 3.56 s, total: 7.16 s
Wall time: 7.28 s
```

#### reading from disk
```python
%timeit df = pandas.read_csv(fname)

CPU times: user 32.3 s, sys: 6.87 s, total: 39.2 s
Wall time: 26.5 s
```
#### reading from bytes

```python
with open(fname, 'rb') as f:
    df_bytes = f.read()

%time df = pd.read_csv(io.BytesIO(df_bytes))

CPU times: user 34.8 s, sys: 6.23 s, total: 41 s
Wall time: 28.1 s
```

#### file to download

The file can be downloaded from: 
 
https://console.cloud.google.com/storage/browser/_details/anaconda-public-data/nyc-taxi/csv/2015/yellow_tripdata_2015-01.csv

### Note, file is also preset at:
```
/datasets/nyc_taxi/2015/
/rapidspub/nyc_taxi/2015
```

Edit: Removed incorrect `pandas`, `io.BytesIO` call.

**Comment by ayushdg** [comment]
The discussion in #2421 might be of interest

**Comment by j-ieong** [comment]
> In cudf , i have seen that when i read from disk as compared to a byte-stream the performance is approx. 1.7x worse

Do you mean reading from `disk` (passing in filename) is faster than reading from `BytesIO`?
Your cudf example shows 4.4s for `cudf.read_csv(fname)` vs. 7.28s for `cudf.read_csv(BytesIO)`...

Also:
> **reading from bytes**
> ```python
> with open(fname, 'rb') as f:
>    df_bytes = f.read()
>
> %timeit df = pandas.read_csv(fname)
> CPU times: user 33.2 s, sys: 6.41 s, total: 39.6 s
> Wall time: 27.1 s
> ```
For the PANDAS example, should that line be `pandas.read_csv(io.BytesIO(df_bytes))`?

For cudf, we expect direct passing in of filename to be faster than if the user read the whole file into a bytes buffer that is then passed into cudf.

In the former, `libcudf` directly maps the file into memory, then only the relevant parts of the data are read.

In the latter, the CSV reader currently has an extra copy from the Python bytes to libcudf buffer input in Cython. Parquet and ORC don't have the issue since it directly accesses the bytes buffer. We haven't gotten around to making the change to CSV yet...

**Comment by VibhuJawa** [comment]
> > In cudf , i have seen that when i read from disk as compared to a byte-stream the performance is approx. 1.7x worse
> 
> Do you mean reading from `disk` (passing in filename) is faster than reading from `BytesIO`?

Yup. 

> For the PANDAS example, should that line be `pandas.read_csv(io.BytesIO(df_bytes))`?

Corrected that, i incorrectly pasted it. My bad. 
 
> For cudf, we expect direct passing in of filename to be faster than if the user read the whole file into a bytes buffer that is then passed into cudf.
> 
> In the former, `libcudf` directly maps the file into memory, then only the relevant parts of the data are read.
> 
> In the latter, the CSV reader currently has an extra copy from the Python bytes to libcudf buffer input in Cython. Parquet and ORC don't have the issue since it directly accesses the bytes buffer. We haven't gotten around to making the change to CSV yet...

Gotcha, that makes sense. Thanks for clarifying.
