### ISSUE TITLE
[BUG] Astype on String and CategoricalColumns coerces all values to be 0

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2707]
I'd expect these to result in either a ValueError or TypeError, rather than silently create a column of zeros (dtype depends on the astype call). This is what happens in pandas

```python
import cudf
​
s = cudf.Series(['aaaa','bbb','cc'])
s.astype('int')
0    0
1    0
2    0
dtype: int64
```

```python
import cudf
​
s = cudf.Series(['aaaa','bbb','cc']).astype('category')
print(s.cat.codes)
s.astype('int')
0    0
1    1
2    2
dtype: int32
0    0
1    0
2    0
dtype: int64
```

**Comment by ayushdg** [comment]
The underlying cause seems to be the behavior of custrings.
```
import nvstrings as nvs
a = nvs.to_device(['a','aaa','b'])
a.stoi()
[0, 0, 0]
```

**Comment by beckernick** [comment]
Thanks @ayushdg . I think the ideal behavior here (from a python perspective at least) is to raise a ValueError or TypeError

**Comment by ayushdg** [comment]
I agree. Checking for all 0's in the list probably isn't a good idea, since ['0','0'] also works. Based on an issue I had seen in custrings https://github.com/rapidsai/custrings/issues/405#issuecomment-524288113 it seems like the stoi/stol methods were also designed in a similar way.

One possible solution that comes to mind is if these methods returned a null value instead of `0` we could do checks at the python level checking `if null count(result) > null count(input) throw some error`.

**Comment by kkraus14** [comment]
In chat with @davidwendt we should explore using `isnumeric` before the typecast call to catch any errors.

**Comment by galipremsagar** [comment]
This is yet to be fixed as python/cython changes are needed to plumb into libcudf changes, hence reopening. I'll take care of those changes.
