### ISSUE TITLE
[FEA] TIFF reader

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2727]
This isn't so much a cudf issue as a cuio issue, but it would be great to have a TIFF reader.  TIFF is a common image format that is commonly used both in satellite imagery and scientific imaging fields.  It has a well-defined (if somewhat poorly scoped) spec and should, I hope, be straightforward to implement.  

I would expect the result of this to be something like a CuPy array, or at least something that satisfies the `__cuda_array_interface__` protocol.  It seems a little odd to include this issue in the cudf repository, but I know that this is where the cuio folks listen, so it seems like the best place at the moment.

@mjsamoht @jakirkham

**Comment by mjsamoht** [comment]
cc @j-ieong @OlivierNV

**Comment by OlivierNV** [comment]
It would be good to get some specific details, maybe an existing similar API along with sample files, since TIFF can apparently include 5 different types of compression (including LZW and JPEG)

**Comment by mrocklin** [comment]
@jakirkham when you have a moment can you point @OlivierNV to current Python APIs that you think Python users interested in biological image data enjoy and would be good to model?  Is this `skimage.io.imread`?

Also, do you have any pointers to publicly accessible files somewhere?  Maybe FlyEM?

**Comment by mrocklin** [comment]
@djhoese if I could ask a favor from you, can you point the folks here to pleasant Python APIs for reading in GeoTIFF data?  Also, do you have some samples of real-world satellite imagery?

**Comment by djhoese** [comment]
The go to lately in the python community (at least the ones I'm a part of) is `rasterio` (https://rasterio.readthedocs.io/en/stable/) which uses the GDAL C library underneath. It is what xarray uses for geotiff reading through its [`open_rasterio`](http://xarray.pydata.org/en/stable/generated/xarray.open_rasterio.html) interface too. Rasterio is also what we use in Satpy to both read geotiff files and write geotiff files (with dask).

That said, I should point out that there are two parts to every geotiff file: the image data and the geolocation information. The image data is stored just like a traditional TIFF image and can be read by PIL. The image data has your semi-usual variations (L, LA, RGB, RGBA, or L + color table). So if you were only worried about getting the image data in to the GPU then PIL would work. Geolocation information is a longer discussion.

CC @snowman2 who usually helps me with rasterio and pyproj stuff. Let me see if I can throw a basic geotiff together.

**Comment by djhoese** [comment]
Here is GOES-16 ABI Channel 7 data of Hurricane Florence:

http://bin.ssec.wisc.edu/pub/davidh/C07_20180911_150221.tif

I usually investigate geotiffs from the command line by installing GDAL and running `gdalinfo <tif>`.

**Comment by pmessmer** [comment]
Is the plan to implement a tiff reader from scratch or incorporate a GPU/cuIO path into libTIFF? The latter might be a bit more work, but will result in GPU advantage to all apps built on top of it..

**Comment by jakirkham** [comment]
> @jakirkham when you have a moment can you point @OlivierNV to current Python APIs that you think Python users interested in biological image data enjoy and would be good to model? Is this `skimage.io.imread`?

The canonical thing to use here would be @cgohlke's `tifffile`. I think users would like something similar to `skimage.io.imread` (which also uses `tifffile` if I'm not mistaken), but there can be tricks depending on their data needs. For instance they may want to delay reading the data into memory, they may want to read one page at a time, or they may want to memory-map large files.

> Also, do you have any pointers to publicly accessible files somewhere? Maybe FlyEM?

I'd start with @rxist525's [TIFF files]( https://drive.google.com/drive/folders/13mpIfqspKTIINkfoWbFsVtFF8D7jbTqJ ).

**Comment by mrocklin** [comment]
@OlivierNV , is this the kind of feedback you're looking for?  This is a good set of people of whom to ask questions I think.

**Comment by OlivierNV** [comment]
Yup, this is good, I need to time to digest all this. As far as the API, I think the best match would be something that is already tied to cuda acceleration in some way, I don't think there is much point in having the gpu read something to end up returning it in sysmem (not clear yet if the tiff-reading part would be much faster than on cpu, in which case the benefit would mainly be convenience)
It would be good to also get an idea of what's the expectations/benefits over existing methods.

**Comment by mrocklin** [comment]
My guess is that a Python user would be happy to receive something like a `cupy.ndarray` or `numba.DeviceArray` as an output.

**Comment by OlivierNV** [comment]
Out of the two files mentioned by @djhoese and @jakirkham ,  it seems the first one is 500x500 using "Adobe Deflate" compression with 8-line strips (single image), and the other is 768x1024 using no compression but many images. Assuming Tiff + Adobe deflate stores the compressed size such that each strip can be decompressed independently, it would be doable to get a speedup on GPU, also assuming that we'd have many such images or much larger resolution (to give you an idea, in order to get 100% utilization of a T4 (40 SMs), we need about 320 compressed zip/deflate streams ~ GV100 has 100 SMs, so 800+ streams, ie: 800 images or a single 6400-pixels-high image).
The main concern I have is what would be the benefit over just using the existing libtiff+libgeotiff and following an image load with a cudaMemcpyHtoD, or cupy.from_sysmem_array() equivalent ?

**Comment by djhoese** [comment]
Since you mentioned image size I wanted to mention that the image I gave was the smallest one I could make quickly. On the larger side of satellite images that Satpy generates (from NetCDF files) we have 21696x21696 images which we could save as striped images (like the one I sent you) or tiled (like a [COG](https://www.cogeo.org/)). Satpy also lets you change the compression to anything that GDAL/rasterio supports.

**Comment by mrocklin** [comment]
cc @henrypinkard , who also deals with large TIFF images in biology

**Comment by djhoese** [comment]
Here is an example of the size I was talking about (~1.2GB, compressed, striped): [GOES-16 ABI True Color at 500m resolution](https://bin.ssec.wisc.edu/pub/davidh/GOES-16_ABI_RadF_true_color_20190422_170022_GOES-East.tif)

This is what I had lying around. If it was tiled it would be smaller in size from the improved compression.

**Comment by OlivierNV** [comment]
> Here is an example of the size I was talking about (~1.2GB, compressed, striped, RGBA): [GOES-16 ABI True Color at 500m resolution]

This one is using LZW compression with single-line blocks (we currently don't have a gpu implementation, but should not be a problem ~ similar challenges as zip, probably better for perf)
Ideally, we'd want to hook up into libtiff to get pointers to the compressed data instead of decoded pixels ~ I haven't looked much into it, but it looks like libtiff is fairly low-level should we could re-use most blocks as is, and libgeotiff could also be used as is just linking with a modified version of libtiff.

**Comment by henrypinkard** [comment]
I have many 4GB Tiff files that are part of bigger datasets up to a 1TB  in size that I use for storing microscopy data in ~500x500 pixel chunks. I use a custom python class that returns memory mapped numpy arrays for reading them. I am happy to share one of these files if it would be helpful

**Comment by datametrician** [comment]
I'm not sure this is the right repo for this request. I believe https://github.com/NVIDIA/DALI would be better since they maintain the kernels for image IO.

**Comment by kkraus14** [comment]
Closing as out of scope.
