### ISSUE TITLE
[FEA] Add support for cuDF DataFrame.dropna(inplace=True)

### ISSUE THREAD

**Issue by hokiegeek2** [rapidsai/cudf#2797]
I recommend adding the ability to replace rows containing null values within an existing cuDF DataFrame to avoid copies in analogy to Pandas DataFrame.dropna(inplace=True)

**Comment by shwina** [comment]
I don't believe this would be possible to do in a copy-free manner. We could add support for `inplace=True` but it will still perform a copy under the hood (Pandas creates a copy).

**Comment by hokiegeek2** [comment]
@shwina gotcha, okay, did not know that pandas creates a copy

**Comment by thomcom** [comment]
Recommend that we close this issue as such.

**Comment by thomcom** [comment]
Reopening because after some consideration there's still the question of DataFrame mutability in respect to `inplace=True`. Some users want to mutate their existing DataFrame:

```
pdf.dropna(inplace=True)
```

instead of creating a new one
```
pdf = pdf.dropna(inplace=True)
```

while I strongly prefer the second usage, many developers might prefer the first. We could support it...
