### ISSUE TITLE
Does Dask Distributed or dask_cudf supports Apache Arrow Flight batch stream for IO?

### ISSUE THREAD

**Issue by vnkesarwani** [rapidsai/cudf#2880]
**What is your question?**
I am sharing my data in arrow format through arrow flight as stream; and need to consume it from dask_cudf in GPU.

What i tried 
 - read arrow batch stream as a table.
 - Create cudf
 - pass it to dask_cudf.
 
This works for small data, but reading full stream as a single arrow table into cudf may cause out of memory error.

Is there any better way out of the box in dask distributed or in dask_cudf to read/write to Arrow Flight Buffer?

**Comment by kkraus14** [comment]
@vnkesarwani is there a reason you couldn't read the Arrow batch stream directly on a worker so that you don't have to do the local --> distributed data movement? I.E. using delayed function(s) to read the Arrow flight source on the workers and create the arrow tables and pass to cudf in an embarassingly parallel manner? Once you have the cudf DataFrames created on the workers it's a simple `dask_cudf.from_delayed(...)` call (zero-op) to create a dask dataframe from them.

**Comment by vnkesarwani** [comment]
Thanks @kkraus14. 

I am able to run in distributed mode.
