### ISSUE TITLE
cudf flatten API [QST]

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/cudf#2958]
**What is your question?**
Does CUDF  support an api to flat the dataframe like pd.values.flatten() ? Thanks you.
```python
In [40]: df_matchColor1                                       
Out[40]: 
      color  key_index
0   #ffffd9          0
1   #7fcdbb          1
2   #41b6c4          2
3   #1d91c0          3
4   #ffffd9          4
5   #7fcdbb          5
6   #41b6c4          6
7   #1d91c0          7
8   #ffffd9          8
9   #7fcdbb          9
10  #41b6c4         10
11  #1d91c0         11

In [53]: df_matchColor1.to_pandas().values.flatten()                                 
Out[53]: 
array(['#ffffd9', 0, '#7fcdbb', 1, '#41b6c4', 2, '#1d91c0', 3, '#ffffd9',
       4, '#7fcdbb', 5, '#41b6c4', 6, '#1d91c0', 7, '#ffffd9', 8,
       '#7fcdbb', 9, '#41b6c4', 10, '#1d91c0', 11], dtype=object)
```

**Comment by kkraus14** [comment]
@MikeChenfu in your use case you're utilizing Pandas/Numpy's ability to fall back to using Python objects to created a mixed dtype array. This is extremely detrimental to performance and won't be supported in cuDF for mixed dtypes.

Otherwise, you should be able to use the same code as `df.values.flatten()` that will go from cuDF --> cuPy --> flattened cuPy array.

**Comment by MikeChenfu** [comment]
Thanks @kkraus14. It works right now. Thanks for your kind help.:)

**Comment by Mirror-HHf** [comment]
Hello, I saw that you were learning NSGA2 algorithm before, could you give me a contact information opportunity to communicate with you?

**Comment by randerzander** [comment]
I believe @MikeChenfu solved his problem another way
