### ISSUE TITLE
[FEA] Support regex lookarounds

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3100]
## Description
As a user, I would like to be able to include positive and negative lookaheads / lookbehinds in my regular expressions.

## Example Behavior
As an example of a negative lookahead, see: https://regex101.com/r/0275Hq/1

Given
```
qate
quit
qatar
```
The regex pattern `q(?!u)` should match the q in `qate` and in  `qatar`, but not in `quit`. In words, "Find the q, but only if it's not followed by a u."

For a nice description of lookarounds, see: https://www.regular-expressions.info/lookaround.html

**Comment by GregoryKimball** [comment]
I'm closing this as "wontfix" because [lookarounds are not compatible](https://swtch.com/~rsc/regexp/) with the current NFA regex engine. We would need a new engine to support lookarounds. If there is more demand for lookarounds, we recommend dispatching to a CPU regex engine - something that will become much faster in next gen hardware such as the [Grace Hopper Superchip](https://www.nvidia.com/en-us/data-center/grace-cpu/).
