### ISSUE TITLE
gdf_hash() ignores NULL values, hashes the junk stored for invalid elements

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#314]
- [X] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The [code](https://github.com/rapidsai/cudf/blob/master/libgdf/src/hashing.cu) for the `gdf_hash()` operator ignores the `valid` pseudo-columns of the input columns, i.e. ignores whether or not the records have any elements which are NULL. It hashes whatever is stored in the `data` pseudo-columns.

Proposed solution options:
1. The gdf_hash() operator will only take non-nullable columns (or 0-null-count columns)
2. When the input is a nullable column, The gdf_hash() operator will produce a nullable column, which has 1 whenever at least one element of the record is NULL, and 0 otherwise - and only be required to compute hashes of non-null records.

There are more complicated approaches which I haven't mentioned, but did come up in an initial discussion between me and @felipearamburu .

**Comment by kkraus14** [comment]
I'd be in favor of 2. cc @jrhemstad since I believe he implemented this function.

Currently we check if there's nulls at the Python side and throw an exception accordingly if there is nulls.

**Comment by jrhemstad** [comment]
This is just one of many features that don't yet support the `valid` bitmasks.

I think a third and more efficient option would be just to compute the hash-value of all elements in the column (even the NULL ones). Then copy the `valid` mask from the input column to the output column.  Yes, you'll be producing garbage hash values, but it doesn't matter because you'll be setting them to NULL.

This would save you from having to do the `gdf_is_valid` check for every single element in the input column.

**Comment by eyalroz** [comment]
@jrhemstad : Your suggestion is actually a special case of my (2.) - I'm just saying libgdf will not make _guarantees_ about the contents of the `data` pseudo-column for null elements. 

Having said that - you can only copy the `valid` pseudo-column if you have a single input column to hash. If you pass two or more, you have to perform an elementwise logical AND of the vaildity indicators.

Also, for mostly-NULL inputs (i.e. most warps will mostly work on all-NULL records)  it will probably be  less efficient to compute the hashes for NULL elements.

**Comment by jrhemstad** [comment]
@eyalroz 
>Having said that - you can only copy the valid pseudo-column if you have a single input column to hash. If you pass two or more, you have to perform an elementwise logical AND of the vaildity indicators.

Indeed, this is already being done. See here: https://github.com/rapidsai/cudf/blob/master/libgdf/src/gdf_table.cuh#L315 

You can copy the `d_row_valid` from the `gdf_table` to the output column from `gdf_hash`. 

>Also, for mostly-NULL inputs (i.e. most warps will mostly work on all-NULL records) it will probably be less efficient to compute the hashes for NULL elements.

Perhaps, but that sounds like an uncommon case. I suppose you could special case it by comparing the `null_count` to the `size` of the column. But that seems like more trouble than it's worth.

**Comment by eyalroz** [comment]
> that sounds like an uncommon case.

It depends. For example, consider the US Bureau of Transport Statistics flight [on-time data](http://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236&DB_Short_Name=On-Time). Many columns have information regarding flight diversions (since it's a single, de-normalized table) - and those columns are mostly NULL.

**Comment by jrhemstad** [comment]
Recently updated the `hash_row` functionality to check for null values. See: https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/table/device_table.cuh#L268

Furthermore, the new `row_bitmask` function I added can be used for computing the output bitmask required for `gdf_hash` (i.e., it ANDs a set of input column's bitmasks together). 

All that is required to close this issue out is to update `gdf_hash` to use `row_bitmask` to compute the output column's bitmask.

Some modification will be necessary since `row_bitmask` returns a `rmm::device_vector`, which will free the underlying memory when it goes out of scope. I don't believe `device_vector` has any kind of `release` mechanism. Therefore, some refactoring is necessary to heap allocate the result bitmask.

**Comment by harrism** [comment]
@jrhemstad @trevorsm7 is this fixed?

**Comment by trevorsm7** [comment]
The new implementation uses a default hash value for null elements rather than hashing junk. This is different from the proposed solutions in the original post, but I believe this fixes the issue.

**Comment by harrism** [comment]
Sounds good, closing.
