### ISSUE TITLE
[FEA] cross joins

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#3194]
**Is your feature request related to a problem? Please describe.**
While translating SQL operations to libcudf calls, occasionally a full cross-join operation is encountered.  It would be great if libcudf could accelerate these types of joins as it has for left and inner joins.

**Describe the solution you'd like**
A new cross join API that would be similarly typed as the existing left and inner join APIs but returns the result of a full cross join.

Due to the explosive nature of cross joins, I realize this is a very significant ask.  However I'd like to start the conversation to see if there are ideas in the community on how this could be implemented.  There are some cases where the cross joins might be small enough to fit.  Or maybe it makes sense to add predicate pushdown support directly into the call so the join could avoid materializing results when a filter condition is present.

**Comment by jtommaney** [comment]
In my experience cross-join has very limited practical value because of the cardinality issues.  Many times it is included by accident and in some cases resolved with some distinct operations at the outer layer as a hack.  
However variations will come up.  TPCH5 includes "and c_nationkey = s_nationkey" which is O(n/25*n/25)... this may be optimized out and dealt with as a post-join filter depending on Calcite.    
In addition, someone could write "select count(*) from a, b where sign(a.key) = sign(b.key) ;"  functionally equivalent to a cross join syntax.   

So, handling of cross-join out-of-resource conditions will likely come up.  Support for explicit syntax is a separate decision.

**Comment by williamBlazing** [comment]
We are also finding a need for support for CROSS JOINS. Even if it does not gracefully handle out of resource conditions, it could be left up to the user to handle with care

**Comment by jrhemstad** [comment]
@bdice will be working on this in 0.15. This can be implemented in terms of the existing functions `repeat` and `tile`.

API should be something like:
```
pair< unique_ptr<table>, unique_ptr<table> > cross_join(table_view const& lhs, table_view const& rhs, rmm::mr::device_memory_resource* mr);
```

Implementation can be done by using `repeat(lhs, rhs.num_rows())` and `tile(rhs, lhs.num_rows())`.

**Comment by brandon-b-miller** [comment]
Driving by to say I liked the way this was handled in spark back when I was using it (~2.2-2.3). At least back then, cross joins were disabled by default and if you tried to do one it would actually fail:

```
org.apache.spark.sql.AnalysisException: Detected cartesian product for INNER join between logical plans
```

There was a config option you could enable when spinning up the job that disabled this check and allowed the join to proceed, so you really had to consciously 'mean it' for it to work. A lot of the time people ran into this it was because they weren't specifying what they wanted correctly.

**Comment by harrism** [comment]
@brandon-b-miller I suspect that cuDF Python, Spark RAPIDS plugin, etc. is the right level for that check.
