### ISSUE TITLE
[FEA] Make dask_cudf support SQL style "null" values in groupby key columns

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3302]
Related to #2627 

Pandas and Dask don't yet support the `dropna` keyword, and thus `dask_cudf` doesn't either.

**Comment by mrocklin** [comment]
I've raised this upstream here: https://github.com/dask/dask/issues/5565

**Comment by rjzamora** [comment]
@randerzander - Just a clarification question... Plumming the `dropna=` argument trhough dask's groupby implementation isn't a problem (I already implemented something rough that seems to work for a simple test).  This will result in null values being labeled by a `-1` index for numerical columns (matching cudf behavior) --  Is this the desired behavior?

Ex:

**Original DataFrame** (`df`):
```
       a  b
0     1  4
1     2  5
3     3  6
5     4  3
6  null  2
8  null  1
9     7  0
9     8  0
9     9  0
```

**dask_cudf Groupby** (`ddf.groupby("a", dropna=False).b.sum().compute().sort_index()`):
```
a
-1    4
 2    5
 3    6
 4    3
 7    0
 8    0
 9    0
-1    3
Name: b, dtype: int64
```

**cudf Groupby** (`df.groupby("a", dropna=False).b.sum()`):
```
a
-1    4
 2    5
 3    6
 4    3
 7    0
 8    0
 9    0
-1    3
Name: b, dtype: int64
```

Note that the existing `"-1"` value in `df` does not result in an "incorrect" output for the "null" values, but the null values do use the same `"-1"` label (not `None`, or `null`).

**Comment by rjzamora** [comment]
@randerzander [dask#5579](https://github.com/dask/dask/pull/5579) was merged. This should address this issue for numerical index columns.  We will need to remove cudf assertions [like this one](https://github.com/rapidsai/cudf/blob/70084f482fb9fcdec575fb1acca2adaf0af0c434/python/cudf/cudf/core/index.py#L950) in order to get [an exhaustive test like this one](https://github.com/dask/dask/blob/4a42071f50d12f30e15afe1348a147cb45ebaa69/dask/dataframe/tests/test_groupby.py#L2216) to pass for string/categorical index columns.

I can submit a small PR today to remove these assertions and add a similar test.
