### ISSUE TITLE
[QST]why apply_rows works so different compare to the apply in pandas dataframe

### ISSUE THREAD

**Issue by naturesphere** [rapidsai/cudf#3315]
The way to call apply_rows method is so bad! why not make is the same as pandas dataframe apply?
for example:
>>> in1 = df['in1']
>>> in2 = df['in2']
>>> in3 = df['in3']
>>> def kernel(in1, in2, in3, out1, out2, kwarg1, kwarg2):
...     for i, (x, y, z) in enumerate(zip(in1, in2, in3)):
...         out1[i] = kwarg2 * x - kwarg1 * y
...         out2[i] = y - kwarg1 * z

Call ``.apply_rows`` with the name of the input columns, the name and
dtype of the output columns, and, optionally, a dict of extra
arguments.

>>> df.apply_rows(kernel,
...               incols=['in1', 'in2', 'in3'],
...               outcols=dict(out1=np.float64, out2=np.float64),
...               kwargs=dict(kwarg1=3, kwarg2=4))

The for loop in kernel function looks so redundancy and feels uncomfortable！

It's looks like we should use kernel function like this: kernel(df.in1, df.in2, df.in3, df.out1, df.out2, kwarg1, kwarg2) but not the appy_rows!

why do not make it the same as pandas dataframe apply!

**Comment by kkraus14** [comment]
@naturesphere we are due for a large refactor of UDFs and apply functions. That being said, because we execute vectorized on the GPU via the Numba library as opposed to via Python iteration, we can only support what Numba can compile. This unfortunately limits what functionality we can support in UDFs but makes our UDFs orders of magnitude faster than Pandas.
