### ISSUE TITLE
[BUG] Inconsistent output order for dask-cudf groupby

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#3319]
**Describe the bug**
Cudf groupby sorts the groupby output by default. (Longer discussion here: #2717 ).

Based on how the groupby API is used, I can reproduce cases where the index is sorted vs where it isn't

**Steps/Code to reproduce bug**
```
n = 100
df = cudf.DataFrame({'a':[0,1,0,1]*n,'b':[0,0,2,1]*n,'c':[0,0,0,0]*n})
df = dask_cudf.from_cudf(df,npartitions=2)
```

_V1_
```
group_counts = df.groupby(['a','b']).count()
group_counts.compute()

       c
a b     
1 1  100
0 0  100
1 0  100
0 2  100
```
Output (index) not sorted

_V2_
```
group_counts = df.groupby(['a','b']).c.count()
group_counts.compute()

a  b
1  1    100
0  0    100
1  0    100
0  2    100
```
Output (index) not sorted

_V3_
```
group_counts = df.groupby(['a','b']).agg({'c':'count})
group_counts.compute()

       c
a b     
0 0  100
  2  100
1 0  100
  1  100
```
Sorted output!

**Expected behavior**
Identical behavior in all 3 cases.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
  - Nightly from 26th Oct

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
If the number of rows are lesser (if n=1 in the example above) then the behavior is the same for all three cases.

cc: @VibhuJawa who was using one version of the api while I was using another when we noticed a difference in output.

**Comment by kkraus14** [comment]
IIRC Dask doesn’t guarantee the order of partitions here, so within each partition the index is sorted, but when you call compute there’s no guarantee that the index is sorted as the partitions aren’t in the correct order.

@quasiben @rjzamora does that sound correct or do we have an issue here?

**Comment by rjzamora** [comment]
> IIRC Dask doesn’t guarantee the order of partitions here, so within each partition the index is sorted, but when you call compute there’s no guarantee that the index is sorted as the partitions aren’t in the correct order.

I could be confused, but the output should probably be sorted in this case.  After the groupby operation, the result is collapsed into a single partition, because the `split_out` argument is never used to set the number of output partitions to be >1.  The above experiment does seem to return sorted results for V1-3 using dask.dataframe with pandas.

**Comment by rjzamora** [comment]
I did a fair bit of exploration here.  As far as I can tell, the `cudf`-based output makes sense given what dask is trying to do...  

Dask uses an ACA (apply-concat-apply) procedure for groupby aggregations.  Since the example is effectively using `split_out=1`, dask (1) performs `count` on each partition (first apply step), (2) concats the results in into `split_out` partitions (concat step), and then (3) performs a `sum` aggregation on the concatenated results (second apply step).

For V1 & V2, the result is unsorted, because dask literally has [`sort=False` hard-coded within  `_groupby_aggregate`](https://github.com/dask/dask/blob/2ee98716b96ff7f66ea1dcfd7a43f374cc92ed94/dask/dataframe/groupby.py#L279) for the final apply step.  For both pandas and cudf, the first apply step (before the concat) **does** results in a sorted dataframe, but the order is lost at the end.  I set a breakpoint within `_groupby_aggregate` and discovered that, for whatever reason, the `sort=` argument does **not** affect the output for pandas (the result is sorted either way).  My guess is that pandas is not sorting the keys, but that it is merely preserving the initial (sorted) order.  Since the cudf algorithm is hash based (is this correct?), the initial order is **not** preserved.

The reason V3 **does** produce a sorted result for both cudf and pandas that the ACA algorithm uses a different function (`_agg_finalize` rather than `_groupby_aggregate`) for the final apply step when the aggregation is executed using the dictionary-based definition.

**Comment by rjzamora** [comment]
Given my comments above, the best solution here may be to expose the `sort=` argument for groupby operations in dask (i.e. pick up on [dask#5450](https://github.com/dask/dask/pull/5450))

**Comment by rjzamora** [comment]
@ayushdg -  This *may* have been addressed by [dask#5801](https://github.com/dask/dask/pull/5801) (which is now merged).  When calling `df.groupby(...)`, you can now pass the argument `sort=True` (E.g. `df.groupby(['a','b'], sort=True)`).  The `sort=True` argument will then be passed along to any subsequent aggregation operations (so that the output of all your examples, above, will have consistent index ordering).

One caveat is that the sorting will only take place during the final aggregation/apply phase of Dask's  "apply-concat-apply" algorithm.  This means that the sorting will only occur within each `split_out` partition (if `split_out>1`).  For this reason, dask will raise an error if you set `split_out>1` for an aggregation after passing `sort=True` to `groupby`.  In the future, we can probably handle sorting accross multiple partitions, but the feature is not in place just  yet.

**Comment by rjzamora** [comment]
cc @beckernick - Let me know if support for `sort=True` with `split_out>1` is a high-priority item.

**Comment by wence-** [comment]
All three examples now produce identical results (an unsorted index). Good to close?

**Comment by vyasr** [comment]
I confirm what Lawrence noticed above:
```
In [14]: group_counts = df.groupby(['a','b']).count()
    ...: group_counts.compute()
Out[14]: 
       c
a b     
0 2  100
1 1  100
0 0  100
1 0  100

In [15]: group_counts = df.groupby(['a','b']).c.count()
    ...: group_counts.compute()
Out[15]: 
a  b
0  2    100
1  1    100
0  0    100
1  0    100
Name: c, dtype: int64

In [17]: group_counts = df.groupby(['a','b']).agg({'c':'count'})
    ...: group_counts.compute()
Out[17]: 
       c
a b     
0 2  100
1 1  100
0 0  100
1 0  100
```
