### ISSUE TITLE
[BUG]dask-cudf sort implemention may be improved,because there is Superfluous sort_values call

### ISSUE THREAD

**Issue by chi2liu** [rapidsai/cudf#3436]
**Describe the bug**
In the dask-cudf, the implemention of sort method, there is a improvment.

```python
def _compare_frame(a, b, max_part_size, by):
    if a is not None and b is not None:
        joint = gd.concat([a, b])
        sorten = joint.sort_values(by=by)
        # Split the sorted frame using the *max_part_size*
        lhs, rhs = sorten[:max_part_size], sorten[max_part_size:]
        # Replace empty frame with None
        return lhs or None, rhs or None
    elif a is None and b is None:
        return None, None
    elif a is None:
        return b.sort_values(by=by), None # don't need to sort, just return b
    else:
        return a.sort_values(by=by), None # don't need to sort, just return a
```
like the comment，
when a is None，don't need to sort, just return b
when b is None，don't need to sort, just return a

because the a or b will be sorted when a is not None and b is not None

This will improve the performance when None is more.

**Comment by beckernick** [comment]
Thanks for filing this issue and highlight an opportunity for improvement!

In the time since this was filed, we've significantly reworked `sort_values` and upstreamed `rearrange_by_column` (a core component of the sort algorithm) to dask.dataframe.

I'm going to close this issue, but if you identify any additional areas for improvement please don't hesitate to re-open.
