### ISSUE TITLE
[FEA] signed 128-bit Integer Type

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#3558]
**Is your feature request related to a problem? Please describe.**
In order to implement #3556 (fixed-point decimal) we need to add a signed 128-bit integer type.

**Comment by jrhemstad** [comment]
To be clear, we need a _signed_ 128 bit integer. 

Some notes from my research:

- Sadly, unlike [`gcc`](https://gcc.gnu.org/onlinedocs/gcc-4.6.4/gcc/_005f_005fint128.html) , `nvcc` does not support a `__int128` extension type. 

- There is a preexisting 128bit _unsigned_ integer type built for device code [here](https://github.com/curtisseizert/CUDA-uint128), but that's of limited use as we need _signed_ integer support. Though it could be useful for a reference where the operations on signed/unsigned are similar.

- Implementing this type correctly and efficiently will require the use of inline PTX (see the CUDA-uint128 type and [here](https://stackoverflow.com/questions/35386298/cuda-signed-128-bit-multiplication-error)) 

- Abseil has a 128bit integer type that should be fairly straightforward to port to device code: https://abseil.io/docs/cpp/guides/numeric

- [Boost Multi Precision](http://cs.swan.ac.uk/~csoliver/ok-sat-library/internet_html/doc/doc/Boost/1_53_0/libs/multiprecision/doc/html/boost_multiprecision/tut/ints/cpp_int.html) also has a 128 bit int

- Ideally, a 128 bit integer is something that libcu++ should provide. It checks the boxes: vocabulary type, hard to implement (correctness and performance). 


Additional Concerns:
- Any algorithm that requires atomics on the elements of the column will not work with a 16B type since CUDA does not yet support 16B atomicCAS. Likewise, a lock-based algorithm to replace atomics won't work pre-Volta.
