### ISSUE TITLE
[DOC] libcudf++ presentation not public?

### ISSUE THREAD

**Issue by zingdle** [rapidsai/cudf#3625]
## Report incorrect documentation

**Location of incorrect documentation**

https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/docs/TRANSITIONGUIDE.md

**Describe the problems or issues found in the documentation**

[libcudf++ presentation](https://docs.google.com/presentation/d/1zKzAtc1AWFKfMhiUlV5yRZxSiPLwsObxMlWRWz_f5hA/edit?usp=sharing) mentioned is not public available. 

By the way, are there any other presentation / doc / material that I can get myself familiar with cudf?

**Comment by jrhemstad** [comment]
The [presentation](https://docs.google.com/presentation/d/1zKzAtc1AWFKfMhiUlV5yRZxSiPLwsObxMlWRWz_f5hA/edit?usp=sharing) is now publicly accessible. 

If you're interested in the C++ side of cuDF (libcudf), this [talk](https://on-demand-gtc.gputechconf.com/gtcnew/sessionview.php?sessionName=s91043-rapids+cuda+dataframe+internals+for+c%2b%2b+developers) may be of interest. Otherwise there is a multitude of similar recordings/talks on the Python side of the library. 

https://on-demand-gtc.gputechconf.com/gtcnew/sessionview.php?sessionName=s9793-cudf%3a+rapids+gpu-accelerated+data+frame+library

https://www.youtube.com/watch?v=lV7rtDW94do&t=171s

https://www.youtube.com/watch?v=kQ6UWd9t2Go
