### ISSUE TITLE
[BUG] `\` aren't replaced in string accessor or nvstring, even with escacpe character

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#3725]
**Describe the bug**
Neither string accessor nor nvstrings can replace a `\` character, even if escaped.  Also, there is a bug where the kernel will crash if you don't escape a special character 

**Steps/Code to reproduce bug**
nvStrings Minimal
```
import nvstrings
s = nvstrings.to_device(["h\llo","go\dbye"])
print(s.replace('\\', ''))
```
outputs: 
```
['h\\llo', 'go\\dbye']
```
**cuDF with string accessor**
```
import cudf

fn = 'test.csv'
lines = """a, b, c
test \\ phase* 1, 2, 3
test  \\phase 2, 4, 5
test\\phase* 3, 6, 7
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
df = cudf.read_csv(fn)
df.head()
```
output:

  | a | b | c
-- | -- | -- | --
0| test \ phase* 1 | 2 | 3
1| test \phase 2 | 4 | 5
2| test\phase* 3 | 6 | 7

And then replacement code:
```
df['a'] = df['a'].str.replace("\\","")
df['a'] = df['a'].str.replace("e","") # to show it works with alphanumerics
df['a'] = df['a'].str.replace("\*","") # to show it works with other escaped characters
df.head()
```
Outputs:

  | a | b | c
-- | -- | -- | --
0 |tst \ phas 1 | 2 | 3
1| tst \phas 2 | 4 | 5
2| tst\phas 3 | 6 | 7

**Expected behavior**
as with replace in strings, 
```
s = "h\llo"
print(s.replace('\\', ''))
```
Outputs:
```
hllo
```
i should get this output from `df['a'] = df['a'].str.replace("\\","")`:

  | a | b | c
-- | -- | -- | --
0 |tst  phas 1 | 2 | 3
1| tst phas 2 | 4 | 5
2| tstphas 3 | 6 | 7

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker using standard pull

**Additional context**
Was making a solution for https://stackoverflow.com/questions/59530094/python-coding-for-gpu/59651737#59651737 when i discovered the bug

Also, when testing, i wanted to see what would happen if i neglected the `\` and `df['a'] = df['a'].str.replace("*","")` ran for about 10-20 seconds until the kernal crashed.

**Comment by taureandyernv** [comment]
FYI, As per @beckernick 's suggestion, `df['a'] = df['a'].str.replace("\\","", regex=False)` works.  This is more on user expectation.

**Comment by davidwendt** [comment]
So this is actually working correctly. Technically, a single backslash \ is not allowed and is ignored. There must be a character after it. The \\ is interpreted by Python as a single \ and passed into the function and the regex compiler ignores this invalid instruction. Same thing happens with Pandas:

import pandas as pd
ps = pd.Series(["hello\\wor-ld","good-bye\\asd"])
print(ps.replace('\\',''))
0    hello\wor-ld
1    good-bye\asd
Also the builtin Python re class throws an error:

import re
re.sub('hello\\world','\\','')
Traceback (most recent call last):
 ....
re.error: bad escape (end of pattern) at position 0
Even passing builtin instructions requires two backslashes as in s.replace('\\s+','') this gets passed to the code as \s+. If you pass just \s+ it will not work.

So there are 2 options.

Pass 2 backslashes using the form '\\\\' (4 backslashes)
Use the 'r' prefix to keep Python from interpreting the string: r'\\'
s = nvstrings.to_device(["hello\\wor-ld","good-bye\\asd"])
print(s.replace('\\\\', ''))
print(s.replace(r'\\', ''))
['hellowor-ld', 'good-byeasd']
['hellowor-ld', 'good-byeasd']
Actually, there is a third option specifically for this case. Do not use regex at all here since this is just a single character and regex is overkill and probably slower:

s = nvstrings.to_device(["hello\\wor-ld","good-bye\\asd"])
print(s.replace('\\', '', regex=False))
['hellowor-ld', 'good-byeasd']

**Comment by kkraus14** [comment]
Working as intended.

**Comment by taureandyernv** [comment]
@davidwendt, regret the delay in response.  I think you misread my issue and went someplace that was correct, expected, but out of scope for my issue :). 

I specifically my issue wasn't when trying to use a single backslash, but double backslash (escaped backslash).  I was only trying to remove a single backslash.  Also, my method works in Pandas. :)

@kkraus14 , please reopen this, as it is **not** working as intended.  See below:

PANDAS <-- WORKS!
```
import pandas as pd

fn = 'test.csv'
lines = """a, b, c
test \\ phase* 1, 2, 3
test  \\phase 2, 4, 5
test\\phase* 3, 6, 7
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
df = pd.read_csv(fn)
df['a'] = df['a'].str.replace("\\","")
df.head()
```
Outputs <-- backslashes are gone :)
```
	a	b	c
0	test phase* 1	2	3
1	test phase 2	4	5
2	testphase* 3	6	7
```

CUDF <-- Not working!
```
import cudf

fn = 'test.csv'
lines = """a, b, c
test \\ phase* 1, 2, 3
test  \\phase 2, 4, 5
test\\phase* 3, 6, 7
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
df = cudf.read_csv(fn)
df['a'] = df['a'].str.replace("\\","")
df.head()
```
Outputs <-- backslashes are still there :(
```
a | b | c
-- | -- | --
test \ phase* 1 | 2 | 3
test \phase 2 | 4 | 5
test\phase* 3 | 6 | 7
```

**Comment by davidwendt** [comment]
The single, unescaped backslash regex pattern is not valid.
```
import re
re.compile("\\")
re.error: bad escape (end of pattern) at position 0
```
For whatever reason, Pandas treats this invalid pattern as a literal (dynamically turning off regex?) giving you the result you have described above. The cudf regex is just ignoring the invalid pattern resulting in no matches and no replacement.

We can make Pandas fail if the invalid escape is not the only character (?)
```
ps = pd.read_csv(fn)['a']

ps.str.replace(" \\","")
re.error: bad escape (end of pattern) at position 1

ps.str.replace("\\p","")
re.error: bad escape \p at position 0
```
Again, cudf just ignores the invalid escape.
```
ds = cudf.read_csv(fn)['a']

ds.str.replace(" \\","")
0    test\phase*1
1     test\phase2
2    test\phase*3

ds.str.replace("\\p","")
0    test \ hase* 1
1     test  \hase 2
2      test\hase* 3
```
I feel the right thing would be throw an error regardless instead of ignoring the invalid pattern or silently converting it into a non-regex literal.

**Comment by davidwendt** [comment]
I did a little more experimentation and found that if the `pat` argument passed to Pandas `.str.replace()` is a single character then it treats the single character as a literal -- forces `regex=False`. This is likely because escaped characters and quantifies require at least two characters. Any more than 1 character then Pandas throws the appropriate invalid regex pattern error.

```
ps.str.replace("*","")   -- no error
ps.str.replace("*?","")  -- throws re.error
```

If feature parity is desired here, I propose adding logic to the cudf `.str.replace()` function to call `cpp_replace()` instead of `cpp_replace_re()` if the `pat` variable is only 1 character.
Likewise, I think the libcudf code should throw an error if an invalid escape character is detected inside `replace_re()`. 

I will create a PR to include both of these changes.
