### ISSUE TITLE
[BUG] Special Characters cause `str.replace()` to crash if you don't use an escape character

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#3732]
**Describe the bug**
Running `str.replace()` on a special character without the escape character `\` causes the kernel to crash without an error

**Steps/Code to reproduce bug**
```
import cudf

fn = 'test.csv'
lines = """a, b, c
test \\ phase* 1, 2, 3
test  \\phase 2, 4, 5
test\\phase* 3, 6, 7
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
df = cudf.read_csv(fn)
df['a'] = df['a'].str.replace("*","")
```
---Kernel will crash in less than 30 seconds----

**Expected behavior**
I expect an error to be thrown, and the kernel still run.  

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker

**Environment details**
RAPIDS v0.12

**Comment by beckernick** [comment]
We should not expect an error to be thrown here

**Comment by davidwendt** [comment]
See my answer here for why you are seeing this behavior.
https://github.com/rapidsai/cudf/issues/3725#issuecomment-573184104

**Comment by kkraus14** [comment]
So this doesn't crash for me but just hangs forever with 0% GPU usage.

**Comment by davidwendt** [comment]
This is actually invalid regex expression. Regex compilers will report `nothing to repeat at position 0`.
This expression was causing an infinite loop during the pattern compile step. I can fix the error but the output would be undefined -- it may or may not replace anything.
So, looking for opinions here. I don't think we can match Pandas here since the expression is technically incorrect. Should I have the code throw an error or should it just continue and you get undefined results?

**Comment by taureandyernv** [comment]
@davidwendt , the desired output was to have an error thrown.  Thanks!

**Comment by davidwendt** [comment]
See comment here: https://github.com/rapidsai/cudf/issues/3725#issuecomment-604471956
