### ISSUE TITLE
[FEA] greatest/least in list of columns and scalars.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3762]
**Is your feature request related to a problem? Please describe.**
We would like to implement the Spark SQL greatest function and least function.  They return the largest or smallest non-null value among a list of scalars and columns respectively. 

**Describe the solution you'd like**
I would love some functions that take in a vector of columns and a vector of scalars and return the largest value or the smallest value depending on the function or null if all values were null.

**Describe alternatives you've considered**
We can implement this using existing operators like >, isNull, and copy_if_else but it would materialize a lot more intermediate data than would be ideal.

**Comment by rgsl888prabhu** [comment]
Will it be returning a vector of greatest or smallest if it's vector of columns ?

**Comment by devavret** [comment]
Unless you're operating on a large number of vectors, you could implement this with series `MAX` and `MIN` [reductions](https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/reduction.hpp) and it would yield a single scalar per column. Then you can compare the scalars. As for a vector of scalars, since each scalar lives in its own single allocation, it would not be any faster if max and min for those was handled in libcudf. We'd still need to copy all scalar values to a single array, copy it to device and run the same series `MAX`/`MIN` on it. And that would be slower than comparing them right away.

If you do use reductions, recommend to base your work off updated API in #3880

**Comment by harrism** [comment]
So it's `row_max`? Why is the scalar in there? Do you want this to be a table, or is it always two columns? The API you suggest is a bit strange in that regard.

**Comment by devavret** [comment]
I'm thinking of implementing binaryop min/max for this. It won't do k-way greatest/least but it would allow this:
```c++
column_1 = [1, 2, 3, 4, 5]
scalar   = 3
column_2 = [0, 1, 3, 5, 1]

temp = binary_operation(column_1, scalar, binary_operator::MAX)
// temp = [3, 3, 3, 4, 5]
result = binary_operation(column_2, temp_max, binary_operator::MAX)
// result = [3, 3, 3, 5, 5]
```

Would that suffice? If so, I can further look into how to handle nulls s.t. `op(x, null) == x` instead of the current `op(x, null) == null`
