### ISSUE TITLE
[FEA] round double with rint

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3789]
**Is your feature request related to a problem? Please describe.**
For spark we would like to support the rint function which "Returns the double value that is closest in value to the argument and is equal to a mathematical integer."

**Describe the solution you'd like**
This sounds like a Unary operations.  But we really only need it for doubles so we could optimize just for that.

**Describe alternatives you've considered**
There really is no rounding in cudf yet.

**Comment by jrhemstad** [comment]
To be clear, the kind of rounding desired is "round to nearest"? 

I assume this should be for `float` as well?

**Comment by jlowe** [comment]
It's essentially "round to nearest."  It's implemented in terms of Java's `Math.rint`.  More details at https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#rint-double-

I believe double is all that's needed for the Spark use case, since its query planning tends to casts inputs to double before math expressions like this.  However I would expect other users of libcudf to find a `float` form to be useful as well.

**Comment by jrhemstad** [comment]
> It's implemented in terms of Java's `Math.rint`. More details at https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#rint-double-

This sounds funny to me.

> Returns the **double** value that is closest in value to the argument and is equal to a mathematical integer.

So the output of this function is still floating point? Or is it integral?

If the former, what if the closest integer value cannot be exactly represented by a `double`?

**Comment by jrhemstad** [comment]
Or does it return the closest `double` that is exactly equal to an integer? That sounds kind of bananas.

**Comment by jlowe** [comment]
> So the output of this function is still floating point?

Yes, it takes a double and returns a double.

> what if the closest integer value cannot be exactly represented by a double?

While not explicitly specified, I believe the intent here is to return a double that most closely represents the nearest integral value, i.e. the double represented by casting the closest integral value to a double.  In other words, trying to compare the resulting value to the closest integer would return true when you cast them to the same type in order to compare them.

**Comment by jrhemstad** [comment]
Okay, that makes more sense, thanks.

**Comment by devavret** [comment]
Similar to https://github.com/rapidsai/cudf/issues/3791#issuecomment-578332645, I think this and similar requests #3753 and #3788 should ideally be done using [transform](https://github.com/rapidsai/cudf/blob/e51abbf7bc88241e3e9087946686f2b58086f8eb/cpp/include/cudf/transform.hpp#L44). In case of transform, we actually do have CUDA UDF support so you can make a function string like this:
```c++
__device__ inline void func(float* result, float input) {
  *result = std::rint(input);
}
```
and pass to transform.

Although, I think the function signature requirement should now be changed to 
```c++
__device__ inline float func(float input)
```

**Comment by rgsl888prabhu** [comment]
@devavret unaryops is using `transform` [here](https://github.com/rapidsai/cudf/blob/c4047687e3f5a5a621d62972f40fb12868d43fa4/cpp/src/unary/unary_ops.cuh#L66). So, is it as per the expectation  or it requires some other change.

**Comment by devavret** [comment]
@rgsl888prabhu I meant cudf::transform which takes a UDF string.

**Comment by rgsl888prabhu** [comment]
I will add an API to use UDFs in unary, but would also prefer to keep the new operation already defined in #3910.

**Comment by devavret** [comment]
> I will add an API to use UDFs in unary

No. Unary transform already exists.

> but would also prefer to keep the new operation already defined in #3910.

Sure. I just want people to be aware that unary transform exists and can be used for when you don't want to wait for libcudf developers to add your desired unary op.
