### ISSUE TITLE
[FEA] Merge `N` sorted tables into a single table

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3822]
**Is your feature request related to a problem? Please describe.**

It is common in algorithms (like distributed sort) to have multiple sorted tables that need to be merged into a single sorted table. 

libcudf currently provides [`cudf::merge` ](https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/include/cudf/merge.hpp#L78) which can merge two sorted tables into a single sorted table. 

It is possible to merge `N` sorted tables into a single table via repeated pair-wise calls to the current `cudf::merge`, however, this is inefficient because it requires materializing unnecessary intermediate results.

**Describe the solution you'd like**

We should explore providing an implementation that can merge `N` sorted tables into a single table that avoids the intermediate materializations.

**Comment by jrhemstad** [comment]
API probably looks something like:

```c++
std::unique_ptr<cudf::experimental::table> merge(std::vector<table_view> const& tables_to_merge,
                                                 std::vector<cudf::size_type> const& key_cols,
                                                 std::vector<cudf::order> const& column_order,
                                                 std::vector<cudf::null_order> const& null_precedence = {},
                                                 rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```

**Comment by felipeblazing** [comment]
Some minor optimizations could be checking to see if there are any non overlapping ranges, If so those cant just be concatenated together to avoid some of the merge operations. 

I have wondered myself what would be a good way to handle something like this. 
One idea
Partition the data in A * N buckets where N is the number of thread blocks and A is some multiple we pick. The threads in each block read a region of global memory into shared memory  so that they can read multiple values at a time and reduce the inefficiencies introduced by the non coalesced memory access. By partition I mean collect the start and end point for each bucket range in each column.

You then perform the merge in shared memory with each thread operating on some portion of the bucket. But N way is kind of tough because you need to store some offset into each starting point to know where you are in each list, So those indices would need to be in shared memory as well if we didnt want to incur the penalty of making global memory accesses for something that we would usually want to store in a register but can't because we don't know how many columns we are merging. (unless we want to put an upper limit and just use that many registers always).

I googled "n way sorted gpu merge" and the first thing that popped up was [https://web.cs.ucdavis.edu/~amenta/f15/GPUmp.pdf](https://web.cs.ucdavis.edu/~amenta/f15/GPUmp.pdf). I know @ogreen  works with you guys so I am sure his ideas are going to be way more informed than mine. I am going to start reading that paper now, I am pretty sure someone sent this to me before.

**Comment by jrhemstad** [comment]
@kkraus14 @shwina @rjzamora since I assume Pandas doesn't have an equivalent for a "k-way" merge, can we get the wheels in motion for defining a Python API so this is ready to use ASAP at the Python layer?

**Comment by vuule** [comment]
I have an implementation of the "binary tree of 2-way merges" approach working. Here's some performance numbers that show that this implementation scales as expected:
![image](https://user-images.githubusercontent.com/16005690/73503294-c3519500-4380-11ea-9589-e922f097d1ec.png)
The incremental merge scales linearly with the number of tables, while the binary tree merge scales logarithmically.
 
I plan to merge the current implementation so it's available ASAP, and then work on further performance improvements. @jrhemstad , does this sound good?

**Comment by kkraus14** [comment]
> @kkraus14 @shwina @rjzamora since I assume Pandas doesn't have an equivalent for a "k-way" merge, can we get the wheels in motion for defining a cuDF Python API so this is ready to use ASAP at the dask_cudf Python layer?

Yes, is there any API changes to `cudf::merge` or is the API staying the same as is?

**Comment by jrhemstad** [comment]
I think this function warrants a new API. Something like `multi_merge`? 

> I plan to merge the current implementation so it's available ASAP, and then work on further performance improvements. @jrhemstad , does this sound good?

Getting the API and initial implementation available ASAP sounds great.

**Comment by vuule** [comment]
Here are a few options I see for the API:
1. Change the current _merge_ API to take a vector of table_view's instead of two table_view's. This way we have one API to handle any number of input tables;
2. Add a _merge_ API overload, taking a vector of table_view's;
3. Add a new _multi_merge_ (or similar name distinct from merge) API, taking a vector of table_view's;

I slightly prefer the option 1, since there is nothing special about merging two tables compared to any other (valid) number so having a separate API does not make a lot of sense to me. 

@jrhemstad what is your preference here?

**Comment by kkraus14** [comment]
+1 to 1 from my perspective as well

**Comment by jrhemstad** [comment]
Sure, option 1 is good.

**Comment by jrhemstad** [comment]
@vuule is that performance graph with RMM pool mode enabled? If not, I'm guessing memory allocation is a significant portion of the performance bottleneck.

**Comment by rjzamora** [comment]
Keeping everything in `cudf::merge` sounds good to me.  

For python, we should probably add something like `cudf.sorted_merge` or `cudf.sorted_concat`.  Please correct me if I am wrong (somewhat likely), but it is my understanding that libcudf's `merge` focuses on a less-general objective than the python cudf/pandas `merge` API.

**Comment by vuule** [comment]
@jrhemstad not sure, I just ran the benchmark with default settings. I'll look inro enabling pool mode and share the numbers.

**Comment by kkraus14** [comment]
> For python, we should probably add something like cudf.sorted_merge or cudf.sorted_concat. Please correct me if I am wrong (somewhat likely), but it is my understanding that libcudf's merge focuses on a less-general objective than the python cudf/pandas merge API.

Yes this will be a new `sorted_merge` API and we can eventually kick off discussions with the Pandas community in the future to agree on a standardized API.

**Comment by vuule** [comment]
> is that performance graph with RMM pool mode enabled?

Confirmed that pool mode was enabled in the benchmark. Without it, the number are much worse, and scaling is similar (bit flatter line).

**Comment by jrhemstad** [comment]
Closed by https://github.com/rapidsai/cudf/pull/4040
