### ISSUE TITLE
[FEA] There should be a way of reading an entire parquet folder with *cu_df*

### ISSUE THREAD

**Issue by alexsisu** [rapidsai/cudf#3841]
**Problem**
I have to read a parquet folder containing parquet files directly into the gpu memory.

**Current way**
Right now there's only one way of doing that: reading them file by file and concatenating it. However this implies concat operation and iteration code that adds to the penalty of reading an entire folder.

```
final_df = None
for i in range(0, nr_of_files):
    got = cudf.read_parquet(target_files[i])
    if i == 0:
        final_df = got
    else:
        final_df = cudf.concat([final_df, got])

print(final_df)
```

**What would be nice to have something like this:**

```final_df=cudf.read_parquet(parquet_folder_path)```

**Comment by OlivierNV** [comment]
I think this should be doable with a mix of python, cython and cudf-io changes: we'd have to first parse the metadata of individual files, filtering out unwanted rowgroups, then concatenate in-memory the individual parquet files, and replace the metadata to create an in-memory larger parquet input.

**Comment by claudiuba** [comment]
in our case, concatenating in memory prevents us from loading all the files as we hit the maximum GPU mem available, even though the full dataset would comfortably fit in memory. Also, our files are part files of the same dataset with the same metadata.
@OlivierNV why would you need to filter unwanted rowgroups?

**Comment by OlivierNV** [comment]
@claudiuba Unwanted rowgroups would be solely for supporting first_row/num_rows in the API (we'd want to exclude the rowgroups that are not within range).
If we want to load multiple parquet files as a dataframe, we would have to assume that the parquet files we want to load would fit in gpu memory (though we'd presumably want to trim unwanted columns before concatenation as well).
Alternatively, we could make individual read_parquet calls per file then subsequently concatenate the resulting dataframes (would not require any CPP API changes), but that would eliminate any perf benefits vs single-file.

**Comment by claudiuba** [comment]
for the time being we'll concatenate the files into via with Spark

**Comment by kkraus14** [comment]
@OlivierNV say we were to update the DataSource implementation to allow for passing a `std::vector` of filenames or buffers for input, does that give you enough information to know what the resulting size of the output column buffers should be say before you need to allocate the output buffers for the columns in the Table?

If so, that could be a route to allowing to read a parquet/ORC directory as opposed to needing the 2x memory overhead to read each one into a separate table and then concatenate those tables.

**Comment by OlivierNV** [comment]
@kkraus14 Yes, I think if we had a vector of names (and assuming the files we're loading all have matching schemas), we could in-place re-assemble the concatenated metadata, then read it pretty much as if it was a larger parquet file (would also work with a vector of byte vectors for buffer input).
The actual column memory allocation occurs relatively late in the parquet reading pipeline.

**Comment by jlowe** [comment]
The Spark plugin could benefit from being able to load multiple host buffers in one call.  Being able to load a series of small Parquet files without needing to concatenate all the row groups into a single host buffer would be nice for improving performance when a task's input is multiple files.

**Comment by harrism** [comment]
@OlivierNV could you take this on for 0.15? It's P0 based on requests from cuDF and Spark.

**Comment by OlivierNV** [comment]
@harrism Sorry, I'm no longer a contributor to the RAPIDS/cudf (will still provide support/advice for columnar readers, but no PRs).

**Comment by vuule** [comment]
@alexsisu @jlowe how important is the use of row selection parameters (`row_groups`, `start_row`, etc.) when reading the whole directory?

**Comment by jlowe** [comment]
Spark would not use an API to load an entire folder of files at once. Spark's driver decides how the input files are split and grouped for a particular task, so it's not often that a single Spark task would want to read an entire directory.  Normally it would read at most a subset of files within a single directory.  So from the Spark perspective, we would want an interface where we could specify a set of files rather than 1 file vs. all files.

Even with such an interface, without support for predicate pushdown in the libcudf loader (at least to the row group level) we would not use it in practice.  Predicate pushdown is an important optimization that we would lose if libcudf completely controlled the loading process.

That's why the Spark plugin currently does not specify the `row_groups` or `start_row` parameters even for a single file.  We are reading the file footer on the CPU, processing it with predicate pushdown to decide which row groups we want, then only loading the compressed row group data from the distributed filesystem for the desired subset of columns.  This minimizes the distributed filesystem I/O and allows predicate-pushdown to the row-group level per file.  We then fabricate a new Parquet file in host memory with an updated footer and feed that to libcudf's Parquet loader.

Our current plan to coalesce multiple file loads into a single libcudf parse is to do the predicate pushdown on each file as we do today then concatenate the row group data across the files into a single Parquet file in memory that is loaded all at once via libcudf.

**Comment by kkraus14** [comment]
It would be nice for libcudf to handle reading a partitioned directory but that's not needed as a first step. As a first step if we could handle a vector of input files / buffers along with a vector of vectors of row groups to read that would be ideal.

**Comment by vuule** [comment]
> vector of vectors of row groups

Great, I wasn't sure about that part. Since specifying the same row groups for all files does not make sense.

**Comment by vuule** [comment]
@jlowe I did not phrase my question well. It was not pertaining to whole directory reads specificaly, but any read calls that include multiple files/buffers.
The row selection parameters complicate this feature so I wanted to make sure they are useful enough to include from the start.

**Comment by kkraus14** [comment]
Yea, I think there's also an opportunity for us to simplify our API where instead of having `row_group` / `row_group_count` as well as `stripe` / `stripe_count` we could just always use the `row_group_list` and `stripe_list` parameters and treat a nullptr as indication to read everything.

**Comment by vuule** [comment]
> Yea, I think there's also an opportunity for us to simplify our API where instead of having `row_group` / `row_group_count` as well as `stripe` / `stripe_count` we could just always use the `row_group_list` and `stripe_list` parameters and treat a nullptr as indication to read everything.

@kkraus14 does this refer to libcudf API? Python only exposes `row_group` / `row_group_count`. I can convert these into a `row_group_list` and pass that into the cpp layer. How does that sound? My only concern is the difference between cpp and python APIs.

**Comment by kkraus14** [comment]
Yes this refers to the libcudf API. In Python we should similarly just take an array of row groups instead of exposing row_group / row_group_count.

**Comment by vuule** [comment]
> In Python we should similarly just take an array of row groups instead of exposing row_group / row_group_count.

In Python it can probably be either an array of indices, or an array of arrays of indices.
