### ISSUE TITLE
[FEA] Expose left semi join to Python

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3903]
With the merge of #3538 , it should be possible to expose left semi (and anti-join) to Python. This is not currently a join option natively supported in the pandas API, but it would be valuable for us to expose this functionality.

**Comment by brandon-b-miller** [comment]
Working on this 👍

**Comment by kkraus14** [comment]
> Working on this

Before diving into implementation I would suggest raising an API proposal PR or talking it through here.

**Comment by brandon-b-miller** [comment]
@kkraus14 I'm working under the assumption that this is just a matter of plumbing the join through to libcudf via cython similarly to the way we handle the current allowable joins - is there anything special about semi/anti joins that we should handle differently?

**Comment by brandon-b-miller** [comment]
Ah, I see this wasn't added to the legacy header (this seems obvious in retrospect).

**Comment by kkraus14** [comment]
Joins map into the Python APIs for merge/join under the hood after some craziness, so these new semi joins should likely integrate into the existing APIs via a new `how` type, but others may have differing opinions.

**Comment by brandon-b-miller** [comment]
From the python perspective I think it's as simple as just allowing `how='leftanti'`, which should be familiar to spark users especially where the api is `result = left.join(right, on=join_cols, how='leftanti')`. IMO the bulk of the work is in cython since these joins don't exist in legacy libcudf. In that sense exposing them at this point also involves a concurrent rewiring of the cython to point to the new `join.hpp`. The new libcudf api involves some rmm machinery I'm not sure we have cython helpers for yet.

**Comment by randerzander** [comment]
@quasiben @rjzamora what changes if any would Dask need to support left semi joins?

**Comment by quasiben** [comment]
@randerzander probably pandas would need to support this first.   Semi joins can be expressed through fany-ish selections.  Something like:

> df1[df1.x.isin(df2.x)]

Obviously, we have more flexibility in dask-cudf.  But I think what we are seeing/asking is, can dask be pushed on to move beyond Pandas for other dataframe libraries and i don't know the answer to that.
