### ISSUE TITLE
[BUG] .loc fails to assign values properly.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#3951]
Code to reproduce:

```
import cudf
df = cudf.DataFrame({'x':[1], 'y':[1]})
df.loc[0]['x'] = 2
```

throws error:
`UnboundLocalError: local variable 'out' referenced before assignment`

**Comment by rgsl888prabhu** [comment]
This is kind of tricky to handle as `df.loc[0]` returns a Series rather than a DataFrame,
where Column names are indices and Column would be value of that row.
As per the above example

```
>>> import cudf
>>> df = cudf.DataFrame({'x':[1], 'y':[1]})
>>> print(df.loc[0])
x    1
y    1
```

So, `df.loc[0]['x'] = 2` would be updating a series and not the data-frame.
as we are converting a row to a Series, there is no better way to use the same memory, so we end-up creating new series.
One more issue to support such scenarios are places where columns are of different types which can't be casted to another.

And even Pandas throws error in some cases, for example
``` 
>>> import pandas as pd

>>> pdf = pd.DataFrame({'index': [0, 1, 2, 3], 'a': [0., 1., 2., 3.]})
>>>
>>> pdf.iloc[0]
index    0.0
a        0.0
Name: 0, dtype: float64
>>> pdf.iloc[0]['index'] = 5
__main__:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
```

So, I was thinking to error if anyone tries to update such series. And if the user just wants the series to be updated, then he should explicitly deep copy it.

I am open for suggestions and discussions.

**Comment by kkraus14** [comment]
I'm going to close this as a `wontfix`. This code only works due to internal implementation details of Pandas with regards to the block manager and is likely going to be broken in the near future with Pandas moving towards a 1d array manager.
