### ISSUE TITLE
[FEA] Tests for Python Buffer class

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#3977]
**Is your feature request related to a problem? Please describe.**

Currently there are no tests of [the Python `Buffer` class]( https://github.com/rapidsai/cudf/blob/b4275944bdd1fd22d8d70bc749d54ff68064e6f5/python/cudf/cudf/core/buffer.py ).

**Describe the solution you'd like**

Would be good be good to add some unit tests.

**Describe alternatives you've considered**

Suggestions welcome 🙂

**Additional context**

NA

**Comment by vyasr** [comment]
I think this is unlikely to ever happen within cudf. `cudf.Buffer` is an internal implementation detail, not something that should be exposed publicly. We've discussed spinning something like this object out into a separate standalone library, in which case it would absolutely make sense to add tests, but otherwise we typically rely on API tests to catch issues with internals.
