### ISSUE TITLE
[FEA] The IO writer currently writes to a container that owns the buffer

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4019]
**Is your feature request related to a problem? Please describe.**
We are using the IO writer to write files to a buffer. Currently the writer writes to a container (std::vector) which won't release the ownership of the underlying buffers. Therefor its not possible for the java side to use the buffer beyond the life of the container. 

**Describe the solution you'd like**
We need a resizeable container that has something like release()

**Describe alternatives you've considered**
We have considered returning the entire std::vector and release it after we are done with the data but that just adds more object tracking on the java side that is not ideal 

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by revans2** [comment]
Just to clarify a bit.

We have the requirements/desire to be able to.

1) We want to be able to transfer the data from the device in an optimized way.  We already have a pinned memory pool which we would like to try and reuse, because there is already a non-trivial overhead in allocating that pool.
2) We want to minimize the number of memory copies we have to make, well because java is horrible at this already and we really don't want to make it any worse.  Ideally we would want to take ownership of any host side buffers because in many cases we have to send them through java specific APIs that do not operate on raw buffers anyways.

After having thought about it for a while I think we would like a lower level API.  One that does not do any data movement, but instead hands back the raw buffers.

```
  explicit writer(
      std::vector<std::unique_ptr<rmm:device_buffer>>* buffers, writer_options const& options,
      rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```

If there is a mixture of host and device buffers it would be great to use something like std::variant, but we are not on that version of the c++ standard.  This allows us to optimize the transfers to/from the device and also to minimize the number of transfers between host memory and whatever java API we need to interact with.

**Comment by revans2** [comment]
We don't need that exact API, but something like it would be great.

**Comment by harrism** [comment]
@OlivierNV @vuule Any comments on this discussion?

**Comment by OlivierNV** [comment]
I'm thinking that if we extended the datasink interface with members like devicememwrite() and pinnedmemwrite() (where the default implementation could memcpy to an intermediate pinned mem buffer), then the caller could implement its own hooks in a custom implementation.

**Comment by vuule** [comment]
@OlivierNV Is every datasink type then expected to support both device and host writes? 

I would avoid placing a concrete API in the generic datasink. Instead, we can add a datasink-inherited class that writes into pinned memory, instead of a vector. It would return a pointer and size of the buffer, and it would be on the user to free the memory.
@revans2 would this work for your use case?

One concern I have about this approach is that the output size is not known ahead of time (AFAIK) so reallocation(s) could get expensive.

**Comment by harrism** [comment]
Why not  abstract it via memory_resource or buffers? This is the reason that libcudf and RMM use `device_memory_resource`. And @jrhemstad is in the process of adding a `host_memory_resource` to enable abstracting allocation of pinned host memory.

**Comment by vuule** [comment]
> Why not abstract it via memory_resource or buffers? This is the reason that libcudf and RMM use `device_memory_resource`. And @jrhemstad is in the process of adding a `host_memory_resource` to enable abstracting allocation of pinned host memory.

That sounds great. No need to add a writer type.
Is this one blocked on `host_memory_resource` then?

**Comment by OlivierNV** [comment]
It would be good to have the buffer-based sink be either hostmem of regular sysmem, but I don't think it's enough to avoid memory copies (see @revans2 's requirements): if we want to avoid copies and allow the client to directly use the source data, it may come from a random memory location (local variable on the stack, generic sysmem vector, device memory address or pinned host mem).

**Comment by vuule** [comment]
I must be missing something because to me it seems that it's sufficient to provide the following:
* Output to pinned buffer that user can take ownership of;
* Output directly to device buffer that user can take ownership of;

@revans2 does your mock API return a vector of buffers (instead of a single buffer) to avoid reallocation?

**Comment by OlivierNV** [comment]
I think that would be sufficient for the existing hostbuffer sink. The second part of this feature seems to be a zero-copy sink, where the sink is gradually given input fragments from various locations (it can't be given *all* the fragments for the entire file, since the writer will typically re-use some intermediate buffers for io)

**Comment by revans2** [comment]
This all sounds great.  I would love to see some class exposed so we can get callbacks to handle the data.  Having separate APIs for host buffers vs device buffers is even better because then a consumer of the API can control how to copy the data to its final destination.  We could have a default implementation for the device buffer that would copy it to a host buffer and call the host API. Like Mark called out we need to be sure that ownership of the memory passed into the API is accounted for properly. I know that for the parquet writer they allocate a single pinned host buffer and reuse it when copying the data. We can probably emulate that by letting the writer pass some hints to the sink, like the maximum device buffer size it will use, this way the sink itself can decide how to properly optimize the transfers.

**Comment by OlivierNV** [comment]
We could add a reserve(size_t) member on the base data sink to minimize resizing, along with provide a max expected buffer size for subsequent calls (io writers should be able to infer both). If we have a device_mem write, we should be able to eliminate the parquet hostmem buffer and directly pass device addresses to the sink, though the caller would have to be aware that these addresses are temporary and likely to be freed or re-used immediately after the call (if copying from device mem, the caller would have to use the same stream that was passed in to the writer, or we'd have to also pass in the cudaStream_t along with the device ptr).

**Comment by harrism** [comment]
Is this feature request satisfied at all by #4231 ?

**Comment by jlowe** [comment]
Yes, it resolves the issue.  We've moved to that new API in #4498.
