### ISSUE TITLE
[BUG] make_string_scalar creates invalid string scalar

### ISSUE THREAD

**Issue by jeanp413** [rapidsai/cudf#4085]
**Describe the bug**
make_string_scalar creates invalid string scalar

**Steps/Code to reproduce bug**
 1. Call ` cudf::make_string_scalar("my_string");`
 2. The returned scalar is invalid.

https://github.com/rapidsai/cudf/blob/b451ce60ae6310d9cb7b5a2d7fabc8dae79f581d/cpp/src/strings/strings_scalar_factories.cpp#L27

The second constructor argument should be `true`.

**Expected behavior**
The string scalar should be valid

**Comment by harrism** [comment]
Actually, I think that this is just copying from `make_numeric_scalar`, which just allocates space for the scalar and sets it invalid but does not set its value. You are expected to call `set_value()` and `set_valid()`. But I don't think that is a useful factory. 

So I plan to add `make_*_scalar` factories that take a value for the scalar, so that they work like `make_string_scalar`, which takes a string value. I will also fix the latter to set validity to true.

**Comment by jrhemstad** [comment]
Closed by https://github.com/rapidsai/cudf/pull/4610
