### ISSUE TITLE
[BUG] Parquet reader can load non-null strings as null values

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#4286]
**Describe the bug**
Reading a Parquet file with strings sometimes is returning null entries for strings that are not null.  Spark loads the file and shows there are no nulls, but libcudf loads the file containing one or more nulls.  It appears the values that can become null are supposed to be loaded as empty strings.

**Steps/Code to reproduce bug**
I am not sure yet how to forcefully trigger it with a unit test, but I have some Parquet files that demonstrate the issue.  I can provide them upon request.

**Expected behavior**
libcudf Parquet reader should produce the same data as Spark's Parquet reader.

**Comment by OlivierNV** [comment]
Think I found the bug with code inspection. I think this happens if the last string of a column (or rowgroup) is an empty string (with PLAIN encoding), or all empty string if the empty string is the last dictionary entry (offset is considered out of bounds because it is outside the [0..size-1] range, but it's not out of range for zero-length strings.
