### ISSUE TITLE
[FEA] Enable the construction of shared/dedicated parquet-metadata files

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#4340]
**Is your feature request related to a problem? Please describe.**
I would like cudf to include the necessary mechinisms needed to generate a standalone parquet metadata file (`"_metadata"`) for a multi-file parquet dataset.

When reading a parquet dataset, dask.dataframe/dask_cudf uses a single shared `"_metadata"` file (when available).  That is, the dask client can/will use the single metadata file to define the task graph needed to read the dataset, without needing to use the file system for file discovery or needing to parse the footer of every file.  For this reason, having a shared `"_metadata"` file can be a significant performance boost for large datasets and/or remote file systems.

**Describe the solution you'd like**
When using the `pyarrow.parquet`-based engine for `to_parquet` in dask.dataframe, the creation of a shared metadata file requires three steps:
1. The metadata for each individual file is accessed in python by [passing an empty list to the `metadata_collector` argument of `pyarrow.parquet.write_table`](https://github.com/dask/dask/blob/ed6932a7cd7472064f640f2e6d835bfe5830a38c/dask/dataframe/io/parquet/arrow.py#L508). Since pyarrow does **not** set the `file_path` metadata for each column-chunk in the metadata, dask also uses the [set_file_path](https://github.com/dask/dask/blob/ed6932a7cd7472064f640f2e6d835bfe5830a38c/dask/dataframe/io/parquet/arrow.py#L512) method to populate the field.
2. After all "data" has been written to the parquet dataset, dask needs to aggregate the metadata from each file into a single metadata object.  To do this, dask iterates through the metadata objects, and uses [`append_row_groups`](https://github.com/dask/dask/blob/ed6932a7cd7472064f640f2e6d835bfe5830a38c/dask/dataframe/io/parquet/arrow.py#L539) to aggregate them.
3. After the metadata has been aggregated into a single object, dask finally uses the metadata object's [`write_metadata_file`](https://github.com/dask/dask/blob/ed6932a7cd7472064f640f2e6d835bfe5830a38c/dask/dataframe/io/parquet/arrow.py#L541) method to write the file.

There may be better alternatives.  However, if we follow the same approach as pyarrow, we need the following features:
- A feature to access the metadata written during a `cudf.io.to_parquet` call
- A feature to set the column-chunk `file_path` value in the metadata (note that we do **not** want this value set in the footer metadata, just in the shared file)
- A feature to aggregate multiple metadata objects into a single object (not necessary if the aggregation is handled when the `"_metadata"` file is finally written)
- A feature to write out a dedicated metadata file 

**Describe alternatives you've considered**
The alternaives are to (1) not write a shared metadata file, or to (2) continue using pyarrow to write large (many-file) parquet datasets.

**Other context**
This is relevant to [#4236](https://github.com/rapidsai/cudf/pull/4236) (and is required to use cudf as the backend when the user specifies `write_metadata_file=False`)

**Comment by rjzamora** [comment]
cc @randerzander

**Comment by OlivierNV** [comment]
It seems that we have most of that already in place with the chunked support (the metadata is essentially the pq_chunked_state), we'd just need to update the file_path member of parquet::ColumnCheck and make a CompactProtocolWriter::Write(&state.md) call to convert the FileMetaData struct into a byte array, then just write the resulting byte vector to a separate file (along with the standard fixed header/footer magic).

**Comment by OlivierNV** [comment]
dask presumably uses the python api though, so probably the first step would be to expose chunking on the python/cython side before anything else.

**Comment by rjzamora** [comment]
Thanks @OlivierNV!  Very interesting - I didn't realize the there was "chunked" support down in cpp :)

I see the `pq_chunked_state` [here](https://github.com/nvdbaranec/cudf/blob/110057a9ca927820051c225bf0e4beff94696156/cpp/include/cudf/io/writers.hpp#L230).  I think you are correct that we would want cython bindings to the `write_parquet_chunked` functionality.  In order to aggregate metadata from multiple different dask workers, I'm guessing we would also need an API to combine a list of `pq_chunked_state` or `FileMetaData` objects as well.  Is that correct?

**Comment by OlivierNV** [comment]
Yeah, if the data comes from multiple workers, we'd need an API (separate from the chunking) that allows building parquet parquet metadata without actually writing anything until the end call that would just write an empty parquet file with just the metadata (pq_chunked_state itself is already an aggregation of metadata for multiple calls to write_parquet_chunked, so it can be used as-is for the metadata purposes).

**Comment by OlivierNV** [comment]
I've been thinking about this, and pq_chunked_state isn't a good match, since we want something that can be aggregated from multiple different dask workers. On the C++ side, I think we can have a simple api, that makes aggregation trivial:
1. Modify libcudf to_parquet such that it can take in the file_path string that will be stuffed in the footer metadata, and optionally return the raw parquet file footer into a client-provided byte vector.
Having the raw footer makes aggregation trivial, as it consists of simply concatenating the byte vectors from different workers, and raw byte vectors can be exchanged as-is across the network between different dask workers.
2. On the python side, the aggregated metadata-only parquet file can be constructed by writing the following elements to the file:
`magic_four_bytes, raw_footer_1, raw_footer_2, ..., raw_footer_N, footer_size, magic_four_bytes`
where 'magic_four_bytes` are the 4-character parquet signature "PAR1", raw_footer_x are the raw byte arrays filled in by to_parquet(), and footer_size is a uint32 that is the combined size of all footers.

**Comment by OlivierNV** [comment]
@rjzamora Can you take a look at PR #4450 to see if that would work for dask ? It turns out that it wasn't a simple concatenation of binary blobs, so I also had to add an API similar to arrow's append_row_groups, except that it just takes a list of metadata blobs and concatenate them all in one shot, and returns the final binary blob, which is then up to the caller to write it to disk or whatever.

**Comment by rjzamora** [comment]
Great - Thanks @OlivierNV ! I'll take a look really soon.

> except that it just takes a list of metadata blobs and concatenate them all in one shot

Sounds better to me :)

**Comment by OlivierNV** [comment]
PR #4340 is pretty much ready, though I'm not sure how to go about it for testing, since the resulting parquet blob is pretty much dask-specific...
