### ISSUE TITLE
[QST] Optimal Parquet size for CUDF dataframe.

### ISSUE THREAD

**Issue by raviy0807** [rapidsai/cudf#4356]
**What is your question?**

For huge data like 60GB, what will be best approach to create the parquet file?

Should be have multiple parquet file or single parquet file?

In which scenario, cudf will read faster? 
Also, what should be max size of parquet to get best performance of CUDF dataframe and query?

**Comment by OlivierNV** [comment]
For single gpu, it shouldn't matter much (assuming you can iteratively read a subset of the large file in each read using the min_row/num_rows or rowgroup apis, and/or iteratively write the file using the recently-added chunked write APIs).
For multiple GPUs, it is preferable to distribute separate files to different GPUs, but you generally want each parquet file to be at least 500MB to 1GB per read_parquet() call in order to get maximum throughput.

**Comment by kkraus14** [comment]
Thanks for answering @OlivierNV! Closing
