### ISSUE TITLE
[FEA] Change `mutable_column_view` to capture it's null count by reference

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4382]
**Is your feature request related to a problem? Please describe.**

Currently, `mutable_column_view` accepts it's null count parameter [by value](https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/column/column_view.hpp#L398).

This leads to a surprising result:

```c++

cud:column c{...};
c.set_null_count(0);
auto mv = c.mutable_view();
mv.set_null_count(42);
std::cout << (mv.null_count() == c.null_count()) << std::endl;
``` 
The result is that it prints `false`.

This is because calling `mutable_view::set_null_count` does not modify a viewed `column`'s null count (because it's passed by value). 

By design, this will never produce incorrect results. However, it can be inefficient as it will require unnecessary invocations of `count_set_bits`. 

@trevorsm7 made me realize that this pass-by-value design has another consequence on performance.

```c++
auto out_col = allocate_like(in_col, out_size);
auto out_view = out_col->mutable_view(); // <- forces null count to be materialized
```

Because `mutable_column_view` expects it's null count to be passed by value, calling `column::operator mutable_column_view` necessarily requires materializing the `null_count` if it is `UNKNOWN_NULL_COUNT`. Instead, if it were passed by reference/pointer, there would be no need to materialize the viewed `column`'s null count upon invocation of `operator mutable_column_view()` as it could instead simply pass a reference to the viewed column's unknown null count, avoiding the materialization.

**Describe the solution you'd like**

Update `mutable_column_view` to have it's `null_count` member be a pointer (or non-const reference). This would solve both of the problems above.

**Comment by devavret** [comment]
What about the case where the `mutable_column_view` has an offset? Is the null count still supposed to be the same as the `column` it was made from?

**Comment by trevorsm7** [comment]
Yikes, that's a good point Devavret. I don't see how this could work in that case.

I wonder if another solution to the problem of `mutable_view()` materializing the null count would be to instead initially set it to unknown (and for the parent column as well; no need to call `null_count()`) since the user should be overwriting the data in a mutable column anyway.

**Comment by jrhemstad** [comment]
> What about the case where the `mutable_column_view` has an offset? Is the null count still supposed to be the same as the `column` it was made from?

Hm, great point! That certainly breaks this idea. 





> I wonder if another solution to the problem of `mutable_view()` materializing the null count would be to instead initially set it to unknown (and for the parent column as well; no need to call `null_count()`) since the user should be overwriting the data in a mutable column anyway.

This would certainly solve the latter issue you identified.

**Comment by trevorsm7** [comment]
While, looking through cases where `mutable_view()` is unnecessarily invoking null count (there are a lot!), I noticed something very surprising. The following innocent looking code will invoke count nulls at least once and possibly twice, since the first call resets the null count to unknown, forcing the second call to compute it, even if the first call had already invoked count nulls.
```cpp
thrust::fill(rmm::exec_policy(stream)->on(stream),
    _keys_bitmask_column->mutable_view().begin<T>(),
    _keys_bitmask_column->mutable_view().end<T>(),
    0);
```

**Comment by trevorsm7** [comment]
In almost all places I could find, having `mutable_view()` set both the parent and the mutable view to unknown null count instead of invoking count nulls appears to be a win. The most notable exception I could find was https://github.com/rapidsai/cudf/blob/99fd2e6eaa51fd7bc08385d0988e7c4b28661596/cpp/include/cudf/detail/copy_range.cuh#L165-L170 ; the logic here would need to be changed in this case, as this would now always be forcing the null count of the entire input column to be computed.

I still think it might be worth considering adding a function that would return either the pre-computed null count or UNKNOWN_NULL_COUNT. It would be useful at least in the case of `copy_range` and it could be an alternative to using `has_nulls()` for dispatching between kernel variants that handle/ignore nulls

**Comment by trevorsm7** [comment]
Here's a list of places where this change would prevent totally unnecessary count nulls invocations (generally where allocating a column with an `UNINITIALIZED` mask and then calling `mutable_view()`):
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/groupby/sort/group_quantiles.cu#L51-L61
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/binaryop/compiled/binary_ops.cu#L81-L85
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/binaryop/compiled/binary_ops.cu#L111-L115
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/binaryop/binaryop.cpp#L260-L267
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/binaryop/binaryop.cpp#L292-L299
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/binaryop/binaryop.cpp#L326-L334
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/binaryop/binaryop.cpp#L361-L369
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/include/cudf/detail/copy_if.cuh#L247-L248
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/groupby/sort/group_std.cu#L86-L103
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/groupby/sort/sort_helper.cu#L252-L260
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/reductions/scan.cu#L123-L130
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/rolling/rolling.cu#L311-L314
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/rolling/rolling.cu#L339-L342
https://github.com/rapidsai/cudf/blob/c07e46ee9304db6cbc6b63e057eb777166980dc1/cpp/src/rolling/rolling.cu#L500-L503

**Comment by jrhemstad** [comment]
> I noticed something very surprising. The following innocent looking code will invoke count nulls twice

I guess I don't think that's very innocent looking :) I generally try and ask people not to do stuff like this in reviews. 

> I still think it might be worth considering adding a function that would return either the pre-computed null count or UNKNOWN_NULL_COUNT.

Until I see evidence to the contrary, I still believe this would be more harmful than helpful due to the extra complexity added to the code paths.
