### ISSUE TITLE
[FEA]  partition_cols support for GPU-accelerated  Parquet writer

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4413]
Is the GPU-accelerated parquet writer going to support `partition_cols` soon? 

Are there any other other features of the CPU-based writer that are yet to be added to the GPU-acc one?

**Comment by OlivierNV** [comment]
How big is a typical number of partitions and the size of a single output partition ?

**Comment by chinmaychandak** [comment]
Well, I need to be sure and will let you know soon. 

But, in any case, this would be one of the imperative features to have in a parquet writer. Is it difficult to add/ any ETA for this?

**Comment by OlivierNV** [comment]
I'm hoping we can rely on existing cudf partitioning capability upstream from the c++ writer, but either way, it sounds like this should be doable for the 0.14 release.

**Comment by chinmaychandak** [comment]
@satishvarmadandu, should we prioritize this?

**Comment by OlivierNV** [comment]
I'm thinking there are two ways to go about it:
- Option 1: Generate individual partitions, and call the parquet writer for each partition (low-level parquet writer itself remains essentially unaware of the partitioning). Has some benefits in memory utilization (scratch size of largest partition), but might result in poor utilization if we have many small partitions (for good writer throughput, we want at least 250MB per partition)
- Option 2: Create a big dataframe that consists of concatenated partitions, and pass in a list of partition info to the writer (like `{start_row, num_rows}` pairs, or just an array of `table_view`). The parquet writer would then encode all partitions in one pass, only split to individual files before io write stage (likely requires a custom io writer that has something like a `set_partition_id(n)` to switch from one file to the next)
In both cases, it might be possible to hide everything within the c++ layer, and just pass in the list of column names to use for partitioning, though I'd prefer to keep this logic in the python layer if we can, since it's mostly unrelated parquet itself.
