### ISSUE TITLE
[BUG] Kafka external datasource to follow CK convention of creating consumer

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4444]
@jdye64 

`from custreamz import kafka`

`consumer = kafka.KafkaHandle(kafka_configs, topics=[topic], partitions=[partition])` needs to be changed  to `consumer = kafka.Consumer(kafka_configs)`

**Comment by jdye64** [comment]
@chinmaychandak I'm going to move the "committed" API failure to another issue as that is different from changing the API function definitions.

**Comment by chinmaychandak** [comment]
Done, do send me the link to the new issue

**Comment by jdye64** [comment]
@chinmaychandak I can change the name from `consumer = kafka.KafkaHandle(kafka_configs, topics=[topic], partitions=[partition])` to `consumer = kafka.Consumer(kafka_configs)` BUT it will still need to have the list of topics and partitions like KafkaHandle does. Otherwise I would have no way of knowing what topics and partitions that the consumer needed to subscribe to

**Comment by chinmaychandak** [comment]
Why can't we have it like CK — [Consumer](https://docs.confluent.io/current/clients/confluent-kafka-python/#confluent_kafka.Consumer.Consumer)?
 
All the other API take TopicPartition or the topic as a parameter, so why do we need it in KafkaHandle?

**Comment by jdye64** [comment]
That Consumer object creation takes configs and not a TopicPartition instance

**Comment by jdye64** [comment]
We could add an "assign(TopicPartition)" function that would be an extra call you would need to make from your end however. I'm fine with that however.

**Comment by chinmaychandak** [comment]
> That Consumer object creation takes configs and not a TopicPartition instance

Yes, exactly. It does not take the list of topics and partitions like KafkaHandle, that was my point.

> We could add an "assign(TopicPartition)" function that would be an extra call you would need 
to make from your end however. I'm fine with that however.

Yes, that's what I was going to suggest. This should be fine.

**Comment by jsmaupin** [comment]
Can we also verify that the `get_watermark_offsets` functions respects the `timeout` parameter and doesn't replicate the the issue in the Confluent lib?

**Comment by chinmaychandak** [comment]
@jdye64 Can we verify this, as Jarod pointed out: https://github.com/confluentinc/confluent-kafka-python/issues/413

**Comment by jdye64** [comment]
@chinmaychandak @jsmaupin I did validate that the timeout is being honored.

**Comment by jsmaupin** [comment]
This is great. That should mean that we have HA with this change.

**Comment by jdye64** [comment]
@jsmaupin just in case you aren't aware of this when calling `get_watermark_offsets` you want to set `cached=False` for your use with HA. What does this do you might be asking?

If you set `cached=False` the client will query the Kafka server and ask for the latest offsets, which is what you want for what you are doing. If `cached=True` it will simply return the latest offsets stored at the client level.

A timeout is only associated and used when `cached=False` otherwise the call immediately returns.

**Comment by jsmaupin** [comment]
Do we know how the Confluent lib behaves?  Does it always fetch the cached values?

**Comment by jdye64** [comment]
It does not have that capability. No. If you don’t specify cached it behaves just as CK however

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jsmaupin** [comment]
Great, that sounds pefect.
