### ISSUE TITLE
[BUG] Kafka External Datasource — produce() with no message key throws an error

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4580]
@jdye64 

Reproduce using:

```
from time import sleep

import confluent_kafka as ck
from custreamz import kafka


def main():
    params = {
        "metadata.broker.list": "localhost:9092",
        "enable.partition.eof": "true",
        "group.id": "custreamz",
        "auto.offset.reset": "earliest",
        "enable.auto.commit": "false",
        "session.timeout.ms": "60000"
     }

    c = kafka.Consumer(params)
    c.produce("test-topic","test message")
    tp = ck.TopicPartition('test-topic', 0, 0)
    
    while True:
        print(c.get_watermark_offsets(tp, timeout=1, cached=False))
        print('tick')
        sleep(1)


if __name__ == '__main__':
    main()
```

Error: `TypeError: descriptor 'encode' requires a 'str' object but received a 'NoneType'`

**Comment by jsmaupin** [comment]
I'm assuming we need to encode to `utf-8` here. Without peeking at the code, are we encoding before returning. The Confluent lib returns bytes.  Can we do the same?

**Comment by jdye64** [comment]
Why are you not passing a message key here? You do understand the implications of not doing that correct? I can add a check and if its None set it to "" but just want to make sure you understand this is going to lead to significant broker hotspotting

**Comment by chinmaychandak** [comment]
Well, like CK, it shouldn't be mandatory to pass a message key, right? How does CK handle this?

**Comment by jdye64** [comment]
I guess it just dumbly writes to the same broker. I just added a check so this is fixed to behave like that now too I guess

**Comment by jsmaupin** [comment]
I think there are two strategies here. If there is no key, the producers I've seen either:

1. Pick one with a random number generator
1. Cycle through them one by one for each batch pushed.

**Comment by chinmaychandak** [comment]
Also, we'd eventually need a `Producer` class for this `produce()` method.

**Comment by kkraus14** [comment]
@jdye64 The Kafka integration code isn't merged into cuDF yet, right?

**Comment by jdye64** [comment]
That is correct. It is really close, probably could be, but is probably
best to let it slide till a time that is better for everyone.

Get Outlook for iOS <https://aka.ms/o0ukef>
------------------------------
*From:* Keith Kraus <notifications@github.com>
*Sent:* Tuesday, April 7, 2020 7:47:32 PM
*To:* rapidsai/cudf <cudf@noreply.github.com>
*Cc:* Jeremy Dyer <jdye64@gmail.com>; Mention <mention@noreply.github.com>
*Subject:* Re: [rapidsai/cudf] [BUG] Kafka External Datasource — produce()
with no message key throws an error (#4580)


@jdye64 <https://github.com/jdye64> The Kafka integration code isn't merged
into cuDF yet, right?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/rapidsai/cudf/issues/4580#issuecomment-610674384>, or
unsubscribe
