### ISSUE TITLE
[BUG] contains doesn't return true for NaN

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4640]
**Describe the bug**
contains should return true if a column contains NaN but it doesn't

**Steps/Code to reproduce bug**
```
try (ColumnVector cv = ColumnVector.fromFloats(Float.NaN);
         ColumnVector needles = ColumnVector.fromFloats(Float.NaN);
         ColumnVector expected = ColumnVector.fromBoxedBooleans(true);
         ColumnVector result = cv.contains(needles)) {
      assertColumnsAreEqual(expected, result);
    }
```
**Expected behavior**
The following test above should pass.

**Additional context**
https://github.com/rapidsai/cudf/issues/4635

**Comment by razajafri** [comment]
This is linked to https://github.com/rapidsai/cudf/issues/4635

**Comment by vuule** [comment]
Similar to [#4635](https://github.com/rapidsai/cudf/issues/4635), the current behavior seems consistent with C++ NaN semantics, where NaN does not compares equal to NaN. Based on the discussion [#4760](https://github.com/rapidsai/cudf/issues/4760) this is the desired behavior for libcudf.

**Comment by jlowe** [comment]
If the original need is for `contains` to support NaN, then we can emulate that behavior with something like this:
1. call `contains` to produce boolean mask X
1. call `is_nan` on the "needles" and reduce this mask to a single boolean to determine if any needles were NaNs.  If no NaN "needles" then return mask X
1. Otherwise call `is_nan` on "haystack" to produce boolean mask Y
1. logical-OR mask X and Y together to produce the result.
