### ISSUE TITLE
[BUG] dask_cudf.read_csv to read large CSV file (more than 4GB) failed with  cudaErrorMemoryAllocation: out of memory error

### ISSUE THREAD

**Issue by ljj10298497** [rapidsai/cudf#4646]
using dask_cudf.read_csv to read single large CSV file (more than 4GB) or bunch of CVS files (total size more than 4GB) failed with the error message " parallel_for failed: cudaErrorMemoryAllocation: out of memory"

code as below:

import os
import numpy as np
import pandas as pd
import cudf
import dask_cudf
ddf = dask_cudf.read_csv('data/*.csv')
ddf.compute()
ddf.head(5)

The file size as below:
(rapids) root@1ede3bdf99b6:/rapids/notebooks/data# ls -alh
total 13G
drwxr-xr-x 2 root root 4.0K Mar 20 02:57 .
drwxrwxrwx 1 root root 4.0K Mar 22 11:01 ..
-rw-r--r-- 1 root root 2.2G Mar 20 02:47 foo.csv
-rw-r--r-- 1 root root 2.2G Mar 20 02:56 foo1.csv
-rw-r--r-- 1 root root 2.2G Mar 20 02:56 foo2.csv
-rw-r--r-- 1 root root 2.2G Mar 20 02:57 foo3.csv
-rw-r--r-- 1 root root 2.2G Mar 20 02:57 foo4.csv
-rw-r--r-- 1 root root 2.2G Mar 20 02:57 foo5.csv

The dask_cudf version is 
print('Version:', dask_cudf.__version__)
Version: 0.12.0b+2032.gab97331

I am using a server with 8 V100 (16GB) GPUs.

Thanks!
Jianjun

**Comment by ayushdg** [comment]
Thanks for raising the issue. 

Couple of updates that could help:
- The current snippet does not create a cluster. If a cluster is not created, dask_cudf will default to single GPU. You can find snippets on how to use a `LocalCUDACluster` [here](https://rapidsai.github.io/projects/cudf/en/0.12.0/10min.html#Dask-Performance-Tips).

- `ddf.compute` is an operation that triggers an eager execution i.e. dask will read the csv files using all gpus in the cluster and then move that result over to a single cudf dataframe on one gpu. Since the overall memory used by the csv files is big, it might fail if all your data does not fit on one gpu.

**Comment by ljj10298497** [comment]
Thanks Ayush. Follow your guide, large file reading works fine with multiple GPU now. Code snippet below (however dask_cudf.read_csv() need a "file" prefix so is more stable and I found some times for large file, direct read to GPU memory could lead to data corruption. ):

I will close this one. Thanks again!

from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()
client = Client(cluster)
client

import dask_cudf
ddf = dask_cudf.read_csv('file://data/*.csv')
ddf = ddf.persist()
wait(ddf)
