### ISSUE TITLE
[BUG] cudf.to_csv overwrites files even when opened in append mode

### ISSUE THREAD

**Issue by ntadimeti** [rapidsai/cudf#4715]
**Describe the bug**
cudf.to_csv() is overwriting files even when the file object is opened in append mode.

**Steps/Code to reproduce bug**
```
import cudf

df = cudf.DataFrame()
df["key"] = [0,1]
df["value"] = [5,6]

#create the file
with open("sample-cuda.csv", "a+") as outfile:
    df.to_csv(outfile)
#append to the above file
with open("sample-cuda.csv", "a+") as outfile:
    df.to_csv(outfile)

#convert to pandas and append to new file
df = df.to_pandas()
with open("sample.csv", "a+") as outfile:
    df.to_csv(outfile)
#append to above file
with open("sample.csv", "a+") as outfile:
    df.to_csv(outfile)
```
**Expected behavior**
sample-cuda.csv should have the following output : 
```
,"key","value"
0,0,5
1,1,6
,"key","value"
0,0,5
1,1,6
```
instead the output is this: 
```
,"key","value"
0,0,5
1,1,6
```
Running cudf - 0.12 installed from conda.

**Comment by vuule** [comment]
Currently, Python `to_csv` API has a `path` parameter, whereas Pandas has `path_or_buf` (as does `cudf.read_csv`). So passing a buffer-like object is not really supported.
In the implementation, the `path` parameter is converted to a string and passed to C++ implementation. This means that information about how the file was opened is lost before the parser is created.

**Comment by trevorsm7** [comment]
It looks like the file mode could be queried here here as `path.mode` and an arg for write/append could be piped through to the `csv_write_arg` struct.
https://github.com/rapidsai/cudf/blob/4e153a5fecea690fe0b708e4a60a5c020e6f4173/python/cudf/cudf/io/csv.py#L118-L119

**Comment by trevorsm7** [comment]
Implementing this for libcudf++ will depend on https://github.com/rapidsai/cudf/pull/5058 (which itself depends on https://github.com/rapidsai/cudf/pull/4484)

I'm thinking that a better way to implement this may be to query the file descriptor from the buffer (`path.fileno()`) rather than the filename and pass this and the mode (`path.mode`) to `fdopen()` from `stdio.h`. This would additionally work for non-file buffers like `sys.stdin` and `sys.stdout`.

Oh! I just noticed `make_sink_info()` from this recently submitted PR https://github.com/rapidsai/cudf/pull/5061 which creates a `data_sink` wrapper around an `IOBase`. @benfred do you think `make_sink_info()` would be suitable for handling files opened in append mode, as in the description of this bug?
https://github.com/rapidsai/cudf/blob/01d35741d1ea296fdcd7e44c03bfd7292533ec9e/python/cudf/cudf/_lib/io/utils.pyx#L43-L69

**Comment by benfred** [comment]
@trevorsm7 make_sink_info will work for files opened in append mode (as well as any other python file- like object like BytesIO etc). If you can hook use this to create a sink_info that the cpp csv_writer uses that should fix this bug.

It doesn't look like csv is using the sink_info type yet (just parquet/orc are afaict) - but once https://github.com/rapidsai/cudf/pull/5058 is merged this should be really easy to integrate (1-2 line change to call make_sink_info instead of directly instantiating sink_info).  We should also probably hook this into orc file writing to be consistent too

**Comment by benfred** [comment]
To support appending to files opened in text mode,  I think we will have to change the  make_source_info implementatio- to use the underlying binary write buffer instead of trying to write binary to the text file.

A change like this:

```diff
diff --git a/python/cudf/cudf/_lib/io/utils.pyx b/python/cudf/cudf/_lib/io/utils.pyx
index 30dc9e6eb..44776e3ab 100644
--- a/python/cudf/cudf/_lib/io/utils.pyx
+++ b/python/cudf/cudf/_lib/io/utils.pyx
@@ -7,6 +7,7 @@ from libcpp.pair cimport pair
 from libcpp.string cimport string
 from cudf._lib.cpp.io.types cimport source_info, sink_info, data_sink, io_type
 
+import codecs
 import errno
 import io
 import os
@@ -42,7 +43,12 @@ cdef source_info make_source_info(src) except*:
 
 # Converts the Python sink input to libcudf++ IO sink_info.
 cdef sink_info make_sink_info(src, unique_ptr[data_sink] * data) except*:
-    if isinstance(src, io.IOBase):
+    if isinstance(src, io.TextIOBase)
+        if codecs.lookup(src.encoding).name != "utf-8":
+            raise NotImplementedError(f"Unsupported encoding f{src.encoding}")
+        data.reset(new iobase_data_sink(src.buffer))
+        return sink_info(data.get())
+    elif isinstance(src, io.IOBase):
         data.reset(new iobase_data_sink(src))
         return sink_info(data.get())
     elif isinstance(src, (int, float, complex, basestring, os.PathLike)):
```

should make this iobase_data_sink class work with text files though (even opened in append mode).
