### ISSUE TITLE
[BUG] dask_cudf.read_paquet gather statistics=None causes slow_down

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#4724]
**Describe the bug**

`dask_cudf.read_paquet` with the default `gather statistics=None` is much slower compared to 
`gather_statistics = False` . 

**Steps/Code to reproduce bug**

```python
%time x = dask_cudf.read_parquet(fn,split_row_groups=False,gather_statistics=None)
Wall time: 6.13 s
```

```python
%time x = dask_cudf.read_parquet(fn,split_row_groups=False,gather_statistics=False)
Wall time: 159 ms
```

**Expected behavior**
I would expect similar performance.

**Comment by rjzamora** [comment]
@VibhuJawa - Using `gather_statistics=False` guarentees that the statistics will not be gathered, and that the metadata will not be parsed at all.  When `gather_statistics=None`, dask will gather statistics if it finds a `"_metadata"` file.  Is there a metadata file present in this case?

**Comment by VibhuJawa** [comment]
> @VibhuJawa - Using `gather_statistics=False` guarentees that the statistics will not be gathered, and that the metadata will not be parsed at all. When `gather_statistics=None`, dask will gather statistics if it finds a `"_metadata"` file. Is there a metadata file present in this case?

Nope it is not .  May be there is an issue with code-path when `_metadata` is absent ?

**Comment by rjzamora** [comment]
Actually - Just looked through the dask code again.  You really do need to be explicit about setting `gather_statistics=False` if you absolutely don't want dask to try to parse the metadata.  In your case, the dataset is simple, and you aren't using any filters, so you can definely set `gather_statistics=False`.  You should think of this as an optimization that is specific to your dataset, since you **don't** have a `"_metadata"` file, but also don't really need anything more than the file paths to "plan" the parellel write.

**Comment by VibhuJawa** [comment]
> Actually - Just looked through the dask code again. You really do need to be explicit about setting `gather_statistics=False` if you absolutely don't want dask to try to parse the metadata. In your case, the dataset is simple, and you aren't using any filters, so you can definely set `gather_statistics=False`. 

Got it , Thanks a lot for your work on this.  

Just to be sure in case/when we have  a `_metadta` file , gather_statistics=None will become faster ?

**Comment by rjzamora** [comment]
> Just to be sure in case/when we have a _metadta file , gather_statistics=None will become faster ?

Yes, the "planning" phase that you are timing above will always be fastest if you use `gather_statistics=False`, because you are literally skipping the need to open any files or read any metadata at all.  However, this limits your options for the actual read phase.

If you use `gather_statistics=True/None` and have a `"_metadata"` file, the client will only need to open that single file to "plan" the parallel read, and will only need to parse the metadata from that one file if the statistics are gathered.  If you **don't** have that `"_metadata"` file, the client will end up touching every file in the dataset during the "planning" phase (just to generate the pyarrow `dataset` object).

That said - I will play around with the logic a bit and see if/when it is safe to avoid the problematic behavior for `gather_statistics=None`

**Comment by VibhuJawa** [comment]
Thanks a lot for the explanation, it makes sense .  


Feel free to close the issue from my end.

**Comment by rjzamora** [comment]
Thanks @VibhuJawa - I will close this for now.  However, I do think there are some serious problems with the way the `ParquetDataset` object is initially constructed in dask.dataframe.  So, thank you for motivating me to poke around in this part of the upstream code again.  Although I originally wrote the code I am complaingin about, I was a bit confused about certain behaviors of the pyarrow at the time (and I now see that some of the logic is "wrong"/questionable).

Overall, the problems with the dask code should not really affect your use case, nor should it affect my general advice: If you don't need statistics/filtering, use `gather_statistics=False`.  If you do want statistics/filtering, pass the name of a directory to `read_parquet` (not a list of files).  If possible, include a `"_metadata"` file within this directory.
