### ISSUE TITLE
[BUG] Timestamp casting to Datetime from `us` to `ns` results in wrong value

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#4784]
**Describe the bug**
Casting a timestamp of `us` to datetime `ns` returns wrong value

**Steps/Code to reproduce bug**
```
>>> import cudf
>>> s = cudf.Series('2016-01-01 00:00:03.333333')
>>> s1 = s.astype('datetime64[ns]')
>>> print(s1)
0   1970-01-01
```

**Expected behavior**
```
>>> import pandas as pd
>>> s = pd.Series('2016-01-01 00:00:03.333333')
>>> print(s.astype('datetime64[ns]'))
0   2016-01-01 00:00:03.333333
dtype: datetime64[ns]
```

**Comment by rgsl888prabhu** [comment]
This is happening because libcudf++ is expecting `9` characters in place of `%f` but we have only `6`, so it skips [here](https://github.com/rapidsai/cudf/blob/627ebc51cc48188ea06c801bc1924e72060789ed/cpp/src/strings/convert/convert_datetime.cu#L214), which leads to some issues . One of the solution that @davidwendt suggested was to add number chars present in subsecond position in timestamp to be updated in expected format like `%6f` if timestamp is `2016-01-01 00:00:03.333333`, so that additional digits can be added later, currently this is not supported in libcudf side and need to be modified to accommodate this. But would like to keep the discussion open for other solutions.

**Comment by davidwendt** [comment]
One limitation here is that the libcudf date-time parser uses the timestamp column type to decide the number of digits to read for the `%f` specifier. This means that if the timestamp type indicates `ns` then 9 digits are expected in the string for `%f`. And if the timestamp is `ms` then only 3 digits are read from the string. Otherwise 6 digits are assumed regardless of timestamp unit -- days, seconds, etc. 

This is problematic because it prevents parsing the same string into different timestamp types. This problem is highlighted by this issue where we simply wish to cast a strings column to any timestamp type column. One possible solution is to match the timestamp units to the format and then cast the results to the desired timestamp column. This would create an intermediate column that is thrown away.

I recommend removing the format/timestamp-type coupling and completely honor the `%f` specifier which should always match the string format regardless of output type. Since the `%f` only officially supports 6 digits I further propose we support an augmented set of specifiers: `%3f` `%6f` and `%9f` so that the number of digits can match the date-time strings more correctly.

Also, I should point out that this coupling is also in the timestamp to string conversion and should be removed from there for the same reasons.
