### ISSUE TITLE
[DOC] Create example C++ application using cudf APIs

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#4824]
Some users want to integrate existing C++ codebases with cudf but are finding it difficult to get started.

We should create & document an example application that uses libcudf++ to:
1. Read a CSV file
2. Run a filter then groupby and aggregation
3. Write results to CSV

**Comment by jdye64** [comment]
For reference I placed the example [here](https://github.com/jdye64/libcudf-examples) and it is completed now.

**Comment by jdye64** [comment]
@harrism @jrhemstad I wanted to get your opinions on creating a location in the existing codebase where we could have some tangible C++ examples. Couple of questions in my mind.

1. Does it actually live in cudf repo or another location? Seems to me that cudf repo is a good spot due to supporting artifacts already being there.
2. Should we make multiple smaller examples/cmake projects or a more "uber" approach. I'm guessing small but once again wanted input.
3. Should be provide a CMake "FindCUDF.cmake" somewhere in the parent project?

Just wanted to kick off the discussions as I know we wanted to add more docs / examples in the upcoming release.

**Comment by jrhemstad** [comment]
I'd follow what Thrust does and have an `examples` directory: https://github.com/thrust/thrust/tree/master/examples

**Comment by jdye64** [comment]
I like that idea as well. @harrism how do you feel about that? I will of course make a more formal proposal issue for this but just wanted to get a gauge for thoughts here first.

**Comment by harrism** [comment]
Agree. I think for C++ examples it should be cudf/cpp/examples

**Comment by harrism** [comment]
That's a pretty complex example. It would be nice to start with simpler examples -- say 10-15 lines of code.

**Comment by yjhjstz** [comment]
how to convert cudf::column to C POD types ?
