### ISSUE TITLE
[QST] ai.rapids:cudf:cuda10 for CUDA 10.2

### ISSUE THREAD

**Issue by schernolyas** [rapidsai/cudf#4874]
Hi!
I need artifact
`<dependency>
        <groupId>ai.rapids</groupId>
        <artifactId>cudf</artifactId>
        <classifier>cuda10-1</classifier>
        <version>0.9.2</version>
    </dependency>`
for CUDA 10.2. How I can build it?

**Comment by schernolyas** [comment]
Or ... can someone build and push the artifact to central maven repository? Please ...

**Comment by jlowe** [comment]
`<classifier>cuda10-1</classifier>` indicates it is built for CUDA 10.1.  The cudf 0.9.2 release does not support CUDA 10.2.  CUDA 10.2 is supported starting with 0.13.

Note that multiple CUDA runtime versions can be installed on a system because the kernel driver is guaranteed to be backwards compatible.   Therefore the 10.2-compatible driver also supports running applications using the 10.1 runtime.  The easiest solution may be to install CUDA 10.1 on the system somewhere and update `LD_LIBRARY_PATH` if necessary so the application can find the 10.1 libraries.

**Comment by schernolyas** [comment]
Hi @jlowe !
Thank you very much for the comment.
