### ISSUE TITLE
[BUG] Dask cudf Read_parquet does not partition the data based on the variable `npartitions`

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cudf#5012]
Code:
```
import os
import numpy as np
import pandas as pd
import cudf
import dask_cudf
df = cudf.DataFrame({'a': list(range(2000)),
                     'b': list(reversed(range(2000))),
                     'c': list(range(2000))})
df.to_parquet('temp_parquet')
check = dask_cudf.read_parquet('temp_parquet', npartitions=2)
print(check)
print(check.compute().shape)
```
Output:
```
<dask_cudf.DataFrame | 1 tasks | 1 npartitions>
(2000, 3)
```

The dask_cudf read_parquet seems to return the dask_cudf.Dataframe with the same number of partitions it was created with.
```
import os
import numpy as np
import pandas as pd

import dask.dataframe as dd
import cudf

import dask_cudf

nrows = 40
npartitions = 15
df = pd.DataFrame(
    {
        "x": [i * 7 % 5 for i in range(nrows)],  # Not sorted
        "y": [i * 2.5 for i in range(nrows)],
    },
    index=pd.Index(range(nrows), name="index"),
)  # Sorted
ddf = dd.from_pandas(df, npartitions=10)

ddf.to_parquet("file",
               engine="pyarrow",
               )

read_ddf= dask_cudf.read_parquet('file')
print(read_ddf)

less_partitions = dask_cudf.read_parquet('file', npartitions=5)
print(less_partitions )
```

Output :
```
<dask_cudf.DataFrame | 10 tasks | 10 npartitions>
<dask_cudf.DataFrame | 10 tasks | 10 npartitions>
```

**Comment by ayushdg** [comment]
`npartitions` is not currently supported by upstream `dask.dataframe.read_parquet`. ([Doc](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_parquet))

The existing behavior is `npartitions` will either be `num_files` or `num_row_groups` or something in between (if chunksize is given), based on the arguments: `gather_statistics`, `split_row_groups` and `chunksize`. 

One possibility could be repartitioning after reading: `read_ddf.repartition(npartitions=5)`.

cc: @rjzamora Since he's more familiar with this and might have something to add.

**Comment by rjzamora** [comment]
I'm going to close this for now since `npartitions` is not a supported `read_parquet` option (and so this is not really a "bug"). 
 With that said, it probably makes sense to throw an error or warning if the user tries to pass this option.  The upstream-dask routine passes kwargs through to the backend, so this is probably a case where a bad argument is silently ignored.

In addition to the workarounds mentioned above, it is also possible to pass an integer value to `split_row_groups`.  Each partition will then correspond to `split_row_groups` row-groups (as long as they are stored contiguously in the same file).
