### ISSUE TITLE
[FEA] Make DataFrame.clean_renderable_dataframe() and DataFrame.get_renderable_dataframe non-public methods

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5164]
Currently, the helper methods `DataFrame.clean_renderable_dataframe` and `DataFrame.get_renderable_dataframe` appear as part of the public API. They should be converted to underscore methods `_clean_renderable_dataframe` and `_get_renderable_dataframe` instead.

**Comment by Liamdoult** [comment]
I would like to attempt this problem, is it available?

**Comment by kkraus14** [comment]
> I would like to attempt this problem, is it available?

Absolutely, a pull request would be very welcome!

**Comment by Liamdoult** [comment]
Preface: This comment is mostly unrelated to the issue. I am not sure if there is a better place to ask this question.

I have made the changes but would like to test locally. I usually use WSL as my dev environment which does not support CUDA. In an attempt to work around this (using windows), I attempted to build the application using Docker. However, I am getting the following build errors:
```
[ 95%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/ipc/reader.cc.o
[ 96%] Building CXX object src/arrow/CMakeFiles/arrow_objlib.dir/ipc/json_simple.cc.o
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/build.make:95: recipe for target 'src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_base.cc.o' failed
make[5]: *** [src/arrow/dataset/CMakeFiles/arrow_dataset_objlib.dir/file_base.cc.o] Error 4
make[5]: *** Waiting for unfinished jobs....
g++-5: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
```

My assumptions are:
1) That I do not need `nvidia-docker2` anymore [Based on the Nvidia Docker repository]( https://github.com/NVIDIA/nvidia-docker). "Note that with the release of Docker 19.03, usage of nvidia-docker2 packages are deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime."
2) That the build process should run within the container.

I was wondering if this is:
a. A general docker build issue, or
b. a circumstance of my environment, or
c. an actual bug?

Finally, do you think using the docker image would be a viable method to test my changes or should I attempt to use CMD/PowerShell?

**Comment by kkraus14** [comment]
That error typically means that you ran out of memory during compilation. This is a bit surprising because this is happening before we even get to the libcudf build and is happening in building Arrow cpp libraries.

**Comment by Liamdoult** [comment]
It is not a memory limitation of my system as during the build process (until and including the failure) my system does not come close to running out of memory:
![image](https://user-images.githubusercontent.com/12427907/82469984-aa4e2a80-9abc-11ea-8f5f-e5d424c105ea.png)

Perhaps it is a memory limitation of the Docker build process or WSL, but I have not heard of such.

**Comment by kkraus14** [comment]
Are you using Docker or WSL? If using Docker I believe there's memory limits set in the Docker Desktop application.
