### ISSUE TITLE
[FEA][DISCUSSION] IntervalDtype and IntervalIndex

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#5376]
**Is your feature request related to a problem? Please describe.**
Currently we don't support [IntervalDtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.IntervalDtype.html) or [IntervalIndex](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.IntervalIndex.html) which are quite useful when you want to convert a data to a range of values. For example histogram, [value_counts](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.value_counts.html) with bins and [cut.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html). 

The Interval object would have
> left -> left_edge
> right -> right_edge
> closed -> which edge/both edge is closed

example `Interval(0, 1, closed='right')` would imply (0, 1]

**Describe the solution you'd like**
May be we can have something similar to string column, where child columns will have the left and right intervals with `closed` being part of column object to track which side is closed.

But if we want different intervals with different side closed under one column, that would be an issue.

Any ideas/suggestions are welcomed.

**Comment by kkraus14** [comment]
So `IntervalIndex` is backed by an `IntervalArray` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.arrays.IntervalArray.html) which controls the `closed` behavior at the column level instead of individually for each element. It's a bit strange to me that this is control at the `IntervalArray` object instead of the `IntervalDtype` object, but that's what Pandas does.

For us to implement this, I think we could likely reuse `IntervalDtype` for our dtype, and then for an `IntervalColumn` (our version of `IntervalArray`), we could have two children integer columns for the left / right values in each interval.

The API footprint looks relatively small for interval types where we can likely implement all of it using our existing primitives from what I can see. The challenge will be round tripping things through libcudf as two separate integer columns.

**Comment by harrism** [comment]
> The challenge will be round tripping things through libcudf as two separate integer columns.

Do you need to operate all operations supported on Series on this dtype?

**Comment by kkraus14** [comment]
> Do you need to operate all operations supported on Series on this dtype?

I don't believe so but don't quote me on it. In general I think we'd like to just take a stab at implementing this on the Python side first using existing primitives and once we have an idea of what things look like we can re-evaluate moving it down to libcudf (if there's demand outside of cuDF Python or big performance reasons to do so).

**Comment by harrism** [comment]
Sounds good. Adding even more types to libcudf right now is not attractive. :)

**Comment by kkraus14** [comment]
Took a quick pass and looks like binary ops / reductions throw for this dtype entirely so we should be good just treating this as two separate integer / float columns and defining ops using existing primitives.

**Comment by kkraus14** [comment]
Reopened as #7182 will address IntervalIndex

**Comment by kkraus14** [comment]
This is resolved between #6984 and #7182. Great work @marlenezw!
