### ISSUE TITLE
[BUG] cudf.Series.str.ngrams_tokenize performance appears slower than nvtext.ngrams_tokenize

### ISSUE THREAD

**Issue by Garfounkel** [rapidsai/cudf#5412]
**Describe the bug**
cudf.Series.str.ngrams_tokenize performance appears slower than nvtext.ngrams_tokenize.

**Steps/Code to reproduce bug**
Unfortunately I only noticed this with a specific dataset and I was not able to reproduce it with generated data. Here is a link to download that dataset as a [csv file (4.8Mb)](https://storage.googleapis.com/dataset-uploader/bbc/bbc-text.csv).

With the dataset downloaded and named `bbc-text.csv`:

```python
import pandas as pd
from cudf import Series
import nvtext


df = pd.read_csv('bbc-text.csv')

s = Series(df['text'])

print("nvstrings:", flush=True)
%time nvtext.ngrams_tokenize(s._column.nvstrings)
# nvstrings:
# CPU times: user 736 ms, sys: 484 ms, total: 1.22 s
# Wall time: 1.22 s

print("cuDF:", flush=True)
%time s.str.ngrams_tokenize()
# cuDF:
# CPU times: user 2.78 s, sys: 1.7 s, total: 4.49 s
# Wall time: 4.49 s
```

**Expected behavior**
Performance should be more closely aligned with nvstrings.

**Comment by kkraus14** [comment]
cc @davidwendt

**Comment by harrism** [comment]
In addition to improving perf if possible, we should use this to guide creating a unit benchmark for this feature.

**Comment by davidwendt** [comment]
Thanks for providing the data file. This 'text' column is 2225 rows with an average of 2263 bytes per row. Overall the strings appear to be all lower-case along with some numbers and a few symbols. 

All of the characters are ASCII (single-byte) except for one. The `£` character is a 3-byte (0xc2a30a) UTF-8 character that appears 1403 times in the column. In general, this is no big deal but can become significant for both nvstrings and cudf strings if the multi-byte character appears within long strings as in this case.

The nvstrings implementation handles this case slightly differently by storing extra information about each string in order to try to more quickly navigate bytes/characters. This overhead does not exist in the cudf version and I believe this is why the performance difference exists between the two.

One possible workaround here is to replace the character with another ASCII character temporarily. For example, the data does not include an upper-case 'L' character so you could replace the multi-byte character with a single-byte one using `s = s.str.replace('£','L',False)`

You should see that both nvtext and cudf strings `ngrams_tokenize` execute much faster (sub-second on my machine) using this modified string. Once the ngrams are created, you can change the 'L' back to  '£' in the resulting column of ngrams to get the original result:

```
import cudf
df = cudf.read_csv('bbc-text.csv')
s = df['text']
s = s.str.replace('£','L',False)
ngrams = s.str.ngrams_tokenize()
ngrams = ngrams.str.replace('L','£',False)
```

Even with the extra replace steps, this is still faster than without them.

Anyway, I'm still looking at this but thought I would share a possible workaround that hopefully works for you.
