### ISSUE TITLE
[FEA] create cmake 'find_package' module for cudf

### ISSUE THREAD

**Issue by jdye64** [rapidsai/cudf#5569]
Using cudf in a third party application currently relies on anaconda. Several third party applications would like to use cudf but not use anaconda. We should offer a cmake 'find_module' file named. **FindCUDF.cmake** that would allow thirdparty applications to easily include cudf into their cmake applications using cmake 'find_package(cudf)'

**Comment by germasch** [comment]
To leave my $.02 here: If one wants to support adding an existing library to downstream cmake projects via `find_package(CUDF)`, a find module (`FindCUDF.cmake`) is the only option.

But it has lots of drawbacks, most clearly that such a find module needs to be integrated into downstream projects (or into cmake itself) and will almost inevitably become out-of-sync with the latest upstream CUDF over time.

The alternative is to update future CUDF to install cmake config files (`cudf-config.cmake`), which will allow a downstream package to use the install simply via `find_package(CUDF)` without requiring a find module as part of the downstream app.

I'm saying this because, as you might guess, I regard the alternative as much preferable. In fact, I'm working on doing this for RMM. I have this working in a proof-of-concept fashion -- the major issue is about handling dependencies of RMM correctly.  That's an issue that's essentially independent of how one supports `find_package`, though. 

The main thing is that `find_package(rmm)` also needs to pull in dependencies, and that can either be done by installing the dependencies together with rmm or by pulling in external installs. In most cases, I think it's not desirable to install, e.g., spdlog as part of rmm, since a downstream app may already be using spdlog, and one could easily end up with two different versions in the same build.

**Comment by vyasr** [comment]
cudf now exports a CMake config file (via rapids-cmake) so it is discoverable via `find_package`.
