### ISSUE TITLE
[FEA] libcudf `dictionary` types to support only `unsigned types` in indices. 

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#5576]
**Describe the bug**
As per the [discussion] (https://github.com/rapidsai/cudf/pull/5501#discussion_r441954317), `dictionary` should be supporting only unsigned type indices as it would provide wider range of values.

**Comment by kkraus14** [comment]
Note that supporting **only** unsigned types in dictionary columns could introduce overheads or additional complexity in things like IO readers / writers where their dictionary types use signed integers.

@devavret @vuule how do Parquet / ORC handle dictionary encoded columns? Do they use signed or unsigned integers in representing them?

We know that in Apache Arrow (C++/Python at least) dictionary types currently require signed integers, which means we need to pay the overhead to convert our unsigned types into signed types to go to/from Arrow. Pandas also uses signed integer types.

**Comment by vuule** [comment]
AFAICT Parquet is using unsigned indices. 
Took a quick look at ORC too, and it seems like it also uses unsigned indices.

**Comment by devavret** [comment]
IIRC, ORC doesn't have first class support for unsigned integers, presumably because java doesn't either. Not sure about dictionary indices. Let me check

**Comment by jrhemstad** [comment]
@jlowe @revans2 
If we only supported unsigned indices for dictionary columns, what that preclude their use in Java/Spark?

**Comment by jlowe** [comment]
I'm a bit confused about the use-case.  Having dictionaries with more than 2^31 dictionary entries implies we're building libcudf columns with more than 2^31 rows to fully leverage that dictionary.  I didn't think libcudf supported columns that large because Arrow doesn't support column buffers that large.  With that many dictionary entries, it seems like a case of a column that shouldn't have been dictionary-encoded because we would be sparsely referencing it.

Java does not have direct support for unsigned types.  It can wield them, but the application code has to go out of its way to interpret them (e.g.: using `java.lang.Integer.toUnsignedLong` to interpret 32-bits as an unsigned value).  Apache Spark supports a dictionary-encoded column but the [indices are used directly as a Java array index](https://github.com/apache/spark/blob/master/sql/core/src/main/java/org/apache/spark/sql/execution/columnar/ColumnDictionary.java#L41) and thus will be treated as a signed value.  The same is true for [Parquet's dictionary code in Java](https://github.com/apache/parquet-mr/blob/master/parquet-column/src/main/java/org/apache/parquet/column/values/dictionary/PlainValuesDictionary.java#L165).

We're not using libcudf's dictionary-encoded columns nor currently have plans to use them.  Therefore I don't want to impede progress for those that are.  When we convert from GPU to CPU processing in Spark we currently also have to convert from columns to rows.  That means we're not leveraging Spark's columnar representation anyway (and even if we did, it would need to be converted immediately from columns to rows for the rest of Spark's CPU processing).  Since we're doing the column-to-row conversion before we handoff to Apache Spark's CPU code, we could be aware of the dictionary index interpretation and handle it appropriately if and when we start using libcudf's dictionary columns.

**Comment by revans2** [comment]
@jlowe I think the use case is for a dictionary of byte keys if we know that there are few enough entries to support it. And an unsigned byte key would have a larger range than a singed byte key. Same for short.  Once you get to int I agree there is no point.

**Comment by revans2** [comment]
Sorry I didn't read the title properly yes I agree if you need a 32-bit dictionary key it is probably not worth signed vs unsigned, even for a byte column.

**Comment by jlowe** [comment]
Ah yes, that makes sense.  Same then applies, we would need to be aware of how to interpret the dictionary index, either casting unsigned to a 32-bit int when converting to Spark CPU's columnar format or when converting from columns-to-rows directly as we do today.  It's straightforward either way.

**Comment by kkraus14** [comment]
To be clear this conversation isn't just for `dictionary32` but for all future dictionary types in libcudf. We'll want to have an equivalent to `dictionary8` and `dictionary16` as well.

**Comment by kkraus14** [comment]
Updated title

**Comment by revans2** [comment]
The main reason I see issues with us trying to use dictionary types generically is that Spark is distributed.  This causes two issues. 

First is that we split apart and combine tables all of the time as a part of the shuffle.  When we tried to do this with string dictionaries we saw all kinds of slowness because it required combining the data and rewriting the dictionary each time it happened. If that was cheap we would be interested in using it.

The second issue is knowing when we can and when we cannot use it.  Spark does not reliably keep track of the cardinality of a column.  Without that, we don't know if we are wanting memory/computation by using a dictionary or not.  I would see some value in having the parquet and orc readers optionally produce dictionary columns, but unless the computation for each operator is smart enough to know when its output should be a dictionary and when it should not we are not going to have much value in using it because we have even less knowledge about the cardinality of the output data.
