### ISSUE TITLE
[BUG]cuDF-0.14's per_thread_default_stream DO NOT work well

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/cudf#5598]
**Describe the bug**
the cuDF cpp code was build with per_thread_default_stream, then we test the read_parquet() + aggregate() cpp interface, 
the read_parquet()'s ptds works well,  but the agg() call a _kernel_agent() funtion (i found it in thrust library), the _kernel_agent() ws executed in the legacy deafult stream, which i think it is a bug, since we want each thread to run in parallel, because each host thread process different data (no sync was needed between them)

the thrust was provided by cuda-10.2

**Comment by jrhemstad** [comment]
This was a Thrust bug that was fixed here: https://github.com/thrust/thrust/pull/1128

This fix is not present in any of the toolkit versions. 

cuDF was updated to pull in the latest Thrust here: https://github.com/rapidsai/cudf/pull/5414

Since you are using Thrust from 10.2, you will not see this fix.
