### ISSUE TITLE
[QST] Bugfix release schedule?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#562]
What is our release schedule for bugfix releases?

I was sitting down with @cmgreen210 and we ran into the issue where `merge` was printing out dtypes.   
 This made things pretty unusable for him.  I believe that this has been resolved on the development branch but there hasn't yet been a release.  To resolve this we ended up hacking up a bit in his local cudf installation, but it was ugly.

Are we planning to do a 0.4.1 release, or are we waiting until January to do a 0.5.0 release?

More generally, what is the time cost to doing a release?  How quickly can we push these out?

**Comment by mrocklin** [comment]
To be a bit more incendiary, I'll suggest that if releasing is somewhat cheap then we release much more frequently.  Perhaps at the end of every week.  I think that a rapid cadence like this is appropriate for an early stage project like `cudf` because we'll often be in a situation where master has more bugs fixed than bugs subtly introduced.

**Comment by mrocklin** [comment]
> The challenge here is we are still in our first release of trying to do a more release driven development process. The framework of which has been just agreed upon and we are still implementing. I would prefer that we give ourselves time to work out the growing pains and focus on where there could be improvements in the following release. Changing the process again, while we are in the middle of implementing it, I don't think will be productive.

Fair enough.  I also acknowledge that I'm jumping onto a system that folks here have been keeping running and I'm shouting "hey wait, lets do things differently!" without a ton of context.  That being said, respectfully, I'm going to keep shouting that for a short time.  Please forgive me and feel free to ignore me for the next few weeks.  Mostly I want to put ideas out there.  I have no expectation that we act on them any time in the near future (or ever).

> In addition, I have it planned to release containers more-frequently

FWIW containers don't significantly affect the users I've encountered, who seem to conda install onto their local environment.

> The second set, are updated nightly allowing developers to use the latest development code; like the nightly conda packages

Nightly conda packages would help much more.

>  The challenge with trying to do a v0.4.1 release, to expose the bug fixes we made, is cherry picking and figuring out which fixes belong in v0.4.1 and which need to wait until v0.5.

Is there somewhere I can go to learn more about the choice for having a development branch other than master?  I suspect that this discussion happened in a slack channel somewhere lost in time or in person, but I thought I'd ask just in case.  I'm slightly confused by this choice.

> For v0.4.X releases in our current plan these are reserved for hotfixes which are a "bug that affects the majority of users for which there is no reasonable workaround."

I think that we're still young enough that we're going to have these constantly for a while.

From my perspective the fact that `join` prints things is a bug that would cause an immediate bugfix release all on its own.  The fact that bugs like this exist are totally understandable (it's a young project) but it's important that we be able to respond to them quickly with new bugfix releases.

> As far as time costs with the releases, it becomes costly due to the updates to the web sites, containers, documentation, and testing to ensure the containers & notebooks work as described. Last release was a heavy lift by ops and many of the dev team over the course of 2+ days. While I have been able to automate some of the process, not every process is able to be automated. Especially those that need a developer to walk through and use the container/notebook and check the documentation step-by-step.

I suggest that for a library this young this level of process might not be ideal.  We might consider losing some of these features (container builds, complex notebooks, etc.) for a while until things clean up.  In an idealized world I would ask ops to provide a generic CI service and then I would ask developers to create testable examples and notebooks.  I would trash notebooks that require serious by-hand testing.

Alternatively, maybe we only update those materials every 0.X.0 release and forget about them on point releases?

*Again, thank you for listening to this.  I definitely don't expect any action on this near-term, but wanted to start pushing up some ideas and have this conversation early.*

**Comment by raydouglass** [comment]
> Fair enough. I also acknowledge that I'm jumping onto a system that folks here have been keeping running and I'm shouting "hey wait, lets do things differently!" without a ton of context. That being said, respectfully, I'm going to keep shouting that for a short time. Please forgive me and feel free to ignore me for the next few weeks. Mostly I want to put ideas out there. I have no expectation that we act on them any time in the near future (or ever).

Feedback from someone who has run a successful open source project is always appreciated. Please don't take us ignoring advice as a negative. In many cases, we would likely agree with you, but it's just not possible currently.

> Is there somewhere I can go to learn more about the choice for having a development branch other than master? I suspect that this discussion happened in a slack channel somewhere lost in time or in person, but I thought I'd ask just in case. I'm slightly confused by this choice.

There were some calls where we decided to use a modified gitflow development approach. The developer docs will fully outline the process. Unfortunately, the docs are still being written.
> From my perspective the fact that `join` prints things is a bug that would cause an immediate bugfix release all on its own. The fact that bugs like this exist are totally understandable (it's a young project) but it's important that we be able to respond to them quickly with new bugfix releases.

So, Mike used my line about hotfixes: "bug that affects the majority of users for which there is no reasonable workaround." So...
1. Affect the majority of users - I assume it does as `join` would be a common operation
2. Is there a reasonable workaround - I would think no because it's not something that be controlled

Therefore, this is a candidate for a hotfix. Open an issue and pull in some of the major stakeholders for them to agree on the hotfix and then we can do it.

> I suggest that for a library this young this level of process might not be ideal. We might consider losing some of these features (container builds, complex notebooks, etc.) for a while until things clean up. In an idealized world I would ask ops to provide a generic CI service and then I would ask developers to create testable examples and notebooks. I would trash notebooks that require serious by-hand testing.

Unfortunately, this isn't possible. We need to publish container and notebooks to demonstrate the abilities of the libraries.

> Alternatively, maybe we only update those materials every 0.X.0 release and forget about them on point releases?

This isn't a bad idea. But I'd have to give it some more thought.

Overall, I agree with Mike. He and I are working very hard to reduce the release overhead. If releases can be fully (or nearly fully) automated, then the definition of what constitutes a hotfix could potentially be relaxed.

Releases need to be deliberate and carefully thought out. This is a library and therefore at risk of affecting downstream users whenever a release occurs. I think caution for a project this young is warranted and as development and code stabilizes, we should aim for faster releases.

**Comment by harrism** [comment]
I agree with and defer to @mike-wendt and @raydouglass since we depend on them heavily for our releases. @mrocklin unfortunately you missed the meetings about the processes by only about a week! I will share with you the draft versioning and release process documentation which will hopefully soon become public.

And I agree that the fix that prompted this is a candidate for a hotfix release.

**Comment by thomcom** [comment]
I, too, am strongly opinionated about CI, but didn't want to jump in waving my opinions on a project I was two weeks into. :) I'm thankful for the work that @mike-wendt and @raydouglass are putting into releases. I'll debate you any time about it. ;)

**Comment by mike-wendt** [comment]
As with #570 we are in the middle of the first release where we have changed the release process and how development is handled. I want to postpone changes until we have one or two releases and feedback from the team, that way we can make a more educated decision and understand the true pros/cons.

**Comment by datametrician** [comment]
To avoid lingering issues, let's close this and try the new process for a few versions. If we still want to change things in the future, let's open a new issue.
