### ISSUE TITLE
[DISCUSSION] Replacing `na_sentinel` with null mask for `Series.label_encoding`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5622]
**What is your question?**

Opening up the discussion into a new issue that happened in [PR 5619](https://github.com/rapidsai/cudf/pull/5619)

We might want to retain `na_sentinel` for feature parity with Pandas `Series.factorize`(which internally calls `label_encoding`). But the proposal here is to default `label_encoding`'s `na_sentinel` to `None` and set rows to nulls when we don't have a `na_sentinel` value supplied.

cc: @kkraus14 @rgsl888prabhu  @shwina

**Comment by kkraus14** [comment]
Some thoughts:

`Series.label_encoding` is very much a legacy function from the early days of `pygdf` where I don't know if we want to support it as a public API moving forward, especially considering Pandas doesn't have it as an API.

The main difference between `Series.label_encoding` and `Series.factorize` is that you can pass an existing dictionary for the categories to `Series.label_encoding` instead of it calculating the uniques. In Pandas, this is effectively the same as doing `pd.Categorical(values, categories=dictionary)` which returns a `pd.Categorical` object which you can access `.codes` from. Note that `pd.Categorical` uses `-1` as a sentinel value to indicate a value that isn't in the dictionary, whereas cudf's `CategoricalColumn` implementation uses nulls. When we support `cudf.Categorical`, we'll have the same functionality as `Series.label_encoding` in the same API as Pandas, albeit using `null` instead of `-1` for missing values.

Due to this, I'd propose we change the `cudf.Series.factorize` API to default `na_sentinel=None` instead of `na_sentinel=-1`. If `na_sentinel` is `None`, that indicates we should use `null` as the missing data value. Since the implementation under the hood will likely generate nulls for missing data anyway, if a user passes a value other than `None`, we can just use a `fillna` afterwards to get expected results.

**Comment by shwina** [comment]
Input here is also welcome: https://github.com/rapidsai/cudf/issues/5498

**Comment by vyasr** [comment]
At this point `label_encoding` has been removed. We need to address #6946 to implement Keith's proposal above of using `None` as the default. 

#9474 is tangentially related.

**Comment by vyasr** [comment]
As of pandas 1.5 [the `na_sentinel` parameter is deprecated](https://github.com/pandas-dev/pandas/issues/46910). In 2.0 there will only be a new parameter `use_na_sentinel`. I'm going to repurpose #6946 to track that and close this issue as resolved since `label_encoding` is long gone now.
