### ISSUE TITLE
[FEA] cuIO for custom data types

### ISSUE THREAD

**Issue by v1gnesh** [rapidsai/cudf#5633]
**Scenario:**
To process large (tens or hundreds of gigabytes) binary files that have multiple records of different record types & the record type (info in the first few header bytes) dictates the record structure & length, will I/O parallelization with cuIO help?

**Solution/Idea:**
Can cuIO help parallelize reading such custom-structured (as opposed to, say, CSV) files direct into GPU memory (yes, I understand disk to GPU memory direct is a more general 'problem'/optimization that's being worked on), so it's easier to then process (deserialize the different types of records, do some inline codepage conversion/calculations, and then serialize to Arrow)?

For reference - https://github.com/rayon-rs/rayon/issues/529
(Rayon is a Rust library to help parallelize CPU tasks).
The relevant bit - 

`Now, let's say I have a TB large file of fixed-sized items (or some other way to know where things are in there) and I wanted to process it as fast as possible. It would probably be faster if each thread takes a buffer, they split the file into parts and each one starts processing on its own, buffering the data in as needed to avoid fighting over seeking in the file.`

**Comment by kkraus14** [comment]
@v1gnesh In general if you wanted to parse a new format you'd have to build a new parser and there wouldn't be much reusable from the existing cuIO code other than using the data source abstractions.

> Now, let's say I have a TB large file of fixed-sized items (or some other way to know where things are in there) and I wanted to process it as fast as possible. It would probably be faster if each thread takes a buffer, they split the file into parts and each one starts processing on its own, buffering the data in as needed to avoid fighting over seeking in the file.

GPUs don't quite work this way. As opposed to CPU threads where you can launch different chunks of work on different threads, on the GPU you launch a kernel with a chunk of work (typically a buffer), and the GPU threads access different sections of that buffer to parallelize the work.

Depending on the file format you're looking to handle, it may be easy to take advantage of GPU parallelization if for example you have binary fixed width non-encoded/non-compressed data, or it may be very difficult if you're having to handle compression/encoding/variable width data.

**Comment by v1gnesh** [comment]
Thanks for your comment.
Yes, sorry, posted that blurb about threads to try to explain the feature/behaviour I'm looking for.
Don't need threads specifically, just a way to process file in parallel chunks, while also handling compression/encoding/etc..

So I'm better off maintaining a buffer (500 MB or whatever) of file data in memory, and split out the records onto their own CPU threads for processing, rather than doing to same (loading a buffer of data) on a GPU ... because processing/conversion/encoding is difficult to do on GPU? 

I understand that this may not fully be in cuIO scope; just wondering if any level of support/simplification can be added (or is feasible at all) in cuIO for handling custom-format binary data... considering that RAPIDS cudf could then use cuIO APIs to process custom data types.

So let's say I have dataclasses in Python for each record type. 
Instances of different dataclasses would be to hold different records of different record types.
In a chunk of memory (VRAM or DRAM), I have `n` records of `<=n` different record types.
What would be the best way to process those different record types (process = do whatever the dataclass fields need; may be codepage conversion, format conversion, etc.) as parallelly & efficiently as possible.

**Comment by kkraus14** [comment]
> So I'm better off maintaining a buffer (500 MB or whatever) of file data in memory, and split out the records onto their own CPU threads for processing, rather than doing to same (loading a buffer of data) on a GPU ... because processing/conversion/encoding is difficult to do on GPU?

It's not that it's difficult to do on the GPU, it's that in order to effectively target the GPU you'd need to write code that is GPU parallel friendly. This typically means finding parallelism at some level of either records or chunks within the data, and having enough of those records or chunks to keep a GPU busy.

> I understand that this may not fully be in cuIO scope; just wondering if any level of support/simplification can be added (or is feasible at all) in cuIO for handling custom-format binary data... considering that RAPIDS cudf could then use cuIO APIs to process custom data types.
> 
> So let's say I have dataclasses in Python for each record type.
> Instances of different dataclasses would be to hold different records of different record types.
> In a chunk of memory (VRAM or DRAM), I have `n` records of `<=n` different record types.
> What would be the best way to process those different record types (process = do whatever the dataclass fields need; may be codepage conversion, format conversion, etc.) as parallelly & efficiently as possible.

Instead of Python dataclasses for records, it would be more effectively to think about it in terms of a "Schema" of the dataset. Once you have a schema, you can try to figure out your parallelization strategy of whether you can process your data row-wise or column-wise for example. I would like to note that if you need to handle custom compression / encoding schemes, that is some of the most complicated code that we currently have within cuDF and is likely extremely non-trivial to get performant where I'd highly advise converting to a more standard format if possible.

**Comment by v1gnesh** [comment]
> It's not that it's difficult to do on the GPU, it's that in order to effectively target the GPU you'd need to write code that is GPU parallel friendly. This typically means finding parallelism at some level of either records or chunks within the data, and having enough of those records or chunks to keep a GPU busy.
Understood, 'complexity' is available in the source data - millions to billions of records, and they can each be one of ~300 different record types. And even within those record types, some record types have variations based on bits/bytes in the first few bytes (header) -- think TLV (type-length-value).

> Once you have a schema, you can try to figure out your parallelization strategy of whether you can process your data row-wise or column-wise for example. 
Data has to be processed row-wise because they're **records**. However, once they're parsed with a schema/structs (it's easier for me to process records 'through' different types of structs, I think), they'll need to be converted to Arrow format for efficient storage & access. 

> I would like to note that if you need to handle custom compression / encoding schemes, that is some of the most complicated code that we currently have within cuDF and is likely extremely non-trivial to get performant where I'd highly advise converting to a more standard format if possible.
Yeah, that's the goal, to process data in non-standard format (one-time cost, trying to reduce cost to a minimum) to a standard format (Arrow), so it's convenient for future use. 
What's more, it's not the record(s) as a whole that follow a particular encoding scheme. It's fields within those records that either require conversion (numeric), en/decoding (codepage), etc.

**Comment by v1gnesh** [comment]
Any further thoughts on this, @kkraus14 ? 
This would be really really _really_ useful to have.
I'm sure many folks will find support for custom data types in cuIO handy... considering that it's currently only Parquet, CSV, etc.

**Comment by kkraus14** [comment]
@v1gnesh Agreed that it would be great to eventually support this, but I just don't see a path forward as of now. cuIO is due for a large refactor that we're beginning to scope, so maybe things reveal themselves based on refactoring.

**Comment by v1gnesh** [comment]
Thanks for that (hopefully temporary) closing note, and the immense work that is RAPIDS.

**Comment by vyasr** [comment]
I'm afraid that I still don't see a real path forward here in our future. The efficiency of our parsers is heavily reliant on baking in knowledge of the file formats in question deep into our kernels to maximize the parallel throughput of GPUs for processing. In theory I could envision writing a generic parser that accepted some generalized idea of a "schema" representing a file format and then parsing according to that. However, I don't see how that could be made performant; in addition to the basic layout of the spec, you would need to do some high-level analysis of the divisions within the data and the natural modes for data parallelism, and tailor the algorithms accordingly. Much of the current work that we're doing in cuIO is around specializing kernels _further_ using data-dependent access patterns (e.g. #14953) since that's how you really optimize the performance of these algorithms. As such, I think the request in this issue is not the direction that cuIO will be going.
