### ISSUE TITLE
[QST] performance CPU VS GPU on String, DateTime, Bool  data type

### ISSUE THREAD

**Issue by liuandy-good** [rapidsai/cudf#5638]
**What is your question?**
Is there any example to show the performance  CPU vs GPU on String, DateTime, Bool data type on CUDF ? i would like to try them. 
Thanks

**Comment by harrism** [comment]
This is an extremely open-ended question. What operations do you want to perform on those data types, and what data sizes are you interested in? A better approach would be to take your desired workflow code, and make the changes necessary to use cuDF instead of Pandas (assuming your existing code is in Pandas).

If you have specific questions, please don't hesitate to reopen or file a new issue, but I'm going to close for now.
