### ISSUE TITLE
[FEA] Pin isort, black, flake8 versions

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5647]
As @jrhemstad reported in https://github.com/rapidsai/cudf/pull/5643, the versions of isort, black and flake8 are currently not pinned in the conda dev environments, causing CI to fail whenever breaking changes are introduced in those projects.

We should consider pinning them to prevent this from happening too frequently.

**Comment by jrhemstad** [comment]
The other time that this blocked CI for the better part of a day is here: https://github.com/rapidsai/cudf/pull/5185

**Comment by jrhemstad** [comment]
Because we always pull in the latest version of these tools, we are currently in a position where, without any action on our part, they can push breaking changes that unexpectedly block our CI. 

We should be pinning these versions, and then updating them at regular intervals where we have a chance to vet the new versions in a controlled environment that doesn't block CI. Perhaps updating these versions every release?
