### ISSUE TITLE
[BUG] Truncated type after calling `gather()` on list columns

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5717]
When gathering from list columns, libcudf appears to truncate the types of empty elements:

Consider for example the column

```
{ {}, {{{1}}} };
```

This is a column of type `List<List<List<int>>>` with one empty element and one non-empty element. Importantly, each element should be considered of type `List<List<List<int>>>`.

Gathering the 0th element of the column gives the column `{ {} }`, but it is of type `List<int>`, not `List<List<List<int>>>`.

What we expect:

```
List<List<List<int32_t>>
Length : 1
Offsets : 0, 0
Children :
    List<List<int32_t>>
    Length : 0
    Offsets : null
    Children
        List<int32_t>
        Length : 0
        Offsets : 0
        Children
```

What we get:

```
List<int32_t>:
Length : 1
Offsets : 0, 0
Children :
```

We need libcudf to maintain the type in these situations.

One way to do this would be for libcudf to hold information about the levels of nesting in the `type` of the column, so "empty" elements can always be correctly interpreted. PyArrow for example stores this information in its `type`:

```python
>>> a = pa.array([[[1]]])
>>> print(a.type)
ListType(list<item: list<item: int64>>)
```

Another approach would be to always maintain fully constructed hierarchies.

That being said, there may be other advantages to having nesting information in the `type` outside of this context, so perhaps it's something libcudf would want to consider doing anyway.

**Comment by nvdbaranec** [comment]
I discussed this with Jake and Jason and it looks like Spark wants this behavior as well.   Between the two options, I think the "maintain the full hierarchy" approach is better - Jason pointed out there's no mismatch or possibility of misinterpreation there.  The columns are fully formed, and the type is a simple match at each level.  The other way around would mean a hierarchy of types and potentially a column struct that doesn't match (meaning lots of code would have to be careful).

**Comment by jlowe** [comment]
> it looks like Spark wants this behavior as well

To clarify, I don't think Spark technically needs this because Spark is separately tracking the schema of the columns, so we always know what types we are wielding with cudf.  We currently don't plan on doing schema discovery via libcudf, so Spark knows (or is told by the user explicitly) what types are being loaded and the plan dictates what types are generated as the data is processed by the query.

However I do think this is important for the consistency of the cudf bindings when the application is not expected to be tracking the type separately.  It is very weird to perform an operation on a List<int> type that mysteriously produces a List<?> type because a filter operation ended up eliminating all rows.

Speaking of code being careful, having child columns always be present also means libcudf code wouldn't have to special-case the missing-child-column-when-no-data scenario to avoid a segfault.

I'm curious if there's compelling arguments for the type to be encoded in the type class.  As Dave mentioned, it opens up new bug possibilities like the type class descriptor not matching the child column types.  It would allow us to avoid creating degenerate child `cudf:column` instances when there are zero rows, but is that something that needs to be optimized?

**Comment by harrism** [comment]
Is this addressed by #5675?

@nvdbaranec why did you assign 3 people?

**Comment by shwina** [comment]
> I'm curious if there's compelling arguments for the type to be encoded in the type class. 

It fully specifies an empty column of lists (https://github.com/rapidsai/cudf/issues/5508).

Also, `a.type() == b.type()` should only hold true for list columns with not only the same leaf type, but also the same levels of nesting. That seems to be the case for PyArrow:

```python
In [28]: a = pa.array([[]])

In [29]: b = pa.array([[[]]])

In [30]: a.type == b.type
Out[30]: False
```

**Comment by nvdbaranec** [comment]
> Is this addressed by #5675?

I think whatever solution we come up with here probably also addresses 5675.  That is, the fix for this probably also fixes make_empty_column.   I lean towards the keep-the-hierarchy-whole-even-if-it's-entirely-empty method, fwiw.
 
> @nvdbaranec why did you assign 3 people?

Just wanted to make sure the right people were on the discussion.  Is that the wrong use of assigning?

**Comment by harrism** [comment]
> I think whatever solution we come up with here probably also addresses 5675.

#5675 is a PR, not an issue.

**Comment by harrism** [comment]
This is a quandary. Has anyone estimated the work required for the two different approaches? Pros and cons?

**Comment by nvdbaranec** [comment]
I believe the keep-the-columns-intact method is easier.  Bulk of the work there is in the lists_column_wrapper so that it always constructs what you'd expect for the purposes of testing.   The other remaining functionality (at this point just gather and concatenate) is pretty simple to fix.  

I think the keep-the-columns-intact method is better because:
- If you do it via a nested type class, you could then have a mismatch between what the type says and how the columns are structured once they get truncated - potentially leading to bugs or inconsistent behaviors.
- You get to dodge the added complexity of what structs (coming soon) will bring.  That is - not only would the type class have to be nested, it would need an array of types at every level.

The only real drawback of not doing the type class method is that you can't just compare column.type() fields directly. We could also do both, of course.

**Comment by shwina** [comment]
Strongly agree that we should implement keep-the-columns-intact. My previous message was to make the case for nested types **in addition** to that. Ultimately though, I'm happy with whatever solution libcudf devs feel is best here.
