### ISSUE TITLE
[Java] jni_utils.hpp CATCH_STD() with class_name parameter

### ISSUE THREAD

**Issue by byin-nvidia** [rapidsai/cudf#5784]
**Is your feature request related to a problem? Please describe.**
Re-using CATCH_STD(env, ret_val) from jni_utils.hpp in cuspatial JNI layer, the exception class name fixed to be the default cudf::jni::CUDF_ERROR_CLASS.

**Describe the solution you'd like**
```
#define CATCH_STD(env, ret_val)
  CATCH_STD(env, cudf::jni::CUDF_ERROR_CLASS, ret_val)

#define CATCH_STD(env, class_name, ret_val)                                                                    \
  catch (const std::bad_alloc &e) {                                                                \
    /* In some cases a cuda exception can be the cause so peek and clear if needed*/               \
    if (cudaErrorMemoryAllocation == cudaPeekAtLastError()) {                                      \
      cudaGetLastError();                                                                          \
    }                                                                                              \
    JNI_CHECK_THROW_NEW(env, cudf::jni::OOM_CLASS, "Could not allocate native memory", ret_val);   \
  }                                                                                                \
  catch (const std::exception &e) {                                                                \
    /* If jni_exception caught then a Java exception is pending and this will not overwrite it. */ \
    JNI_CHECK_THROW_NEW(env, class_name, e.what(), ret_val);                      \
  }
```
Then user build their JNI based on cudf can re-use CATCH_STD(env, **class_name**, ret_val) 

**Describe alternatives you've considered**
Alternatively user need to maintain another copy of CATCH_STD(env, **class_name**, ret_val)

**Comment by revans2** [comment]
I'll take a look at this.

@byin-nvidia I was thinking that I should split our header into two.  One that others can use and really is a header only library, and another that is for internal APIs.  If I do this I would like to know what APIs you are using out of it `jni_utils.hpp` that I need to keep, just so I don't remove something you really need.

We also discussed about `auto_set_device`. I think I will expose it as a java API that you could call directly.  It is not ideal because it would be an extra JNI call, but it should be a minor overhead.  Is that okay?

**Comment by revans2** [comment]
Because of how C macros work I cannot have two MACROS named the same thing, but take a different number of arguments.
