### ISSUE TITLE
[QST] Why construction of `std::chrono::duration` from `T{0}` differs from T{}`?

### ISSUE THREAD

**Issue by codereport** [rapidsai/cudf#5805]
This is more of a task to investigate but I spent several hours today tracking down why `ROLLING_TEST` and `GROUP_ROLLING` were failing for my `fixed_point` PR https://github.com/rapidsai/cudf/pull/5704. It came down to this change: https://github.com/rapidsai/cudf/pull/5704/commits/d2eb6b6fe355412276abd30e6669e53d8eb51105 

It always concerns me when I see `T{0}` in some generic function because it requires that type `T` be constructible from `0`, and many types do not have this requirement (i.e. `fixed_point`). 

Investigate to see if this is a bug or if this is actually what we want for `duration`.

**Comment by harrism** [comment]
https://stackoverflow.com/questions/46402944/how-does-stdchronoduration-default-constructed
And
https://groups.google.com/a/isocpp.org/forum/#!topic/std-discussion/OcGX7Yj3meI

That implies that T{} when T is a std::chrono::duration should zero-initialize.

**Comment by kkraus14** [comment]
Closing this as answered.

**Comment by harrism** [comment]
@kkraus14 . I don't think I answered the question, I just provided more information agreeing with Conor's position.  There's still the question of why Conor had to change a `T{}` (preferred) to a `T{0}` for compilation to succeed.

**Comment by harrism** [comment]
@codereport is this still needed?

**Comment by codereport** [comment]
> @codereport is this still needed?

Yes, this is still an open question. I will try to look into it today if I find time.

**Comment by jrhemstad** [comment]
This is because we use a custom wrapper around `time_point` whose default constructor is empty. 

https://github.com/rapidsai/cudf/blob/53ed28e91c71bd5f7413949c8cdaf0e3bbd0b5b8/cpp/include/cudf/wrappers/timestamps.hpp#L39-L42

This is because CUDA doesn't allow types with non-empty default constructors to be used in shared memory. I would really like to eliminate this wrapper type and use `cuda::std::time_point` directly, but we would need to eliminate any use of it in shared memory.

**Comment by codereport** [comment]
@jrhemstad Interesting. I didn't know CUDA had this restriction. Thanks for the reply. Saved me from having to investigate. 

Closing now.
