### ISSUE TITLE
[BUG] cudf.read_parquet does not properly read column of type string that is full of nulls

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#5831]
**Describe the bug**
`cudf.read_parquet` does not properly read column of type string that is full of nulls. 

**Steps/Code to reproduce bug**
Download this file:
https://github.com/BlazingDB/blazingsql-testing-files/blob/master/results/drill/PREDWNULLS-TEST_07.parquet

```
import cudf
gdf = cudf.read_parquet('PREDWNULLS-TEST_07.parquet')
gdf.dtypes

import pandas
pdf = pandas.read_parquet('PREDWNULLS-TEST_07.parquet')
pdf.dtypes
```
The reported types from cudf are:
```n_nationkey    float64
n_name          object
r_regionkey    float64
r_name           int32
```
and from pandas are:
```
n_nationkey    float64
n_name          object
r_regionkey    float64
r_name           object
```

**Expected behavior**
In cudf the string column full of nulls should be read as type string and not int32

**Environment overview (please complete the following information)**
cudf                      0.15.0a200731   py38_ga128c1b32_3829    rapidsai-nightly
dask-cudf                 0.15.0a200731   py38_ga128c1b32_3829    rapidsai-nightly
libcudf                   0.15.0a200731   cuda10.2_ga128c1b32_3829    rapidsai-nightly

**Environment details**
cudf                      0.15.0a200731   py38_ga128c1b32_3829    rapidsai-nightly
dask-cudf                 0.15.0a200731   py38_ga128c1b32_3829    rapidsai-nightly
libcudf                   0.15.0a200731   cuda10.2_ga128c1b32_3829    rapidsai-nightly

**Additional context**

**Comment by OlivierNV** [comment]
Weird, the column type should be inferred from the schema, regardless of the column being all nulls.

**Comment by nvdbaranec** [comment]
FWIW, this PR might fix this issue:
https://github.com/rapidsai/cudf/pull/5723

It reworks large chunks of the kernel code, including those which deal with computing validity.

**Comment by karthikeyann** [comment]
@williamBlazing when all-null column is stored as parquet, it is stored a INT32 column with all nulls.
The details about _All-nulls_ and _UTF8 string_ is stored in `LogicalType`.

```python
In [74]: import pyarrow.parquet as pq
In [75]: pq.ParquetFile('PREDWNULLS-TEST_07.parquet').metadata
Out[75]: 
<pyarrow._parquet.ParquetSchema object at 0x7fa7d0339e10>
required group field_id=0 schema {
  optional double field_id=1 n_nationkey;
  optional binary field_id=2 n_name (String);
  optional double field_id=3 r_regionkey;
  optional int32 field_id=4 r_name (Null);
  optional int64 field_id=5 __index_level_0__;
}
In [76]: pq.ParquetFile('PREDWNULLS-TEST_07.parquet').metadata.row_group(0).column(3)
Out[76]: 
<pyarrow._parquet.ColumnChunkMetaData object at 0x7fa90808c780>
  file_offset: 807
  file_path: 
  physical_type: INT32
  num_values: 20
  path_in_schema: r_name
  is_stats_set: False
  statistics:
    None
  compression: GZIP
  encodings: ('PLAIN_DICTIONARY', 'PLAIN', 'RLE')
  has_dictionary_page: True
  dictionary_page_offset: 727
  data_page_offset: 761
  total_compressed_size: 80
  total_uncompressed_size: 40
```
pandas converts this all-null column to object type column. (object type column can hold any datatypes mixed. It's not string column).

Properly reading this will need **LogicalType support** fully. It will be new feature request.
https://github.com/apache/parquet-cpp/blob/642da055adf009652689b20e68a198cffb857651/src/parquet/parquet.thrift#L315-L336

**Comment by devavret** [comment]
This should be possible by reading converted type. LogicalType is basically a better version of that. But converted type should still allow us to populate a pointer for the encoded data. The definition levels will ensure that none of the data is actually read as INT32 since the def level would be 0 for each.

**Comment by nvdbaranec** [comment]
This may be the same as this somewhat newer bug:

https://github.com/rapidsai/cudf/issues/6168

**Comment by karthikeyann** [comment]
In this example, it's not possible to infer STRING column without reading LogicalType. ConvertedType is UNKNOWN.

Since now it's inferred from physical type alone, STR all-null column is treated as INT32 all-null column.
Also, it doesn't seem right to assume INT32 physical, with UNKNOWN convertedType as STRING.

in the given `PREDWNULLS-TEST_07.parquet` file,
- STRING all-null column schema:
> physical=1,converted_type=-1,decimal_scale=0
schema.repetition_type=1,type_length=0,max_definition_level=1,max_repetition_level=0
type_id=3  (INT32)
- index column INT64 schema:
> physical=2,converted_type=-1,decimal_scale=0
schema.repetition_type=1,type_length=0,max_definition_level=1,max_repetition_level=0
type_id=4 (INT64)
If this was INT32 column, schema will look same as STRING .

Note:
Binary representation of ConvertedType and LogicalType are not same.
ConvertedType is an ENUM. LogicalType is a union (all optional field struct).

**Comment by harrism** [comment]
@karthikeyann would it be possible to fix the current issue without adding full support for LogicalType? We'd like to limit the scope to fix the issue faster, and defer adding full LogicalType support to  0.18 if that makes sense.

Let me know what you think. Depends on how far along you are with 6511.  (I am not familiar with LogicalType.)
