### ISSUE TITLE
CUDA GPU Architecture improperly set 

### ISSUE THREAD

**Issue by mt-jones** [rapidsai/cudf#588]
From CMakeLists.txt:

```
IF(CUDA_VERSION_MAJOR GREATER 7)
    set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-gencode;arch=compute_60,code=sm_60)
ENDIF(CUDA_VERSION_MAJOR GREATER 7)

IF(CUDA_VERSION_MAJOR GREATER 8)
    set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-gencode;arch=compute_70,code=sm_70)
ENDIF(CUDA_VERSION_MAJOR GREATER 8)
```
Virtual GPU architecture, and generated code (SASS) are hard-coded. The project will compile properly, but if you're not using (essentially) Volta / V100, you'll get errors like this:

`C++ exception with description "parallel_for failed: no kernel image is available for execution on the device" thrown in the test body.`

or similar.

Virtual GPU architecture and generated code should be discovered by the project. Or the target platforms should be expanded beyond `sm_60`, `sm_70`

**Comment by harrism** [comment]
I disagree that the architecture should be discovered at build time. It's likely that the machine building the library is not the one loading and running it. We need to build code for all supported architectures, and also include PTX (virtual architecture) so the code will JIT for forward compatibility.

With the 0.4.0 release we actually reduced supported architectures due to CI timeouts. Once CI timeouts are no longer an issue we should add them back.

Compile times will suffer. Thinking out loud, I wonder if we can get nvcc to add a mode that parallelizes device code generation across multiple threads (since each target would be independent). If not, we could implement it by breaking apart the nvcc phases manually... future work...

**Comment by kkraus14** [comment]
This is not an issue and is set properly in CMake
