### ISSUE TITLE
[FEA] Add scalar support for lists

### ISSUE THREAD

**Issue by kuhushukla** [rapidsai/cudf#5887]
**Is your feature request related to a problem? Please describe.**
This issue tracks discussion on how we can support scalars for LIST Column Vector, which may need changes on the cpp side as well once we discuss what the layout should be.

**Describe the solution you'd like**
Ability to create a List column vector from a scalar 

**Describe alternatives you've considered**
None.

**Comment by kuhushukla** [comment]
CC: @nvdbaranec

**Comment by kuhushukla** [comment]
Wanted to ask for some inputs here from @nvdbaranec , @jlowe , @jrhemstad on how we can support scalars for list columns. Could we allow creating column views of type list from a scalar value and return some metadata to indicate that it is in fact a scalar? I am not sure exactly how difficult or easy this might be.

**Comment by harrism** [comment]
Does this mean a scalar that contains a single list? Or a column of lists of scalars? (The latter doesn't make sense to me -- it would just be a column of lists)

**Comment by kuhushukla** [comment]
It is the former.

**Comment by jlowe** [comment]
This brings up the recurring question of why are scalars not just a column with a single row.  With a nested type, there has to be something like a column underneath it (e.g.: a scalar element of a list-of-ints column could be a list of 100,000 integers).

Does it makes sense to have scalars be implemented in terms of a column?  The scalar type needs to remain, as it provides the semantic meaning at the API level (e.g.: a binop of column+scalar is different than column+column).  However having scalars use a column underneath may be convenient/simplifying for the device kernels if they only deal with a column structure rather than a column structure and a separate scalar structure.  It's also convenient for the case where we want to reduce to or slice a single row out of a column and treat it as if it were a scalar.

**Comment by jlowe** [comment]
A few of us met offline about this and decided since one of the primary use-cases for scalars comes from data on the host side (e.g.: a literal in a SQL query), we'd like to minimize the overhead of building the scalar from the host side.  If a list scalar contained a list column of length 1 then we would need to not only copy the child data, but also offset data so it was a proper list column.

So the plan for now is to extract the child data for the list row that represents the scalar value into `list_scalar`.  A `list_scalar` would contain:
- the boolean value for validity of the list scalar (analogous to the validity of a primitive scalar)
- a column of the list child element type containing the data for the scalar value

For example, a scalar value for a LIST of INT32 is a column of INT32.  More concretely, if the list scalar value for the example is `[3, null, 5]` then `list_scalar` would contain:
- a boolean scalar validity value of true, since the scalar is a valid value
- a `column` of `INT32` with three rows: 3, null, and 5.

`struct_scalar` would contain:
- the boolean value for validity of the struct scalar
- a `table` representing the child elements for the single struct scalar value

There was a discussion of supporting zero-copy slicing of a single row from a list or struct column and treating it as a scalar, but currently scalar values are always owning and zero-copy slicing requires a non-owning view.  @harrism mentioned we could add something like a `view_scalar` type in the future if the need arises, and that type could use something like a 1-row `column_view`.

As for an initial use-case for nested-type scalar support, binary-op comparison would be a good starting point.  For example, I would like to select all rows from a table where the values of a particular LIST of INT32 column equal `[3, 4, 5]`.  Or select rows where a struct column of INT32 and STRING has the value `{ 5, "xyz" }`.

**Comment by harrism** [comment]
This is being worked in 0.19
