### ISSUE TITLE
[BUG] .to_pandas() produces unexpected behavior.

### ISSUE THREAD

**Issue by drobison00** [rapidsai/cudf#5928]
#### Describe the bug
Converting cuDf DataFrame to pandas returns a Pandas DataFrame with data types that may not be consistent with expectation, and may not correctly convert to the expected numpy type. 

#### Steps/Code to Reproduce

Example:
```python
import cudf
import numpy as np
from sklearn.feature_selection import chi2 # Just to exercise the SKlearn data preprocessing functions.

X = cudf.DataFrame(np.arange(9).reshape(3,3))
y = cudf.Series([1, 0, 1])

Xp = X.to_pandas()
yp = y.to_pandas()
```
```shell script
>>> Xp.dtypes
0    Int64
1    Int64
2    Int64
dtype: object
>>> yp.dtype
Int64Dtype()
>>>
>>> chi2(Xp, yp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/python3.7/site-packages/sklearn/feature_selection/_univariate_selection.py", line 219, in chi2
    Y = LabelBinarizer().fit_transform(y)
  File "~/python3.7/site-packages/sklearn/preprocessing/_label.py", line 460, in fit_transform
    return self.fit(y).transform(y)
  File "~/python3.7/site-packages/sklearn/preprocessing/_label.py", line 437, in fit
    self.classes_ = unique_labels(y)
  File "~/python3.7/site-packages/sklearn/utils/multiclass.py", line 97, in unique_labels
    raise ValueError("Unknown label type: %s" % repr(ys))
ValueError: Unknown label type: (0    1
1    0
2    1
dtype: Int64,)

>>> chi2(Xp, yp.astype('int64'))
(array([0., 0., 0.]), array([1., 1., 1.]))
```
#### Expected Results
No error should be thrown, as with the ```chi2(Xp, yp.astype('int64'))``` call.

#### Actual Results
As seen above with the ```chi2(Xp, yp)``` call.

#### Additional Info
The breaking change looks to be related to https://github.com/rapidsai/cudf/pull/5645

The SKlearn array conversion then fails, here: https://github.com/scikit-learn/scikit-learn/blob/1ac9d6817da4d54d07f11e538d3447290cedfca3/sklearn/utils/validation.py#L587

#### Versions
Clean Anaconda environment with RAPIDS 0.15

**Comment by brandon-b-miller** [comment]
Hi @drobison00 , allow me to provide some context here. Up until recently there's been some gaps in the way pandas handles missing data vs cuDF, and some pretty imperfect ways of bridging that gap that we're trying to do away with. In particular there wasn't a performant way of representing nullable integer or string data - in fact, still today this kind of thing happens:

```
>>> import pandas as pd
>>> pd.__version__
'1.0.5'
>>> pd.Series([1,None,3])
0    1.0
1    NaN
2    3.0
dtype: float64
```

Since cuDF uses a validity mask to indicate where values are null for all of our supported data types, we don't have this issue:

```
>>> import cudf
>>> cudf.Series([1,None,3])
0       1
1    <NA>
2       3
dtype: int64
```

This meant that up until pandas introduced true nullable dtypes in 1.0, we had to commit some sins to come up with the closest equivalent pandas representation of our data in the event that there were nulls. This involved filling with a [default value](https://github.com/rapidsai/cudf/blob/branch-0.14/python/cudf/cudf/core/column/column.py#L286) in some cases (what default value should one use for integer data?) or in other cases, giving the user back a dataframe that had `object` dtype columns that could hold `None`. Both of these approaches have the potential to introduce bugs or subtly nuke performance downstream.

Nullable dtypes in pandas (`Int64`, etc) give us a way of actually constructing a pandas object that is conceptually equivalent to what people are working with when they use cuDF. This of course poses a problem for workflows like the one in the issue description where someone expects to cleanly deliver cuDF data to a third party library. Ideally, over the long term the community will adopt true nullable dtypes, and this sort of thing will "just work". Until then, we think that cuDF picking what it thinks is the most sensible fill value or dtype promotion under the hood is a rather error prone approach. We considered providing some kind of `na_value=` option as part of our `to_pandas()` api, but how would that work for a dataframe with mixed dtypes? Would one pass a dict? We didn't really see a way of doing that which wasn't fairly cumbersome.

In this release we plan to provide some guidance on how to take the result you get from `to_pandas()` and turn it back into what you would have previously obtained, but we more or less plan on directing users to explicitly go through their columns and either fill the missing values on the pandas side with a value that they specify explicitly, or cast to float/object if they know that's what they really want.

**Comment by drobison00** [comment]
@brandon-b-miller 
Hi Brandon, thanks for the update. I definitely get the rationale; however, it seems like this is something that we'd want to promote better awareness of and/or add warnings when making conversions, because the breakages are non-intuitive and in some cases likely to introduce more subtle errors downstream.

In this particular case, we have a 3rd party library, 'xfeat', which makes use of SKlearn's model_selection libraries, and does something fairly innocuous, passing a dataframe.to_pandas() object to SKlearn. Where this worked, as expected, previously, it now returns a fairly strange error and results in broken code in two libraries we don't control.

The fact that, now, doing something as simple as df.to_pandas().to_numpy() results in an array of 'objects' for any numeric type, is a fairly substantial change. Additionally, things like np.type(df.to_pandas().dtype), no longer work or are inconsistent, for example:

```python
>>> cdf = cudf.DataFrame(np.arange(9).reshape(3,3))
>>> cdf.dtypes
0    int64
1    int64
2    int64
dtype: object
>>> cdf.dtypes[0]
dtype('int64')
>>> np.dtype(cdf.dtypes[0])
dtype('int64')

>>> cdf.to_pandas().dtypes
0    Int64
1    Int64
2    Int64
dtype: object
>>> cdf.to_pandas().dtypes[0]
Int64Dtype()

>>> np.dtype(cdf.to_pandas().dtypes[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot interpret 'Int64Dtype()' as a data type
```

**Comment by brandon-b-miller** [comment]
I'm definitely on board for dropping a loud warning both in the code and in our communication to users over the short and long term. As for the example you provided I'd argue that the reason it previously worked is because in that particular situation there weren't any nulls in the data. If there had been, those integer columns would have contained `-sys.minint -1` that cuDF imputed into the nulls. Maybe sklearn would sensibly error and tell you exactly what was wrong in the case of labels (I think it does some basic checking for that) but if they made it into your features, your model would just start training strangely and producing bad results and not necessarily error. In my opinion that's a worse situation then even a cryptic dtype error (although a warning would definitely help or maybe even something stronger). 

This piece of code that you mentioned is definitely problematic:
`np.dtype(some_pandas_nullable_type)`

But I don't really think that this _should_ work, because there's a conceptual boundary between the two and they do not convert. Assuming a numpy dtype everywhere in the ecosystem is somewhat limiting in this regard. 

Where I will agree with you is that it certainly is confusing to produce a numpy dtype from the `.dtype` attribute of cudf objects whereas after `to_pandas()`, you'll get a pandas nullable dtype. However fixing this isn't as straightforward as just updating that attribute. Producing a pandas dtype there would imply something about the way the data is stored that doesn't really fit the reality, in some ways what we should produce here should be closer to a pyarrow dtype then anything else. But whatever it is needs to maintain some degree of interoperability, e.g. `cudf_object.dtype == np.dtype('int64')` should produce `True` or `False` and not error. Implementing our own dtype object represents a fairly sweeping set of changes, but ones we're actively working on should actually be in place sooner rather then later.

**Comment by brandon-b-miller** [comment]
@drobison00 after some discussion and surveying of the feedback around the community we decided that it was a little premature to do this by default. You should see numpy dtypes in the coming nightlies, 0.15, and in the short term future. Thanks again for the feedback as it's very helpful to see where the changes we make can cause issues in the wild. Let us know here if things do not resolve. If not I'll close the issue in the next few days.

**Comment by drobison00** [comment]
@brandon-b-miller Sounds good, thanks!

**Comment by brandon-b-miller** [comment]
closed by https://github.com/rapidsai/cudf/pull/5970
