### ISSUE TITLE
Reduce the use of output parameters in cuIO

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5943]
There are many places in cuIO where the function result is passed as an output parameter instead of the return value, e.g.:
https://github.com/rapidsai/cudf/blob/57df1a053f4018112fa31f527acdbb23872d76ef/cpp/src/io/csv/csv_gpu.h#L206-L213
https://github.com/rapidsai/cudf/blob/57df1a053f4018112fa31f527acdbb23872d76ef/cpp/src/io/json/json_gpu.h#L74-L82
Some functions return cudaError_t (always success) and some return void.
Most of the functions that need to be fixed can be found by searching for "param[out]".

Higher priority components:
- [ ] Parquet
- [ ] ORC;
- [ ] Compression;
- [ ] Utilities;

Lower priority components:
- [ ] Avro;
- [ ] CSV;
- [ ] JSON;

**Comment by cwharris** [comment]
Some thoughts I had while looking at `io/csv/reader_impl.cu`:

```
  // Essentially, we're building a table, and some meta-data. The meta-data is per-column (verify).

  // Option A:
  // So let's init some builders for the available columns. Some of them might be ignored due to
  // parsing configuration, but we create a builder for it none-the-less. Each stage in the reading
  // process will update specific parts of the builder, using information from previous stages.
  // This would elliminate the idea of "active" vs "actual" column count by simply skipping column
  // builders representing "inactive" columns. This approach will reduce the number of out-params
  // by embracing the idea of a _single_ out-param.

  // Option B:
  // Factor out the loops. Use a decorator pattern or a recursive-column-factory situation.
  // This could result in less out-params, but require more intermediate data types
  // (or redundant copies of the same type). It's very possible Option A leads to a better
  // understanding of this approach.

  // Option C:
  // Refactor the kernel to read a single column at a time. This has the advantage of out-of-kernel
  // type-dispatching, and therefore allows more flexibility in the creation of individual columns.
  // However due to the row-oriented nature of the data we're reading, this flexibility is provided
  // at the cost of multiple strided reads of the input.

  // Option A seems the most appropriate, given that we want performance, and it is a natural step
  // to Option B, should we choose to go that route.
```

**Comment by cwharris** [comment]
I was talking to @trxcllnt and realized we can use `mutable_column_device_view` in `DecodeRowColumnData` rather than `data_type *`,` `void **`, `bitmask_type **`. I didn't realize this at first, because strings are represented as `std::pair<const char *, size_t>`, which are later used to copy strings in to a strings columns. However, if we use _offsets_ from the beginning of the csv, rather than a pointer to the char (read: pointer), we can represent the string "ranges" as a single `column`, where ever `ith * 2` element is the offset of a string, and every `ith * 2 + 1` element is the length (or end offset, whichever suits our needs).

**Comment by vuule** [comment]
This has been largely addressed through other changes, closing.
