### ISSUE TITLE
[FEA] Phase out CFFI from libcudf

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#599]
**Is your feature request related to a problem? Please describe.**
Currently both CFFI and Cython bindings are being built for the `libcudf` API. CFFI is problematic because it requires us to enforce a pure C interface in the external `libcudf` APIs. Furthermore, we cannot have any `include` statements in the files parsed by CFFI.

**Describe the solution you'd like**
We should fully phase out CFFI in favor of Cython. In this way, new APIs can be made to be C++ and old APIs can be converted (if desired) from their C interfaces to C++ interfaces.

**Additional context**
As I understand it from @mt-jones, all of the libcudf bindings to cuDF are already updated to Cython, therefore we should have no problem fully removing CFFI.

**Comment by dantegd** [comment]
Responding with the status for full migration: 

- **Most** bindings have been written, some (quite a few actually) I haven't pushed, my attention has been big time on the other side of the river lately (aka cuML). 
- We can already start adding C++ functionality in separate `.hpp` headers as suggested by a very smart person (aka yourself @jrhemstad ;) ). Then they can be wrapped with cython already skipping cffi. 
- Full transition will happen before 0.5 is complete, but I would **strongly** encourage not deleting the cffi files until branch-0.6 is open. This is so that 0.5 includes the code in case that a binding bug would escape us, a fast hotfix to roll back to cffi can be done for 0.5 for fast bug resolution then. 0.6 then should be fully cffi free (queue party sounds).
