### ISSUE TITLE
[FEA] Cast column to a list of bytes column

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#6069]
Spark casting allows for strings and primitive types to be cast to an array of bytes --  with the primitive types rewritten in big endian order. The endianness flip is necessary to match spark's functionality, including downstream when matching hashing results.

When mimicking the string functionality in cudf we would like to avoid copying the data because the data and offsets would be identical.

What's the best approach to implementing these transformations?

**Comment by jrhemstad** [comment]
Summarizing what the asks are here:

1. Zero-copy cast `STRING` to `LIST<UINT8>`
2. Zero-copy cast fixed-width types like `INT64` to `LIST<UINT8>` (i.e., each element is a list of 8 `uint8_t` bytes)
3. Control little vs. big-endian byte ordering

Sounds like this may be best served by a `to_bytes` function. Though 1 and 2 being zero-copy is incompatible with 3. 

Assuming zero-copy:
```
column_view to_bytes(column_view const& c);
```
I don't really know what the expected behavior of this function would be for other nested list/struct columns. 

To do endianess, we'd need some kind of list specific function for reversing the order of each list element. 

Assuming deep copy, allows controlling endianess:
```
enum class endianness{ BIG, LITTLE };
unique_ptr<column> to_bytes(column_view const& c, endianness e);
```
