### ISSUE TITLE
[BUG] cudf.read_csv fails when using dtype=str

### ISSUE THREAD

**Issue by argenisleon** [rapidsai/cudf#6606]
**Describe the bug**
Using  `read_csv`, `dtype=str` param  should load the csv file without inferring the columns dtypes. But it is returning
```
~/anaconda3/envs/rapids_blazing/lib/python3.8/site-packages/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, parse_dates, comment, na_values, keep_default_na, na_filter, prefix, index_col, **kwargs)
     52         **kwargs,
     53     )
---> 54     return libcudf.csv.read_csv(
     55         filepath_or_buffer,
     56         lineterminator=lineterminator,
cudf/_lib/csv.pyx in cudf._lib.csv.read_csv()
RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1603299723461/work/cpp/src/io/csv/reader_impl.cu:600: Unsupported data type
```

**Steps/Code to reproduce bug**
```
io import StringIO

lines = [','.join(dtypes),
"1.1, 1",
"12.12, 2",
"123.123, 3",
"1234.1234, 4"]
buffer = '\n'.join(lines) + '\n'
df_correct = cudf.read_csv(StringIO(buffer), dtype='str')
```

**Expected behavior**
Load the dataframe without inferring the columns dtypes

**Comment by davidwendt** [comment]
Passing `dtype=['str']` instead works.

The `read_csv` documentation implies `dtype='str'` is allowed

> Use _str_ to preserve data and not infer or interpret to dtype

https://docs.rapids.ai/api/cudf/stable/api.html#cudf.io.csv.read_csv

When specified, it falls into this `elif`:
```
        elif isinstance(dtype, abc.Iterable):
            c_dtypes.reserve(len(dtype))
            for col_dtype in dtype:
                c_dtypes.push_back(str(col_dtype).encode())
```
https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/_lib/csv.pyx#L238-L241

Since a string is iterable this logic ends up producing a `c_dtypes` list with `['s', 't', 'r']` instead of a single `['str']`

This easiest solution may be to just change the documentation to specify `['str']` instead of just `str`.
