### ISSUE TITLE
[FEA] Boolean data type

### ISSUE THREAD

**Issue by BradReesWork** [rapidsai/cudf#667]
Add support for a GDF_BOOL data type.   This would be int8 to match Python.  The Arrow spec calls out a single bit, but that introduces issues (could reuse valid bitmask code).

- [x] update types.h
- [x] update wrapper_types.hpp
- [x] update type_dispatcher.hpp
- [x] update tests/type_test.cpp

This does not touch the Python side of the problem

**Comment by jrhemstad** [comment]
This will require updating the `type_dispatcher` as well as creating an appropriate wrapper type in https://github.com/rapidsai/cudf/blob/branch-0.5/cpp/src/utilities/wrapper_types.hpp

**Comment by BradReesWork** [comment]
from side conversation with Jake, this will just be a wrapper

`using cudf_bool = detail::wrapper::<int8_t, GDF_BOOL>` in `wrapper_types.hpp`
it defines a new concrete type associated with `GDF_BOOL` that simply wraps an `int8_t` value

**Comment by randerzander** [comment]
@mjsamoht - when this and #705 are resolved, I think CSV reader support for booleans will need an update

**Comment by jrhemstad** [comment]
@williamBlazing @eyalroz do you have any data (theoretical or empirical) showing that using a bit-resolution bool will be more performant than byte-resolution? 

Just thinking about it, it seems like it'd be a wash between the two for something like join/groupby.

That said, I don't love the idea of deviating from Arrow if we don't have a solid reason to do so, because then we'll have to provide functionality to expand a bit-resolution column of bools into a byte-resolution column of bools and then back again.

**Comment by kkraus14** [comment]
One of the concerns is using Numba and especially using Numba naively for things like UDFs in Python becomes much more difficult and complicated. For example we won't be able to write a simple loop over boolean elements in a Numba kernel. We'd need to check the bit within an int32 element and that would somehow need to be handled in the UDF codepath or have the bit expanded to a byte before running a UDF.
