### ISSUE TITLE
[FEA] context reset

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#6684]
**Is your feature request related to a problem? Please describe.**

Our app occasionally reach states where `cudf` / `cugraph` get corrupted (ex: https://github.com/rapidsai/cudf/issues/6683 ), but as cudf is still slow for us on initial kernel use (1-2min to warmup on first run of what should be 1-10s tasks), we'd like to try doing a soft reset within the python process (reinit cudf?) before a hard one (kill & restart the python process, restart the container, full reboot.) Likewise, in notebook use, I can imagine `cudf.reset()` before restarting the notebook context.

We're doing a pkill for now, so not a huge priority, but keeps coming up as part of our postmortems and there was nothing filed.

**Describe the solution you'd like**

Method `cudf.reset(hard=True)` or something like it:

* Reimport cudf?
* Reset dependencies (cupy, ...)?
* Reinit cuda context?
* Reset cudf memory?

Keith mentioned related methods in other GPU libs like numba & cupy.

**Describe alternatives you've considered**

For now, we're containing without this as a pkill.

We probably won't trust data after a reset, so that's less of a priority for this request.

**Comment by harrism** [comment]
Libcudf has no state and therefore no initialization. If there is initialization on module load it's in Python.

RMM of course has state but it has a `reinitialize` function in the Python API.

**Comment by kkraus14** [comment]
@harrism I think the request is for an API that effectively does a `cudaDeviceReset` to allow recovering from a corrupted CUDA context.

I'm not sure what the behavior would be if someone called this function while still holding references cuDF / RMM objects though.

**Comment by harrism** [comment]
I think we can safely call that Undefined Behavior.  I think we should think long and hard before providing such an API.

**Comment by lmeyerov** [comment]
Agreed. The reality is cudf/cugraph, in practice, often enter into corrupted states _today_ -- almost everyone I've worked with hits memory limits, library bugs, etc.  -- so they're already sitting in undefined behavior states, with the only recovery mechanism is starting their work over, including non-GPU session state.

**Comment by harrism** [comment]
Bugs are bugs. We should fix them. Adding a context reset doesn't fix bugs.

Memory limits and OOM errors are not corrupted states, and should not be fixed by resetting the CUDA context. They should be fixed by freeing memory.

**Comment by lmeyerov** [comment]
The more I think about the classes of bugs here, the more attractive an explicit notion of a first-class `cudf context` becomes, especially when you think of properties like isolation, blast radius, recovery, testability, introspection, etc.

For API users, this gives interfaces for manipulating bad state and starting afresh. Ex: User OOM bugs -> destruct old session, start new. Ex: Library corruption -> Alert warning and any session stats, and start new session. Of more peripheral interest, it paves a path to ideas like tracking resource use across different sessions.

For library writers, this is about moving from globals to reified contexts & with more managed lifecycles. That's a more defensive and compositional style => more resilient, testable, & introspectable. How that breaks down between Python vs C++ vs CUDA is unclear to me. 

I'm not pushing to prioritize this, especially for something architecture-level like a notion of isolated cudf context with a faithful implementation. However, the issues it addresses, and the potential mechanism for doing so, are worth thinking about as related incidents keep happening..

**Comment by vyasr** [comment]
@lmeyerov @harrism is this now resolved by using `cuda-python` to call `cudaDeviceReset`? I think that resolves the original ask for an easy way to reset and see if that fixes behavior. 

Unless I'm misunderstanding the subsequent asks, I don't see a way to provide an isolated cudf context in the way requested without actually using the CUDA driver API to manually create and destroy CUDA contexts. That would be a dramatic expansion of libcudf's scope and not something that I see happening.

**Comment by harrism** [comment]
Wouldn't we still call it Undefined Behavior from the cuDF side if the device was reset "out from underneath" cuDF? Sure, it would probably work as long as you re-import RMM and cuDF, etc. But still, I don't think we can say you can trust data after resetting the device.

**Comment by lmeyerov** [comment]
Even if we call `cudaResetDevice` and dropped all our user-side df references, between numba, cudf, dask_cudf, RMM, etc, I suspect there may be dangling references .likewise,  In python, I think calling `import cudf` a second time will not re-run anything  as the module is already loaded. I'm not deep in the internals so don't know.

Getting soft isolation and memory isolation is tough and valuable (testing, security, etc), part of why I brought it up earlier in the API design. It took ~5 years to fix js stlib to be capability safe, for example.

**Comment by vyasr** [comment]
I agree, resetting the device would be UB, I'm just offering it as the short-term "try it and see" band-aid because the longer term solution seems like a huge change. 

@lmeyerov is correct that running `import cudf` a second time will not do anything. The correct way to reimport a module is using [the `imp.reload` function](https://docs.python.org/3/library/imp.html#imp.reload), but it doesn't work for extension modules (anything with compiled code, aka cuDF/libcudf). Reloading extension modules essentially requires restarting the process, so there's no way to accomplish that in this context. However, I don't think that's all that important here. What we need is something different to accomplish the kind of reset requested in this issue.

Here's what I'm envisioning as the request:

```
with cudf.context(...):
    sr = cudf.Series(...)
    ...
    # Do something that OOMs

sr # This is UB (or every cudf object checks that it wasn't created inside a now invalid context, but I don't really want to do that)
sr = cudf.Series(...)  # This should work again
```

Assuming that this is correct, here's the minimal set of things that I think needs to happen, roughly in order (this is basically a fleshed out version of the list @lmeyerov proposed in the original issue description:
- All previously created objects for every CUDA-dependent library (cudf, cupy, numba, rmm, etc) immediately become invalidated
- All internally stored objects in these libraries must be deleted
- We call cuDevicePrimaryCtxReset
- We reinitialize each library one at a time.

In order for this to work, it's not sufficient for each library to offer a "reset". They must independently offer an "unload" and a "reload", because we have to unload all libraries, reset the primary context, then reload all the libraries so that they all initialize into the fresh context. The reload functionality must account for any and all logic that happens on package import, and it must be fully supported by all dependencies. If any library supports the use of the driver API for creating additional contexts, we would also need access to that stack so that we can reset all of them (at least up to level of the stack containing a sticky error) so that we can unload all of those too.

Does that all sound right? If so, I'm just not sure that I see this happening without a sustained, concerted push across all libraries in the ecosystem that use CUDA. Perhaps if we reach a point that cuda-python actually has penetration and everyone makes use of it we could implement some form of registering reset functionality into a cuda-python callback, but with the current setup it doesn't seem feasible. Any library that fails to follow the rules or provide the necessary APIs could trigger UB for any of the other libraries by continuing to hold onto references pointing to the old context, right?

@shwina do you have any further thoughts here? Perhaps I'm missing some key insight that would make this goal more realistically achievable?

**Comment by vyasr** [comment]
I'm going to close this for now as out of scope, but happy to reopen if there are ways to surmount the difficulties listed in my previous message.

**Comment by lmeyerov** [comment]
I think it's fine to have this scoped to an individual repo. It's unrealistic to do everywhere, but it's quite realistic for individual repo's to not be broken.
