### ISSUE TITLE
[BUG] the max operation with specified type in ColumnVector doesn't work any more

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#6783]
**Describe the bug**
I added a unit test in **ColumnVectorTest.java** to test max with the specified type, just like below code

``` java
  void testMaxWithSpecifiedType () {
    try (ColumnVector cv = ColumnVector.fromBoxedFloats(2.33f, 32.12f, null, -121.32f, 0.0f, 0.00001f)) {
      Scalar x = cv.max(DType.FLOAT64);
      System.out.println(x.getDouble());
    }
  }
```

The cudf native threw an exception with 
```
ai.rapids.cudf.CudfException: cuDF failure at: /home/bobwang/work.d/nvspark/30/nv.xgboost.cudf/cudf.clion/cudf/cpp/src/reductions/max.cu:28: max() operation requires matching output type

	at ai.rapids.cudf.ColumnVector.reduce(Native Method)
	at ai.rapids.cudf.ColumnVector.reduce(ColumnVector.java:1616)
	at ai.rapids.cudf.ColumnVector.max(ColumnVector.java:1447)
```

**Expected behavior**
It's like a regression. The previous version can work

**Comment by revans2** [comment]
This is expected as was discussed in https://github.com/rapidsai/cudf/issues/6717 It is a little hard to keep the java code in sync with the c++ code at times.  I personally would like to deprecate the max/min APIs that take a DType because they are not going to work any more.  I might add in a temporary cast in some cases though.
