### ISSUE TITLE
[FEA] Support using conda supplied gcc/g++ and libraries for building from source

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#688]
This would give us better compatibility with the conda ecosystem, and more importantly resolve issues with OS dependent compilers / libraries.

**Comment by cjnolet** [comment]
I like this idea a lot- it decouples the underlying linux distribution from the user's ability to build the code. 

Because I'm on centos7, even installing the devtoolset-7 did not fix the problems I was having in the cudf build because the nvstrings shared object that ships with the cudf source was built with a newer libstdc++ than what I had available (devtoolset did not supply a newer version).  

Linking against the libstdc++ in my conda distribution worked.

**Comment by MasoodK** [comment]
Hi @cjnolet, would you mind sharing some detailed instructions/steps in order to make compiling on CentOS work (with or without libstdc++ in conda)? Not sure how much documentation I am asking for here; if it's not much, I appreciate it if you could write here. Thanks.

**Comment by beckernick** [comment]
Currently, it is possible to build 21.08 on Ubuntu using conda supplied gcc/g++. With `conda install -c conda-forge gcc_linux-64 gxx_linux-64` one can build from source even if the machine's default compiler is not supported.

**Comment by harrism** [comment]
So can we close this?

**Comment by beckernick** [comment]
As noted above, this is now possible. Closing
