### ISSUE TITLE
[FEA] In parquet writer, use column_device_view in EncColumnDesc

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#6893]
`EncColumnDesc` currently inherits from `stats_column_desc` which holds pointers to data and validity mask as well as a cuIO specific dtype which basically repeats the list of datatypes supported by cudf.
https://github.com/rapidsai/cudf/blob/8cc23bdd4f894c85d5ee400712db994711244b3d/cpp%2Fsrc%2Fio%2Fstatistics%2Fcolumn_stats.h#L40-L48
This is the same information stored by `cudf::column_device_view` and therefore can be replaced by it/contain it.
This gives us a few benefits:
1. Automatic application of offset to data and nullmask ptr. (The latter didn't exist; although, it's being added in #6889)
2. Helpful accessors for `is_null(i)` which de-duplicates functionality.
3. `element<T>()` accessor, which allows for the following:
   1. On the fly construction of `string_view` in case of string columns, thus obviating the need to construct a vector of `string_view`s (or, `nvstrdesc_s`, as it is right now) at the time of construction of `parquet_column_view`. This limitation exists because string columns contain two data streams (offsets and chars) while `stats_column_desc` only has pointer to one data stream. This would also automatically resolve #5682
   2. Automatic construction of `decimal32/64` using the scale stored per column.
   3. Automatic construction of `dictionary32` using indexalator.
   3. Future proofing any other data type added that needs a custom accessor.
4. Encapsulation of nesting offset data https://github.com/rapidsai/cudf/blob/2ce59fccaac0277cc79a4d0d3a961adb90f1cd21/cpp%2Fsrc%2Fio%2Fparquet%2Fparquet_gpu.hpp#L225-L227 which currently incurs a memcpy at the time of `parquet_column_view` construction. https://github.com/rapidsai/cudf/blob/2ce59fccaac0277cc79a4d0d3a961adb90f1cd21/cpp%2Fsrc%2Fio%2Fparquet%2Fwriter_impl.cu#L325-L330

The construction of all these `column_device_view`s might cause many `cudaMemcpy`s if done using `column_device_view::create`. Since `write_parquet` and `write_chunk` are called with a `table_view`, it'd be better to call `table_device_view::create` and use a kernel to copy them into `EncColumnDesc`.

Because of list columns, we'd also want a second `column_device_view` member in `EncColumnDesc` so that we can have both the parent column and the leaf column. The leaf column would be the main column for non-list types and the parent column would only be populated for list types.

**Comment by vuule** [comment]
What about other uses of stats_column_desc? Should we replace it everywhere with column_device_view?

**Comment by devavret** [comment]
> What about other uses of stats_column_desc? Should we replace it everywhere with column_device_view?

As discussed offline, for now we should move away from `EncColumnDesc` inheriting from `stats_column_desc` and have a `column_device_view` member instead. If/when we resolve #6920, `stats_column_desc` can be removed.

**Comment by kaatish** [comment]
[page_enc.cu::gpuInitFragmentStats(...)](https://github.com/rapidsai/cudf/blob/8c1f01e1fd713d873cf3d943ab409f3e9efc48f8/cpp/src/io/parquet/page_enc.cu#L411) has a [line](https://github.com/rapidsai/cudf/blob/8c1f01e1fd713d873cf3d943ab409f3e9efc48f8/cpp/src/io/parquet/page_enc.cu#L425) which assigns a EncColumnDesc to a stats_column_desc which is a [member](https://github.com/rapidsai/cudf/blob/8c1f01e1fd713d873cf3d943ab409f3e9efc48f8/cpp/src/io/statistics/column_stats.h#L81) of statistics_group. This is possible because as of now `EncColumnDesc` inherits from `stats_column_desc`.

Do we plan to replace all occurrences of `stats_column_desc` with `column_device_view` to keep this possible? That might not work because stats_column_desc also contains `stats_dtype`, `num_values` and `ts_scale` which aren't directly contained in `column_device_view`.

Perhaps we can create an assignment operator between `EncColumnDesc` and `stats_column_desc`?

**Comment by jrhemstad** [comment]
> The construction of all these `column_device_view`s might cause many `cudaMemcpy`s if done using `column_device_view::create`

The functionality added in https://github.com/rapidsai/cudf/pull/6605 should be able to help with this.
