### ISSUE TITLE
[BUG]`to_arrow` function slowed down in 0.17

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cudf#6905]
The cudf function `to_arrow` takes more time to run in cudf 0.17 than it did in cudf 0.15
The code below will help reproduce the observed slow down
```
import cudf
from cuml import make_regression
import time
n_samples = 2**21
n_features = 2**10

random_state = 23
X, _ = make_regression(n_samples=n_samples, n_features=n_features, random_state=random_state)

X = cudf.DataFrame(X)
X.columns = [str(i) for i in range(2**10)]

time_start = time.time()
conv = X.to_arrow(preserve_index=False)
time_end = time.time()
print(time_end-time_start)
```
0.15 takes 3.594 secs and 0.17 takes 4.702 secs on 32GB GV100

**Comment by kkraus14** [comment]
cc @rgsl888prabhu

**Comment by vyasr** [comment]
Given how old these performance numbers are, I'm going to close this issue. We can revisit performance optimizations during a more concerted push on improving overall library performance, but given how much has changed in the library since this issue was created we'll likely need to reevaluate with a fresh start.
