### ISSUE TITLE
[FEA] support reading decimal data stored as byte array from parquet files

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#6909]
Currently, we can read decimal columns from parquet files, if their storage type are INT32 or INT64. But in real world applications, there are many parquet files containing decimal columns stored with FIXED_LENGTH_BYTE_ARRAY.

 I think we had better to support reading them as fixed-point data type, just as integer based decimal columns. For data exceeding 8 bytes, perhaps we can perform rounding cast to fit them in DECIMAL64?

**Comment by revans2** [comment]
Just to be clear here we have noticed that in files written by pyarrow and older versions of spark there can be decimal columne that would fit in INT32 or INT64, but are stored as FIXED_LENGTH_BYTE_ARRAY, just because the INT32 and INT64 format is newer.

Supporting these is a priority for us from the Spark side.  Reading > 64-bit decimal values is not something we are planning on trying to support until we have 128-bit decimal support.

**Comment by sperlingxx** [comment]
Close this issue since corresponding pull request has been merged.
