### ISSUE TITLE
[DOC] groupby sort=False performance docs

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#7026]
pandas groupby docs

> sort bool, default True
Sort group keys. Get better performance by turning this off. Note this does not influence the order of observations within each group. Groupby preserves the order of rows within each group.

cudf groupby docs

> sort True, optional
If True (default), sort results by group9s). Note that unlike Pandas, this also sorts values within each group.

Question: how does setting this to False affect performance of groupby in cudf?

**Comment by kkraus14** [comment]
cc @shwina in case I get anything wrong here 😄

Currently the if `sort` is set to `True` we sort by the group column(s) after calculating the groupby result. Setting it to False will definitely improve performance in the typical cases of non-apply aggregations. Note that with `sort=False` we have an unstable output order.

Under the hood, libcudf supports both hash based groupbys and sort based groupbys where if `sort=True` we may want to take the sort based path instead of doing hash based and then sorting the result, but this is purely an optimization.

**Comment by kkraus14** [comment]
Also, updated the issue to indicate that we should update our docs to reflect this behavior.

**Comment by shwina** [comment]
@kkraus14 that's an accurate summary, with the caveat that libcudf doesn't provide sort-based implementations for all aggregations (whether a sort based implementation is available is an implementation detail). So currently, we can't really guarantee that setting `sort=True` will use a sort groupby at the libcudf layer.
