### ISSUE TITLE
[FEA] Provide fixed-point support for MOD, PMOD and TRUE_DIV

### ISSUE THREAD

**Issue by nartal1** [rapidsai/cudf#7132]
**Is your feature request related to a problem? Please describe.**
Fixed-point support missing for MOD, PMOD and TRUE_DIV.

**Describe the solution you'd like**
We should support Fixed-point for MOD, PMOD and TRUE_DIV operations.

**Additional context**
This issue builds upon https://github.com/rapidsai/cudf/issues/3556

**Comment by harrism** [comment]
@codereport Assigning you, though this is likely to be 0.19.

**Comment by codereport** [comment]
Just spoke with @revans2, here is a summary of our conversation:
* Currently, libcudf `fixed_point` only supports `DIV`, which calculates resulting scale as `s1 - s2` 
* Java/Spark/Python have `TRUE_DIV` which calculates resulting scale as `max(6, s1 + p2 + 1)`
* libcudf `fixed_point` has no concept of `TRUE_DIV` and also no concept of `precision`

_Note: `s1 = scale_lhs, s2 = scale_rhs, p2 = precision_rhs`_

**Suggested Path Forward to Support `TRUE_DIV`:**
Have the `cudf::binary_operation` for `fixed_point` `TRUE_DIV` require resulting scale to be passed in (instead of calculating it on its own. This will work for both Python, Spark/Java and doesn't conflict with anything in C++ - and would be relatively straight forward to implement.

@harrism, @jrhemstad If you don't object ... I will move forward with this plan for `TRUE_DIV`

**Comment by harrism** [comment]
Sounds like a good plan.

**Comment by kkraus14** [comment]
cc @shwina for visibility related to what's needed in the Python side for the binop

**Comment by revans2** [comment]
this is still desired

**Comment by nartal1** [comment]
this still needs to be addressed.

**Comment by beckernick** [comment]
Are the outstanding elements in this feature request MOD and PMOD?

**Comment by nartal1** [comment]
Yes, that's correct.

**Comment by GregoryKimball** [comment]
Closed by #10179
