### ISSUE TITLE
[QST] Possibility to change the code into cudf

### ISSUE THREAD

**Issue by khawar512** [rapidsai/cudf#7330]
Actually, I am retrieving 55000 images and my system get hanged so now I am changing my code into CUDF. I don't know how I can change my code. Please help me

```
positives = pd.DataFrame()
for value in tqdm(identities.values(), desc="Positives"):
    positives = positives.append(pd.DataFrame(itertools.combinations(value, 2), columns=["file_x", "file_y"]),
                                 ignore_index=True)
positives["decision"] = "Yes"
print(positives)
samples_list = list(identities.values())
negatives = pd.DataFrame()
######################====================Functions=============##############

def compute_cross_samples(x):
    return pd.DataFrame(itertools.product(*x), columns=["file_x", "file_y"])

####################################
if __name__ == "__main__":
    if Path("positives_negatives.csv").exists():
        df = pd.read_csv("positives_negatives.csv")
    else:
        with ProcessPoolExecutor() as pool:
            # take cpu_count combinations from identities.values
            for combos in tqdm(more_itertools.ichunked(itertools.combinations(identities.values(), 2), cpu_count())):
                # for each combination iterator that comes out, calculate the cross
                for cross_samples in pool.map(compute_cross_samples, combos):
                    # for each product iterator "cross_samples", iterate over its values and append them to negatives
                    negatives = negatives.append(cross_samples)

        negatives["decision"] = "No"

negatives = negatives.sample(positives.shape[0])
df = pd.concat([positives, negatives]).reset_index(drop=True)
df.to_csv("positives_negatives.csv", index=False)`
```

**Comment by taureandyernv** [comment]
Hey @khawar512 , with your code there are two things you need to consider:

1. Due to the API similarity, the first place to start is importing cudf.  Then, where you use `pd` (your pandas import variable name) you, replace it with `cudf`.   While this is a start, [please check out this guide](https://github.com/rapidsai-community/notebooks-contrib/tree/community_relaunch/getting_started_materials) that will help you understand the basics of the transition.  Coding wise, begin with the [cudf and dask cuDF tutorial notebooks](https://github.com/rapidsai-community/notebooks-contrib/tree/community_relaunch/getting_started_materials#1-the-basics-of-rapids-cudf-and-dask), especially [this one](https://github.com/rapidsai-community/notebooks-contrib/blob/community_relaunch/getting_started_materials/intro_tutorials_and_guides/01_Introduction_to_RAPIDS.ipynb).  

2. you may want to refactor your function to not require `for loops`.  cuDF and the other RAPIDS libraries do a lot under the hood to parallelize your code for the GPU.  Adding for loops makes the process serial and slows you down.
