### ISSUE TITLE
[BUG] Evaluating predicates for columns with Decimal32 results in invalid answer 

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#7350]
**Describe the bug**
Comparing two decimal32 numbers left value(scale: -4) 5076.8852, Right value(sclae: -2) -407144.33 results in invalid answer when evaluating 

GreaterThan
java.lang.IllegalStateException: Expected: true. Actual: false. Left value: Some(5076.8852), Right value: Some(-407144.33)

GreaterThanOrEqual
java.lang.IllegalStateException: Expected: true. Actual: false. Left value: Some(5076.8852), Right value: Some(-407144.33)

LessThan
java.lang.IllegalStateException: Expected: false. Actual: true. Left value: Some(5076.8852), Right value: Some(-407144.33)

LessThanOrEqual
java.lang.IllegalStateException: Expected: false. Actual: true. Left value: Some(5076.8852), Right value: Some(-407144.33)

**Steps/Code to reproduce bug**
use the above values in a vector and evaluate the above predicates

**Comment by codereport** [comment]
@razajafri What are the two scales?

**Comment by codereport** [comment]
I see you updated the description to include the scales, I will test in `libcudf` and post my findings.

**Comment by codereport** [comment]
@razajafri So I wrote a test, it failed - and then upon looking at the values - it is integer overflow that is causing the incorrect values.
`-407144.33` with `scale=2` will be shift to`scale=-4` in order to compare with other `scale=-4` number. This means the number stored will be `-407144.33 * 10^4` which is `-4,071,443,300` and this exceeds `int32_t` limit.

So I don't think this is a bug. Just overflow.

**Comment by razajafri** [comment]
gotcha, thanks Conor for the quick turn around
