### ISSUE TITLE
[FEA] an operator that will give you a fairly accurate size per row for a table.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7408]
**Is your feature request related to a problem? Please describe.**
There are various operations where the size of the output can grow significantly compared to the size of the input.  Join and explode are big examples of this, but we expect there to be others too.

Most of these algorithms can be adapted to output gather maps instead of doing the gather directly.  That way we can split up the gather map and gather in stages where the output fits given criteria.

The limits that we care about are first the row limits set by CUDF. This is especially difficult for nested types, and the size limits set by the spark user to avoid running out of GPU memory when processing data. Because the row limit problem is really hard to solve efficiently we have taken a short cut in Spark and simply limit the size of a target batch size to 2GB because even if we have a single byte column with no validity 2GB will not go over the size type limit set by CUDF.

As such we really would like an API that when given a table will produce return a column of the approximate size of each row in that table.  That way if we have nested types in a gather we can instead gather the size per row column, do a running sum on it and a lower bound on 2GB to how many output rows we can gather at once. (For tables that are made completely of fixed width types it would be nice to have a separate API that would return the size of the row as a single value, but we can do that too without too much work)

**Describe the solution you'd like**
I would like an API that when given a table will return a column of INT32 vales with the approximate size of each row in bytes.  I say approximate because we cannot represent the exact size of all rows as an INT32. This is because of validity bits and offsets. For validity bits each entry really gets about 1/8th of a byte. Offset columns have one more entry than the original data has.

For offset columns I would assume that the number of rows in a table is large enough that the value of the extra offset values is small enough to ignore.  For validity I would prefer to have us round up to the next byte. So For example if we have a row in a table that has 2 int columns (A and B) and a list of bytes column (C), each with validity possible.

If the row looks like 
`0, 1, null` then the size would be 4 (column A size) + 4 (column B size) + 4 (column C offset size) + 0 (column C data size) + 1(validity bit for A, B, and C divided 8 and rounded up) = 13 bytes
but if the row looked like

`2, null, [4, 5, 6, 7, 8, 9, 10]` the size would be 4 (column A size) + 4 (column B size) + 4 (column C offset size) + 7 (column C data size) + 2(validity bit for A, B, C and 7 for the data in C divided by b and rounded up) = 21 bytes

**Describe alternatives you've considered**
What we have done so far in different places is to get the entire size of the memory backing a batch and then get the average size of a row to estimate how many rows to are needed.  But this is really just for out of core sort where if we get it wrong we don't run out of memory so it is acceptable there.

**Additional context**
We discussed this with several people in the CUDF team and figuring out how to do a lot of the out of core/chunked processing is still a work in progress, but we think that this is at least one of the first steps towards finding an efficient and somewhat generic way to accomplish this.

**Comment by jrhemstad** [comment]
In your examples, are all columns nullable? i.e., all of them contain an allocated bitmask?

Dictionary columns are another place where it's difficult to provide an exact answer. I'm not sure what you can do there other than just count the indices and not the keys. Otherwise how do you account for the keys across all of the rows?

**Comment by jrhemstad** [comment]
Proposed API would look like:
```
unique_ptr<column> row_byte_count(table_view const& t, memory_resource * mr);
```

Returns a non-nullable column of `INT32` elements where `output[i]` contains the approximate number of bytes in row `i` of `t`.

**Comment by revans2** [comment]
> In your examples, are all columns nullable? i.e., all of them contain an allocated bitmask?

In my example all columns were nullable.  If they were not then we would remove one bit worth from each.

> Dictionary columns are another place where it's difficult to provide an exact answer. I'm not sure what you can do there other than just count the indices and not the keys. Otherwise how do you account for the keys across all of the rows?

I had not considered dictionaries because we don't use them currently, but you are totally correct. I think we would count the indices and not the keys. If you wanted to account for the key size I assume that you would then calculate the size of the keys for each dictionary column and subtract that from the target size you were trying to go for because the keys would be replicated in the output.

The API looks good to me.

**Comment by sameerz** [comment]
Issues https://github.com/NVIDIA/spark-rapids/issues/1628 https://github.com/NVIDIA/spark-rapids/issues/1629, https://github.com/NVIDIA/spark-rapids/issues/1630 depend on this.

**Comment by jrhemstad** [comment]
@revans2 with your proposed solution for counting the null mask, if you were to pass in only a single nullable column then you'd end up counting an extra byte for each element. Is that what you want?

More concretely, for each rows byte count you would add `ceil(#nullable columns/8)`.

**Comment by revans2** [comment]
> @revans2 with your proposed solution for counting the null mask, if you were to pass in only a single nullable column then you'd end up counting an extra byte for each element. Is that what you want?
> 
> More concretely, for each rows byte count you would add `ceil(#nullable columns/8)`.

The alternative would be to return a double, so we could count parts of a byte or a long so we could count every bit. That would make the size column twice as large vs in some cases we return a batch that is smaller than expected. 

Worst case would be a single nullable byte column where we would split on at most 1GB of data, not including validity, instead of 1.78GB with a more accurate count. But then the size of each row is going to be larger than our target size anyways, and we want to be careful about that too. If the goal is to keep maximum GPU memory usage in check then with an INT32 size per row I would need 4GB of storage to know that I can return 1GB of actual data.  In those extreme cases we probably would end up looking at maximum row counts a lot smaller anyways.

**Comment by jrhemstad** [comment]
> The alternative would be to return a double, so we could count parts of a byte or a long so we could count every bit. That would make the size column twice as large vs in some cases we return a batch that is smaller than expected.

I hadn't considered returning a non-integer value. Wouldn't `float` be good enough?

**Comment by revans2** [comment]
A float would give us 23 bits of precision before it starts to drop things (technically 24 bits because for most non-0 values a 1 is assumed as the upper bit.  That means we can store sizes of up to 2^24 bits before we lose information (or 2MiB). Returning a bit count in an int would give us 256 MiB max per row, but have a much worse failure mode if we did go over it. hmmm I am a bit conflicted about it. A 2MB row feels like a real possibility for long strings or long lists.

@jlowe do you have an opinion on this?

**Comment by jlowe** [comment]
Hmm, this is problematic.  `INT32` will not work in the general case because there could be too many list-like leaf columns with large row sizes that overflow the sum.  32-bit floating point could be wildly off in that situation as well (but at least not negative, so there's that).  64-bit essentially solves it, but manifesting 8 bytes per row when there's close to 2**31 top-level rows is quite pricey.

I'm a little dubious on the float/double approach.  You end up with accidental coalescing across columns that doesn't make sense.  A validity bit in column X can't merge with a validity bit in column Y yet the bit sum will imply they can.  Granted this is a "fairly accurate" size request, so I suppose this is close enough.

How about "return an INT32 column when it works, INT64 when it doesn't"?  :smile:  That's essentially the behavior I'd want but realize that's unlikely to happen.

> A 2MB row feels like a real possibility for long strings or long lists.

Agreed, I'm certain someone is doing this, like encoding an image per row or getting this size across many fields of a struct column.  However I think it gets back to what is meant "fairly accurate."  If we can live with the accumulated errors within the floating point value for the intended purpose then maybe it still fits the "fairly" part?  If not then I think we'll either need to go full 64-bit (long or double) or the "use the appropriate sized output" approach.

**Comment by revans2** [comment]
The thing that scares me about floating point is that it can lose data if we are not careful. Once we hit about 2MB of data if I add in a small row it is not going to change the result.

```
scala> 2097152f + 0.125f
res1: Float = 2097152.0
```

And then if 2MB rows is not common we end up with really odd errors that happen and cause us to crash with out of memory. I would be okay with returning floating point rows, so long as we did the actual summation as a double and then cast the result back to a float at the end. But I would rather return batches that are too small than too large, and if we just round up for the validity bits then we don't have to worry about any of that.

**Comment by jrhemstad** [comment]
> `INT32` will not work in the general case because there could be too many list-like leaf columns with large row sizes that overflow the sum.

Really? I'd think if you have a single _row_ that's anywhere near 2GB (4GB if we use UINT32) you have much, much larger problems on your hands.

**Comment by revans2** [comment]
Spark has a limit of 2GB per row. We are not going to get anywhere close to supporting that for so many reasons, but 2MB per row I expect there are customers that hit that. I personally think that INT32 for counting bits (256 MB/row max) is enough and we can clearly document that limitation.

**Comment by nvdbaranec** [comment]
Should these sizes take into account padding or do we want them to be "logical" sizes?  It probably doesn't matter much but if you had a column like  `List<List<List<int>>>`

There's up to 7 actual buffers that will be allocated there (3 offset buffers, 3 validity buffers, 1 int buffer) each of which could be separately padded out. 

In the grand scheme of "identifying things that come close to 2 GB" it probably doesn't matter, but just wanted to check.

**Comment by revans2** [comment]
No padding, this is not for conversion to a row format that would include padding. This is to chunk the output still in columnar format.

**Comment by revans2** [comment]
The fractional part of the float still needs to be part of that 23 bit mantissa. You still need to be able to store 1/8th

**Comment by nvdbaranec** [comment]
A note here about lists.  One of the issues with this function is that it can't give you a perfectly precise number for columns that contain lists without some additional information. 

Imagine you had a simple list<int> column.  Every row you retrieve will include one offset in addition to the underlying int data. But since a list isn't fully formed until you have the terminating offset, this leaves us with a problem.

**Twist 1**

- Gathering 1 row will give you 2 offsets
- Gathering 2 rows will give you 3 offsets, not 4. 
- In other words, total # of offsets is always # of rows + 1, _per level of nested list in the hierarchy_

This function doesn't know how many rows you will be gathering.  So what it really needs to return is 

- X, a column of row sizes (as specified now) 
- Y, a terminating cost representing the final cost to terminate all lists within the returned row. This would simply be (# of lists in the hierarchy * 32 bits).

So to compute the true cost of gathering a bunch of random rows, instead of doing `sum(X over all rows)`, you would do `sum(X over all rows) + Y`

**Twist 2**

Even the above isn't really sufficient because it is possible that some/all of the lists returned will be of size 0.  In that case, the # of offsets will be 0.  

Thoughts?

**Comment by jrhemstad** [comment]
> For offset columns I would assume that the number of rows in a table is large enough that the value of the extra offset values is small enough to ignore.

As Bobby said above, I think the extra +1 offset doesn't seem like a big deal, even if there's an unaccounted +1 for every nested list. That's what makes this "fairly accurate" instead of an exact count.

**Comment by nvdbaranec** [comment]
True.  But with the conservative estimate you can guarantee it'll never give you a value too small, so you'll never accidentally overflow.  Whereas with the underestimate you in theory could - although even an absolutely tiny amount of slop space under the 2GB limit would also handle that pretty trivially.

**Comment by revans2** [comment]
The extra slop space is fixed based off of the schema. So simply walking through the schema and counting how many LIST/STRING types there are in it would give us how much data we needed to add. But even then it is not going to be a significant amount of GPU memory going over if we missed it.
