### ISSUE TITLE
[QST] why concurrent_unordered_map's insert() method doesn't support string type element ? 

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#7459]
**What is your question?**
In file [cpp/src/hash/concurrent_unordered_map.cuh](https://github.com/rapidsai/cudf/blob/branch-0.19/cpp/src/hash/concurrent_unordered_map.cuh) , insert() calls atomicCAS(), and it supported cudf types are: int8_t, int16_t, int32_t, int64_t, float ... and my question is :
how to use 'concurrent_unordered_map' to insert a key and value and key value type is string ?

**Comment by jlowe** [comment]
Strings can be supported indirectly by storing location information for the string in the map rather than storing the string directly.  For example, you could store the row index from the string column in the map as the key or value, and the row index fetched from the map can be used to lookup the original string.

The hash join code uses this technique to implement joins on arbitrary number of key columns and arbitrary number of non-key columns.  It hashes all the key columns to generate a hash value for the map key then stores the row index as the map value.  The row index is used to locate all the values associated with that key hash, regardless of how many values there are in the row or their types.

**Comment by jrhemstad** [comment]
@jlowe described it exactly.

That said, I recommend you do not use the `concurrent_unordered_map/multimap` from cuDF. Apart from the fact that they are not part of the public API, these data structures are slated to soon be removed and replaced with https://github.com/NVIDIA/cuCollections.

**Comment by jrhemstad** [comment]
Closing this. Feel free to reopen if you still have any further questions.
