### ISSUE TITLE
[FEA] Improve performance of loading long strings from Parquet

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#7545]
**Is your feature request related to a problem? Please describe.**
Loading a Parquet dataset containing relatively long strings per row (e.g.: 500+ characters per row) takes quite a bit of time due to the time spent in `make_strings_column` as shown in this Nsight Systems trace:
![image](https://user-images.githubusercontent.com/1360766/110568889-5da21180-8119-11eb-862c-1632e06c0b5d.png)

It looks like `make_strings_column` may be using a row-level parallelism algorithm which will not perform well when there are a large number of characters per row.

**Describe the solution you'd like**
Ideally Parquet string decoding for long strings should be fast, whether that be via optimizing `make_strings_column` or using a different approach to string decoding altogether.  Updating `make_strings_column` to use a char-parallel algorithm may be appropriate.

**Comment by jrhemstad** [comment]
I believe this is the code that is suffering on long strings: https://github.com/rapidsai/cudf/blob/e5d0ec96da94da0f67fa7195604737f36d8e08c8/cpp/include/cudf/strings/detail/strings_column_factories.cuh#L78-L87

This could use the same treatment as your optimization to gather. In fact, I wonder if there's a way to cast this factory as a `gather` in order to take of advantage of the optimization that is already there.

**Comment by davidwendt** [comment]
This seems similar if not the same as #7571 
The `make_strings_column` was improved for long strings in #7576 
Can this be closed?

**Comment by jlowe** [comment]
Yes, this is much improved.
