### ISSUE TITLE
[BUG] Dockerfile no longer works as described in README

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/cudf#761]
- [x] Impacts #668
- [ ] Update `Dockerfile`
- [ ] Update `README.md`

If you follow the README instructions here: https://github.com/rapidsai/cudf/blob/branch-0.5/README.md#customizing-the-build

The docker container was originally designed to build cuDF from source and be customized by build arguments. The changes in this PR/commit broke that https://github.com/rapidsai/cudf/commit/3c6fea1797eb41a5c28f4b39b993313ded84ddcb#diff-3254677a7917c6c01f55212f86c57fbf

I think the commit above should be reverted to restore the original functionality and intention of the Dockerfile

@kkraus14 @randerzander @raydouglass  thoughts?

**Comment by kkraus14** [comment]
I'd defer to @randerzander here as I haven't seen how end users are using this Dockerfile / container. The PR in #668 should update that conda environment to fix these issues though.

**Comment by raydouglass** [comment]
I agree, the commit should be reverted.

**Comment by randerzander** [comment]
It still builds cuDF from source, but it pushes the package versions into the conda environment yml file.

The reason for the change, was that defining them inside the Dockerfile led to it drifting out of synch with required package versions. There were a few related issues filed due to numba, numpy, or pandas packages being incorrect in the Dockerfile.

I'm not aware of users actually using the build-args. I'm guessing the RAPIDS container build scripts did, for different Python versions?

In my opinion we should create separate conda environment files for each Python version and maintain the list of conda package versions in those files.. For instance, Python 3.7 needs a different Pandas version than Python 3.5. It would be nice for all Python-version specific conda packages to have their requisite versions defined in separate conda environment ymls.

**Comment by kkraus14** [comment]
> For instance, Python 3.7 needs a different Pandas version than Python 3.5.

Python 3.5 support is being dropped as the conda ecosystem is no longer publishing packages for Python 3.5. Pandas and other package versions are unified across Python 3.6 and 3.7.

**Comment by randerzander** [comment]
@mike-wendt I'm not clear what build-args were being used that you're missing. Can you clarify that?

Perhaps a build-arg could specify which conda environment file to use when building the cudf conda environment?

**Comment by kkraus14** [comment]
> Thanks for clearing that up, @kkraus14. However, I still prefer not defining the package versions in multiple places.
> 
> @mike-wendt I'm not clear what build-args were being used that you're missing. Can you clarify that?
> 
> Perhaps a build-arg could specify which conda environment file to use when building the cudf conda environment?

The environment file is a development environment and given people may want to integrate cuDF with other libraries, the file should be as permissive as possible with regards to package / python versions. It should only define minimum and maximum versions, because a user can always get a specific version using typical conda semantics. The Dockerfile should expose the same ability as using conda.

**Comment by mike-wendt** [comment]
> @mike-wendt I'm not clear what build-args were being used that you're missing. Can you clarify that?

@randerzander https://github.com/rapidsai/cudf/blob/branch-0.5/README.md#customizing-the-build this table here is no longer valid. Only the first three rows are actually available due to the changes in this commit. So you can no longer use the Dockerfile in the section as described.

Which is why I said we either correct the README to reflect the loss of the feature or revert the commit on the Dockerfile so people can use it as described.

**Comment by kkraus14** [comment]
So it looks like you can't combine an environment.yml file with individual package specifications so that throws a wrench in my plan...

**Comment by kkraus14** [comment]
Fixed by #773
