### ISSUE TITLE
[FEA] chunked_parquet_writer_options::_metadata should be a thrust::optional.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#7920]
Currently, the `chunked_parquet_writer_options` class has this field:

```
class chunked_parquet_writer_options {
  // Optional associated metadata.
  table_input_metadata const* _metadata = nullptr;
```

This is somewhat confusing because it looks to the user that if they pass that pointer, the parquet writer being created will end up using the data pointer to by it.  But in fact, it makes a copy of the data and then disregards the pointer entirely.  So the only reason it is a pointer is to indicate optional-ness via nullptr.  

It would be clearer if this was simply

`thrust::optional<table_input_metadata> _metadata;`

**Comment by nvdbaranec** [comment]
Still relevant

**Comment by vyasr** [comment]
@nvdbaranec it looks like this change isn't quite so simple. There's [a public API that allows users to set the metadata](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/include/cudf/io/parquet.hpp#L1027) via a pointer, which means that there is currently a way for users to have a handle on the metadata that the options object owns. I assume that this is undesirable? If so, would we want to keep the `set_metadata` API but change it to set the internal optional by value instead of just assigning to an internal pointer? That would be an API-breaking change, but probably a good one.

**Comment by vuule** [comment]
fixed with https://github.com/rapidsai/cudf/pull/13648
