### ISSUE TITLE
[FEA] Use nvbench for new benchmarks and transition old benchmarks to use nvbench

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#7960]
**Is your feature request related to a problem? Please describe.**

[nvbench](https://github.com/NVIDIA/nvbench) is a new library for writing benchmarks of GPU accelerated applications. It's similar to Google Benchmark, but has several quality of life improvements when doing GPU benchmarking, e.g., it eliminates the need for us to do manual timing in GBench with the `raii_event_timer` object. It also can show things like % of peak BW achieved and other details about the GPU hardware. 

**Describe the solution you'd like**

We have quite a few benchmarks right now, so it would take a while to transition everything to use nvbench. That said, any new benchmarks can and should be written with nvbench.

**Comment by harrism** [comment]
Oops, I've added several new benchmarks in the past two weeks before I saw this.

**Comment by harrism** [comment]
I think before we can switch nvbench would need a replacement for gbench's compare.py, which we rely on heavily.

**Comment by jrhemstad** [comment]
> I think before we can switch nvbench would need a replacement for gbench's compare.py, which we rely on heavily.

Yeah, @allisonvacanti has that on the P0 list already: https://github.com/NVIDIA/nvbench/issues/9

**Comment by vyasr** [comment]
> > I think before we can switch nvbench would need a replacement for gbench's compare.py, which we rely on heavily.
> 
> Yeah, @allisonvacanti has that on the P0 list already: [NVIDIA/nvbench#9](https://github.com/NVIDIA/nvbench/issues/9)

Do we know what next steps are on that? @shwina and I worked on getting a version of compare.py ready and it was merged a while ago, but I don't recall how much more work is necessary to bring it to feature parity with gbench's compare.py so that we can close NVIDIA/nvbench#9. I can follow up if we don't.

**Comment by karthikeyann** [comment]
> I think before we can switch nvbench would need a replacement for gbench's compare.py, which we rely on heavily.

This is implemented in https://github.com/NVIDIA/nvbench/pull/14

**Comment by karthikeyann** [comment]
Basic version is fine. Documentation might be needed. CLI could be improved. 
`benchmarksfiltered` feature might be needed.

**Comment by vyasr** [comment]
@harrism @jrhemstad Now that we're trying to get nightly benchmarks going I think we'll need to prioritize this conversion so that we can standardize the data that will be available and start building more tooling for our dashboards. I'm going to follow up on the comparison script work now to see what next steps are there.
CC @GregoryKimball @randerzander @robertmaynard

**Comment by bdice** [comment]
Shall we update our [Unit Benchmarking in libcudf Guide](https://github.com/rapidsai/cudf/blob/branch-22.04/cpp/docs/BENCHMARKING.md) to reflect the policy that new benchmarks should use nvbench? I think most of the information there still holds, it may just be a matter of updating the name of the tool we recommend.
