### ISSUE TITLE
[BUG] Pool Allocator of RMM isn't used/tested in unit tests

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#797]
We should create a session level pytest fixture to parametrize enabling the pool allocator.

**Comment by kkraus14** [comment]
@harrism @jrhemstad we should try to do the same for the GTest unit tests as well.

**Comment by harrism** [comment]
Assigning myself.

**Comment by jrhemstad** [comment]
After spending some time looking into possible alternatives, I believe the correct way to do this for GTests is to write our own `main()` instead of relying on GTests implicit `main()`.

By writing our own `main()`, we can pass command line options to the GTest executable that would allow controlling the RMM mode, e.g.,
```
int main(int argc, char **argv) {
  ::testing::InitGoogleTest(&argc, argv);
  parse_args(argc, argv);
  if( /* pool mode */)
      // init RMM w/ pool mode
  else if( /* managed */)
     // init RMM w/ managed mode
  return RUN_ALL_TESTS();
}
```

Managing the RMM mode should be encapsulated in a GTest `Environment`, as described here: https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#global-set-up-and-tear-down

Then, in CI, we can invoke the suite of all tests across all the various modes of RMM with a `bash` script, e.g.,
```
#!/bin/bash
./run_tests --mode=pool
./run_tests --mode=cuda
./run_tests --mode=managed
```

**Comment by jrhemstad** [comment]
@shwina this is the issue to run tests across all the allocator modes (both in C++ and Python).

**Comment by vuule** [comment]
With direct calls to RMM_ALLOC removed, I think there is one more task before we can close this - replace the rmmInitialize/finalize with `set_default_resource`. I'm currently looking into this with 30% of my bandwidth.

**Comment by vuule** [comment]
The changes to the GTest unit tests are complete (but now I see this issue also refers to python tests, so it should not be closed).

**Comment by harrism** [comment]
I guess we should move this to 0.15 @kkraus14

**Comment by brandon-b-miller** [comment]
I can take a look at handling the python portion of this.

**Comment by beckernick** [comment]
@brandon-b-miller @shwina in case this is relevant to a testing discussion earlier today

**Comment by vyasr** [comment]
@vuule @harrism if I'm reading our current code right our tests currently [default to running in pool mode](https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/include/cudf_test/base_fixture.hpp#L306), and the only time we test the cuda memory resource is during [nightly builds when we run cuda-memcheck](https://github.com/rapidsai/cudf/blob/branch-22.08/ci/gpu/build.sh#L203). Is that what we want, or was the intent to run tests of both cases regularly? I assume that since we haven't had any major issues in the last two years that just running with the pool is fine (especially since we do have the nightlies to catch any other issues), but I want to confirm.

@brandon-b-miller @shwina implementing this for Python should be straightforward via a parametrized autouse fixture, which I can implement unless one of you made any progress on this earlier. The question would be, do we always want tests to run both ways, or should we be doing this conditionally (e.g. only in nightlies)?

**Comment by jrhemstad** [comment]
>Is that what we want

Yes. We should only test with the pool regularly. Testing the nightly with the non-pool is sufficient.

**Comment by vyasr** [comment]
After some discussion, on the Python end we are happy with continuing to run our tests as is. We don't expect the pool to speed up our tests, and relying on RMM for primary testing and libcudf for some defensive checks should be sufficient.
