### ISSUE TITLE
[BUG] reading large .csv file returns incorrect number of rows

### ISSUE THREAD

**Issue by stokhos** [rapidsai/cudf#7994]
**What is your question?**
I have a large .csv file, which is 1.7GB. 600 million lines. I read it with `cudf.read_csv`. But only a little over 1 million lines were read by cudf. Is this the expected behavior?

**Comment by galipremsagar** [comment]
That is not expected, is the CSV file you are trying to load a publicly accessible one? If yes, could you provide us with a URL to it?

**Comment by stokhos** [comment]
No. it's a private file. The gpu i'm using it V100

**Comment by galipremsagar** [comment]
> No. it's a private file. The gpu i'm using is V100

How many columns does the csv file have?

**Comment by stokhos** [comment]
4 columns, dtype: timestamp[ms], str, float, float.
The file has 509,960,460 lines

**Comment by ayushdg** [comment]
Would it be possible to try `cudf.read_csv(..., quoting=3)` to see if that changes things? I wonder if there is something around the string column similar to #2398.

**Comment by stokhos** [comment]
> Would it be possible to try `cudf.read_csv(..., quoting=3)` to see if that changes things? I wonder if there is something around the string column similar to #2398.

No adding  "quoting=3" doesn't fix the problem

**Comment by davidwendt** [comment]
I assume no error is returned. Do any of the strings contain new-line characters?
```
timestamp, str, float1, float2
1234567890, "ab", 1.0, 2.0
1234567891, "c
d", 2.0, 4.0
```

**Comment by stokhos** [comment]
No error is returned. I'm not sure if the string contain new-line characters.

**Comment by elstehle** [comment]
I'm looking into this. I didn't manage to reproduce this yet. Would it be possible to get the `read_csv` parameters and maybe a small excerpt from what your data looks like, say, a few lines? Do you see anything special around the input lines after which it stops parsing?

**Comment by stokhos** [comment]
@elstehle I will get back to you on May 3.

**Comment by stokhos** [comment]
@elstehle For now, it is not possible to share the data. Me and my advisor are working on a paper, and I will be able to share the data after we published paper. Is there a way to debug like print the log?

**Comment by elstehle** [comment]
Thanks for following up, @stokhos. I believe that, since no error is returned, there'll be no easy indication. Maybe, if you could look at the last record that cudf had returned, then look around the input for that record in the CSV and see if you can find anything suspicious. In case there could be any special, non-printing characters, you may want to look at the CSV using `hd`. 
Could you maybe share the command that you used for reading the CSV into cudf? Are all the columns parsed correctly up to the last record and match pandas result? 
Any other pointers that you may have to help me limit the search space are much appreciated 👍 
Thanks a lot!

**Comment by GregoryKimball** [comment]
Closing this until we have better repro information
