### ISSUE TITLE
[FEA] Support for the ability to split strings by character

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#8094]
**Is your feature request related to a problem? Please describe.**
We currently have libcudf APIs that can split a string by provided delimiter, but `.str.join` is one of the API where in particular scenario, we would need to split strings by characters. For example a pandas equivalent of what we are looking to achieve is:

```python
>>> s = cudf.Series(['abc', 'def', 'gh i'])
>>> s
0     abc
1     def
2    gh i
dtype: object
>>> s.to_pandas().map(list)
0       [a, b, c]
1       [d, e, f]
2    [g, h,  , i]
dtype: object
```

In cudf land, we are essentially trying to convert a string series to list series where all the characters are stored in lists.

**Describe the solution you'd like**
A libcudf API to split by character would be more efficient than the following approach.

**Describe alternatives you've considered**
We have currently implemented this using combination of `character_tokenize` + `count_bytes` APIs as follows:

https://github.com/galipremsagar/cudf/blob/49e92489efe9240ac8cc9cb6f215d26f931c6b6e/python/cudf/cudf/core/column/string.py#L635-L654

**Additional context**
https://github.com/rapidsai/cudf/pull/8085#discussion_r621734606

**Comment by kkraus14** [comment]
@galipremsagar I actually meant to raise an issue to allow string concatenation by character similar to what we do for lists currently, but this is useful as well!

**Comment by davidwendt** [comment]
So I think there is a more efficient way to build the list result without needing any new libcudf APIs.
Using the following example strings column `['abc', 'def', 'gh i']` which has 2 child columns:
```
  chars   = [abcdefgh i]
  offsets = [0,3,6,10]
```
Applying the `character_tokenize` returns the following strings column: `['a','b','c','d','e','f','g','h',' ','i']`
```
  chars   = [abcdefgh i]
  offsets = [0,1,2,3,4,5,6,7,8,9,10]
```
To build the desired lists column `[ ['a','b','c'], ['d','e','f'], ['g','h',' ','i'] ]` would only require building its offsets child column. 
Fortunately, this is identical to the original strings offsets: `[0,3,6,10]`
So there is no need to call `counts_bytes()` and sum-scan them to build the offsets since this would just create the same result.
Just simply copy the offsets column child from the original strings column.
This will work even with multi-byte characters.
