### ISSUE TITLE
cuDF exception : "Deserialization failed"

### ISSUE THREAD

**Issue by eyalhir74** [rapidsai/cudf#8456]
Hi,
  Kinda new to this, so any guidance would be appreciated.
  I am able to run the small join example here (https://nvidia.github.io/spark-rapids/docs/get-started/getting-started-on-prem.html) using a local spark server and via the spark shell command.

  However when I try to run this:
`       Dataset<Row> df = spark.read().option("delimiter", "|").csv("data/lineitem_6MRows.tbl");
        df.printSchema();
`
 
  I get the following execption:
`
21/06/08 16:16:37 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
ai.rapids.cudf.CudfException: Deserialization failed
	at ai.rapids.cudf.ColumnView.binaryOpVS(Native Method)
	at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:1008)
	at ai.rapids.cudf.ColumnView.binaryOp(ColumnView.java:998)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar(GpuExpressions.scala:191)
	at com.nvidia.spark.rapids.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:185)......
.....
`

  As far as I can see, the POM is correct. I work with Ubuntu 20.4 and Cuda 11.0
  POM:
`
<dependency>
      <groupId>com.nvidia</groupId>
      <artifactId>rapids-4-spark_2.12</artifactId>
      <version>0.5.0</version>
    </dependency>
    <dependency>
      <groupId>ai.rapids</groupId>
      <artifactId>cudf</artifactId>
      <version>0.19.2</version>
      <classifier>cuda11</classifier>
    </dependency>
`

  Any assistance would be great.
Thanks
Eyal

**Comment by quasiben** [comment]
@jlowe do you have time to look at this ?

**Comment by revans2** [comment]
@eyalhir74 in the future this should probably be filed under https://github.com/NVIDIA/spark-rapids/issues/new/choose because you are using Spark and the Spark team should probably dig into it before the cudf team takes a crack at it.

In this case the error "Deserialization failed" appears to refer to a problem reading from the jit cache for jitify2, and because I am not an expert on that I would have to bug the cudf team anyways so we can probably keep it here.

Is this running on a distributed cluster or locally? If it is local could you try moving `~/.cudf/` to a new location and then running this again?  `~/.cudf/` holds a JIT cache for various binary operations.  We are in the process of moving away from JIT for this, but it is not done yet. If that does work it might be nice to try and reproduce this here so we can debug it.  Would you be okay with sharing the contents of your `~/.cudf/` cache with us and also "data/lineitem_6MRows.tbl"?

**Comment by eyalhir74** [comment]
Hi @revans2  ,
  I am running on a local machine. Removing the ~/.cudf/ solved the problem. Thanks!
  Would you still be interested in the content of the ~/.cudf folder?

thanks
Eyal

**Comment by revans2** [comment]
@cwharris you seem to be the jitify2 expert here.  Would you be interested in trying to understand how `~/.cudf/` was corrupted for @eyalhir74? Me personally I am not too concerned because we are moving away from JIT for binary ops, which is where most of the usage is in Spark.  If you do want to try and reproduce the issue I am happy to help with it.

**Comment by cwharris** [comment]
Are you using nightly releases? JIT cache keys hashes based on cudf version number, among other things, but the hash does not differ based on pre-processed JIT kernel source code, so it is possible that the kernel (or one of it's includes) was updated, and therefore the cache became invalid in between minor version releases.

The solution is to include a hash of the source kernel code in the hash of each cached jit kerne instance. This work is planned and has been discuessed here: https://github.com/rapidsai/cudf/issues/6689

**Comment by revans2** [comment]
@cwharris I don't think there were any nightly releases being used.  @eyalhir74 was just following the getting started guide for Spark when he ran into this.  Also looking at the code, the only time that "Deserialization failed" is thrown, is if the data was either corrupted (meaning the magic number is wrong or the serialization version is wrong) or the data was truncated.  My guess is that something bad happened and the cache started to write a file but didn't finish.

**Comment by cwharris** [comment]
that line of reasoning makes sense to me. if this is a clean install and there was some kind of interruption while the cache files were being generated, I'd expect a failure. Deleting ~/.cudf would be the appropriate solution, and that seems to have resolved the reported issue.

There's any number of reasons why a file write might fail, though. If this happens again, it could be worth investigating.

**Comment by revans2** [comment]
OK @eyalhir74 I guess we are OK without digging into it for now. If you do run into it again please let us know.

**Comment by eyalhir74** [comment]
@revans2 Great. It is running fine now.
I do have a general question though please.
Is there a Rapids/cuDF developer forum where we can ask questions (usability/performance/guidelines/general questions/etc...) and consult? like there is for CUDA?

thanks
Eyal

**Comment by revans2** [comment]
> @revans2 Great. It is running fine now.
> I do have a general question though please.
> Is there a Rapids/cuDF developer forum where we can ask questions (usability/performance/guidelines/general questions/etc...) and consult? like there is for CUDA?
> 
> thanks
> Eyal

There isn't one specifically for the Spark plugin. 

But if you go to https://rapids.ai/community.html and scroll to the bottom there are links to a Slack channel, stack overflow, and a google group.
