### ISSUE TITLE
[BUG] Groupby collect on struct columns losing field name

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#8474]
**Describe the bug**
Groupby collect aggregation on a struct columns causes loss of the struct field names in the output

**Steps/Code to reproduce bug**
```python
df = cudf.DataFrame(
    {
        'a':['aa','aa','cc'],
        'd':[{"b": '1', "c": "one"}, {"b": '2', "c": "two"}, {"b": '3', "c": "one"}]
     }
)

df
	a	d
0	aa	{'b': '1', 'c': 'one'}
1	aa	{'b': '2', 'c': 'two'}
2	cc	{'b': '3', 'c': 'one'}

df.groupby('a').collect()

	d
a	
aa	[{'0': '1', '1': 'one'}, {'0': '2', '1': 'two'}]
cc	[{'0': '3', '1': 'one'}]
```

**Expected behavior**
```python
	d
a	
aa	[{'b': '1', 'c': 'one'}, {'b': '2', 'c': 'two'}]
cc	[{'b': '3', 'c': 'one'}]
```

**Environment overview (please complete the following information)**
- Docker nightly (21.08)

**Comment by charlesbluca** [comment]
Are we expecting libcudf's groupby agg to return the underlying struct column with its metadata? If not, the fix here might be to reapply the source `StructColumn`'s metadata to the resulting column's elements before returning. 

That being said, I think the underlying issue here might be that we shouldn't be allowing for a collect agg on `StructColumns` in the first place; looking in `groupby.pyx`, we can see that no aggs should be possible for `StructColumns`:

https://github.com/rapidsai/cudf/blob/0a4e8a1c860518c9e30f5289dea07bd0879fb642/python/cudf/cudf/_lib/groupby.pyx#L42-L51

But we erroneously use `_STRING_AGGS` for struct dtypes:

https://github.com/rapidsai/cudf/blob/0a4e8a1c860518c9e30f5289dea07bd0879fb642/python/cudf/cudf/_lib/groupby.pyx#L139

**Comment by charlesbluca** [comment]
Opened up an issue to address the underlying bug #8499; though in theory, we should have been able to fix this bug by simply applying the input column's metadata to the resulting list's elements. This might be worth exploring if we want to add the collect agg later on.
