### ISSUE TITLE
[BUG] cudaErrorIllegalAddress when doing a min or max scan on large string columns

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8684]
**Describe the bug**
When I try to do a min or max scan on large string columns I get

```
C++ exception with description "inclusive_scan failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered" thrown in the test body.
```

**Steps/Code to reproduce bug**
```diff
diff --git a/cpp/tests/reductions/scan_tests.cpp b/cpp/tests/reductions/scan_tests.cpp
index 92ba1f9e60..47ce656b57 100644
--- a/cpp/tests/reductions/scan_tests.cpp
+++ b/cpp/tests/reductions/scan_tests.cpp
@@ -290,6 +290,26 @@ struct ScanTest : public cudf::test::BaseFixture {
   }
 };
 
+
+class BigScanTest : public ::testing::Test {
+};
+
+
+TEST_F(BigScanTest, StringsTest)
+{
+  std::vector<std::string> test_data;
+  for (int i = 0; i < 512; i++) {
+    test_data.emplace_back("a");
+  }
+
+  cudf::test::strings_column_wrapper col(test_data.begin(), test_data.end());
+  cudf::test::print(col);
+  // Both aggregations get an IllegalMemoryAccess error
+  //auto agg = cudf::make_max_aggregation();
+  auto agg = cudf::make_min_aggregation();
+  auto result = cudf::scan(col, agg, cudf::scan_type::INCLUSIVE);
+}
+
 using Types = cudf::test::Concat<cudf::test::NumericTypes,
                                  cudf::test::FixedPointTypes,
                                  cudf::test::Types<cudf::string_view>>;
```

Then run the tests. This happens for both min and max. It starts to work when you use a lot fewer values (like 256 instead of 512).

**Comment by harrism** [comment]
I have a local repro, thanks @revans2 . I don't understand how scans of strings ever worked -- the code currently assumes that the scanned result will fit in an array of the same size as the input.

**Comment by harrism** [comment]
@davidwendt to make this work correctly requires scanning the string_view `size_bytes()` sizes first with a min-scan, using that to allocate output space, then performing the min-scan on the string data, then scanning the nulls, and finally constructing the resulting strings column.

I found `cudf::strings::detail::child_offsets_from_string_iterator` which helps with the first step, but how do we properly perform the min-scan on the string data since it contains multibyte characters? Is there a utility to help with this part?

**Comment by davidwendt** [comment]
This definitely should work as currently implemented. The `rmm::device_uvector<string_view>` is not much different than `rmm::device_uvector<thrust::pair<const char*,size_type>>` and the inclusive-scan should just be shuffling these around since `string_view` has `operator<` and such. The `make_strings_column` at the end does a gather-like operation to convert the vector of `string_view`s back into a strings column.

Some initial debugging shows that inclusive-scan seems to be passing garbage to the Operator functor so there may be a bug with thrust. I will try to build a small standalone testcase.

**Comment by davidwendt** [comment]
Filed an issue with thrust: https://github.com/NVIDIA/thrust/issues/1479
Currently working on a workaround.
