### ISSUE TITLE
[QST] About ORC reader reads multiple ORC files

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#8993]
``` python
import cudf
df = cudf.read_orc('/tmp/row-stripe*.orc')
```

Above python code reads all `"row-stripe*.orc"` under /tmp directory into a table. So what I'm asking is what the cudf Orc Reader will do when the orc files have different things like version/RowInStripes/Encryption/Compression ...?

For JAVA In ORC open source code, there are [many checks](https://github.com/apache/orc/blob/a9a528693828ab4addf4607bb8da15a6027fe21b/java/core/src/java/org/apache/orc/OrcFile.java#L1111) when trying to merge ORC files.  So what about CUDF?

**Comment by ayushdg** [comment]
cc @jdye64

**Comment by jdye64** [comment]
CUDF follows these rules for for reading in multiple ORC files.

- Each file must have the same compression type, really this isn't a technical requirement and we could change it to not be this way but did it to follow the same way Java does it
- Encryption is not handled by CUDF
- The number of columns and types of each column must match exactly. Otherwise an exception will be raised explaining this
- Differing ORC versions is currently ok as the reader will adjust to using the appropriate implementation based on the ORC footer information.

This is not all of the checks but you can find these [here](https://github.com/rapidsai/cudf/blob/branch-21.10/cpp/src/io/orc/reader_impl.cu#L325) to see what is happening

**Comment by wbo4958** [comment]
Thx for the info, Close this issue.
