### ISSUE TITLE
[FEA] Expand support for cupy universal functions (ufuncs)

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#9083]
Using numpy/cupy universal functions (ufuncs) directly on dataframes is a common usage pattern that we partially support today. https://github.com/rapidsai/cudf/issues/256 requested support for a comprehensive set of ufuncs. Many of these ufuncs are now supported on Series through a codepath that hits:

https://github.com/rapidsai/cudf/blob/417b34df0f91593c90d688def32f1bddf4b4b52c/python/cudf/cudf/utils/utils.py#L331-L334

For DataFrames, we dispatch only a small subset of functions enumerated in https://github.com/rapidsai/cudf/blob/be25a30ca20f3135f341c51b36cb075b376d5def/python/cudf/cudf/core/ops.py

It would be nice to expand our support for ufuncs on DataFrames (and Series as appropriate). As @vyasr noted offline, we may want to explore our approach to this dispatch as well.

When we don't support a ufunc, we get the following with direct usage of the cupy ufunc:

```python
import cudf
import numpy as np
​
df = cudf.DataFrame({
    "a": [0,1,2],
    "b": [0,1,2]
})
​
cp.isinf(df)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_89993/1699247483.py in <module>
      7 })
      8 
----> 9 cp.isinf(df)

cupy/_core/_kernel.pyx in cupy._core._kernel.ufunc.__call__()

cupy/_core/_kernel.pyx in cupy._core._kernel._preprocess_args()

TypeError: Unsupported type <class 'cudf.core.dataframe.DataFrame'>
```

If we rely on the array function protocol to dispatch first from numpy to cupy, we get the following:

```python
import cudf
import cupy as cp
​
df = cudf.DataFrame({
    "a": [0,1,2],
    "b": [0,1,2]
})
​
np.isinf(df)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_89993/695126611.py in <module>
      7 })
      8 
----> 9 np.isinf(df)

TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'isinf'>, '__call__',    a  b
0  0  0
1  1  1
2  2  2): 'DataFrame'
```

**Comment by vyasr** [comment]
Yes, I think we want to unify our approach to `__array_ufunc__` and `__array_function__` a bit more and standardize across `Series` and `DataFrame`. In the best case, our current approach to dispatch is roughly the following cascade of attempts:
1. Use a method in the `cudf` namespace with the desired name if one exists.
2. Use a class method with this name if one exists.
3. Dispatch to cupy if cupy has the method.

I say best case because I think `DataFrame.__array_ufunc__` only does (1) as @beckernick pointed out above. This is another case where not having a single source of truth hurts us because it's not necessarily obvious which methods will get dispatched and how. I think unifying at least the lookup logic between these two classes would help alleviate one source of confusion since `Series` calls `get_appropriate_dispatched_func` while `DataFrame` does not. It would also help to get rid of (1) entirely IMO because that code path is essentially just a trivial wrapper around (2) anyway. In that case we may be able to get rid of our current `ops.py` module entirely (although I think there may be one other use case for it somewhere that I've forgotten); although `pandas.core.ops` does exist, it contains very different methods from `cudf.core.ops` so I would be OK removing ours for now if we could work around its uses.

**Comment by bdice** [comment]
Following up on this -- we should update the dispatch so that we do not define all the ufuncs (`add`, `arccos`, `arcsin`, ..., `log`, `logical_and`, ...) in the root namespace like `cudf.add`.

See also this list of available ufuncs in NumPy: https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs
