### ISSUE TITLE
[FEA] Rename the API `parent()` for various derived classes of `cudf::column_view`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#9111]
Currently, various derived classes of `cudf::column_view` such as `dictionary_column_view`, `strings_column_view` etc have a public API `parent()` which returns a `column_view` object that is casted from the current object. So, it just casts the current object to an object of another type, not returning any "parent" object. Because of that, using the name `parent()` here is very confusing/incorrect. In my impression, `parent()` should return the `column_view` object of the parent column of the current column, not another view of the current column.

I would like to rename it to something else that is more intuitive and less error-prone. The name `get_column_view()` can express its purpose in the best way, but seems to be lengthy. Some other name such as just `column_view()` is fine. Any other better suggestion would be great.

**Comment by harrism** [comment]
An (implicit or explicit) cast operator to `column_view`, perhaps? CC @jrhemstad

**Comment by davidwendt** [comment]
The `strings_column_view` and `dictionary_column_view` are not `column_view's` (despite the name) but rather wrappers in _has a_ instead of _is a_  relationship with `column_view`. Using private inheritance for _has a_  relationship is described [here](https://isocpp.org/wiki/faq/private-inheritance) and also mentioned by Scott Meyer's Effective C++ in item 39.

So these classes are convenient wrappers over the components of the column it is wrapping. The components of a strings column are the parent, offsets, and chars. Therefore, the accessors to those components are `parent()`, `offsets()` and `chars()`. The private inheritance avoids having the _has a_ class to declare a member variable but an accessor is still required.

**Comment by jrhemstad** [comment]
Exactly as @davidwendt said, the fact that the `parent()` function casts the `strings_column_view` object to a `column_view` is an implementation detail. It could just as well been that a `strings_column_view` had a `column_view` member in which case the `parent()` function would return that member `column_view`.

The point is that these classes encapsulate the logical concept of a strings/lists/structs column including the parent and children. Thus, the "parent" terminology is the correct one. How the `parent` is manifested is an implementation detail.

**Comment by ttnghia** [comment]
Whether or not the `column_view` is the "parent" **super class**, the name "parent" intuitively says "it is the parent column of the current column", not "view the current column by a parent type". You could argue that "it is implementation detail" and we can know exactly what it is doing by looking at the code. But I could also argue that I want to have a name that exposes its purpose in the most intuitive way, nobody needs to look at the code to understand its meaning.

**Comment by jrhemstad** [comment]
> the name "parent" intuitively says "it is the parent column of the current column"

I think that's a fundamental misunderstanding of what `strings_column_view` et al. represent.

A `strings_column_view` doesn't itself have a parent. A `strings_column_view` _contains_ a parent column (the one that owns the size and null mask) in addition to the two children (chars and offsets).

**Comment by ttnghia** [comment]
Thanks Jake. I understood the data structure. I want to stress that I want to change the name `parent` because it is not "intuitive" that anybody has to spend some time to figure out what it is (by reading the code) and understand why it is implemented that way. I believe that everybody had to read its implementation because of that. If somebody is new to the system, he/she may misunderstand until reading the implementation (`return static_cast<column_view>(*this)`). So, it would be great to have a better name that anybody can understand immediately in the correct way.

**Comment by davidwendt** [comment]
Can we close this now?

**Comment by shwina** [comment]
Without reading the implementation, I'd have to agree that `parent` sounds very much like a column whose `child` is *this* column :-)

**Comment by harrism** [comment]
If nothing else, it is clear that this naming is nonintuitive.

>  The components of a strings column are the parent, offsets, and chars. Therefore, the accessors to those components are parent(), offsets() and chars(). 

I can't find a definition of a "strings column" type. If one existed, I would think that a `strings_column_view` would be constructable from it, but `strings_column_view` is only constructable from `column_view`. `column_view` and `column` do not have a member or method called `parent`. `column_view` *does* have a concept of "parent", embodied in this function, which I would argue *is* intuitive.

```
/**
 * @brief Counts the number of descendants of the specified parent.
 *
 * @param parent The parent whose descendants will be counted
 * @return size_type The number of descendants of the parent
 */
size_type count_descendants(column_view parent);
```
So my question is this: in a strings column, what actually is the "parent"? Perhaps there is a better name for it.

**Comment by jrhemstad** [comment]
> I can't find a definition of a "strings column" type

`strings_column_view` _is_ the definition of a "strings column" type. It's sole purpose for existing is to codify things like which child is the offsets, which is the chars, where does the offset live, where does the nullmask live, etc. 

> `column_view` and `column` do not have a member or method called parent

That's because any arbitrary column may not contain a parent. i.e., what would `column_view::parent()` mean when `column.type() == INT32`? 

`strings_column_view` is a more specialized type than a generic `column_view` to expressly communicate things like "Hey, this column has 3 components. Here's how you access them without having to worry about the implementation details of which child is which, where the null mask lives, etc"

> in a strings column, what actually is the "parent"?

Just to be very pedantic, a strings column is a logical concept physically composed of three individual columns. 

1. One column's type is `STRING` and holds the bitmask indicating the validity of each string, the count of the number of strings, and the logical offset. 

2. The second column's type is `INT8` and contains all of the concatenated characters of all the strings. The `size` is the number of characters. It does not have an offset and does not have a validity bitmask.

3. The final column's type is `INT32` and contains the offset of the beginning of each string into the second column. The size is the number of strings + 1. It contains no offset nor validity bitmask. 

As it happens, 2 and 3 are stored as children of 1. Thus, we refer to 1 as the "parent".

**Comment by jrhemstad** [comment]
@davidwendt and I were talking and it's likely we can just remove the `strings_column_view::parent` API all together (or at least make it private). David is investigating.

**Comment by harrism** [comment]
I'm my own grandpa

**Comment by GregoryKimball** [comment]
We made a good effort to try and remove the `strings_column_view::parent` API as a solution to this issue but we could not make that work. For now I'll close this issue.

**Comment by ttnghia** [comment]
This is not to remove anything. Instead, it's asking for renaming.
