### ISSUE TITLE
[BUG] Odd behavior with byte_ranges kw in read_csv

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#928]
## setup

- cudf.__version__:  '0.6.0.dev0+356.g3079090.dirty'
- bare metal

## data

```
a,b,c
1,2,0
3,4,0
5,6,0
7,8,0
```

cudf, without `byte_range` correctly reads the csv:

```
In [10]: cudf.read_csv('example.csv').to_pandas()
Out[10]:
   a  b  c
0  1  2  0
1  3  4  0
2  5  6  0
3  7  8  0
```

When using `byte_range`, with a size larger than the file, the last row is missing:

```
In [12]: cudf.read_csv('/home/nfs/bzaitlen/example.csv', byte_range=(0,int(25e6))).to_pandas()
Out[12]:
   a  b  c
0  1  2  0
1  3  4  0
2  5  6  0
```

Am I doing something incorrect here? Perhaps, I need to define another kwarg along with `byte_range` ?

In playing around further, I found that adding the `names` produced a rather interesting output:
```
In [14]: cudf.read_csv('/home/nfs/bzaitlen/example.csv', byte_range=(0,int(25e6)), names=['a', 'b', 'c']).to_pandas()
Out[14]:
            a           b           c
0  -478287406 -2100116156  1838231202
1  1557606259   522772239   924163256
2  -510988378 -1087772063   924163256
3  -334873126 -1355884552   924163256
```

**Comment by quasiben** [comment]
cc @kkraus14

**Comment by mrocklin** [comment]
cc also @mjsamoht

**Comment by vuule** [comment]
The PR in progress addresses the original issue, where the last row is missing.

The issue with the names parameter set is not related to byte_range: header is implicitly set to None. This means that the first row in the file is treated as a data row. In this case, cudf infers that the data types are int32 and the parsing fails because the data does not conform to the format. You can avoid this issue with skiprows.
However, even with the malformed data in the first row, I would expect the rest of the dataframe to have correct values. I can look into this next.

**Comment by vuule** [comment]
It appears that type deduction infers GDF_CATEGORY for the type when some of the data is string-like (and we have a,b,c,d,e in a data row now). In category columns, data is converted into hash values, and this is the output you see. 

This is expected behavior, at least until read_csv gets full string support.
