### ISSUE TITLE
[QST] Should Series.merge be removed?

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#9316]
**What is your question?**
There is a cuDF method [`Series.merge`](https://github.com/rapidsai/cudf/blob/4de968e2b1281c038bec7d5edb784668371dbca7/python/cudf/cudf/core/series.py#L4909). However, there is no corresponding `Series.merge` in pandas. This method was added in #4044 and revised in #5023. There is also [no docstring](https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.Series.merge.html) (as of 21.10 nightly).

I chatted with @brandon-b-miller (original author) and it sounds like the `Series.merge` method may not need to exist. He looked back over some earlier design discussions and there did not appear to be a clear historical need for this feature.

It may be possible to remove (or deprecate, then remove) the `Series.merge` method. If the feature is removed, users should create a one-column DataFrame from the Series and call `DataFrame.merge` for equivalent behavior.

The `Series.merge` method is tested in only one place, when "Series" is provided as an argument for `lhs` here:
https://github.com/rapidsai/cudf/blob/4de968e2b1281c038bec7d5edb784668371dbca7/python/cudf/cudf/tests/test_joining.py#L1781-L1830

**Comment by vyasr** [comment]
I'm in favor of removing this method. The only caveat I would add is that we should validate that `cudf.merge` behaves identically to `pd.merge` when one of the arguments is a `Series`. I notice that the [`pd.merge` documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.merge.html) says that `left` should be a `DataFrame` while `right` could be a `DataFrame` or a `Series`, but in practice I am able to perform a merge with the opposite data types. Since `cudf.merge` is basically a trivial alias for `cudf.DataFrame.merge`, I don't think our `merge` functionality will match pandas, so we should aim for feature parity in the treatment of `Series` objects before we remove `Series.merge`.

**Comment by vyasr** [comment]
This was resolved by #10450. `Series.merge` has been removed, but `cudf.merge(series, dataframe)` will automatically upcast `series` to a `DataFrame`, matching the `pandas.merge` behavior.
