### ISSUE TITLE
[FEA] numeric::detail::ipow optimization for Base 10 & 2

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9346]
**Is your feature request related to a problem? Please describe.**

The [`ipow`](https://github.com/rapidsai/cudf/blob/b4560f4e0991f140d3625f8f96c4c8943ca15686/cpp/include/cudf/fixed_point/fixed_point.hpp#L62-L94) function is used in the internals of the `fixed_point` type for rescaling operations. 

The current implementation uses a generic iterative algorithm. 

This can be optimized for both base 10 and base 2 using a lookup table instead of an iterative algorithm.

For example, for base 10: https://godbolt.org/z/orocxrMsr

(Note: This implementation is limited to 10^19. However, this is fine as 19 is the maximum scale value for `decimal64`)

Quickbench: https://quick-bench.com/q/J5IueamHNsXNVAqbRbUKUgFF5zM

**Describe the solution you'd like**

Add specializations for `ipow` for base 10 (optionally base 2) to use a lookup table based implementation.

**Comment by jrhemstad** [comment]
https://godbolt.org/z/fsdodc6n3

Updated the implementation to work for either base 2 or base 10.

**Comment by pmattione-nvidia** [comment]
In the end this cannot be done, as it adds too much register pressure to kernels that don't even use decimals, slowing them down significantly.  Why did unrelated kernels get slower?  Because we're using the type_dispatcher inside of kernels, and so templated functions for all types (int/float/decimal/etc) are inlined directly into the kernels.
