### ISSUE TITLE
[FEA] Make CMake style check used in CI easy to run locally

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#9396]
**Is your feature request related to a problem? Please describe.**

It's easy for developers to run the C++ and Python linters that get run in CI locally. I would like the same to be true of cmake style. Right now, fixing cmake style errors is an iterative process of looking at CI output, fixing locally, pushing, and then seeing more errors in the CI check and repeating.

**Describe the solution you'd like**
Include a shell script in the repo for running cmake style checks, like we have with `run-clang-format.sh`.

**Additional context**

I ran into this working on RMM, but it applies to cuDF and other repos as well, so I filed it here for visibility.

CC @robertmaynard

**Comment by vyasr** [comment]
I could be wrong, but while I see runs of `cmake-format` and `cmake-lint` in rmm's [style check CI script](https://github.com/rapidsai/rmm/blob/branch-21.12/ci/checks/style.sh), I don't see one in [cudf's CI](https://github.com/rapidsai/cudf/blob/branch-21.12/ci/checks/style.sh). That's not to say that we shouldn't do that linting, I would definitely be in favor of that.

Both clang-format and all of the linters that we use for cuDF Python (black, isort, flake8) are currently configured to work with [pre-commit](https://pre-commit.com/) as well as by running them directly (and in clang-format's case, using the `run-calng-format.sh` script). I'm currently working on #9309, which aims to unify all Python linting using pre-commit. There are a number of benefits discussed in #9309, but the short version is that it gives us a single source of truth for maintaining desired linter versions while also making it easier for different RAPIDS libs to use different versions of the same linters if necessary. I'm only planning to touch Python linters when resolving #9309 since I expect that switching to pre-commit will be a (slightly) larger energy barrier for libcudf developers who aren't accustomed to it, but I have previously set up `cmake-format` to run via pre-commit on a different project and would be happy to do that for cudf as a follow-up. This is probably something worth discussing more before making any decision, but in the long run I think it would be preferable to centralize on pre-commit since in addition to making it easy to run (using something like `pre-commit run cmake-format --all-files`) it also allows (but does not require) users to automatically set up Git hooks for linting

**Comment by harrism** [comment]
I prefer format-on-save and automatic in-IDE linter plugins (e.g. clangd).  Precommit only lints when I commit, which is not frequently enough IMO.

**Comment by robertmaynard** [comment]
> For more clarity (after talking to Vyas offline), in this issue I'm purely asking for the prerequisites to run cmake-format locally. Specifically, that means that the `cmake-format-rapids-cmake.json` configuration file be available as part of the repo.
> 
> Now as I'm typing this, I'm noticing that that file is installed into `build/_deps/rapids-cmake-src` when you build locally. So perhaps the prerequisites are already here.

Yes for developers the requisite files will exist once a build directory exists. CI runs the formatting pass without generating a build directory and therefore needs to fetch the file from the internet explicitly.
