### ISSUE TITLE
[BUG] Missing Boundaries

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#946]
In fully exploring the resolution for #928 @mrocklin and I noticed a potential bug around how boundaries are parsed when using `read_csv` .  Below is example code which demonstrates a missing row when using `byte_range`.   Additionally, we show a segfault when seeking past the size of the file
## Setup
- cudf version: '0.6.0.dev0+403.g00be629.dirty'
- bare metal

## Working Example Code
```python
import os
import numpy as np
import cudf
import pandas as pd
df = pd.DataFrame(dict(x=np.arange(10), y=np.arange(10)))
df.to_csv('myfile.csv')

a = cudf.read_csv('myfile.csv', byte_range=(0, 50))
b = cudf.read_csv('myfile.csv', byte_range=(50, 50), header=None, names=a.columns)

with open('myfile.csv') as f:
    data = f.read()

print(df)
print(a.to_pandas())
print(b.to_pandas())

print("50th byte is within the line of sevens")
print(data[50:55])
print("context (bytes 40-60):", data[40: 60])

c = cudf.read_csv('myfile.csv', byte_range=(1000, 50))  # segfaults
```

## Output
```
   x  y
0  0  0
1  1  1
2  2  2
3  3  3
4  4  4
5  5  5
6  6  6
7  7  7
8  8  8
9  9  9
   Unnamed: 0  x  y
0           0  0  0
1           1  1  1
2           2  2  2
3           3  3  3
4           4  4  4
5           5  5  5
6           6  6  6
   Unnamed: 0  x  y
0           8  8  8
1           9  9  9
50th byte is within the line of sevens
,7
8,
context (bytes 40-60):
6,6,6
7,7,7
8,8,8
9
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    c = cudf.read_csv('myfile.csv', byte_range=(1000, 50))  # segfaults
  File "/home/nfs/bzaitlen/GitRepos/cudf/python/cudf/io/csv.py", line 345, in read_csv
    libgdf.read_csv(csv_reader)
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/site-packages/libgdf_cffi/wrapper.py", line 27, in wrap
    raise GDFError(errname, msg)
libgdf_cffi.wrapper.GDFError: GDF_INVALID_API_CALL
```

Notice that `row 7` is missing cudf frames a,b.  As a sanity check, are we correctly using the appropriate `kwargs` in the `read_csv` call ?

cc @vuule @kkraus14

**Comment by kkraus14** [comment]
cc @mjsamoht

**Comment by mjsamoht** [comment]
cc @vuule to comment since he is most familiar

My understanding is that:
- If the byte range **starts** in the middle of a record this record will **not** be returned (`a` in your example)
- If the byte range **ends** in the middle of a record this record will **not** be returned (`b` in your example)
We have to discuss how we want to handle this since `dask` won't be able to split at record boundaries. 

Regarding `c` I don't believe there is a segfault.  `read_csv()` returns `GDF_INVALID_API_CALL` from the function `uploadDataToDevice` in the first check because there are no records:
`GDF_REQUIRE(raw_csv->num_records > raw_csv->skiprows, GDF_INVALID_API_CALL);`

IMO we should validate that the byte range is non-zero and return a specific error code if it is zero.  Right now we bail out much later in `read_csv()` with a generic `GDF_INVALID_API_CALL` error code.

**Comment by mrocklin** [comment]
> * If the byte range **ends** in the middle of a record this record will **not** be returned (`b` in your example)

I think that we should probably include these.  That way we can select ranges like 

-  (0, 100)
-  (100, 100)
-  (200, 100)
-  (300, 100)
- ...

And know that every record is counted exactly once.

**Comment by mrocklin** [comment]
My apologies about the segfault comment, you're right.  Mostly I think that the ask here is a nicer error message, though this is much lower priority than the dropped record.

**Comment by mjsamoht** [comment]
Had a quick chat with @mrocklin 

- If the input is a **file** and the byte range **ends** in the middle of a record, `read_csv()` should return that record.  This means we have to read past the end of the byte range to get the complete record.
- If the input is a **file** and the byte range **begins** in the middle of a record, `read_csv()` should skip that first, partial record.
- If the input is a **buffer** we can try to implement the same type of behavior or simply disallow the combination of buffer input and byte ranges.

**Comment by mrocklin** [comment]
+1

**Comment by vuule** [comment]
The POR described above is what I had in mind when implementing the feature. You can see the intended behavior in the documentation for the new parameters.  You are using the API as expected. Any missing rows are due to a bug and I'll look into this tomorrow.
The interesting part is that we have a test for this use case, and it's passing. I'm starting to suspect that the test is not valid.

**Comment by mrocklin** [comment]
Thanks for clarifying @vuule .  

I should also point out that, except for these occasional missing rows, using the API and implementation that you've provided everything seems to work great.  It has been a pleasure to work with so far :)

**Comment by vuule** [comment]
@mrocklin Regarding the error message when the offset is too large: 
I can see the debug message "The offset is too high" when running the tests with such offset. Maybe you don't have the std output enabled when you are running the tests? I'll change the message to clarify that the issue is about the byte_range offset. 
The only other improvement that I can think of is to change the error code to better reflect the issue. Maybe GDF_INVALID_API_CALL would be clearer?
