### ISSUE TITLE
How to read massive data files (60G) on multiple GPUs? 

### ISSUE THREAD

**Issue by yangl57** [rapidsai/cudf#9584]
I want to read the dataframes on multiple GPUs before running XGBoost. However, client.persist takes forever for me...

My current implementation follows: 
```
cluster = LocalCUDACluster(n_workers=3) ## I have three GPUs 
client = Client(cluster)
df_train_feature = pd.DataFrame(train_feature, ... )
df_train_label = pd.DataFrame(y_train[:,2756], ...)
df_train_feature = dask_cudf.from_cudf(df_train_feature, npartitions=38663)
df_train_label = dask_cudf.from_cudf(df_train_label, npartitions=38663)
```

`X_train, y_train = client.persist([df_train_feature, df_train_label])
`****** I am currently on this step and it takes forever while the memory usage of GPUs from nvidia-smi doesn't change
`wait([X_train, y_train])`

My next steps are:

```
Xy = dxgb.DaskDeviceQuantileDMatrix(client, X_train, y_train)

booster = dxgb.train(
                 client,
                 {
                     "objective": "binary:logistic",
                     "tree_method": "gpu_hist",
                 },
                 Xy, 
                 num_boost_round=1000,
                 early_stopping_rounds=10
              )["booster"]

```

Previously, I doing this but had memory error. Only a single GPU takes the data.   

```
df_train_feature = cudf.DataFrame.from_pandas(df_train_feature)
df_train_label = cudf.DataFrame.from_pandas(df_train_label[:,2756])
```
<img width="578" alt="Screen Shot 2021-11-02 at 8 59 49 PM" src="https://user-images.githubusercontent.com/15113700/140012169-ea4ecdf2-4496-44e3-b1f7-a34131a92e34.png">

What would be an efficient way to read the massive data on multiple gpus before the XGBoost computation? Thank you for your help in advance.

**Comment by beckernick** [comment]
You should read your data directly with Dask rather than using cuDF to read it into a single GPU first.

You may find this [blog on reading larger than memory CSVs(https://medium.com/rapids-ai/reading-larger-than-memory-csvs-with-rapids-and-dask-e6e27dfa6c0f) and this [blog on multi-GPU XGBoost training with Dask](https://developer.nvidia.com/blog/accelerating-xgboost-on-gpu-clusters-with-dask/) helpful.

Note that depending on the size of your data and total GPU memory, you may not be able to fit the entire dataset in memory for training. We also generally recommend using fewer partitions than in your example.

I'm going to close this question issue as answered, but please feel free to re-open.

**Comment by ajalberd** [comment]
Hey @666-sudo, have you found a solution to this?
