### ISSUE TITLE
[BUG] Too many places in the code say "bits come in units of 32"

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#961]
As bits are not native types in C++, nor are they really "first-class citizens" on CPUs and GPUs, we always have bits in some sort of containers - whether packed (each bit in a larger integral value is of distinct interest) or upcast (integers with 0 meaning false, anything else meaning true). Now, for contiguous sequences packed bitsm it's convenient to assume that the packing is consistent, that there's a certain quantum; and since nVIDIA GPUs use 32-bit registers mostly, and these are also reasonably liked by CPUs - it's reasonable to set 32-bit quanta for packing, i.e. taking packed bits via  `uint32_t` sequences.

The problem is, that this setting is made explicit in multiple places in the cudf codebase; other places rely on one or the other of the explicit settings; and yet others still just assume 32-bit quants implicitly.

This is coming up as I'm addressing comments in my `gpu_apply_stencil` reimplementation (PR #902). I've made my own definitions, just within the `.cu` file with the implementation of this function:
```
using bit_container = uint32_t;
enum : unsigned { bits_per_container = cudf::util::size_in_bits<bit_container>() };
```
but now I notice that in `src/bit_mask/bit_mask.h` we have:
```
  typedef uint32_t     bit_mask_t;
```
within `class bit_mask`. And in `valid_ops.cu` we have:
```
using valid32_t = uint32_t;
```
and in `utilities/bit_util.h` we have:
```
static constexpr int ValidSize = 32;
using ValidType = uint32_t;
```

This need to be unified somehow. If not entirely centralized, local type definitions and constant should at least alias central ones.

**Comment by jrhemstad** [comment]
>This need to be unified somehow.

100% agreed.

The purpose of `bit_mask_t` and associated functions: https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/bitmask/bit_mask.h is to do exactly that---centralize all of the the valid bit manipulation code such that everyone is using the same thing.

Someone just has to go through and do the work of updating all of the existing code to use the new centralized type/functions. 

It's not something that can really be done in pieces because the first step is changing `gdf_valid_type` to be `bit_mask_t`, which is going from 1B to 4B, and will require updating everything both on the Python and C++ side.

It'll be a lot of work, but it is definitely a high priority for me. I'm hoping we can get it done for the 0.7 release.

**Comment by jrhemstad** [comment]
This issue can be used to track the work of doing the update to use the centralized `bit_mask_t`.

**Comment by OlivierNV** [comment]
Alternatively, we could just eliminate all these cosmetic appearances of portability and use uint32_t directly, since it's always very much tied to the underlying implementation... Since all supported arch are little endian, some parts of the code could use 8-bit, and other 32 or 64-bit containers all pointing to the same memory (the allocation alignment is probably what matters the most).

**Comment by eyalroz** [comment]
@OlivierNV : Using "magic types" is not much better than using "magic numbers". We shouldn't use `uint32_t`, we should use a typedef to give it more meaning. But - we shouldn't do it in a zillion places.

**Comment by jrhemstad** [comment]
No longer relevant in libcudf++.
