### ISSUE TITLE
[FEA] Convert hexadecimal strings ("0x...") to int data type in read_csv 

### ISSUE THREAD

**Issue by mjsamoht** [rapidsai/cudf#973]
Function `read_csv()` should detect hexadecimal numbers, starting with "0x", and convert them to integer data types.  Currently such numbers are treated as strings.

**Comment by quasiben** [comment]
As a python user this might be a bit strange.  That is, I would not expect `read_csv` to both detect and convert data.  As reference implementation, I would consult [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html). 

With that said, Pandas does, however, make an exception wrt detection and conversion for datetimes.  These can be converted on the fly if the user defines the column as an optional flag:

```python
# myfile.csv
# a,b,c
# 1.2,2017-01-09 11:13:28,N
 df = pd.read_csv('myfile.csv', parse_dates=['b'])
```

Do you work with many csvs with hexadecimal strings ?  If so, perhaps `cudf` should consider a optional flag asking the user to define which columns require hexadecimal conversion.

**Comment by j-ieong** [comment]
I think this feature request is in response to some benchmark.

AFAIK, PANDAS's read_csv() doesn't inherently support interpreting/conversion to hexadecimal and requires either passing in a lambda through converters argument or manually through apply() on the dataframe.

We talked about it internally, and ideally this should be a function supported by NvStrings, rather than the CSV reader, and any conversion would be a one-off thing. For the latter, maybe have it as a separate branch.
