### ISSUE TITLE
[FEA] Expose isnull/isnan 

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#976]
Data is often missing and messy.  It would be nice to expose `isna` and `isnull` methods on series objects.  These methods are often used for during filter operations like those below:

```python
cdf = cudf.read_csv(...)
cdf[cdf.isna()]

cdf[cdf.isnull()]
```

**Comment by kkraus14** [comment]
@dillon-cullinan You should be able to tackle this as part of #1126 since I think you already generate the boolean mask.

**Comment by beckernick** [comment]
It would also be good (for downstream usage and pandas API compatibility) to expose this functionality as a top level function. `isna` and `isnull` can be access via `pd.isnull` and `pd.isna`.

**Comment by beckernick** [comment]
Lack of the `isnull` method is now partially blocking a dask change to permit cumulative aggregation operations in dask-cudf

**Comment by randerzander** [comment]
@dillon-cullinan are you able to tackle isnull/isna as part of #1126?

@beckernick can you confirm if we need to add special logic for handling strings too?

**Comment by beckernick** [comment]
In terms of blocking cumulative aggregations, since they are are only operating on numeric columns these methods could be implemented at the series level and raise exceptions if the column is a StringColumn.

In general, I think we would need different logic than the work in #1126 as the StringColumns won't be understood by the numba kernel to check the validity mask in that PR.

**Comment by beckernick** [comment]
As an update, this specific issue is not necessarily blocking the dask functionality. Either `isnull` or `notna` methods (and top-level functions) would suffice as long as `isnull` could be used with the negation operator such as `ser[~ser.isnull()]`.
