### ISSUE TITLE
[QST] cuDF Memorycpy Problems

### ISSUE THREAD

**Issue by EdisonZiXing** [rapidsai/cudf#9780]
**What is your question?**
Hello every master,here is another for the cuDF:
Recently ,I've been using and reading the codes of cuDF.
The function **from_arrow()** is a wonderful work
In the from_arrow.cu I saw that **return detail::from_arrow(input_table, rmm::cuda_stream_default, mr);**
So I wonder if the cuDF doing the Memcpy with only one stream as rmm::cuda_stream_default Or rmm::cuda_stream_default is a parallel way of loading data?
Is there any other way to accelerate the Data Loading process?
Thx for your replies!!!

**Comment by harrism** [comment]
> `return detail::from_arrow(input_table, rmm::cuda_stream_default, mr);` 

All libcudf public APIs have a corresponding `detail` API that takes a stream. Since CUDA streams are not exposed in the public API, we pass `rmm::cuda_stream_default` from the public to the detail API. That's what the above line is doing. One day, we plan to expose streams in the public APIs, but we have not done that. `cuda_stream_default` is just CUDA's default stream. If per-thread default stream is enabled, this will be the per-thread default stream. So one could call `from_arrow` on different data from multiple threads and get parallelism. However, there is nothing inherently parallel about `cuda_stream_default`.

> Is there any other way to accelerate the Data Loading process?

I think for us to look at this we should ask you about your specific problem: do you have a workflow where `from_arrow` is a significant bottleneck that needs to be accelerated? What specifically do you mean by `Data Loading`? From file? From Arrow? Something else?

**Comment by EdisonZiXing** [comment]
> > `return detail::from_arrow(input_table, rmm::cuda_stream_default, mr);`
> 
> All libcudf public APIs have a corresponding `detail` API that takes a stream. Since CUDA streams are not exposed in the public API, we pass `rmm::cuda_stream_default` from the public to the detail API. That's what the above line is doing. One day, we plan to expose streams in the public APIs, but we have not done that. `cuda_stream_default` is just CUDA's default stream. If per-thread default stream is enabled, this will be the per-thread default stream. So one could call `from_arrow` on different data from multiple threads and get parallelism. However, there is nothing inherently parallel about `cuda_stream_default`.
> 
> > Is there any other way to accelerate the Data Loading process?
> 
> I think for us to look at this we should ask you about your specific problem: do you have a workflow where `from_arrow` is a significant bottleneck that needs to be accelerated? What specifically do you mean by `Data Loading`? From file? From Arrow? Something else?

@harrism 
Dear Harrism:
Thank you for the instruction about Q1 and I really looking forward to seeing cuda_stream_per_thread coming out!!!
I've seen cuda_stream_per_thread in the code and now I knew that this part of function is still working on.
About Q2,I should have clearly explained my  question and your infer is right:Our data is loaded in host in-mem,so we do have a workflow where from_arrow is a significant bottleneck that needs to be accelerated.I was trying to pull multi processes by manual  and doing from_arrow(),seems like the speed of transmission from Host to Device become higher, 14GB/s at peak but still not meeting the 32GB/s of Tesla-v100 PCIE .But we still want to accelerate this part so that we could lower the cost of data transmitting.As a member of cuDF and the expert of this area,do you have any suggests about the using ways of cuDF that we could using the extreme performance of the host(cpu/in-mem) and device or any other plans?
Thanks again for your patient and advice,Harrism!

**Comment by harrism** [comment]
I don't think we can reach peak PCI-E rates with data in host without registering (pinning) the host memory. I think we would need a test program to look at your specific use case.

**Comment by shwina** [comment]
Going to mark this one closed, but please feel free to reopen if necessary.
