### ISSUE TITLE
[QST] How to estimate the GPU-memory needed to uncompress a Parquet dataset?

### ISSUE THREAD

**Issue by Franc-Z** [rapidsai/cudf#9819]
**What is your question?**
Due to the limited volume of GPU memory, sometime when one wants to load a Parquet dataset, it would lead to a OOM error. 
Does any expert know that if we could pre-estimate the memory required (and the space needed in disk) before actually uncompressing a Parquet file in cuDF? Python or C++ samples or indications are all welcome.

**Comment by nvdbaranec** [comment]
Is this in regards to the resulting output data size, or also including the scratch space (which can be non-trivial) using during the decompression/decoding?

**Comment by Franc-Z** [comment]
> Is this in regards to the resulting output data size, or also including the scratch space (which can be non-trivial) used during the decompression/decoding?

Also including the scratch space used during decompression. (To estimate the peak device-memory needed during decompression to avoid OOM error)

**Comment by Franc-Z** [comment]
https://docs.rapids.ai/api/libcudf/stable/group__io__readers.html#ga539a82d720387747800c360ba68d748f
From the above link, I get the code snippet as below. Can we get some useful infos (like row count, row format) from the second line to calculate **the peak required device-memory**?
_auto source  = cudf::io::source_info("dataset.parquet");
auto options = cudf::io::parquet_reader_options::builder(source);
auto result  = cudf::io::read_parquet(options);_

**Comment by vuule** [comment]
To answer you question, the team looked into ways to more accurately estimate the total memory usage. Unfortunately, the conclusion is that this is not feasible without decoding much of the file, because of complex encoding in the Parquet format, including the use of dictionaries.

As for getting the number of rows + data types:
We don't have any APIs to get this information. The closest API we have is the Python function `read_parquet_metadata`.
You can use PyArrow to get the number of rows and the data types in both C++ and Python. Please note that this might not give you a good estimate with some column types (lists, strings).
If you do predominantly use fixed size columns, you can estimate the peak memory use as 3X the data size (decoded, decompressed).

**Comment by Franc-Z** [comment]
> To answer you question, the team looked into ways to more accurately estimate the total memory usage. Unfortunately, the conclusion is that this is not feasible without decoding much of the file, because of complex encoding in the Parquet format, including the use of dictionaries.
> 
> As for getting the number of rows + data types: We don't have any APIs to get this information. The closest API we have is the Python function `read_parquet_metadata`. You can use PyArrow to get the number of rows and the data types in both C++ and Python. Please note that this might not give you a good estimate with some column types (lists, strings). If you do predominantly use fixed size columns, you can estimate the peak memory use as 3X the data size (decoded, decompressed).

Thanks! Now It seems more clear.
