### ISSUE TITLE
[BUG] Java bindings for ORC/Parquet writers always set decimal precision

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#9851]
`createTableMetaData` calls `set_decimal_precision` even when there are no values for the precision. This causes incorrect precision values in the output file. 

Affects https://github.com/rapidsai/cudf/pull/9775, where precision is used to choose the decimal type when reading ORC files.

**Comment by vuule** [comment]
CC @jlowe

**Comment by jlowe** [comment]
To clarify, the core issue is that the Java bindings do not have the concept of a column having writer options but _not_ having a decimal precision specified by the user.  So if the user sets up column names for a table but does not specify any precision values, Java will default the precisions to zero rather than "not set."  The Java bindings need a way to convey that the precision is unspecified (e.g.: use a sentinel value of -1) and then only set the precision in the corresponding libcudf table metadata when calling the libcudf write.

**Comment by sperlingxx** [comment]
Shall we close this issue ?

**Comment by sperlingxx** [comment]
Oh, I overlooked this issue before. For now, I picked it up.
