### ISSUE TITLE
[BUG] Java CI times out trying to solve conda env

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9976]
**Describe the bug**
Recent Java CI builds have been failing with a solve timeout on the conda environment.  This was seen in other gpuci environments and fixed by #9951, but the Java build was not updated at that time since the changes caused CMake to fail to find the JDK native headers and libraries.

**Steps/Code to reproduce bug**
Run gpuci on any PR and examine the Java build logs

**Expected behavior**
gpuci Java build should pass

**Comment by ajschmidt8** [comment]
I've been looking into the logs here and I think I've found something that may be contributing to this issue. After looking at the logs from [this commit](https://github.com/rapidsai/cudf/pull/9951/commits/9e05a8f91d0f4a1c8c98b64c785a8e1b22e4c3d0) on Bradley's PR, it seems that `mamba` installed an older version of some packages.

![image](https://user-images.githubusercontent.com/7400326/148423881-d1f905fe-ff88-4774-8075-0961827623d2.png)


That's likely due to [this](https://github.com/rapidsai/integration/pull/386) `integration` PR being merged without Jeremy's corresponding `cudf` [PR](https://github.com/rapidsai/cudf/pull/9486) being merged yet.

I've just merged Jeremy's `cudf` PR. Let's see if that resolves the `cudf` build issues for Java. If so, we can probably try switching the line below to use `mamba install` again.

https://github.com/rapidsai/cudf/blob/23603d16804f13f16ed4cb2c45831836e080017e/ci/gpu/java.sh#L133

**Comment by bdice** [comment]
@ajschmidt8 Thanks so much! I'll open a PR to test that change to the Java CI.
